### ISSUE TITLE
Slint LSP support for IntelliJ

### ISSUE THREAD

**Issue by jared201** [slint-ui/slint#1014]
Hi, this may have already been solved, I just want to be in the right direction as to enable slint lsp in IntelliJ IDE. thanks

**Comment by ogoffart** [comment]
I am not familiar with IntelliJ, but I believe it should support LSP. A quick search leads me to

**Comment by ogoffart** [comment]
I am not familiar with IntelliJ, but I believe it should support LSP. A quick search leads me to  https://github.com/gtache/intellij-lsp 
You should then be able to configure it to use the slint-lsp.
I'd be interested to know if this work well, and yould welcome a pull request to the editor/README that explain how to set it up.

(Sorry for closing the issue earlier, I pressed the wrong button)
