### ISSUE TITLE
ListView doesn't show last few entries on mac with retina

### ISSUE THREAD

**Issue by lukas-jung** [slint-ui/slint#1030]
When moving a Window to a retina/highdpi display on macos the last few entries are not rendered properly.

It can be reproduced easily with the gallery example.

here's a video of the bug that @tronical made:
https://user-images.githubusercontent.com/22800467/157456775-5af2d747-9d12-4830-9488-f5d1963b5673.mp4

**Comment by tronical** [comment]
I can't reproduce this anymore. I hope it was #2282 that fixed this.
