### ISSUE TITLE
On-Hover callback

### ISSUE THREAD

**Issue by leofidus** [slint-ui/slint#1037]
I can change color or other properties based on a TouchArea's `has-hover` attribute, but unless I'm missing something obvious there's no way to make a callback that reacts to an element being hovered over (for example to show additional information).

**Comment by tronical** [comment]
Hm, perhaps you’re looking for the [`pointer-event`](https://github.com/slint-ui/slint/blob/master/docs/builtin_elements.md#callbacks) callback?

**Comment by ogoffart** [comment]
Long term we want to have a callback when a property change: https://github.com/slint-ui/slint/issues/112

As a workaround you can  use this hack:

```
callback my_callback(bool) -> color;
my_callback(x) => { debug("HELLO", x); }
//...
background: my_callback(touch.has-hover);
```

Because the background property will be re-evaluated when the hover change, the callback will be called.

**Comment by leofidus** [comment]
That's a pretty clever workaround and works great, thank you.

#112 would be a quite elegant way to solve it, and would allow replacing a couple of other callbacks with properties as well (e.g. TouchArea.clicked is just a change handler for TouchArea.pressed). I understand the reservations against it, but without it there's a weird divide where simple changes based on a property are possible with bindings but more complex changes based on the same property are impossible (without your workaround or ballooning the built-in elements with lots of callbacks)

**Comment by ogoffart** [comment]
If we really need this kind of event, we could extend PointerEvent or the `moved` callback or something.
But i'm going to close this now and only track #112

**Comment by wuanzhuan** [comment]
> @wuanzhuan: You have better chances of people seeing your question when you post them as a discussion or as a fresh issue. People rarely look into closed bug reports!
> 
> Anyway: I'd try to two-way link the local has-hover in the `TableViewCell`s to `row_element.has-hover` (`has-hover <=> row_element.has-hover` in all the `TableViewCells`).
> 
> But I have not tried this :-) It may or may not actually work.

thanks，i will new a issue.  And  the <=> binding can't work
