### ISSUE TITLE
CMake build produces absolute paths for `DT_NEEDED` on Linux

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#1066]
How to reproduce:

1. Build Slint with CMake and install it with `cmake --build . --target install ` into some directory.
2. Go into `examples/` in the Slint source tree.
3. `mkdir build`
4. `cd build`
5. `cmake -DCMAKE_PREFIX_PATH=/path/to/where/it/is/installed ..`
6. `cmake --build .`
7. `patchelf --print-needed ./printerdemo/cpp/printerdemo`

Output on my Linux system:

```sh
/home/simon/src/cppinstall/lib/libslint_cpp.so
libstdc++.so.6
libm.so.6
libgcc_s.so.1
libc.so.6
```

It is not evident why this happens, when linking against other libraries CMake does not produce an absolute path for `DT_NEEDED`. Maybe this is somehow related to the absolute import location we receive from Corrosion?

**Comment by hunger** [comment]
I do not find this very surprising: CMake was asked to install the library to that place. So it is sure that this _is_ the place to find that library. So why should it look elsewhere?

**Comment by hunger** [comment]
The location is generated in the SlintConfig.cmake that we generate and install, where it finds the library relative to that file itself.

[`target_link_library` documentation](https://cmake.org/cmake/help/latest/command/target_link_libraries.html?highlight=link) states this:

> If an imported library has the [IMPORTED_NO_SONAME](https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_NO_SONAME.html#prop_tgt:IMPORTED_NO_SONAME) target property set, CMake may ask the linker to search for the library instead of using the full path (e.g. /usr/lib/libfoo.so becomes -lfoo).

Does this help?

**Comment by tronical** [comment]
Yes. This seems to related to https://github.com/rust-lang/cargo/issues/5045 as well. The `cdylib` that cargo/rustc creates doesn't have `DT_SONAME` set, that's why the absolute path ends up in `DT_NEEDED`.
