### ISSUE TITLE
Add support for cross-compilation of the CMake build with slint-compiler

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#1085]
The current build of the slint-compiler on Linux requires linkage against the fontconfig library. When cross-compiling with CMake, corrosion takes care of invoking cargo correctly to build slint-compiler as a host binary. However the library search paths provided by CMake will be target specific, so linkage against fontconfig might fail.

We can solve this by adding support for a two-step build process:

1. First Slint is built with CMake as a host build and then installed (optional: Disable library build, only build slint-compiler)
2. Now Slint is built for the target, but configured in a way that the CMake command line provides a path to the previously installed host build, so that the generated SlintConfig.cmake/SlintMacro.cmake can invoke the host slint-compiler binary.

**Comment by ogoffart** [comment]
Two step build process was implemented long time ago.
