### ISSUE TITLE
TouchArea pressed / released signal.

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#113]
There is already a `pressed` property, so there can't be a signal with that name.

Or Do we even need such signal if we have an way to run code on property change (#112) then we would just check the pressed changed action.

**Comment by jturcotte** [comment]
This is going to be one of the main signals of the whole toolkit, so either way I think that it should be as convenient as it can be to use it.

**Comment by ogoffart** [comment]
there is a pointer-event callback
