### ISSUE TITLE
Korean characters shown as squares in OpenGL rendering

### ISSUE THREAD

**Issue by teminian** [slint-ui/slint#1139]
![hangul-broken](https://user-images.githubusercontent.com/16410454/161390932-d1ee7eb6-6a75-47dc-8b74-fe738c618df1.png)
If you follow instructions below, you find that Korean characters are shown as squares(as if there's no such font)

1. Run gallery example
2. Click LineEdit
3. Input in this sequence: DDDDjjjj가나다라 (or you can just copy-and-paste the left characters)
4. And you'll meet the same "broken" text rendering

As of current the only workaround is as follows:

1. Input Korean characters along with others(e.g. 가나다라DDDDjjjj)
2. Erase all of them
3. Input the "erroneous" stuff
4. The text is rendered, but "pulled down" as I uploaded in https://github.com/slint-ui/slint/issues/1138

For your reference, I used OpenGL backend in Windows, and the language is C++.

**Comment by tronical** [comment]
Thanks for the detailed report!

On Windows we're using [IDWriteFontFallback::MapCharacters](https://docs.microsoft.com/en-us/windows/win32/api/dwrite_2/nf-dwrite_2-idwritefontfallback-mapcharacters) to determine the list of fonts we need to render a given piece of text. When that text starts with Korean characters, we locate the correct font. When it starts with latin, we either fail to pick the correct fallback font or the font we pick claims to cover CJK when in fact it doesn't.

This is also reproducible with Chinese characters, so this is most likely related to us calling the function incorrect or interpreting the results wrongly.

**Comment by tronical** [comment]
The [implementation](https://github.com/servo/font-kit/blob/75f99cf648885c180c7ccfb9b6d55eae259e1d71/src/loaders/directwrite.rs#L676) returns only a single font ever, so there's definitely something fishy there.

**Comment by ogoffart** [comment]
I can reproduce on Linux btw

![Screenshot_20220404_104753](https://user-images.githubusercontent.com/959326/161508218-20a6f4b4-3666-427c-ab1f-160ac3daba8e.png)

(string: "e.g. 가나다라DDDDjjjj")

**Comment by ogoffart** [comment]
But I think I just don't have the character in my fonts. Because Qt is also not showing it. And even in the browser it is replacement character.

**Comment by teminian** [comment]
I agree with @ogoffart. I think you can install a few Korean fonts in Linux and try again, for example Nanum.
For Ubuntu the package name must be **fonts-nanum** and for Fedora and like I think it's **nhn-nanum-fonts**.

**Comment by legend59** [comment]
It can be used in the font of the following address.

https://hangeul.naver.com/hangeul_static/webfont/zips/nanum-myeongjo.zip

The prefix 'nanum' means open, and all nanum fonts follow the open source license.
Because the default font is already used, Hangul(Korean characters) is shown as squares. To use Hangul, the font was changed by adding "NanumGothic" to default-font-family. Add below parameter

default-font-family: "NanumMyeongjo";

in gallery.slint file.

**Comment by tronical** [comment]
> The [implementation](https://github.com/servo/font-kit/blob/75f99cf648885c180c7ccfb9b6d55eae259e1d71/src/loaders/directwrite.rs#L676) returns only a single font ever, so there's definitely something fishy there.

What's fishy is that we're not looking at the valid_len field.
