### ISSUE TITLE
Initial Window Draw Latency

### ISSUE THREAD

**Issue by sciguyryan** [slint-ui/slint#1150]
Hi there.

I'm exploring using Slint as a GUI framework for a project I'm working on. I've been looking through the examples and have added the basic "hello world" example into my project.

I've noticed that there is maybe half a second of latency after the window opens before the coloured text is drawn to the window.

Is there any reason for this, and is there any way to avoid this happening? I'm concerned that it could end up quite significant with a more complex GUI.

Thanks in advance,

Ryan.

**Comment by tronical** [comment]
Hi! Which operating system and windowing system are you using?

**Comment by ogoffart** [comment]
Also make sure you are building in release mode as debug mode can be slow (but still shouldn't take half a second)

**Comment by sciguyryan** [comment]
> Hi! Which operating system and windowing system are you using?

I'm using Windows, specifically Windows 10 at present.

**Comment by tronical** [comment]
This might be the same cause as #418, i.e. winit's event handling on Windows. If you look for a workaround on Windows, you could try with Qt: https://github.com/slint-ui/slint/blob/master/docs/install_qt.md

**Comment by ogoffart** [comment]
Please re-open or comment if this is still an issue
