### ISSUE TITLE
Color Palette

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#116]
The idea would be to have a `Palette` singleton in the style, similar to the `StyleMetrics` one.

The palette would have property for each interresting color.

Idea for picking the different color roles:
 * Material style: https://material.io/design/color/the-color-system.html#color-theme-creation
 * QPalette: https://doc.qt.io/qt-5/qpalette.html#ColorRole-enum
 * UIKit: https://developer.apple.com/documentation/uikit/uicolor/ui_element_colors
 * MS Windows: https://docs.microsoft.com/en-us/dotnet/api/system.windows.systemcolors?view=net-5.0

**Comment by tronical** [comment]
* Fluent UI's [semantic colors](https://docs.microsoft.com/en-us/javascript/api/theme/isemanticcolors?view=office-ui-fabric-react-latest) . See also the "Semantic Slots" under "Theme Slots" in the [Fluent UI Theme Designer](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/7.0/theming-designer/index.html)

**Comment by ogoffart** [comment]
* KDE: https://api.kde.org/frameworks/kconfigwidgets/html/classKColorScheme.html
* GTK: https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-22/gtk/theme/Adwaita/_colors-public.scss

Another point: do we want to add api such as color.darker()  color.lighter() ?

**Comment by wigy-opensource-developer** [comment]
You already have [impl InterpolatedPropertyValue for Color](https://github.com/sixtyfpsui/sixtyfps/blob/bf84bb2ab6e552df92c32876da7042f8c3005ed0/sixtyfps_runtime/corelib/graphics/color.rs#L201) for animating colors. If you could expose that as [`color.mix(another-color, weight)`](https://sass-lang.com/documentation/modules/color#mix) as Sass does, it would even use the [same RGB colorspace Sass uses](https://github.com/sass/node-sass/blob/4115e9de35a26a6c27604e22c9c1981bf19b0f5f/src/libsass/src/functions.cpp#L424).

With that function in place, you could drastically reduce the number of colors in the Palette and calculate the rest of them, making the theming easier for the end-users.

**Comment by tronical** [comment]
I think that's a very good idea. The CSS [color-mix()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix()) function takes that a step further by adding a color space parameter. API wise that might be even better for future support for different color spaces. What do you think?

**Comment by wigy-opensource-developer** [comment]
Although more color spaces give more flexibility to a designer, personally I would not miss them. If this `color.mix` function would be shipped earlier, and Sass users do not miss them, I would postpone their introduction.

At the moment the HSL space used for `color.brighten` and `color.darken` are not accessible to the `.60` language either, nor the red, green, blue and alpha components of the internal representation, so in the far future I would rather have a consistent way of introducing color spaces all around the language (gradients, animations, constructing from color components, extracting color components).

**Comment by tronical** [comment]
Coming from #1315 I'm wondering if the palette should perhaps be a model instead of a struct, and the rows are roles.

If the palette was a struct and we'd have a per-widget palette, then that's a substantial amount of bytes spent for each widget when in most cases it would be copied from the global palette.

If the palette were a model, then it would be basically a smart pointer that defaults pointing to the global palette but can be overridden by the user.

**Comment by wigy-opensource-developer** [comment]
Yes! And switching themes (dark mode - light mode - accessible mode) could also be implemented by just replacing the global palette. And as I mentioned, in many color schemes, intermediate tones are used by mixing base colors together.

That could be done either on the palette by defining role colors mixed from base colors, or on the widget itself.

**Comment by ogoffart** [comment]
Having the palette being of type `[Color]` is not a bad idea, and then we can have constants in some namespace for the indices.

But another possibility would be to just have special compiler support for this.  So not every element would have a palette at runtime. in the implementation widget, one would simply do

```
FooWidget := Rectangle { 
   background: Colors.button-background;  
}
```

And when using it we can override some of the palette with

```
FooWidget {
    palette: { button-background: red;    }  // the other color are "inherited"
}
```

Where palette is a builtin property.

**Comment by tronical** [comment]
Ahh, interesting idea - this combines after all. We could use a model in the implementation but hide it behind the syntax you're proposing. Let me see if I understood correctly:

1. If an element uses `Colors.XXX` in a binding, then this is translated to resolve to a newly materialised `palette` property.
2. The newly materialised palette property is publicly visible
3. A binding to the palette property with object assignment results in a binding that inherits unset values from the global palette.

**Comment by hunger** [comment]
Where is this "button-background" defined? What happens when I mistype that as "butn-background" somewhere? Is that recognized as an error or will that silently add a new color to the palette?

**Comment by ogoffart** [comment]
It would be defined in the compiler and typo would be detected

**Comment by nahsheef** [comment]
Might we get an additional choice as an interim solution? A grey color scheme with high contrast text and widget outlines would be sufficient until custom colors are implemented.

**Comment by ogoffart** [comment]
MVP merged in https://github.com/slint-ui/slint/pull/3984
