### ISSUE TITLE
Should Model::get_row_data trigger tracking for that row?

### ISSUE THREAD

**Issue by FlorentBecker** [slint-ui/slint#1177]
While trying to implement an indicator of the percentage of tasks done in the TodoList demo, I wrote the following callback:
```
    main_window.on_percent_done({
        let todo_model = todo_model.clone();
        move || {
            let n = todo_model.row_count();
            if n == 0 {
                return 0.3252;
            }
            let mut done = 0;
            for i in 0..todo_model.row_count() {
                if todo_model.row_data(i).unwrap().checked {
                    done += 1
                }
            }
            return (done as f32 / todo_model.row_count() as f32);
        }
    });
```

Then I added a
```
	Text {
	    text: "Tasks " + root.percent-done()*100 + "% done";
	}

```

In the UI. This does not refresh when the user selects or deselects the Tasks in the UI. It turns out that a ` model.model_tracker().track_row_data_changes(i)` is needed in the loop. This is inconsistent with the way the `get_whatever()` methods of properties work. Please consider adding a method
```
fn tracked_row_data(&self, row: usize) {
    self.track_row_data_changes(row);
    self.row_data(row)
}
```
to the Model trait.

Then it needs to be decided whether the current row_data should be named `current_row_data` or `volatile_row_data` or `snapshot_row_data`, and what should happen when iterating over a model. 

From the user point of view, it would be nice to:
- either always have the tracking version, or have both tracking and snapshot versions in all cases (scalar property, model length, model row contents, model iterator)
- ideally, have the default be the same each time (or only have qualified methods).

**Comment by tronical** [comment]
I agree, the inconsistency is a little unfortunate.

Tracking row data changes in a Model comes at a cost, which is why we're not doing it by default. We could add a `tracked_row_data` function as suggested, and the first thing that function would do is check if we're currently evaluating a binding.

In the light of that check, we could also consider changing the behavior of `row_data` to do this by default and rather have a `row_data_untracked` (or use the "untracking" helper function inside Slint when we need it).

**Comment by tronical** [comment]
We discussed this and concluded against an automatic tracking of `row_data` but rather add a `row_data_tracked` convenience function.

One of the reasons is that this complicates the implementation of each model, while tracking may not always be needed.
