### ISSUE TITLE
Consider a dedicated `Group` element to group items together

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#119]
Sometimes it is useful to group items together without a specific graphical purpose, for example solely for component encapsulation. Right now the `Rectangle` element is typically used to achieve that, but it would perhaps make sense to have a dedicated element for that, such as `Group`. It shall have dimensional and positional properties, but not `color`, `border-width` or other properties that result in a specific visual appearance.

**Comment by ogoffart** [comment]
Looks like we are happy with Rectangle
