### ISSUE TITLE
How to listen for text input widget value change event in real time?

### ISSUE THREAD

**Issue by Arkinux** [slint-ui/slint#1192]
How to listen for text input widget value change event in real time? Has a API?

**Comment by ogoffart** [comment]
TextInput and LineEdit have an `edited` callback.

```
    LineEdit {
       edited => { debug("the text was edited", text); }
    }
```

From the callback you can forward to another callback which is exposed.
Does that do what you want? Or what are you trying to do more precisely?

**Comment by Arkinux** [comment]
> TextInput and LineEdit have an `edited` callback.
> 
> ```
>     LineEdit {
>        edited => { debug("the text was edited", text); }
>     }
> ```
> 
> From the callback you can forward to another callback which is exposed. Does that do what you want? Or what are you trying to do more precisely?

This is what I want. You solve my problem. Thank you！
