### ISSUE TITLE
Dockerfile for building x86 linux

### ISSUE THREAD

**Issue by a1ecbr0wn** [slint-ui/slint#1197]
Based on cross-rs's x86_64-unknown-linux-gnu container with additional slint dependencies.
This is slightly different from the armv7 one as this is based off Centos7 rather than ubuntu

**Comment by tronical** [comment]
Commit 8429fbd493f79bd519ef52c0b0b010054f32fff7 adds the container and 7b0dab4ab1fd49cba37ab4827efe9dd93841d20d shows the line to add to `Cross.toml` for use.
