### ISSUE TITLE
If the text does not start with Chinese, the characters will be unrecognized and garbled.

### ISSUE THREAD

**Issue by Misaka15535** [slint-ui/slint#1199]
```rust
slint::slint! {
    MainWindow := Window {
        Text { text: " 当开头不是中文就会不识别"; }
    }
}
fn main() {
    MainWindow::new().run();
}
```

If the text does not start with Chinese, the characters will be unrecognized and garbled.
![image](https://user-images.githubusercontent.com/46892084/165914262-6a22a081-7b00-4f62-a6e5-f1ae9f19e278.png)
![image](https://user-images.githubusercontent.com/46892084/165914319-245adf53-8504-4f38-8c41-e561ac83f18d.png)
![image](https://user-images.githubusercontent.com/46892084/165914374-1c397739-2d43-4343-8fb5-039cf63eda17.png)

Although I haven't tested it, I think this problem occurs in other languages as well.

**Comment by ogoffart** [comment]
Thanks for your bug report!

I believe this is a duplicate of #1139 which already has been fixed in the master branch.
You can try using the git version of slint, or wait for the next release

**Comment by Misaka15535** [comment]
![image](https://user-images.githubusercontent.com/46892084/166095503-f782d6c9-ca09-4bac-8d21-d1f302ba7108.png)

May I ask why the code I wrote can't find the checkbox, and now I use the git version.

**Comment by ogoffart** [comment]
did you do 
```
import { CheckBox } from "std-widgets.slint";
```

**Comment by Misaka15535** [comment]
How to read the checked field of the checkBox in the code. 

Slint's design is very creative. but Slint's documentation feels inadequate. 
Although I make simple things, I can't always find the content I need.
(I can't find what I need, or it may have something to do with my poor English.

**Comment by Misaka15535** [comment]
thank you
