### ISSUE TITLE
Optimise empty `Rectangle` elements

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#120]
`Rectangle` is sometimes used as a place-holder to group items together. In that case it's solely used to provide positional and dimensional properties. We should optimise the compiler such that a `Rectangle` that's used like that should not result in the allocation of the typical rectangle properties in the generated code, that are responsible for the appearance of a rectangle. The dimensional and positional properties could become standalone "fake" properties, for example. Or there could be a dedicated type that just has those four (width, height, x, y).

**Comment by ogoffart** [comment]
We now have an Empty for elements that are not optimized away, that saves a bunch of properties
