### ISSUE TITLE
"cargo install slint-viewer" compile error against Qt header

### ISSUE THREAD

**Issue by Montel** [slint-ui/slint#1200]
Hi,
I try to compile it.
I use opensuse tumbleweed

it reports this error:
-
   Compiling num_enum_derive v0.5.7
The following warnings were emitted during compilation:

warning: src/lib.rs:1724:14: erreur fatale: QtCore/QJsonDocument : Aucun fichier ou dossier de ce type
warning:  1724 |     #include <QtCore/QJsonDocument>
warning:       |              ^~~~~~~~~~~~~~~~~~~~~~
warning: compilation terminée.

error: failed to run custom build command for `qttypes v0.2.8`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installVGkbKE/release/build/qttypes-9407e8db2a31510e/build-script-build` (exit status: 1)
-

For sure I have qt5-dev installed (I build all the time kde :) )
but 
"running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "/home/laurent/.cargo/registry/src/github.com-1ecc6299db9ec823/qttypes-0.2.8" "-I" "/usr/include" "-Wall" "-Wextra" "-std=c++11" "-o" "/travail/kdab/git/slint/target/release/build/qttypes-54b02ac1384930a6/out/rust_cpp/cpp_closures.o" "-c" "/travail/kdab/git/slint/target/release/build/qttypes-54b02ac1384930a6/out/rust_cpp/cpp_closures.cpp"

=> it use "-I" "/usr/include" but header is in /usr/include/qt5

I don't know how to fix it
(or workaround it)

Do you have an idea ?
thanks

**Comment by ogoffart** [comment]
What does `qmake -query QT_INSTALL_HEADERS` return for you?  that's what is used to find the Qt include path.

You can also set the QT_INCLUDE_PATH and QT_LIBRARY_PATH env variable to override.
See https://docs.rs/qttypes/latest/qttypes/#finding-qt

**Comment by Montel** [comment]
"qmake -query QT_INSTALL_HEADERS" is for qt4
we need to use qmake-qt5 in opensuse for qt5

but indeed I can use set QT_INCLUDE_PATH/QT_LIBRARY_PATH
thanks for info

**Comment by ogoffart** [comment]
I see, that explain it.  Because we don't check the version in qtypes. so if qt4 is installed it'd try qt4 by default.

It does try qmake-qt5 as well but only if qmake fails:
https://github.com/woboq/qmetaobject-rs/blob/master/qttypes/build.rs#L47

I guess we could check the version in that build script and error out if it is Qt4.

As a workaround, you should set the QMAKE env variable, or  QT_INCLUDE_PATH/QT_LIBRARY_PATH

**Comment by Montel** [comment]
I think that we need to check qmake-qt5 first and after that qmake.

But indeed I will fix my compile error with settings QT_INCLUDE_PATH/QT_LIBRARY_PATH
thanks
