### ISSUE TITLE
How to update UI in the sub thread?

### ISSUE THREAD

**Issue by Arkinux** [slint-ui/slint#1204]
I new a thread in the main thread and i want to update the UI in the new thread. How i can do?

**Comment by ogoffart** [comment]
You can use the invoke_from_event_loop function.
See https://docs.rs/slint/latest/slint/fn.invoke_from_event_loop.html

**Comment by Arkinux** [comment]
> You can use the invoke_from_event_loop function. See https://docs.rs/slint/latest/slint/fn.invoke_from_event_loop.html

Thank you！
