### ISSUE TITLE
string.length or string.empty

### ISSUE THREAD

**Issue by jamesblacklock** [slint-ui/slint#1205]
I need a way to check if a string property is empty. Is there currently any way to do this? As far as I can tell, there is not.

It seems like string.length would be a useful property to expose. What does the team think about this?

Thanks, guys!

**Comment by ogoffart** [comment]
The way to do it is simply `string == ""`

I do think that it is enough.

The problem with string.length is that it is not so obvious as it seems. I suppose we would return utf8 bytes length,  but user may expect other things.
And `.is_empty` or something like that does't really bring so much value compared to `== ""` i'd say.

**Comment by jamesblacklock** [comment]
Both excellent points. I retract the request.
