### ISSUE TITLE
Add support for properties that can refer to elements

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#121]
Should it be possible to declare properties that can refer to other items? Such as in the following example:

```
Button := Rectangle {
    property <string> button_text;
    // ...
}

export App := Window {
    property <Button> current_button: some_button;

    property <string> foo: current_button.button_text;

    some_button := Button { }

    property <Rectangle> some_rect: some_button; // This is ok
    property <string> invalid_binding: some_rect.button_text; // This is NOT ok, Rectangle does not have a button_text property
}
```

We need to address whether a property that holds a reference to another element should keep that element alive (strong reference) or whether a such a reference can be "null" (weak reference).

If it's a strong reference, then we need to decide on what kind of mechanism to put in place to detect cyclic references, in order to prevent memory leaks.

If it's a weak reference, then we need to decide what should happen if code tries to dereference such a null reference.

**Comment by ogoffart** [comment]
Would be nice to collect actual use case for this.

**Comment by ogoffart** [comment]
Currently, Element no longer exist at runtime and implementing reference to element might also be really hard without a garbage collector.  So i'm closing this issue.
