### ISSUE TITLE
Todo example: Quit confirmation window does not show

### ISSUE THREAD

**Issue by hunger** [slint-ui/slint#1211]
Running `cargo run -p todo` on windows starts the todo application. Closing it again via the `X` button makes a popup flicker in existence and directly vanish again without any chance to interact with it.

OS: Windows
Backend: Qt

**Comment by ogoffart** [comment]
Is it a regression?

**Comment by hunger** [comment]
IIRC that confirmation dialog is new.

So you can argue it is a regression: That app did quit nicely without this. On the other hand bugs in new functionality are usually not considered a regression.

**Comment by ogoffart** [comment]
ah right. i had in mind it was already in 0.2.1, but then we should probably investigate that
