### ISSUE TITLE
Todo example: Does not close the application  (Qt)

### ISSUE THREAD

**Issue by hunger** [slint-ui/slint#1212]
I managed to run `cargo run -p todo` on Windows twice without triggering #1211.

I got the close confirmation window show up as expected and was able to quit the application with it. Both the confirmation and the application window were closed, but the terminal stays locked till I hit Ctrl-C in it. At that point I get a warning:

```powershell
QObject::killTimers: Timers can not be stopped from another threat
QObject::~QObject: Timers can not be stopped from another threat
```

OS: Windows
Backend: Qt

**Comment by ogoffart** [comment]
This happens on all platform and all backends.  But the reason is different for each backend.
This issue is for the Qt backend, and #1220 is for the GL backend
