### ISSUE TITLE
Combobox Text is not grayed out properly when disabled.

### ISSUE THREAD

**Issue by lukas-jung** [slint-ui/slint#1215]
In the gallery example if one disables the widgets, the text in of the combobox stays dark black.
(At least using the Qt-Backend and native style on macOS)

This also applies to the text in the listview, but i'm not sure if that is supposed to be grayed out.

**Comment by ogoffart** [comment]
This works well with the Linux style though.

**Comment by lukas-jung** [comment]
odd. is there OS specific stuff in the Qt-backend styling/render code? Or is it perhaps a Qt bug?

**Comment by ogoffart** [comment]
The cupertino style is now recommended on macOS. (and that's the default in 1.3)
closing issue related to the Qt style on macOS
