### ISSUE TITLE
Font loading timeout on macOS with Qt Backend

### ISSUE THREAD

**Issue by lukas-jung** [slint-ui/slint#1216]
When loading a custom font a message like this occurs:
`qt.qpa.fonts: Populating font family aliases took 212 ms. Replace uses of missing font family "Plaster" with one that exists to avoid this cost.`

**Comment by lukas-jung** [comment]
Maybe related to #1022

**Comment by tronical** [comment]
I can't reproduce this :(. The slide_puzzle example works well for me with Qt and it is showing the "Plaster" font as expected. @lukas-jung, do you happen to remember how you launched the slide puzzle to reproduce this?
