### ISSUE TITLE
Make VecModel::remove() return the removed value like Vec

### ISSUE THREAD

**Issue by lukas-jung** [slint-ui/slint#1221]
VecModel's remove() currently just removes the element but does not return it.
VecModel should behave similar to Vec so we should change this behavior.

**Comment by tronical** [comment]
I'm curious, why is this a breaking change?

**Comment by ogoffart** [comment]
If you change the return value of a function, it is a breaking change.

```rust
fn remove(model: &mut VecModel) {
    model.remove(42) // note: no semi colon
}
```

**Comment by tronical** [comment]
Thanks, makes sense :)
