### ISSUE TITLE
widgets: Add text-color to LineEdit

### ISSUE THREAD

**Issue by FlorentBecker** [slint-ui/slint#1232]
It would be nice to have a text-color property in LineEdit.

**Comment by ogoffart** [comment]
I wonder if we really should be able to customize our widget like this, or is this the case where a palette is sufficient (cf #116 )

**Comment by FloVanGH** [comment]
There is no plan to add styling properties like brushes, font settings and spaces to the std-widgets. Instead two alternatives are planned to make widget customization easier: #4371 #4372
