### ISSUE TITLE
`@linear-gradient` macro broken in ternary operator

### ISSUE THREAD

**Issue by levrik** [slint-ui/slint#1235]
When using the `@linear-gradient` macro in the 2nd position of the ternary operator, just the first color value found is being used.

```
Rectangle { 
    background: true ? @linear-gradient(90deg, #fff 0%, #000 100%) : #000;
}
```

![image](https://user-images.githubusercontent.com/9491603/166948156-328988fc-bc41-4311-b5e0-b199076f78f1.png)

```
Rectangle { 
    background: false ? #000 : @linear-gradient(90deg, #fff 0%, #000 100%);
}
```

![image](https://user-images.githubusercontent.com/9491603/166948297-50024705-8e90-4115-a736-f9d7dab7df88.png)

I simplified the code a lot for demonstration purposes.

These 2 codeblocks can be just copied into `Window` of https://slint-ui.com/releases/0.2.2/editor/ to reproduce.

~~I could work around by moving the gradients into a global and just reference it from inside the ternary operator. Looks like a bug in the parser to me.~~

_Edit:_ Above statement isn't true. It's also not working when using a global.

**Comment by ogoffart** [comment]
Thanks for the report. 
Looks like the ternary operator always convert to the type of the first operand when both ways are possible.

Will look into it.

**Comment by levrik** [comment]
@ogoffart Ah, this makes sense. Thanks a lot! I've worked around by ensuring that the gradient comes first for now.
