### ISSUE TITLE
Add a gained_focus / lost_focus callbacks to FocusScope

### ISSUE THREAD

**Issue by FlorentBecker** [slint-ui/slint#1236]
It would be useful to be able to run arbitrary code when a focussable element gains focus / loses. My use case is replacing a "passive" widget with an "active" (editable) one when it gets focus.

**Comment by hunger** [comment]
Maybe have a generic way to react to property changes?

I am still not sure what you actually want to achieve here:-(

**Comment by ogoffart** [comment]
Fixed with https://github.com/slint-ui/slint/pull/3650
