### ISSUE TITLE
key-pressed no animation

### ISSUE THREAD

**Issue by FloVanGH** [slint-ui/slint#1255]
I use a `FocusScope` to change a `selected-index` by left or right arrow key pressed. I navigate translate x of my layout to show the element on the selected-index. The change of `x` is animated. If I change the `selected-index` by a `clicked` handler the animation works fine but if i press left or right arrow key, x is changed but the animation does not work.

```
 focus-scope:= FocusScope {
        key-pressed(event) => {
            if(event.text == Keys.RightArrow) {
                root.selected-index = Math.min(root.selected-index + 1, 3);
                return accept;
            }

            if(event.text == Keys.LeftArrow) {
                root.selected-index = Math.max(root.selected-index - 1, 0);
                return accept;
            }

            return reject;
        }
    }

    HorizontalLayout { 
        animate x { duration: 300ms; easing: ease-in; }
        x: root.selected-index * -136px;
        spacing: 8px;
        height: parent.height;

        @children
    }
```

**Comment by FloVanGH** [comment]
Playing a little bit with fast pressing, the animation sometimes works. If I press slow no animation.

**Comment by ogoffart** [comment]
Thanks for your bug report.  I can reproduce the bug in the [wasm code editor](https://slint-ui.com/releases/0.2.4/editor/?snippet=%0A%0Aimport+%7B+SpinBox%2C+Button%2C+CheckBox%2C+Slider%2C+GroupBox+%7D+from+%22std-widgets.slint%22%3B%0Aexport+Wid+%3A%3D+Window+%7B%0A+++++property%3Cint%3E+selected-index%3B%0A%0A++++focus-scope%3A%3D+FocusScope+%7B%0A++++++++key-pressed%28event%29+%3D%3E+%7B%0A++++++++++++if%28event.text+%3D%3D+Keys.RightArrow%29+%7B%0A++++++++++++++++root.selected-index+%3D+Math.min%28root.selected-index+%2B+1%2C+42%29%3B%0A++++++++++++++++return+accept%3B%0A++++++++++++%7D%0A%0A++++++++++++if%28event.text+%3D%3D+Keys.LeftArrow%29+%7B%0A++++++++++++++++root.selected-index+%3D+Math.max%28root.selected-index+-+1%2C+0%29%3B%0A++++++++++++++++return+accept%3B%0A++++++++++++%7D%0A%0A++++++++++++return+reject%3B%0A++++++++%7D%0A++++%7D%0A%0A++++%2F*TouchArea+%7B%0A++++++clicked+%3D%3E+%7B+%0A+++++++++root.selected-index+%2B%3D+1%3B%0A++++++%7D%0A++++++height%3A+50%25%3B%0A++++%7D*%2F%0A%0A++++HorizontalLayout+%7B+%0A++++++++animate+x+%7B+duration%3A+300ms%3B+easing%3A+ease-in%3B+%7D%0A++++++++x%3A+root.selected-index+*+-136px%3B%0A++++++++spacing%3A+8px%3B%0A++++++++height%3A+parent.height%3B%0A%0A++++++++%40children%0A++++%7D%0A%7D%0A%0ADemo+%3A%3D+Wid+%7B%0A++++for+xx+in+42%3A+%0A++++++++Rectangle+%7B+width%3A+136px+-+8px%3B+border-width%3A+1px%3B+border-color%3A+red%3B%0A++++++++Text+%7B+text%3A+xx%3B+++%7D%0A++++++++%7D%0A%7D%0A)
But i cannot really reproduce it on the X11 desktop (both backend).

I'll have to investigate why the animation don't work. (Maybe something related to the time computation on wasm? (wild guess))

What platform/backend are you using?

**Comment by FloVanGH** [comment]
@ogoffart thank you for the answer.

I tested it on macOS. My guess is, that it looks like that the key event blocks the animation until the key is released. But in the meantime the x position is set through the binding.

**Comment by ogoffart** [comment]
I found out the cause: we were not registering time update before key events, causing the runtime to think that the time was still earlier than it was when the event occurs, making the starting time of the animation too much in the past.

Fix in https://github.com/slint-ui/slint/pull/1256

**Comment by FloVanGH** [comment]
@ogoffart: nice thank you :-)

**Comment by FloVanGH** [comment]
I checked your PR, it works well now :-).
