### ISSUE TITLE
Use `TryFrom` in interpreter API instead of `TryInto`

### ISSUE THREAD

**Issue by akiross** [slint-ui/slint#1258]
Using the interpreter API, I noticed that `Value` implements `TryInto` instead of `TryFrom`: this has a few drawbacks and [the doc suggests to avoid direct implementation](https://doc.rust-lang.org/std/convert/trait.TryInto.html). For example while it's possible to do

```
let v = Value::from(123i32);
let can_do: i32 = v.try_into().expect("Not a i32");
```

but it is not possible to do

```
let v = Value::from(123i32);
let cant_do: i32 = i32::try_from(v).expect("Not a i32");
```

Implementing `TryFrom<Value> for $ty` will provide a blanket implementation for `TryInto<$ty> for Value`, while the inverse is not true. This would also allow to implement functions with generic types that can be obtained from a value, like `where T: TryFrom<Value>` - while AFAICT this is not possible with the current implementation, without using workarounds.

I [forked slint](https://github.com/akiross/slint/) with the intent to open a PR, but I stopped before actually opening it because I'm not sure if this choice was intentional or not (I see no reason why to avoid implementing `TryFrom` instead of `TryInto`, but you might have some).

Would a PR be welcome to fix this?

**Comment by ogoffart** [comment]
Yes, please open a PR.  I don't think this was intentional

**Comment by ogoffart** [comment]
And, in fact, since the conversion cannot fail, i believe even implementing `From` would be working
