### ISSUE TITLE
Window size and resizing issues (GL)

### ISSUE THREAD

**Issue by lukas-jung** [slint-ui/slint#1269]
The calculated window size is not respected after resizing.
Also the jittering...

https://user-images.githubusercontent.com/22800467/168301439-518f5538-3a3c-47a3-acfc-39e1f1787892.mov

**Comment by ogoffart** [comment]
I cannot reproduce that on my X11 setup.
I assume you just take the tempconv.slint example and remove the `prefered-height` 
Maybe it is mac specific because the window is risized too small for mac?

**Comment by lukas-jung** [comment]
Happens with compiled code as well when using the GL Backend.

**Comment by ogoffart** [comment]
Maybe you can add some debug in the `WinitWindow::apply_window_properties` in event_loop.rs and try to figure what happens.

**Comment by lukas-jung** [comment]
It is a regression caused by 16a0f28449330c9aee89a2c2a3a66b745b3b6245.
