### ISSUE TITLE
figma import broking due to Clip?

### ISSUE THREAD

**Issue by fdncred** [slint-ui/slint#1288]
I created a Figma and tried to use the `figma_import` command and it created a nice looking slint file however I'm getting errors because `Clip`. Was `Clip` renamed or something?

![image](https://user-images.githubusercontent.com/343840/169543618-836a3d16-0c66-4355-8dec-0a6697f56627.png)

**Comment by ogoffart** [comment]
Thanks for testing the figma import.  This hasn't bee touched for a quite long time and the `Clip` element was indeed replaced by a `clip:` property some time ago already.

I just pushed a change to use the right property instead of the element.
