### ISSUE TITLE
How to open file dialog to save or choose file

### ISSUE THREAD

**Issue by pubg-hacks** [slint-ui/slint#1296]
Is there a method in slint to open a file dialog  ?

**Comment by ogoffart** [comment]
One way to do it is to use the rfd create https://lib.rs/crates/rfd
For example that is what the cargo ui program does: https://github.com/slint-ui/cargo-ui/blob/3e2780dbffc9f123fc5205ffe242805d887f49ad/src/cargo.rs#L655

**Comment by pubg-hacks** [comment]
thanks. also how to use the fluent style because the current look is very ugly !

**Comment by ogoffart** [comment]
with the SLINT_STYLE environment variable, or using slint_build::CompilerConfiguration::with_style  and slint_build::compile_with_config

**Comment by ogoffart** [comment]
I am closing this issue because i believe the question has been answered.

If you have more question, just use the discussions: https://github.com/slint-ui/slint/discussions
