### ISSUE TITLE
`StandardListView` selection callback

### ISSUE THREAD

**Issue by melvyn2** [slint-ui/slint#1299]
Having a callback for when the selected element is changed would be useful, for similar reasons to `TextEdit`/`LineEdit`: validation, updating buffers, or the rest. I imagine that it would be something like `selected(int)` with `int` being the index, though `LineEdit` emits a simple callback without arguments so there may be a tradeoff I'm missing (an int should be easier to pass around on the other hand).

**Comment by FloVanGH** [comment]
With `1.2.0` the `StandardListView` has now a `current-item-changed` callback.
