### ISSUE TITLE
Unable to run on Mac OS 12.1: symbol not found in flat namespace '__Z5qHash11QStringViewm'

### ISSUE THREAD

**Issue by sheldonth** [slint-ui/slint#1306]
I tried running the slint-rust-template and I'm getting a dyld error. 

$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/foobar`
dyld[84140]: symbol not found in flat namespace '__Z5qHash11QStringViewm'
Abort trap: 6

Apple Silicon M1

Any ideas how I might approach fixing that?

**Comment by ogoffart** [comment]
One way to workaround the issue is to build without Qt (disabling the backend-qt feature or setting the SLINT_NO_QT=1 env variable when running cargo)

As for the reason this happen, i don't really know. maybe it does not use the same version of Qt to compile and to run?

**Comment by sheldonth** [comment]
Ah, that did indeed fix it. I had an old version of Qt (build for x86-64) lingering on the machine (which is aarch64) so once I removed that and did a clean build everything fell into place. Thank you for the help.
