### ISSUE TITLE
Read only line and text edits and a context menu when right click

### ISSUE THREAD

**Issue by pubg-hacks** [slint-ui/slint#1314]
It will be very nice to have a read only line edit or text edit that is enabled but does not allow users to edit its content it only allows them to select text and copy it. Also currently there is no context menu shown when right clicking on a text edit.

**Comment by hunger** [comment]
Yes, that would indeed be great to have!

**Comment by pubg-hacks** [comment]
accept the pull request I opened https://github.com/slint-ui/slint/pull/1320
