### ISSUE TITLE
How to set background and text colors for each widget indepentely

### ISSUE THREAD

**Issue by cppdev123** [slint-ui/slint#1315]
I'm currently missing how to set colors for each widget does slint support this yet ?

**Comment by pubg-hacks** [comment]
If I add a pr will it be accepted ?

**Comment by tronical** [comment]
My feeling is that instead of giving every widget an explicit API for each configurable color property, I think it would be better if we had a palette and it's possible to override the palette of a widget. See also #116.

**Comment by ogoffart** [comment]
but closing this in favor of #116
