### ISSUE TITLE
MCU Simulator shows black Rectangles

### ISSUE THREAD

**Issue by lukas-jung** [slint-ui/slint#1324]
To reproduce start the printerdemo_mcu with `cargo run -p printerdemo_mcu --features=mcu-simulator --release`
![Screen Shot 2022-06-07 at 11 18 42](https://user-images.githubusercontent.com/22800467/172367388-991a297d-2911-4857-be2a-490e01834f20.png)

**Comment by ogoffart** [comment]
That's a bug in the simulator that should be fixed.
(On the other hand it shows the the partial renderer working, so i'm using that as a feature :-) )

But current simulator architecture using winit is not great. We should review that with the new backend API.
I'd say that the current GL backend (which should probably be renamed "winit") could use the software renderer with an env variable and/or a feature.
