### ISSUE TITLE
Support for Gifs and Monaco

### ISSUE THREAD

**Issue by Iskra-Never-Dies** [slint-ui/slint#1326]
I'm trying to add Monaco to a UI I am writing and I'm not sure if loading HTML elements is possible , I am also wondering if Slint supports Gifs and not just images

**Comment by tronical** [comment]
At the moment we don’t support animated GIFs.

We’re in the process of moving the image decoding into the core library and then we could consider using image-rs’s support for animated GIFs, webp and apng.

How do you generated your animated clips? What are they like in terms of resolution?

**Comment by Iskra-Never-Dies** [comment]
I'm not really sure as for the specifcs, as we found this gif on some random website, but this is it
![sea](https://user-images.githubusercontent.com/73405388/172491369-c0d60368-a3b0-4ac9-8fd2-ca57f8c318e3.gif)

As for the monaco does Slint support that?

**Comment by tronical** [comment]
Ok, that sounds alright.

About Monaco: Do you mean embedding the Monaco editor in Slint?

**Comment by Iskra-Never-Dies** [comment]
Yeah, I'm not sure at all how to implement it as I'm not sure how to load HTML elements

**Comment by tronical** [comment]
I’m afraid that embedding HTML elements or components like the Monaco editor is not possible with Slint :(
