### ISSUE TITLE
Fonts (on Windows?) are blurry

### ISSUE THREAD

**Issue by megahomyak** [slint-ui/slint#1362]
Compare the window title and the window contents on the image below. The window title is much sharper than any of the texts in the window.
![Blurry font demonstration](https://user-images.githubusercontent.com/58137927/174333568-59c2581c-7b4b-429d-ba26-168b2162e04c.png)

It can be replicated with any font size and any text-containing element. I have a 1920x1080 display, the OS is Windows 10 and the scaling factor is 1.25 (texts still remain blurry when switching to 1.00). That's the setting I'm talking about:
![Windows scaling factor](https://user-images.githubusercontent.com/58137927/174334760-9f6548c7-8952-49f9-865b-03b011f2fb12.png)

I am using slint v. 0.2.4

**Comment by pubg-hacks** [comment]
same for me https://github.com/slint-ui/slint/issues/1313

**Comment by tronical** [comment]
With the GL backend text is indeed not rendered by Window's own rasteriser but using femtovg. This will always look slightly different. In the context of femtovg we've been discussing plugging in custom rasterisers, and so eventually support for windows native text rendering could be added as a setting perhaps.

Another way to avoid this issue is to use the Slint's Qt backend.

**Comment by tronical** [comment]
The availability of using Skia as renderer solves this issues. You can for example enable it at compile-time via the `renderer-winit-skia` feature and select it at run-time using `SLINT_BACKEND=Skia`. Similarly, there's a CMake feature for enabling the Skia renderer.

**Comment by NEXINEW** [comment]
Bro, I'm using this configuration: 
[dependencies]
slint = { version = "1.13", features = ["backend-qt"] }
But the rendered text is still very blurry

**Comment by ogoffart** [comment]
@NEXINEW Are you using the Qt backend on Windows?
Please open a new issue with screenshot so we can see what you are talking about.
With the Qt backend, the rendering is done by Qt and this is then probably a Qt issue, unless we forgot to set some flags.
