### ISSUE TITLE
Size of the TabBar is not calculated considering its label sizes + unshrinkable window

### ISSUE THREAD

**Issue by megahomyak** [slint-ui/slint#1363]
I wrote the following slint markup: https://gist.github.com/megahomyak/2cec4e7eca97413170ec93e9527a5996
That's how the window looks when spawned:
![Very small window](https://user-images.githubusercontent.com/58137927/174335236-6bf3cfea-bb94-4552-8f62-804ba9d2838f.png)

Also, if I add `width: parent.width` to the `LineEdit` (in the markup above), I can't shrink the window horizontally after resizing it. The same does _not_ happen when I add the same property to the `record-voice-button`.

I am using slint v. 0.2.4

**Comment by hunger** [comment]
A tab bar is surprisingly tricky: Tabs are expected to shrink up to a minimum size that basically displays an elision only:-/ Tab bars also are expected to scroll left/right as they can overflow. None of this is supported in slint at this time :-(

On the other hand some tab bars are expected to not shrink below a size where all tabs are readable.

**Comment by ogoffart** [comment]
The native style's minimum size is working fine. But the fluent style tabbar doesn't seem to have a minimum size.  So definitively a bug in the fluent style.
