### ISSUE TITLE
Support for multiple windows

### ISSUE THREAD

**Issue by DBLouis** [slint-ui/slint#1377]
I could not find a way to instantiate multiple windows. Is this currently not possible?

**Comment by tronical** [comment]
It is possible, but it's a little tricky.

Suppose you have `MyWindow1 := Window { ... }` and `MyWindow2 := Window { ... }` and want to show them. To overcome #784 you could put say `MyWindow2` into a helper crate, build it using [build.rs](https://slint-ui.com/releases/0.2.4/docs/rust/slint/#the-slint-code-in-external-files-is-compiled-with-buildrs) and export it. Then in your main crate you can import `MyWindow` and then write something like this:

```rust
fn main() {
    let my_window_1 = MyWindow1::new();
    let my_window_2 = helper_create::MyWindow2::new();
    my_window_1.show();
    my_window_2.show();
    slint::run_event_loop();
}
```

I haven't tested this, but this might work as workaround until #784 is resolved.

**Comment by ogoffart** [comment]
Closing as the main issue is tracked in https://github.com/slint-ui/slint/issues/784

**Comment by Davidc2525** [comment]
> It is possible, but it's a little tricky.
> 
> Suppose you have `MyWindow1 := Window { ... }` and `MyWindow2 := Window { ... }` and want to show them. To overcome #784 you could put say `MyWindow2` into a helper crate, build it using [build.rs](https://slint-ui.com/releases/0.2.4/docs/rust/slint/#the-slint-code-in-external-files-is-compiled-with-buildrs) and export it. Then in your main crate you can import `MyWindow` and then write something like this:
> 
> ```rust
> fn main() {
>     let my_window_1 = MyWindow1::new();
>     let my_window_2 = helper_create::MyWindow2::new();
>     my_window_1.show();
>     my_window_2.show();
>     slint::run_event_loop();
> }
> ```
> 
> I haven't tested this, but this might work as workaround until #784 is resolved.

I don't know how to do it, can you leave an example?

**Comment by Davidc2525** [comment]
> It is possible, but it's a little tricky.
> 
> Suppose you have `MyWindow1 := Window { ... }` and `MyWindow2 := Window { ... }` and want to show them. To overcome #784 you could put say `MyWindow2` into a helper crate, build it using [build.rs](https://slint-ui.com/releases/0.2.4/docs/rust/slint/#the-slint-code-in-external-files-is-compiled-with-buildrs) and export it. Then in your main crate you can import `MyWindow` and then write something like this:
> 
> ```rust
> fn main() {
>     let my_window_1 = MyWindow1::new();
>     let my_window_2 = helper_create::MyWindow2::new();
>     my_window_1.show();
>     my_window_2.show();
>     slint::run_event_loop();
> }
> ```
> 
> I haven't tested this, but this might work as workaround until #784 is resolved.

I loved slint until I saw that you can create multiple windows, I tried the popupwindow and it turns out that if you open one popup inside another the app freezes
