### ISSUE TITLE
macOS: preview of non-window with unspecified size does not work anymore

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#1395]
With commit e1b4727c9c63facb9e103d1ba363935db8d09e1f previewing the following minimal test-case does not work anymore:

```
MyRect := Rectangle {
    background: green;
}
```

Before this commit (or locally reverted), a green rectangle is shown. After the change a white rectangle is shown.

**Comment by lukas-jung** [comment]
Fixed by #1397
