### ISSUE TITLE
Application logic code separation

### ISSUE THREAD

**Issue by and-elf** [slint-ui/slint#1405]
As a qt developer, I'm used to register an implementation of a backend class to the runtime so that all logic doesn't have to reside in main.cpp. As far as the examples go, all interactions have to be aliased in mainwindow or be located in global scope.
 Is there a way to handle interactions more like it's done in qt?
Maybe the parser have to be changed for this to work? Make it possible to include cpp/rust/js types in slint files?

**Comment by tronical** [comment]
Yes, this is missing functionality. I think #251 captures the same, with some discussion.

**Comment by Lwing** [comment]
Ok, thank you.
I'll try to change the parser/generator to add support to include CPP types to slint.

**Comment by ogoffart** [comment]
Closing as Duplicated of #251
