### ISSUE TITLE
Enums in .slint

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#150]
We should have a way to declare enums in .slint.

```60
enum Foo { bar, bli, bla, blu }
```

**Comment by ogoffart** [comment]
Currently, all our built-in enums values are kebab-case.  The rational for that is that this is closer to CSS syntax.

When we will be able to declare enum values in slint, we will generate Rust or C++ enum.
But in Rust the convention is to use CamelCase enum values.

Should we keep the convention of lower case enum values for enums declared in .slint files by users?

Should we somehow enforce this convention with warning like rust do?

Should we convert to CamelCase enum values while generating rust code?
Or should we make it configurable somehow?

For the builtin enums, they are currently not part of our public API, but maybe they would become part of it. Should we change them to be CamelCase in rust and C++?

**Comment by ogoffart** [comment]
> >  Should we convert to CamelCase enum values while generating rust code?
>
> Could this be done in an automated way? I can't think of how.

Yes we can of course. The compiler can do that, and already does for some internal accessibility enum: https://github.com/slint-ui/slint/blob/ee18236053c6073fedd2497bbd904c4541100880/internal/compiler/llr/lower_to_item_tree.rs#L287 

> >  For the builtin enums, they are currently not part of our public API, but maybe they would become part of it. Should we change them to be CamelCase in rust and C++?
>
> I'm in favor of that, yes.

I'll make that change then.

**Comment by tronical** [comment]
Ah yes, thanks for the reminder. Somehow I thought the types are `randomcamecase` but we have separators between them :)
