### ISSUE TITLE
Review API Documentation of new platform/backend API

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#1502]
This is a reminder task to go through the documentation of the new window and backend traits, the new functions added to the `api::Window`.

**Comment by ogoffart** [comment]
This include:

 - the whole [platform](https://slint-ui.com/snapshots/master/docs/rust/slint/platform/index.html) module.
 - [Window::dispatch_event](https://slint-ui.com/snapshots/master/docs/rust/slint/struct.window#method.dispatch_event) and the  [WindowEvent](https://slint-ui.com/snapshots/master/docs/rust/slint/enum.windowevent) structure
 - the setter and getter for the size and position in the Window struct. As well as the Physical and Logical size and position type and the scale factor
 - [Window::has_active_animations](https://slint-ui.com/snapshots/master/docs/rust/slint/struct.window#method.has_active_animations)
 - the [format](https://slint-ui.com/snapshots/master/docs/rust/slint/macro.format.html) macro
 - some new [feature flags](https://slint-ui.com/snapshots/master/docs/rust/slint/#feature-flags)

**Comment by ogoffart** [comment]
We'll make an API review meeting tomorrow (Tuesday 06.10) at 10:00 CET on [our Mattermost](https://chat.slint-ui.com) (everyone welcome)

**Comment by tronical** [comment]
Notes from the meeting:

# Version number

We decided to increase the version to 0.3.0.

# platform module

* `swrenderer` -> `slint::platform::software_renderer` (T)
* Always compile the `software renderer`, independent of the `renderer-software` feature on the API crate (O)
* Try to see if `set_platform` can be changed to take `Into<Box<...>>` (S)
* Introduce `SetPlatformError` enum that has `AlreadySet` (S)
* return an error from the function of the EventLoopProxy (O)

# SoftwareRenderer (O)

- remove the `=0` for BUFFER_COUNT
- rename `BUFFER_COUNT` to `MAX_BUFFER_AGE`
- Hide implementation of `Renderer` trait from the documentation (don't show internal `text_size` etc. functions)

# `TargetPixel` trait (O)

- Rename `to_fill` to `slice` in `blend_slice`

# slint crate features (O)

* Remove `renderer-software` feature, always support it in the `winit` backend.
* Make sure the error message if no "gl" renderer is enabled is sensible
* Move `log` feature out of the "Backends" section
* Remove compatibility features (also from cmake and interpreter, etc. crates)
* Rename eventloop-* to backend-*
* Remove the `renderer-qt` as an alias
* renderer-*  not strongly depend on winit in the selector
* Documentation should include a matrix/table of supported combinations

# `slint::testing` module (O)

* Move to the `i-slint-backend-testing` crate

# `slint::api::Window`

- Try to get rid of `WindowHandleAccess` trait (alternative: free standing function to get window inner), otherwise try to hide the docs for `impl WindowHandleAccess` (S)
- Fix docs for `scale_factor` to not mention euclid (S)
- Replace `set_position`/`position`/`set_size`/`size` with (S)
  - rust: `set_physical_position`/`set_logical_position`/`physical_position`/`set_physical_size`/`set_logical_size`/`physical_size`
  - js: `physical_position` and `logical_position` properties

**Comment by tronical** [comment]
This is done. There's a pending discussion about the type names `WindowSize` vs. `RequestedSize` vs. `RequestedWindowSize` but that's orthogonal and we might just skip it :)
