### ISSUE TITLE
Review the terms `Backend` and `PlatformWindow` in the public API

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#1503]
Let's have a discussion about if those are the right names or if there are better options.

Generally, the term "backend" has precedence in cargo features and documentation since early on. But there are ways that we can still play with this and mix and match if necessary.

**Comment by ogoffart** [comment]
This include (non exhaustive list)
 - new functions in Window
 - PointerEvent
 - SoftwareRenderer and co.
 - the Backend traits (PlatformWindow trait, Backend trait)
 - ...

**Comment by tronical** [comment]
The plan is to rename `PlatformWindow` to `WindowAdapter` and `PlatformAbstraction` to just `Platform`. `create_window()` then becomes `create_window_adapter()`.
