### ISSUE TITLE
Failed to create OpenGL context

### ISSUE THREAD

**Issue by LeoGitHuber** [slint-ui/slint#1507]
I used `cargo run` to run slint project, but failed.

>    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
>     Running `target/debug/slint_try`
> thread 'main' panicked at 'Failed to create OpenGL context: could not create GlLatest context : Couldn't find any pixel format that matches the criteria.', /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-gl-0.2.5/glcontext.rs:167:17
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
>    1: core::panicking::panic_fmt
>              at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
>    2: i_slint_backend_gl::glcontext::OpenGLContext::new_context_and_renderer::{{closure}}
>              at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-gl-0.2.5/glcontext.rs:167:17
>    3: i_slint_backend_gl::event_loop::with_window_target::{{closure}}
>              at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-gl-0.2.5/event_loop.rs:265:13
>    4: std::thread::local::LocalKey<T>::try_with
>              at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
>    5: std::thread::local::LocalKey<T>::with
>              at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
>    6: i_slint_backend_gl::event_loop::with_window_target
>              at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-gl-0.2.5/event_loop.rs:261:9
>    7: i_slint_backend_gl::glcontext::OpenGLContext::new_context_and_renderer
>              at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-gl-0.2.5/glcontext.rs:108:36
>    8: <i_slint_backend_gl::glwindow::GLWindow as i_slint_core::window::PlatformWindow>::show
>              at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-backend-gl-0.2.5/glwindow.rs:471:13
>    9: i_slint_core::window::Window::show
>              at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-core-0.2.5/window.rs:546:9
>   10: i_slint_core::api::Window::show
>              at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-core-0.2.5/api.rs:122:9
>   11: <slint_try::slint_generatedMainWindow::MainWindow as i_slint_core::api::ComponentHandle>::show
>              at ./src/main.rs:5:1
>   12: <slint_try::slint_generatedMainWindow::MainWindow as i_slint_core::api::ComponentHandle>::run
>              at ./src/main.rs:5:1
>   13: slint_try::main
>              at ./src/main.rs:2:5
>   14: core::ops::function::FnOnce::call_once
>              at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by tronical** [comment]
That’s a little unusual. You’re on Linux, right? Are you using Wayland or X11?

**Comment by LeoGitHuber** [comment]
yes. I work on ubuntu 22.04 wayland.

**Comment by tronical** [comment]
I think #1724 fixes this. Could you try again with current Slint?

**Comment by LeoGitHuber** [comment]
ok now, thanks.
