### ISSUE TITLE
Add support for nine patch images / border images

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#1529]
For image based UIs it is common to use images where the image can be divided into a grid of nine tiles where the nature of the image would allow for certain tiles to be scaled. We should have a BorderImage element that breaks a regular image into nine patches and then allows configuring how the regions behave when changing the size:

|1|2|3|
|-|-|-|
|4|5|6|
|7|8|9|

Typically the corners are not scaled, the regions 2, 4, 6 and 8 can be scaled or repeated.

In QML this is called BorderImage, as well as in CSS (with different APIs).

This can be implemented directly in Slint, but it would be more efficient to have this as a built-in element so that we can use renderer specific optimised ways of rendering these kinds of images that for example allow sharing the underlying texture.

**Comment by FoundationKen** [comment]
I needed this recently and took a pass at it in pure Slint and got it mostly working, but it really wants to have two features:

1. Tiled background images (tile horizontally, vertically or both)
2. Fixed-size images (do not scale the image)

I hacked around the first issue by making the edge images as large as the largest possible size I needed and then using some nesting and clipping.

For the second, I forced the width and height to the width and height of the image.  Would be nice if this was a an option for `image-fit`.

Here is the slint code below (I would have made a SlintPad, but I don't think there is a way to upload image files there to reference).

```
export component NineSliceImage inherits Rectangle {
    // Overridden properties
    clip: true;

    // Private properties
    // private property <int> h-repeats: ((self.width/1px - top-left.width - top-right.width)/top-middle.width);
    // private property <int> v-repeats: (self.height/1px - top-left.height - bottom-left.height)/middle-left.height;

    // Public properties
    in property <string> id;
    in property <image> top-left;
    in property <image> top-middle;
    in property <image> top-right;
    in property <image> middle-left;
    in property <image> middle-middle;
    in property <image> middle-right;
    in property <image> bottom-left;
    in property <image> bottom-middle;
    in property <image> bottom-right;

    // Top Row
    VerticalLayout {
        alignment: stretch;
        HorizontalLayout {
            alignment: stretch;
            Image {
                source: top-left;
                width: top-left.width * 1px;
                height: top-left.height * 1px;
            }
            Rectangle {
                clip: true;
                horizontal-stretch: 1;
                Image {
                    source: top-middle;
                    x: 0px;
                    y: 0px;
                    height: top-middle.height * 1px;
                    width: top-middle.width * 1px;
                }
            }
            Image {
                source: top-right;
                width: top-right.width * 1px;
                height: top-right.height * 1px;
            }
        }
        // Middle Row
        HorizontalLayout {
            alignment: stretch;
            vertical-stretch: 1;
            Image {
                source: middle-left;
                width: middle-left.width * 1px;
                image-fit: cover;
            }
            Rectangle {
                clip: true;
                horizontal-stretch: 1;
                Image {
                    source: middle-middle;
                    image-fit: fill;
                    width: 100%;
                    height: 100%;
                }
            }
            Image {
                source: middle-right;
                width: middle-right.width*1px;
                image-fit: cover;
            }
        }

        // Bottom Row
        HorizontalLayout {
            alignment: stretch;
            Image {
                source: bottom-left;
                width: bottom-left.width*1px;
                height: bottom-left.height*1px;
            }
            Rectangle {
                clip: true;
                horizontal-stretch: 1;
                Image {
                    source: bottom-middle;
                    height: bottom-middle.height * 1px;
                    width: bottom-middle.width * 1px;
                }
            }
            Image {
                source: bottom-right;
                width: bottom-right.width * 1px;
                height: bottom-right.height * 1px;
            }
        }
    }

    @children
}
```

**Comment by ogoffart** [comment]
Thanks for the code snippet.

> Would be nice if this was a an option for image-fit.

#3784 (for reference)

**Comment by ogoffart** [comment]
I discussed this with @tronical and we came to the conclusion that the border is a property of the image and should be included in the image type.

So we'll add an optional argument to @image-url:

```
Image {
 source: @image-url("foo.png", 9slice(44 77 77 78))
}
```

the number follow the rules of css:  `top | right | bottom | left` if there are 4 numbers, or `top and bottom | left and right` if there is two numbers, one number is also valid.

And We're going to add to our rust api (and equivalent for other languages)
```rust
slint::Image::set_9_slice_edges(&mut self, top: usize, right: usize, bottom: usize, left: usize)
```

The border and centered are tiled according to the tiling as defined in #3784

**Comment by FoundationKen** [comment]
So that rectangle is defining the insets?

Will the center segment be tiled as the image expands?

**Comment by ogoffart** [comment]
> Will the center segment be tiled as the image expands?

Depending on the value of tiling property as defined in #3784

**Comment by FoundationKen** [comment]
Will the implementation work properly if any of the offsets are zero?  For example, if I only want a vertical or horizontal stretching (3 slice) image, say a custom scrollbar background?
