### ISSUE TITLE
Rename `PlatformAbstraction` and `PlatformWindow`

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#1536]
In the API review we decided to rename

    `PlatformWindow` to `PlatformAdapter`

and

    `PlatformAbstraction` to just `Platform`

`create_window` in `Platform` becomes `create_window_adapter`, and `set_platform_abstraction()` becomes `slint::platform::set_platform()`.

**Comment by hunger** [comment]
Actually we decided to rename `PlatformWindow` to `WindowAdapter`

**Comment by tronical** [comment]
That’s right:)
