### ISSUE TITLE
Regression: Plotters example shows a black border

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#1558]
The plotters example shows a black border since the 0.2.5 release:

https://slint-ui.com/releases/0.2.5/demos/plotter/

This is not visible in

https://slint-ui.com/releases/0.2.4/demos/plotter/

It's also reproducible on the desktop for me.

It appears that this is fixed upstream at https://github.com/plotters-rs/plotters/issues/368 but upgrading to the newer version causes some build issues:

```
the package `servo-fontconfig` links to the native library `fontconfig`, but it conflicts with a previous package which links to `fontconfig` as well:
package `font-kit v0.11.0`
    ... which satisfies dependency `font-kit = "^0.11.0"` of package `plotters v0.3.3
```

It might be possible to work around this by pre-filling the image on the example side.

**Comment by ogoffart** [comment]
> It might be possible to work around this by pre-filling the image on the example side.

I don't think we should attempt a work around. 
We should ideally fix our use of fontconfig and stuff so that we can make this work.

**Comment by tronical** [comment]
Possibly related PR: https://github.com/slint-ui/slint/pull/956

**Comment by ogoffart** [comment]
Fixed.
