### ISSUE TITLE
Allow individual border radius values for `Rectangle` elements

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#157]
This issue originates from #156 . In CSS the `border-radius` property is short-hand for four individual radius properties:

  * `border-top-left-radius`
  * `border-top-right-radius`
  * `border-bottom-right-radius`
  * `border-bottom-left-radius`

We should support that, to achieve effects like described in #156 (and femtovg at least supports that)

**Comment by ogoffart** [comment]
While we are on it, we probably need border-top-width, border-left-width, ...  and border-bottom-color, border-right-color, ...

(Maybe we even want to support border-style to have dashed or other fancy border)

**Comment by ogoffart** [comment]
Workaround: One can use Path element (or several Path's) to simulate what we want instead of Rectangle.
