### ISSUE TITLE
Images permanently stored in memory with no limit?

### ISSUE THREAD

**Issue by NotAgentBilly** [slint-ui/slint#1578]
I'm just messing around with slint and have a ListView that displays a lot of images, I've noticed that the memory of the app only seems to keep increasing when scrolling through the images. I may be wrong but I'm assuming this is because slint caches images internally and is there anything that I can do about it?

![image](https://user-images.githubusercontent.com/82730686/187975638-04e767f0-ed41-4778-8c5e-937eacea21a2.png)

**Comment by tronical** [comment]
Hmm, could you try with a git version? We have a 5MB cache in place for that now that should not grow beyond that. But perhaps there’s a bug somewhere.

**Comment by NotAgentBilly** [comment]
Ah, apologies for not trying that first. Git version hovers ~170mb, so seems to be resolved.
![image](https://user-images.githubusercontent.com/82730686/188017947-8c0599fb-3c43-4b72-a379-3fc85efb206f.png)

**Comment by ogoffart** [comment]
Thanks for reporting the bug. 

Closing this issue since it is fixed in the next release.
