### ISSUE TITLE
Compute dirty region instead of re-drawing the while window for each frame

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#158]
Currently, we redraw the whole window. We should limit ourselves to redraw regions that are actually dirty.

**Comment by tronical** [comment]
This also makes sense to do for the GL renderer. Even if all pixels are always rendered, not all of them need to be copied to the screen by the compositor. There's an EGL extension for that where at the time swapBuffers is called, a region is provided as argument, and the compositor will copy less pixels. Glutin supports that in the [ContextWrapper](https://docs.rs/glutin/0.28.0/glutin/struct.ContextWrapper.html#method.swap_buffers_with_damage).

**Comment by ogoffart** [comment]
The software rendered does that.
