### ISSUE TITLE
tried on master branch

### ISSUE THREAD

**Issue by langzime** [slint-ui/slint#1587]
![图片](https://user-images.githubusercontent.com/3364128/188426569-4229e253-d1cd-49f5-993e-b2e2f4099ded.png)

**Comment by ogoffart** [comment]
thanks for reporting the issue.

I think this might be a bug in one of the dependencies, that did not specify their dependency properly.

`cargo update` should solve the issue

**Comment by tronical** [comment]
Yes, and this is now also fixed in upstream winit AFAIK.
