### ISSUE TITLE
Add a method like setCentralWidget() in The Qt Widget QMainWindow to Window in order to  allow loading a page in another or update the UI easily.

### ISSUE THREAD

**Issue by Aquiles-o-rei** [slint-ui/slint#1705]

**Comment by Aquiles-o-rei** [comment]
yes , suppose i have a DockWidget  containing several button, and i want to load a central widget depending on the button i clicked .

**Comment by ogoffart** [comment]
I have created https://github.com/slint-ui/slint/issues/1722 and https://github.com/slint-ui/slint/issues/1723 to track the page and dockwidget issues.
