### ISSUE TITLE
In C++, calculating "px" generates type conversion error

### ISSUE THREAD

**Issue by teminian** [slint-ui/slint#1732]
**Working environment:** Windows 11, VC++2022
**Symptom:**
When I put some calcuations into px-unit stuff (for example "x" or "y"), VC++ compiler emits error message of `error C2397: conversion from 'double' to 'float' requires a narrowing conversion`. To resolve this, I have to remove (double) from the represent line.

For example, in Slint I'd put
```
y: parent.height/2
```

It seems to be translated like
```
return [&]{ self->root->window().window_handle().show_popup<Component_popup_6>(self, { (self->root_1.width.get() /(double) 2), 0 }, { self->self_weak.lock()->into_dyn(), self->tree_index }); }();


```
which generates compiler complaint mentioned above. I had to remove **(double)** from `/(double) 2` in the above code to correct it.

I think this is malfunctioning of Slint-to-C++ transpiler. Can you please review and fix it?

P.S: I'm not sure about what happens in Linux environment.

**Comment by ogoffart** [comment]
I'd thought that such conversion would actually be only warnings (wich we would still need to avoid).
But apparently the Point construction for the popup might be an error. So we will need to use explicit conversions there.
Will look into it. Thanks for reporting.

**Comment by teminian** [comment]
In some conditions Visual C++ is more strict than GCC for emitting errors or warnings. I think if it were GCC it would still work, since clangd just "warns" about that. Anyway, to maintain the compatabilities against various C++ compilers, it needs to be fixed.
