### ISSUE TITLE
rustc can't recognize Slint struct from the module

### ISSUE THREAD

**Issue by teminian** [slint-ui/slint#1733]
**Working environment:** Windows 11, Rust 1.64.0, Slint 0.3.0
**Symptom:**
If there's a Slint struct inside a module, after transpiling(preprocessing?) Slint to Rust source code rustc complains that it can't find the struct. For example,

**module1.slint**
```
struct S1:={
    // ......
}

Module:=VerticalLayout {
    property<[S1]> property1;
    ListView {
        for p1[i]: property1: Rectangle {
            ......
        }
    }
}

export { Module };
```

**mainwindow.slint**
```
import { Module } from "./module1.slint"

export MainWindow:=Window{
    ......
    Module {
        // ......
    }
}
```

In the source code above rustc complains that it can't find Slint struct S1, which is used only inside `Module`. Currently the only workaround is to use anonymous struct, and techniques like exporting struct or separating struct to independent source code doesn't help. Can you help me find out what's wrong?

**Comment by ogoffart** [comment]
Thanks for reporting this. This is definitely a bug and we'll see how to fix this.

As a workaround, it is likely that adding a dummy `property<S1> dummy;` in the root should make it sure that slint detects that this struct needs to be generated.

**Comment by teminian** [comment]
Thank you for the workaround. I confirmed it works, though I have to export the struct and make a dummy property in root.

Let me wait for the bugfix. Keep going the good work!
