### ISSUE TITLE
Extend `WindowEvent` enum and handle in `dispatch_event`

### ISSUE THREAD

**Issue by FloVanGH** [slint-ui/slint#1745]
At the moment only pointer events are part of the `WindowEvent` enum. It need to be extended to also support other event types such as key events. The now introduced event types in the enum must then handled in the `dispatch_event` of `Window`.

**Comment by ogoffart** [comment]
The `impl From<crate::api::WindowEvent> for MouseEvent {`  can be removed, and instead the transformation can be done in `dispatch_event`

**Comment by ogoffart** [comment]
Done in 0.3.2
