### ISSUE TITLE
Change type of `text` in `WindowEvent` keyevent to `SharedString`

### ISSUE THREAD

**Issue by FloVanGH** [slint-ui/slint#1749]
To prevent #1747 to introduce a braking change by using `SharedString` for key event text what make it necessary to remove `Clone` derive from `WindowEvent`, char will be used now. It should be replaced by `SharedString` for 0.4.

**Comment by ogoffart** [comment]
I used to think that keys cannot be represented by a `char` and therefore the keys should always be a string instead of a char.
But i now have my doubts.  Maybe `char` is actually enough?

**Comment by tronical** [comment]
Tobias was the last person to have input on this in the previous PR:

https://github.com/slint-ui/slint/pull/1747#issuecomment-1308448798
https://github.com/slint-ui/slint/pull/1747#issuecomment-1308543169

One compelling argument I see is that Apple went for a string as well: 
https://developer.apple.com/documentation/uikit/uikey/3526130-characters
