### ISSUE TITLE
Global cannot access other globals

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#175]
Testcase: 

```qml
global Foo := {
    property <string> hi: "Hi";
}

global Bar := {
    property <string> ho: Foo.hi;
}

export Demo := Window {
    Text {
        text: Bar.ho;
    }
}
```

Tested at least with the interpreter which panics.

**Comment by tronical** [comment]
One possible way of fixing this would be to combine all the properties in the globals into one global just in the implementation/generator.
