### ISSUE TITLE
Visibility does not work when using for .. in expression

### ISSUE THREAD

**Issue by xgroleau** [slint-ui/slint#1846]
It seems the visible property is not working properly when in a for loop. Maybe it's  the case for other property but I'm not sure.

First example. Here we can see the teal square while no square should be shown. Probably that no component are affected by the `visible` property.
```slint
export AppWindow := Window {
    width: 240px;
    height: 240px;

   // Setting to `property <[color]> rectangles: [#f15959, #278090];` gives the same result.
    property <[color]> rectangles: [#278090]; 
    
    
    for rect in rectangles: Rectangle {
        visible: false;
        background: rect;
    }
}
```
![image](https://user-images.githubusercontent.com/31734358/201372669-65f1b501-1031-407c-8654-6f07ceb5f642.png)

Second example is weird. Here only the red square is show and not the teal. I don't understand why the behavior is different here. If the behavior matched the first case, both colors would be shown but only one is.
```slint
export AppWindow := Window {
    width: 240px;
    height: 240px;

    property <[color]> rectangles: [#f15959, #278090];
    
    HorizontalLayout { 
        for rect in rectangles: Rectangle {
            visible: false;
            background: rect;
        }
    }
}
```
![image](https://user-images.githubusercontent.com/31734358/201372476-72a05159-f2ce-4524-9602-c752bcc7b9df.png)

**Comment by ogoffart** [comment]
Thanks for the bug report.  It looks like a bug, indeed.
