### ISSUE TITLE
Syntax for repeated elements and conditional elements

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#1873]
Currently 
```
for tile[i] in memory-tiles: MemoryTile {
   // ...      
}

if foo.some-conditoin : SomeElement {
}
```

It was suggested in https://github.com/slint-ui/slint/discussions/1818#discussioncomment-4182871 to add brace to extand for more elements:

```
for tile[i] in memory-tiles {
        MemoryTile {
            // ...
        }
        // potentially more elements
    }
}

if foo.some-condition {
    SomeElement {
    }
    SomeOtherElement {
    }
}
```

It is assumed that this new scope is not in iteself an element, and when used in layout or other components that do something with their direct children the sub-element are considered direct children.

Unresolved questions:
 - Should the old syntax be deprecated or be kept as a shortened version when there is only one element?  (after all, this would otherwise add a level of indentation for the common case)
 - Can property be declared in the `for` or `if` scope?  If yes, how do we reference them if we want them to be qualified (we don't)

**Comment by ogoffart** [comment]
Example of code which would benefit of condition with several elements: https://github.com/slint-ui/slint/blob/85df47966e0e1a36c7a0de83b0c0bbd1d582391a/examples/printerdemo/ui/printer_queue.slint#L184

**Comment by tronical** [comment]
Whether or not to allow multiple elements is another decision in itself that we could take. We could also say that only one child is allowed, in the event that we can't come up with clear semantics yet for multiple.
