### ISSUE TITLE
online editor: hello world re-appears unexpectedly

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#1926]
Steps to reproduce:

1. Go to http://slint-ui.com/editor ; observe the "Hello World" with the "Ok" button
2. Remember where the "Ok" button is on your screen.
3. Replace the contents of the editor with the following snippet and observe the green rectangle fill the preview;

```
export Demo := Window {
    background: green;
}
```

4. Move your mouse cursor into the area that used to show the "Ok" button
5. Observe how "Hello World" reappears 👀

**Comment by tronical** [comment]
I think that this is not actually a bug in the online editor. I looked at it in the inspector and there's still only one canvas element in the DOM.

**Comment by ogoffart** [comment]
there is probably two active window on the same canvas
