### ISSUE TITLE
NPM pre-build binary

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#1991]
(Discussed in https://github.com/slint-ui/slint/discussions/1969 )

Find a way to have pre-build binary on npm instead of compiling the Rust Slint.

**Comment by tronical** [comment]
Tried with `slint-ui@nightly` on Linux (x64), macOS (x64), and Windows (x64).

**Comment by sigmaSd** [comment]
Awesome seems to work with deno as well

```ts
import * as slint from "npm:slint-ui@1.4.0-nightly.202411718";

let ui = slint.loadFile("main.slint");
let demo = new ui.Demo();

await demo.run();
```

![Uploading image.png…]()

**Comment by FloVanGH** [comment]
Yes deno with Slint works really well. I have good experience with it https://codeberg.org/flovansl/co_sl/src/branch/main/apps/coop_local/deno.
