### ISSUE TITLE
Compiler panic with public function

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2012]
The following test-case produces a panic with Rust and C++ generators:

```
export Foo := Rectangle {
   public function bar() {}
}
```

```
thread 'main' panicked at 'internal error: entered unreachable code', internal/compiler/llr/optim_passes/inline_expressions.rs:252:13
```

Surrounding code in `property_binding_and_analysis`:

```rust
   PropertyReference::Function { .. } | PropertyReference::GlobalFunction { .. } => {
            unreachable!()
        }
```

**Comment by ogoffart** [comment]
Ah yes, i haven't implemented that.
What shall we do for function, generate the `invoke_xxx`  function in native code?

**Comment by tronical** [comment]
Yes, I think that makes sense. And in the interpreter API we'd need `invoke_function` I suppose. Or we introduce just `invoke(name, params)` and say that's for callbacks and functions, and deprecate `invoke_callback`. Any tendency/preference on your side?

**Comment by ogoffart** [comment]
`invoke(name, params)`


Also i wonder if we should deprecate xxx_global_yyy,   and say that the name should be in the form "Global.property" in the non-global functions

**Comment by tronical** [comment]
> `invoke(name, params)`

👍 

> Also i wonder if we should deprecate xxx_global_yyy, and say that the name should be in the form "Global.property" in the non-global functions

I don't feel too strongly about it, but I'm leaning against it.

Old code:

```rust
comp.set_global_property("SomeGlobal", "someProp", 42);
comp.set_global_property(someVar, someProp, 42);
```

New code:

```rust
comp.set_property("SomeGlobal.someProp", 42); // I'd say more or less equally readable as the old code
comp.set_property(&format!("{someVar}.{someProp}"), 42); // Worse: Now our users have to concatenate strings.
```

I think for constant property names, it makes no difference. For dynamic scenarios, I think such an API is worse.

**Comment by ogoffart** [comment]
Then we have 
```
/// Error returned by [`ComponentInstance::invoke_callback`]
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[non_exhaustive]
pub enum InvokeCallbackError {
    /// There is no callback with the given name
    #[error("no such callback")]
    NoSuchCallback,
}
```

What should the equivalent for `invoke` be?

```rust
```
/// Error returned by [`ComponentInstance::invoke`]
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[non_exhaustive]
pub enum InvokeError {
    /// There is no callback of function with the given name
    #[error("no such callback or function")]
    NoSuchCallable,
}

#[deprectated] type InvokeCallbackError = InvokeError;
impl InvokeCallbackError {  #[deprectated] const NoSuchCallback : Self = Self::NoSuchCallable } 
```

But I'm not sure about `NoSuchCallable`

**Comment by tronical** [comment]
Perhaps `NoSuchFunction`?
