### ISSUE TITLE
Compile error QJsonDocument

### ISSUE THREAD

**Issue by Montel** [slint-ui/slint#2017]
When I want to compile on my computer (Opensuse Tumbleweed)
I have this compile error:

`warning: src/lib.rs:1724:14: fatal error: QtCore/QJsonDocument: Aucun fichier ou dossier de ce type
warning:  1724 |     #include <QtCore/QJsonDocument>
warning:       |              ^~~~~~~~~~~~~~~~~~~~~~
warning: compilation terminated.

error: failed to run custom build command for `qttypes v0.2.8`

Caused by:
  process didn't exit successfully: `/travail/kdab/git/rust/ruqola-rust/ruqola-rust/target/debug/build/qttypes-d44d2fa93d8ab37c/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=QT_INCLUDE_PATH
  cargo:rerun-if-env-changed=QT_LIBRARY_PATH
  cargo:rerun-if-env-changed=QMAKE
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CXX_x86_64-unknown-linux-gnu
  CXX_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXX_x86_64_unknown_linux_gnu
  CXX_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CXX_x86_64-unknown-linux-gnu
  CXX_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXX_x86_64_unknown_linux_gnu
  CXX_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-I" "/home/laurent/.cargo/registry/src/github.com-1ecc6299db9ec823/qttypes-0.2.8" "-I" "/usr/include" "-Wall" "-Wextra" "-std=c++11" "-o" "/travail/kdab/git/rust/ruqola-rust/ruqola-rust/target/debug/build/qttypes-8d524bd527ef4529/out/f275512e7fc513ce-cpp_closures.o" "-c" "/travail/kdab/git/rust/ruqola-rust/ruqola-rust/target/debug/build/qttypes-8d524bd527ef4529/out/rust_cpp/cpp_closures.cpp"
  cargo:warning=src/lib.rs:1724:14: fatal error: QtCore/QJsonDocument: Aucun fichier ou dossier de ce type
  cargo:warning= 1724 |     #include <QtCore/QJsonDocument>
  cargo:warning=      |              ^~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.
  exit status: 1

  --- stderr

  error occurred: ToolExecError: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-I" "/home/laurent/.cargo/registry/src/github.com-1ecc6299db9ec823/qttypes-0.2.8" "-I" "/usr/include" "-Wall" "-Wextra" "-std=c++11" "-o" "/travail/kdab/git/rust/ruqola-rust/ruqola-rust/target/debug/build/qttypes-8d524bd527ef4529/out/f275512e7fc513ce-cpp_closures.o" "-c" "/travail/kdab/git/rust/ruqola-rust/ruqola-rust/target/debug/build/qttypes-8d524bd527ef4529/out/rust_cpp/cpp_closures.cpp" with args "c++" did not execute successfully (status code exit status: 1).
`

**Comment by Montel** [comment]
I have : 
/usr/include> find -iname *QJsonDocument*
./qt6/QtCore/qjsondocument.h
./qt6/QtCore/QJsonDocument
./qt5/QtCore/qjsondocument.h
./qt5/QtCore/QJsonDocument

**Comment by Montel** [comment]
Perhaps it doesn't look at in qt6 or qt5 directory

**Comment by ogoffart** [comment]
The header dir is detected automatically with `qmake -query QT_INSTALL_HEADERS`
what does that return on your system?

You can specify the include dir manually with env variable, see https://docs.rs/qttypes/latest/qttypes/#finding-qt

Also, you can set `SLINT_NO_QT=1` env variable to disable the Qt backend.  (or you can also disable it with cargo features)
