### ISSUE TITLE
After compiling, it cannot run on other machines, and it disappears in a flash

### ISSUE THREAD

**Issue by 107295472** [slint-ui/slint#2022]

**Comment by ogoffart** [comment]
What platform are you running? 
Any error message from the command line?
What do you see exactly?

**Comment by 107295472** [comment]
This machine is win10 ltsc, it cannot run on win server 2012

**Comment by ogoffart** [comment]
I'm afraid we will need a bit more information in order to being able to help. Maybe some DLL are missing?
