### ISSUE TITLE
Slint error in seemingly valid struct construction.

### ISSUE THREAD

**Issue by farmaazon** [slint-ui/slint#2023]
The [following code](https://slint-ui.com/releases/0.3.3/editor/?snippet=import+%7B+ComboBox+%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+struct+Player+%3A%3D+%7B%0A++++skill-profile%3A+int%2C%0A%7D%0A%0Aexport+struct+NewGameTeam+%3A%3D+%7B%0A++++players%3A+%5BPlayer%5D%2C%0A%7D%0A%0Aexport+struct+NewGameParameters+%3A%3D+%7B%0A++++teams%3A+%5BNewGameTeam%5D%2C%0A%7D%0A%0Aexport+Demo+%3A%3D+Window+%7B%0A++++width%3A+600px%3B%0A++++height%3A+600px%3B%0A%0A++++property+%3CPlayer%3E+player%3A+%7B+skill-profile%3A+0+%7D%3B%0A++++property+%3CNewGameParameters%3E+parameters%3A+%7B%0A++++++++teams%3A+%5B%7B%0A++++++++++++players%3A+%5B%7B%0A++++++++++++++++skill-profile%3A+0%2C%0A++++++++++++%7D%5D%0A++++++++%7D%5D%0A++++%7D%3B%0A%0A%0A++++HorizontalLayout+%7B%0A%0A++++++++Rectangle+%7B+background%3A+green%3B+%7D%0A%0A++++++++Rectangle+%7B+%0A++++++++++++width%3A+200px%3B%0A++++++++++++horizontal-stretch%3A+0%3B%0A%0A++++++++++++ComboBox+%7B+%0A++++++++++++++++width%3A+100%25%3B%0A++++++++++++++++model%3A+%5B%22One%22%2C+%22Two%22%2C+%22Seventeen%22%5D%3B%0A++++++++++++%7D%0A+++++++++%7D%0A%0A++++++++Rectangle+%7B+%0A++++++++background%3A+green%3B%0A+++++++++%7D%0A++++%7D%0A%7D%0A) gives "cannot convert" error, despite the fact the fields seem to perfectly fit declared structures.

**Comment by ogoffart** [comment]
Thanks for your bug report.  And happy new year 2023 for your issue #2023 🎇 🥳

This is indeed a bug. Fix in PR #2025
