### ISSUE TITLE
mcu-board-support: Panic if the window size is larger than the display size

### ISSUE THREAD

**Issue by jturcotte** [slint-ui/slint#2027]
The first time I managed to compile and run my code for a custom board in mcu-board-support I got the following error:

`panicked at 'range end index 38480 out of range for slice of length 38400', internal/core/software_renderer.rs:744:22`

And seems to be caused by my DISPLAY_SIZE being 240x160 (and the frame buffer sized accordingly) but that carousel demo states 320x240 as the window size.

I started from the pico_st7789 code, which has this line that I have the feeling should be forcing the software renderer to operate on the actual display size:

`self.window.borrow().as_ref().unwrap().set_size(DISPLAY_SIZE);`

But it seems like `MinimalSoftwareWindow` doesn't implement `set_size`, is this a no-op?

At first I thought that maybe the `buffer_stride: usize` parameter in `SoftwareRenderer::render` should be bytes instead of pixels (it doesn't seem documented). Then it actually ran but it took me a while to realize that it looked wrong because the buffer_stride should actually be in pixels (I'm using 16bit colors) and that the panic was caused by the slint file window size.

So I think that to avoid confusion it would be convenient if the slint files don't have to be modified and that the display size overrides the window size.

**Comment by ogoffart** [comment]
Right. That could be improved.

The renderer should indeed either

 1. add extra assert earlier to ensure the sizes are fitting instead of panicking with confusing error later on. 
 2. Or only draw in the part of the buffer that is given.
 3. Maybe ensure consistency of size through other mean. Like as soon as the window is set or something 

> But it seems like MinimalSoftwareWindow doesn't implement set_size, is this a no-op?

But the `slint::Window::set_size` should make sure the size of the slint window is set

**Comment by jturcotte** [comment]
Ah, so you want to keep the window size known at compile time? Is there a way that the mcu-support-board feature could provide the display size to the compiler?

Having a better error would help for sure, but I'm wondering if there could be a way to avoid having to manually tailor the slint code to the target board display size.

**Comment by ogoffart** [comment]
> Ah, so you want to keep the window size known at compile time?

Yes, but that's not the issue here.
Admitively, the carousel demo could easily be made more "reactive" to the window size instead of being fixed.
But I think that's two different problems.

> Is there a way that the mcu-support-board feature could provide the display size to the compiler?

Via some option in the build.rs. we already have a config file that could be used for that actually
