### ISSUE TITLE
Editing text forces inescapable zoom on mobile

### ISSUE THREAD

**Issue by jgarvin** [slint-ui/slint#2028]
On Android phone running Chrome:
* go to slint website and click the playground button
* Click outline tab
* Click any item in the tree

The UI will suddenly zoom in until the text looks absurdly huge, ~72pt, and then won't let you unpinch to zoom out.

**Comment by ogoffart** [comment]
Thanks for filling an issue.

The online editor is not really compatible with mobile platform at the moment.
The frameworks we use (eg, monaco text editor) doesn't support it <https://github.com/microsoft/monaco-editor/issues/246>

I must say that this is not really a priority for us to get the code editor working on mobile.  But any PR is welcome.

**Comment by ogoffart** [comment]
Closing this issue as we can't support mobile if the monaco editor doesn't support it.
