### ISSUE TITLE
Error when showing native preview should disable with error report, or fallback to wasm preview instead of panic

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#204]
In the lsp native preview, we unwrap() and panic when we can't show the preview (eg, cannot connect to display or other GL errors)

https://github.com/slint-ui/slint/blob/0984170cb3e2effb2c788238bdc42c53109966fa/tools/lsp/preview/native.rs#L83
https://github.com/slint-ui/slint/blob/0984170cb3e2effb2c788238bdc42c53109966fa/tools/lsp/preview.rs#L580

Instead, we should report an error to the editor that the preview command failed.
The editor could then report the exact error to the user or fallback to the wasm preview

## original message:

When the extension (and thus the lsp binary) runs in a headless environment (such as code spaces)  the preview functionality should be disabled.

Right now the lsp process aborts with a panic in such environments as winit fails to connect to the display. It would be great to detect this situation gracefully, still run the pure lsp related functionality and disable the preview command in the GUI.

**Comment by ogoffart** [comment]
With the Qt backend, it may even abort as we start the event loop, even if we don't show the preview.

In any case, we should probably wait until there is a request to show the preview before starting the UI event loop.  (we can just block the UI thread with a wait condition before starting the event loop.)

**Comment by tronical** [comment]
True, the Qt backend may abort as well when it tries to start up the platform plugin.

Perhaps another approach to this would be to just check for `DISPLAY` or `WAYLAND_DISPLAY` on Linux when entering main and that's it. Should cover the 99% case likely?

> In any case, we should probably wait until there is a request to show the preview before starting the UI event loop. (we can just block the UI thread with a wait condition before starting the event loop.)

I agree, that makes sense in any case.

**Comment by ogoffart** [comment]
Now that the slint backend return actual error when it's the case, we could forward these error to the editor through the LSP protocol.

**Comment by tronical** [comment]
I think platform initialisation will fail with an error, and we could probably detect that gracefully and disable the preview - if we tried initialising the platform backend in main() early to verify.
