### ISSUE TITLE
Compile error: can not compile when calling function from state

### ISSUE THREAD

**Issue by hbhong** [slint-ui/slint#2047]
I initialized the project with a mcu template. when I try the following slint, calling an empty function from state, it throws some errors when compiling. (slint 0.3.3)

```slint
export   RootPage:=Rectangle{
    function initButtons(){
    }
    property <string> action;
    states [ 
        selectCountDown when self.action=="selectCountDown":{
            initButtons();
            countDownBun.selected:true;
            tomatoBun.selected:false;
        }
        .............
     ]
```

The errors:

```
 error: failed to run custom build command for `esp-buttons v0.1.0 (/RustProjects/esp-buttons)`

Caused by:
  process didn't exit successfully: `/RustProjects/esp-buttons/target/debug/build/esp-buttons-48b2719654b1bbde/build-script-build` (exit status: 101)
  --- stderr
  error: Syntax error: expected ':'
    -->/RustProjects/esp-buttons/ui/root_page.slint:10:24
     |
  10 |             initButtons();
     |                        ^
  error: Syntax error: expected ']'
    --> /RustProjects/esp-buttons/ui/root_page.slint:10:24
     |
  10 |             initButtons();
     |                        ^
  error: Parse error
    -->/RustProjects/esp-buttons/ui/root_page.slint:10:24
     |
  10 |             initButtons();
     |                        ^
  error: Syntax error: expected ':='
    --> /RustProjects/esp-buttons/ui/root_page.slint:14:26
     |
  14 |         selectTomatoDown when self.action=="selectTomato":{
     |                          ^
```

*Edit: I took the liberty to fix the formatting.* @hunger

**Comment by ogoffart** [comment]
> calling an empty function from state, it throws some errors when compiling.

This is not supported. One cannot call code from states, state can only be used to change property with
`plop.foo: bar` syntax.  (and also animation)

What are you trying to achieve exactly?

**Comment by hbhong** [comment]
@ogoffart I want to call some same change common properties statements in the different branch of state, and then append some additional statements to change single property. so I think if I can extract the same codes to a function and call it, the codes will be more simple.

**Comment by ogoffart** [comment]
I see, so what you're trying to do is something like sub-state?
We can't call functions because functions are "imperative" and we would like to keep a declarative description of the UI (so the compiler has a better view on each properties, and also make it possible to edit with the design tool we will soon make)

We were thinking to implement some syntax such as we could either:

1. inherit states 
```
export   RootPage:=Rectangle{
    property <string> action;
    states [ 
        common : { buton1.init: true; /* ... */ }
         selectCountDown inherits common when self.action=="selectCountDown":{
            countDownBun.selected:true;
            tomatoBun.selected:false;
        }
        .............
     ]

```

2. sub-states

```
export   RootPage:=Rectangle{
    property <string> action;
    states [ 
        common when self.action != "" : { 
              buton1.init: true; /* ... */ 
              states [
                   selectCountDown inherits common when self.action=="selectCountDown":{
                      countDownBun.selected:true;
                      tomatoBun.selected:false;
                  }
                  .............
              ]
        }
     ]

```


Would any of the solution fitting your needs?

**Comment by hbhong** [comment]
@ogoffart ,thank for your explain.
the first one `inherit states` is enough for me, it is more easy and clear :)

**Comment by ogoffart** [comment]
Closing in favor of https://github.com/slint-ui/slint/issues/2089
