### ISSUE TITLE
macOS: installed libslint_cpp.dylib has reference to build directory

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2075]
Building with CMake and installing, produces a libslint_cpp.dylib artefact in the configured `CMAKE_INSTALL_PREFIX`. On macOS this installed cdylib has a `LC_ID_DYLIB` load command that points to the internal corrosion build directory. For example:

```
Load command 4
          cmd LC_ID_DYLIB
      cmdsize 120
         name /Users/simon/src/cppbuild/./cargo/build/x86_64-apple-darwin/release/deps/libslint_cpp.dylib (offset 24)
   time stamp 1 Thu Jan  1 01:00:01 1970
      current version 0.0.0
```

This is sub-optimal, as that means that wiping the build directory after installation leaves the installed package dysfunctional.

One way of solving this is to instruct rustc (via cargo) to use rpath for the `LC_ID_DYLIB` command. It appears to me that that would be the correct thing to have in the installed cdylib.

So enabling `rpath = true` in the `dev` and `release` profile of `Cargo.toml` produces what I think is the correct result:

```
Load command 4
          cmd LC_ID_DYLIB
      cmdsize 56
         name @rpath/libslint_cpp.dylib (offset 24)
   time stamp 1 Thu Jan  1 01:00:01 1970
      current version 0.0.0
```

This could also be achieved differently:

    1. Using a cmake install script that runs `install_name_tool`
    2. Setting the `CARGO_<profile>_RPATH` environment variable in `cpp/CMakeLists.txt`

Perhaps there is also a third way?

Given that we have this issue right now only with `libslint_cpp.dylib`, I'm leaning towards a macOS-only fix - instead of enabling rpath globally.

The issue as-is is rather severe though: That on macOS one has to keep the build directory around is bad.

**Comment by jschwe** [comment]
I think probably you would want to set the `install_name` and the `IMPORTED_SONAME` property something like this:

```cmake
# corrosion could provide the Cargo.toml package version as a CMake target property.
corrosion_add_target_local_rustflags(slint-cpp -Clink-arg=-Wl,-install_name,@rpath/libslint_cpp.dylib,-current_version,1.0,-compatibility_version,1.0)
# Set this one to false again explicitely because Corrosion will starting setting this property to true by default.
set_target_properties(slint-cpp-shared PROPERTIES IMPORTED_NO_SONAME 0)
set_target_properties(slint-cpp-shared PROPERTIES  IMPORTED_SONAME libslint_cpp.dylib)
```

This is currently not very well tested from my side, so maybe some other issues would pop up.

**Comment by tronical** [comment]
Thank you @jschwe . I tried this locally and it works like a charm!
