### ISSUE TITLE
Unreachable executed in todo demo when enabling "hide done items"

### ISSUE THREAD

**Issue by mgunyho** [slint-ui/slint#2084]
Hi, I'm looking into Slint and was trying out the todo demo. When I click on the checkbox for "hide done items", the whole app freezes and I get the following stack trace in the console:

```
Uncaught RuntimeError: unreachable executed
    __wbg_adapter_24 https://slint-ui.com/releases/0.3.3/demos/todo/pkg/todo.js:217
    real https://slint-ui.com/releases/0.3.3/demos/todo/pkg/todo.js:202
    __wbg_addEventListener_cbe4c6f619b032f3 https://slint-ui.com/releases/0.3.3/demos/todo/pkg/todo.js:877
    handleError https://slint-ui.com/releases/0.3.3/demos/todo/pkg/todo.js:251
    __wbg_addEventListener_cbe4c6f619b032f3 https://slint-ui.com/releases/0.3.3/demos/todo/pkg/todo.js:876
    finalizeInit https://slint-ui.com/releases/0.3.3/demos/todo/pkg/todo.js:1356
    init https://slint-ui.com/releases/0.3.3/demos/todo/pkg/todo.js:1388
    async* https://slint-ui.com/releases/0.3.3/demos/todo/:37
todo_bg.wasm:1463496:1
```

The other checkboxes and features of the demo seem to work fine.

I'm using Firefox 108.0.2 on OpenSUSE Tumbleweed.

**Comment by ogoffart** [comment]
Hi @mgunyho 

Thanks a lot for the bug report!
This bug was fixed earlier this week in https://github.com/slint-ui/slint/pull/2074

You can try the snapshot build to verify if this works: https://slint-ui.com/snapshots/master/demos/todo/

**Comment by mgunyho** [comment]
Ah, I could not find that issue, I was searching for "unreachable". Sorry about the noise.
