### ISSUE TITLE
updater: missing qualifier when accessing property of repeated element

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2113]
Input:

```
export App := Window {
    for i in 1: TouchArea {
        Text {
            text: enabled ? "a" : "b";
        }
    }
}
```

Output:

```
export component App inherits Window {
    for i in 1: TouchArea {
        Text {
            x:0;y:0;
            text: enabled ? "a" : "b";
        }
    }
}
```

This doesn't compile. The TouchArea should receive a name perhaps and `enabled` should be qualified with that name.

**Comment by tronical** [comment]
Suppose the scope contained the repeated element, how would it transform the code?

I can see how we can't just give it a random name, so I think we'd need logic to reach via `parent` chain. I can give it a try if you think that's a good direction and if it's worth it.

**Comment by ogoffart** [comment]
Good point.
But I think it already does give names to some elements because of strange lookup rules in Path for example.

**Comment by ogoffart** [comment]
Closing as too low priority.
(updates from 0.3 should be done at this point)
