### ISSUE TITLE
Changes to consider in the software renderer API

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#2135]
I'd just want to discuss some problem which may need breaking changes in the software renderer API

 1. [ ] The `SoftwareRenderer::render` function takes a buffer_stride argument, which is the size in pixels.  The problem is that the stride might not be an integrer number of pixel. Example, when trying to use the software renderer from Qt and drawing onto a QImage, i noticed that the QImage aligns all the lines on 32 bits.  But when the pixels are 24bits RGB, then it might not be possible to give a right value, of the stride.    The thing is that the buffer is a &[TargetPixel], so the stride has to be an index within it. 
 2. [X] ~~When using partial rendering, the software renderer only update a part of the image. And this region can be arbitrary.  However, some screen do not support arbitrary updates and need to adjust the dirty region to be aligned on, say, 8pixel columns. This is the case for some monochrome 1bit/pixel images that on which the updates needs still to be done byte per byte.~~  (We can add a function to LineBufferProvider after 1.0)
 3. [ ] The MAX_BUFFER_AGE is a const generic, and this doesn't play well with the C++ FFI interface.  Would it be best to be a runtime parametter instead?

Maybe we can just ignore these issues, but i think we should still discuss them.

**Comment by ogoffart** [comment]
> Do I understand correctly that this affects only the line-by-line rendering? If yes, could this perhaps be solved by allowing the caller to make adjustments to the dirty region after we've determined it?

Yes, LineBufferProvider::adjust_dirty_region would work.

We just need to find a good name for it.

> In my opinion, if we wanted to also support rendering into buffers where lines are aligned on a non-pixel boundary, then we should introduce a new second function where this is reflected.

Either a second function, or change the current function.
LineBuffer is maybe not the right name because it's a Buffer but not a buffer of lines.
For example, QImage is a similar buffer, and has a QImage::scanLine,  but it's not called QImageLines.

So i thin the name would be TargetBuffer  or something like that.

But if you think it would be a second function, this wan wait post 1.0

**Comment by tronical** [comment]
> > In my opinion, if we wanted to also support rendering into buffers where lines are aligned on a non-pixel boundary, then we should introduce a new second function where this is reflected.
> 
> Either a second function, or change the current function. LineBuffer is maybe not the right name because it's a Buffer but not a buffer of lines. For example, QImage is a similar buffer, and has a QImage::scanLine, but it's not called QImageLines.

Right, it's called QImage because its primary purpose (and reason one invention) was to hold images, not be a rendering buffer.

> 
> So i thin the name would be TargetBuffer or something like that.

I think `Line` as a prefix is more descriptive than `Target`, but either way I have no objection against `TargetBuffer`.

> 
> But if you think it would be a second function, this wan wait post 1.0

Perhaps we can get away with just one function and implement the trait for `&mut [TargetPixel]`?

**Comment by ogoffart** [comment]
Also, the `TargetBuffer` or whatever we call it may also get support for things like `blend_image()` or such function that can have hardware acceleration.  I thought we could add there to the TargetPixel trait, but maybe TargetBuffer is a better place.

**Comment by ogoffart** [comment]
So what do we do about the `MAX_BUFFER_AGE`

Currently we have 

```rust
pub struct SoftwareRenderer<const MAX_BUFFER_AGE: usize> {
//...
    /// We really only need MAX_BUFFER_AGE - 1 but that's not allowed because we cannot do operations with
    /// generic parameters
    prev_frame_dirty: [Cell<DirtyRegion>; MAX_BUFFER_AGE],
}


pub struct MinimalSoftwareWindow<const MAX_BUFFER_AGE: usize> {
//...
    renderer: SoftwareRenderer<MAX_BUFFER_AGE>,
}
```

I guess we should remove the const parameter from the SoftwareRenderer and add this API:

```rust
impl SoftwareRenderer {
     /// Sets the maximum buffer age. The max_buffer_age parameter specifies how many buffers are being re-used.
    /// This means that the buffer passed to the render functions still contains a rendering of the window that was 
    /// refreshed as least that amount of frame ago. It will impact how much of the screen needs to be redrawn.
    ///
    /// Typical value can be:
    ///  - **0:** No attempt at tracking dirty items will be made. The full screen is always redrawn.
    ///  - **1:** Only redraw the parts that have changed since the previous call to render.
    ///           This is assuming that the same buffer is passed on every call to render.
    ///  - **2:** Redraw the part that have changed during the two last frames.
    ///           This is assuming double buffering and swapping of the buffers.
    ///
    /// The default value is 0.
    pub fn set_max_buffer_age(&mut self, max_buffer_age: usize) {
        // prev_frame_dirty is now an `Option<Vec<...>>` instead of an array
        self.prev_frame_dirty = (max_buffer_age > 0).then(|| vec![Default::default() ; max_buffer_age - 1]);
    }
    /// Returns the max buffer age. See the documentation of [`Self::set_max_buffer_age()`] for more info.
    pub fn max_buffer_age(&self) -> usize { /*...*/ }
}
```

Or should there be an `SoftwareRenderer::new_with_max_buffer_age(...)` function?

We could keep the MAX_BUFFER_AGE as a const parametter in the MinimalSoftwareWindow, because that's not used from C++. Or Have the Same API as for the SoftwareRenderer.

**Comment by tronical** [comment]
I see three options:

1. Compile time parameter (like right now).
2. A parameter that's specified at construction time but can't be changed afterwards (so parameter to constructor).
3. A paramater that can be changed dynamically at run-time.

I'm in favor of (2).
