### ISSUE TITLE
Should SharedPixelBuffer use usize instead of u32?

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#2138]
The SharedPixelBuffer::width, height, size, stride  all use u32,  but maybe they should use usize

**Comment by tronical** [comment]
Along the same lines, there's the question if they should be `NonZeroUSize` then. There's a similar discussion among the softbuffer folks. I do find `NonZeroXX` cumbersome to use though.

**Comment by tronical** [comment]
In the Rust image crate the dimensions are `u32` and I think from a cross-platform perspective that makes more sense than a platform-dependent size. So I'm in favor of keeping `u32`.

**Comment by ogoffart** [comment]
stride is measured in pixel too, IIRC.
But the thing is that we use width and height and stride to index slices (or to compute index within slices) and then usize is more convenient.  But that's just one usecase.

**Comment by tronical** [comment]
I wish btw that we didn't call it stride but `bytes_per_line` instead. I find that more descriptive anyway and easier to understand for non-native speakers. But I may be on a lonely island with that ;)

**Comment by ogoffart** [comment]
Now would be the time to rename it
(but it is `pixels_per_line`, then)

**Comment by tronical** [comment]
On second thought: I think we should remove the stride() accessor (and internal field).

Unlike `QImage` (where it is rightfully called `bytes_per_line` and it **is** a vector of lines), `SharedPixelBuffer` is not a vector of lines, it is a continuous sequence of pixels. At the moment there is no way to construct a `SharedPixelBuffer` where the number of pixels per line does not equal the width in pixels. We provide api to expose a slice of pixels (`as_slice`) as well as bytes.

If we decide to make it a vector of lines, then I think we should do it properly, and that means removing the `&[TargetPixel]` accessor and instead provide by-line accessors. Then we can also do a correct bytes-per-line and (just for this type!) avoid an issue like you described in #2135.

Apologies for the digression from the original subject of this issue :)

**Comment by ogoffart** [comment]
I think the conclusion from the talk is that there can't be a std::image that will work for every use cases.
And it is true that for our use case, there is no need of the stride, so we can just remove it.

**Comment by ogoffart** [comment]
stride is gone in #2147.  And the remaining sizes can stay in u32

**Comment by bjorn** [comment]
> And it is true that for our use case, there is no need of the stride, so we can just remove it.

While there may be no need, I saw in #2147 that there are quite a few `width * 4` or `width * 3`, so I think it could be useful to keep `stride()` or introduce `bytes_per_line()` as a convenience. Anyway, just a drive-by thought.
