### ISSUE TITLE
Artifact in border radius where they join for big enough border in the GL backend

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#214]
Testcase:

```c
export Demo := Window {
    Rectangle { 
        width: 200px;
        height: width;
        border-width: 40px;
        border-radius: width/2;
        border-color: orange;
    }
}
```

This shows gaps where the corner joins:

![Screenshot_20210429_090435](https://user-images.githubusercontent.com/959326/116513573-1854c180-a8ca-11eb-8c7a-422afb3627e9.png)

live editor link: https://sixtyfps.io/editor/?snippet=%0Aexport+Demo+%3A%3D+Window+%7B%0A+Rectangle+%7B+%0A++width%3A+200px%3B%0A++height%3A+width%3B%0A++border-width%3A+40px%3B%0A++border-radius%3A+width%2F2%3B%0A++border-color%3A+orange%3B%0A+%7D%0A%7D%0A

**Comment by tronical** [comment]
Hm, to me the live editor link rendering still looks exactly like in the screenshot.

**Comment by ogoffart** [comment]
For me it looks alright. but if you can still reproduce it, i'll reopen.

**Comment by ogoffart** [comment]
Actually it renders properly with firefox, but it's wrong with chrome.

**Comment by ogoffart** [comment]
I can't reproduce anymore on neither firefox nor chrome nor in the lsp review

**Comment by ogoffart** [comment]
Can't reproduce
