### ISSUE TITLE
Support for the secondary clippoard

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#2146]
The Platform API for clipboard currently is:

```rust
pub trait Platform {
//...
    fn set_clipboard_text(&self, _text: &str) { ... }
    fn clipboard_text(&self) -> Option<String> { ... }
}
```

We could add a new argument  to these two function.

```rust
#[non_exhaustive]
enum Clipboard {
     /// This is the default clipboard used for text action for Ctrl+V,  Ctrl+C.
     /// Corresponds to the secondary clipboard on X11.
     DefaultClipboard,
     
     /// This is the clipboard that is used when text is selected
     /// Corresponds to the primary clipboard on X11.
     /// The Platform implementation should do nothing if copy on select is not supported on that platform.
     SelectionClipboard,
}
```

I used custom names rather than "Primary" and "Secondary" because i find these names confusing.

That would be the easier.
Now, the question is whether just clipboard_text is good enough?  What about pasting copying rich text, images, files and the like?  Should we support that in the Platform trait?  Since we don't have use case right now, we can delay the decision to later, and add more functions to Platform or more Clipboard variant
(eg: Clipbaord::Image(&mut Image)`

**Comment by tronical** [comment]
> I used custom names rather than "Primary" and "Secondary" because i find these names confusing.

👍 I like your suggested names.

> Now, the question is whether just clipboard_text is good enough? What about pasting copying rich text, images, files and the like? Should we support that in the Platform trait? Since we don't have use case right now, we can delay the decision to later, and add more functions to Platform or more Clipboard variant

I agree.
