### ISSUE TITLE
Online Editor: Highlight remains visible when cursor is not under element type name anymore

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2167]
I noticed that in the vs code extension the highlight disappears as soon as the cursor is not on the element type name anymore. I assume that that's the intended behavior.

In the online editor, the highlight remains visible until the cursor is on another element type name - that's different. The little clip demonstrates that:

https://user-images.githubusercontent.com/1486/216044579-bc3d35ad-3d24-475c-ae7d-bbc96fce1833.mov

**Comment by ogoffart** [comment]
If the behavior really different than in the normal LSP? (in vscode desktop for example)

That's because the LSP only get called for highlight when the cursor gets over a token which is not whitespace.

**Comment by tronical** [comment]
You're right. I was wondering the same before writing the issue (to see if it's different), but I must've placed the cursor on a token by accident (the "text" property name).

I do find the current behavior unintuitive but that's not in scope for this issue but for another discussion. Apologies for the false bug report.
