### ISSUE TITLE
VSCode LSP: report panics properly automatically.

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#217]
When the server panics, we should report the panic in a notification or something so we can debug it easier

**Comment by matklad** [comment]
Tip from a fellow LSP developer: embed the current LSP request into the message: 

* https://github.com/rust-analyzer/rust-analyzer/blob/eb08a27f1bd31cc15db4893dded60663effaf3f9/crates/stdx/src/panic_context.rs
* https://github.com/rust-analyzer/rust-analyzer/blob/eb08a27f1bd31cc15db4893dded60663effaf3f9/crates/rust-analyzer/src/dispatch.rs#L36-L41

**Comment by ogoffart** [comment]
In recent version we do show an error in vscode and open the output pane, with hint to report a bug.

What would actually be nice is to capture the panic message in a telemetry event. But I didn't find a way to capture the message from the extension code.

**Comment by hunger** [comment]
We collect information on panics now as telemetry.
