### ISSUE TITLE
Slint v0.3.4 fails on building the library itself

### ISSUE THREAD

**Issue by teminian** [slint-ui/slint#2183]
**[Working Environment]**

- OS: Windows 11
- Language / Compiler: Visual C++ 2022
- CMake Configuration: WINIT + SKIA
- Commands run: git checkout v0.3.4 → cmake-gui → ninja
- Symptoms summary: with the configuration above, Slint fails to be compiled on linking step.

**[ Error Message ]**
```
skia.lib(skia.SkSLVMCodeGenerator.obj) : error LNK2019: unresolved external symbol __std_max_element_8 referenced in function "private: struct SkSL::`anonymous namespace'::Value __cdecl SkSL::SkVMGenerator::writeIntrinsicCall(class SkSL::FunctionCall const &)" (?writeIntrinsicCall@SkVMGenerator@SkSL@@AEAA?AUValue@?A0x6BA93B68@2@AEBVFunctionCall@2@@Z)
C:\Components\slint-git\build\.\cargo\build\x86_64-pc-windows-msvc\release\deps\slint_cpp.dll : fatal error LNK1120: 1 unresolved externals
```

**Comment by tronical** [comment]
Hi! Is it possible that there is a patch update available for your installation of MSVC 2022? I've seen this error before and it went away after installing the latest patches (they release them quite frequently).

**Comment by teminian** [comment]
It works after upgrading my VS2022. Thank you @tronical !
