### ISSUE TITLE
Two-directional binding to a struct field in repetition produces uninformative error

### ISSUE THREAD

**Issue by d86leader** [slint-ui/slint#2186]
I found after the fact that bindings to struct fields are a complicated matter, but at first as a new user I thought I'm using it wrong.

The code:
```rust
slint::slint! {
    import {ListView, LineEdit} from "std-widgets.slint";
    
    struct S {
        foo: string,
    }

    export component UiMain inherits Window {
        property<[S]> model: [];
        for val in root.model: LineEdit {
            text <=> val.foo;
        }
    }
}

fn main() {
    let win = UiMain::new();
    win.run();
}
```

Gives error:

```
error: Cannot access the field 'foo' of <error>
  --> src/main.rs:11:26
   |
11 |             text <=> val.foo;
   |  
```
It erroneosly says that the field does not exist, and doesn't show the correct type of a struct. Regular illegal two-way bindings are more informative.

**Comment by tronical** [comment]
This appears to be caused by the `resolve_two_way_bindings` being called before the `model` expression of the `RepeatedElementInfo` is resolved. But even if that were fixed, we'd need a fix for #2013 / #814. But I think we can improve the error message for this.
