### ISSUE TITLE
wayland: no window title visible

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2188]
When using slint with current Weston, it appears that client side decorations are used and by default the window title is not visible (and the minimize/maximize buttons look kind of bad).

We should either enable the wayland-csd-adwaita feature in winit by default or re-export that as a feature so that people can also disable it in Slint.

Marking this as a bug as no support for window titles on wayland is a bug :)

**Comment by ogoffart** [comment]
We should indeed enable this feature by default when wayland is enabled.

Long term, we should be able to use slint to design the window decoration.
All we need is mark an area as draggable ( #613 )  and resize handle for the window.  Also api to maximize / minimize the Window

**Comment by tronical** [comment]
I agree. The code to render the decoration is trivial and it would indeed be well suited to do that using Slint.
