### ISSUE TITLE
Panicked while minimizing the window 

### ISSUE THREAD

**Issue by Zhou-Pixel** [slint-ui/slint#2197]
code:
```rust
slint::slint!{
    import { Button, GridBox } from "std-widgets.slint";
    export component HelloWorld inherits Window {
        preferred-width: 800px;
        preferred-height: 480px;
        GridBox {  
            Text {
                text: "hello world";
            }
            Button {  
                text: "click";
            }

        }
    }
}
fn main() {
    HelloWorld::new().run();
}

```

### when happen: always, when minimizing the window 

# panick info:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', C:\Users\zhou\.cargo\git\checkouts\slint-8153123e5dffa129\7990bfe\internal\backends\winit\renderer\femtovg\glcontext.rs:46:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\test_slint.exe` (exit code: 101)
```

**Comment by Zhou-Pixel** [comment]
> Thank you for taking the time to report this issue!
> 
> Could you maybe run with the environment variable RUST_BACKTRACE set to 1? Having the backtrace would help a lot!

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', C:\Users\zhou\.cargo\git\checkouts\slint-8153123e5dffa129\7990bfe\internal\backends\winit\renderer\femtovg\glcontext.rs:46:40
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\panicking.rs:64
   2: core::result::unwrap_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\result.rs:1791
   3: enum2$<core::result::Result<core::num::nonzero::NonZeroU32,core::num::error::TryFromIntError> >::unwrap<core::num::nonzero::NonZeroU32,core::num::error::TryFromIntError>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\result.rs:1113
   4: i_slint_backend_winit::renderer::femtovg::glcontext::OpenGLContext::ensure_resized
             at C:\Users\zhou\.cargo\git\checkouts\slint-8153123e5dffa129\7990bfe\internal\backends\winit\renderer\femtovg\glcontext.rs:46
   5: i_slint_backend_winit::renderer::femtovg::impl$0::resize_event
             at C:\Users\zhou\.cargo\git\checkouts\slint-8153123e5dffa129\7990bfe\internal\backends\winit\renderer\femtovg.rs:245
   6: i_slint_backend_winit::glwindow::impl$1::resize_event<i_slint_backend_winit::renderer::femtovg::FemtoVGRenderer>
             at C:\Users\zhou\.cargo\git\checkouts\slint-8153123e5dffa129\7990bfe\internal\backends\winit\glwindow.rs:244
   7: i_slint_backend_winit::event_loop::process_window_event
             at C:\Users\zhou\.cargo\git\checkouts\slint-8153123e5dffa129\7990bfe\internal\backends\winit\event_loop.rs:271
   8: i_slint_backend_winit::event_loop::run::closure$1
             at C:\Users\zhou\.cargo\git\checkouts\slint-8153123e5dffa129\7990bfe\internal\backends\winit\event_loop.rs:491
   9: i_slint_backend_winit::event_loop::run::closure$2::closure$0
             at C:\Users\zhou\.cargo\git\checkouts\slint-8153123e5dffa129\7990bfe\internal\backends\winit\event_loop.rs:611
  10: i_slint_backend_winit::event_loop::CURRENT_WINDOW_TARGET::set<i_slint_backend_winit::event_loop::run::closure$2::closure_env$0,tuple$<> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\scoped-tls-hkt-0.1.2\src\lib.rs:264
  11: i_slint_backend_winit::event_loop::run::closure$2
             at C:\Users\zhou\.cargo\git\checkouts\slint-8153123e5dffa129\7990bfe\internal\backends\winit\event_loop.rs:611
  12: winit::platform_impl::platform::event_loop::impl$3::run_return::closure$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent>,i_slint_backend_winit::event_loop::run::closure_env$2>
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop.rs:256
  13: alloc::boxed::impl$46::call_mut<tuple$<enum2$<winit::event::Event<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,ref_mut$<enum2$<winit::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum2$<winit::event::Event<enum2$<i_sli
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\alloc\src\boxed.rs:2016
  14: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:250
  15: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\panic\unwind_safe.rs:271
  16: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,tuple$<> >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\panicking.rs:483
  17: i_slint_backend_winit::renderer::femtovg::images::impl$10::default
  18: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\panicking.rs:447
  19: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,tuple$<> >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\panic.rs:137
  20: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::catch_unwind<enum2$<i_slint_backend_winit::event_loop::CustomEvent>,tuple$<>,winit::platform_impl::platform::event_loop::runner::
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:157
  21: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::call_event_handler<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:242
  22: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::send_event<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:224
  23: winit::platform_impl::platform::event_loop::WindowData<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::send_event<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop.rs:141
  24: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop.rs:1198
  25: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >,tuple$<> >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\ops\function.rs:507
  26: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\panic\unwind_safe.rs:271
  27: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,isize>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\panicking.rs:483
  28: i_slint_backend_winit::renderer::femtovg::images::impl$10::default
  29: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\panicking.rs:447
  30: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,isize>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\panic.rs:137
  31: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::catch_unwind<enum2$<i_slint_backend_winit::event_loop::CustomEvent>,isize,winit::platform_impl::platform::event_loop::public_wind
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:157
  32: winit::platform_impl::platform::event_loop::public_window_callback_inner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop.rs:2266
  33: winit::platform_impl::platform::event_loop::public_window_callback<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop.rs:940
  34: DispatchMessageW
  35: CallWindowProcW
  36: wglSwapBuffers
  37: DispatchMessageW
  38: DispatchMessageW
  39: GetClassLongW
  40: KiUserCallbackDispatcher
  41: NtUserMessageCall
  42: SendMessageW
  43: GetDlgCtrlID
  44: GetDlgCtrlID
  45: CloseThemeData
  46: CloseThemeData
  47: GetDlgCtrlID
  48: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop.rs:1173
  49: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >,tuple$<> >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\ops\function.rs:507
  50: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\panic\unwind_safe.rs:271
  51: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,isize>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\panicking.rs:483
  52: i_slint_backend_winit::renderer::femtovg::images::impl$10::default
  53: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\panicking.rs:447
  54: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,isize>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\panic.rs:137
  55: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::catch_unwind<enum2$<i_slint_backend_winit::event_loop::CustomEvent>,isize,winit::platform_impl::platform::event_loop::public_wind
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:157
  56: winit::platform_impl::platform::event_loop::public_window_callback_inner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop.rs:2266
  57: winit::platform_impl::platform::event_loop::public_window_callback<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop.rs:940
  58: DispatchMessageW
  59: CallWindowProcW
  60: wglSwapBuffers
  61: DispatchMessageW
  62: DispatchMessageW
  63: TranslateAcceleratorW
  64: KiUserCallbackDispatcher
  65: NtUserMessageCall
  66: GetDlgCtrlID
  67: GetDlgCtrlID
  68: Ordinal43
  69: GetThemeEnumValue
  70: CloseThemeData
  71: CloseThemeData
  72: GetDlgCtrlID
  73: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop.rs:1374
  74: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >,tuple$<> >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\ops\function.rs:507
  75: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\panic\unwind_safe.rs:271
  76: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,isize>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\panicking.rs:483
  77: i_slint_backend_winit::renderer::femtovg::images::impl$10::default
  78: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > > >
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\panicking.rs:447
  79: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<i_slint_backend_winit::event_loop::CustomEvent> > >,isize>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\std\src\panic.rs:137
  80: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >::catch_unwind<enum2$<i_slint_backend_winit::event_loop::CustomEvent>,isize,winit::platform_impl::platform::event_loop::public_wind
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:157
  81: winit::platform_impl::platform::event_loop::public_window_callback_inner<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop.rs:2266
  82: winit::platform_impl::platform::event_loop::public_window_callback<enum2$<i_slint_backend_winit::event_loop::CustomEvent> >
             at C:\Users\zhou\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.28.1\src\platform_impl\windows\event_loop.rs:940
  83: DispatchMessageW
  84: CallWindowProcW
  85: wglSwapBuffers
  86: DispatchMessageW
  87: DispatchMessageW
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\test_slint.exe` (exit code: 101)

**Comment by tronical** [comment]
I can reproduce this.

**Comment by tronical** [comment]
We receive the following funny events when minimising on Windows:

```
WindowEvent { window_id: WindowId(WindowId(2230020)), event: Moved(PhysicalPosition { x: -32000, y: -32000 }) }
WindowEvent { window_id: WindowId(WindowId(2230020)), event: Resized(PhysicalSize { width: 0, height: 0 }) }
```
