### ISSUE TITLE
Using FocusScope sometimes panics when in no_std

### ISSUE THREAD

**Issue by medhefgo** [slint-ui/slint#2199]
I am currently trying to get slint to work under UEFI. Rendering is working fine, including fonts and animations. I also have input working.

But for some reason, using a FocusScope panics depending on where it is used:
```slint
export component BootMenu inherits Window {
    forward-focus: fs;
    VerticalLayout {
        txt := Text {
        }
        fs := FocusScope {
            key-pressed(key) => {
                txt.text = key.text;
                accept
            }
        }
    }
}
```

The above gives me this panic:
```
[PANIC]: panicked at 'The software renderer requires enabling the `EmbedForSoftwareRenderer` option when compiling slint files.', /home/medhefgo/.cargo/registry/src/github.com-1ecc6299db9ec823/i-slint-core-0.3.4/software_renderer/fonts.rs:89:41
```
Even though the `.slint` file is compiled with that flag set:
```
fn main() {
    let config = slint_build::CompilerConfiguration::new()
        .with_style("material".into())
        .embed_resources(slint_build::EmbedResourcesKind::EmbedForSoftwareRenderer);
    slint_build::compile_with_config("src/boot-menu.slint", config).unwrap();
}
```

The really weird thing is that it sees to depend on where the FocusScope is being used. Moving the text item or removing the layout like this:
```slint
export component BootMenu inherits Window {
    forward-focus: fs;
    txt := Text {
    }
    fs := FocusScope {
        key-pressed(key) => {
            txt.text = key.text;
            accept
        }
    }
}
```
Will result in no panic and I get a white window and the pressed key appears as it should.

This seems to only happen in no_std, as both snippets work like they should in the preview window.

**Comment by ogoffart** [comment]
Hi, thanks for your bug report.

Really great that you try to get Slint to work on UEFI. I'm really interested in seeing the result.

As for your issue, this panic means that the font was not not embedded into the binary. Which is curious because you pass the right option.
The fact that the layout makes a difference makes me think that perhaps this might be cause by the fact that the Text is queried for its size before the initialization completes and the embedded fonts are registered to the runtime.

Could you produce a backtrace?

**Comment by tronical** [comment]
Ditto to what Olivier said, very cool that you're trying to get it working in UEFI!

I also suspect that somehow the registration happens too late. If creating a backtrace is tricky, could you try the following patch to Slint? It looks big, due to the reformat. But it's basically replacing `push(...)` with `insert(0, ...)`:

```patch
diff --git a/internal/compiler/passes/embed_glyphs.rs b/internal/compiler/passes/embed_glyphs.rs
index a1d3e8c81..b35a9da50 100644
--- a/internal/compiler/passes/embed_glyphs.rs
+++ b/internal/compiler/passes/embed_glyphs.rs
@@ -209,14 +209,17 @@ pub fn embed_glyphs<'a>(
             },
         );

-        component.init_code.borrow_mut().push(Expression::FunctionCall {
-            function: Box::new(Expression::BuiltinFunctionReference(
-                BuiltinFunction::RegisterBitmapFont,
-                None,
-            )),
-            arguments: vec![Expression::NumberLiteral(resource_id as _, Unit::None)],
-            source_location: None,
-        });
+        component.init_code.borrow_mut().insert(
+            0,
+            Expression::FunctionCall {
+                function: Box::new(Expression::BuiltinFunctionReference(
+                    BuiltinFunction::RegisterBitmapFont,
+                    None,
+                )),
+                arguments: vec![Expression::NumberLiteral(resource_id as _, Unit::None)],
+                source_location: None,
+            },
+        );
     };

     // Make sure to embed the default font first, because that becomes the default at run-time.
```

**Comment by medhefgo** [comment]
Oh boy, debugging UEFI apps is such a pita. Doesn't help that currently [no debug symbols are created for x86_64](https://github.com/rust-lang/rust/issues/87157).

The above patch seems to work.

**Comment by tronical** [comment]
Alright:). Thanks for trying! @ogoffart if you agree then I can try to replace that init_code vector with specialized vectors and very consciously concatenate them in defined/correct order later.
