### ISSUE TITLE
Shift+mouse wheel should scroll sideways

### ISSUE THREAD

**Issue by mgunyho** [slint-ui/slint#2228]
I think it's fairly standard for applications to scroll sideways with shift + scroll wheel. I would like to have this behavior for the ScrollView.

Related to #1280 I suppose.

**Comment by ogoffart** [comment]
That should be easy to do in the items/flickable.rs file when handling the wheel event we could check if shift is pressed. (We do that check also when clicking on a Textinput)

**Comment by DaMilyutin** [comment]
@ogoffart, some mouses has scroll left and scroll right buttons, too. It is done by tilting the wheel.
I guess it is same as shift+wheel. Just FYI.

**Comment by ogoffart** [comment]
@DaMilyutin Our Flickable and ScrollView already support that

**Comment by ogoffart** [comment]
I tried to look at what other framework do to see if this is really the case. (i'm on linux)

- Firefox and Chromium makes Shift + vertical scroll  an horizontal scroll.  (But shift + horizontal scroll stays a horizontal scroll)
- Qt ScrollArea / QML's flickable don't handle that
- But KDE application use Alt + scroll to reverse the scrolling direction (horizontal or horizontal) in most of their widget.
- Gtk application seems to use Shift + Scroll to reverse the scroll direction
- From the macos docs, i think they use shift + wheel to scroll horizontally
- On windows it depends on the apps.

So i'm tempted to say we can indeed do shift + wheel  to invert scroll direction

**Comment by ogoffart** [comment]
Implemented in PR https://github.com/slint-ui/slint/pull/2242
