### ISSUE TITLE
Git release branch for Slint 1.x releases?

### ISSUE THREAD

**Issue by hunger** [slint-ui/slint#2231]
Our C++ documentation suggests using the `release/0.3` git tag at this time. What should we suggest for post-1.0?

I see the following option:
 * Nothing: Let's just use master and let users do the pinning.
 * Have a `release/1` tag that always points to the latest and greatest 1.x (where x changes!)
 * Have `release/1.x` tags that always point to the latest and greates 1.x release (where x is stable!)
 * Do `release/1.x` branches and use their `HEAD`s
   * ... with `master` being the `release/1` branch at this time.
   * ... with a dedicated `release/1` branch

**Comment by ogoffart** [comment]
tag can't change, so you mean branch.

If we continue what we have now: a branch that follow semver, we would have:

`release/1`  that point to our latest release.  I just find the name a bit strange but i guess that's alright.
We could also have (in addition) a  `release/1.0`  that points to the latest 1.0.x release and have one such branch by minor version

In addition to the release branch, we may want to create version specific branch if we want to backport issues for a 1.0.1 release or something

**Comment by ogoffart** [comment]
> We have a release/0.2 tag

No we don't. Not on our main repository.
I think there might have been a tag by mistake for a very short time.

> CMake's FetchContents seems to need a sha or a tag to fetch a project from. Using a branch is not supported at this time AFAICT.

Well, we've been using it with a branch the all time

**Comment by tronical** [comment]
> How about using release/1.x (literal, no replacement) and release/1.0, release/1.1 for the minor versions?

I like it.

**Comment by ogoffart** [comment]
The checklist was updated in the internal wiki
