### ISSUE TITLE
Embedded SW Renderer doesn't properly show pages when visibility changes

### ISSUE THREAD

**Issue by A0lson** [slint-ui/slint#2261]
Inspired by the `printerdemo` example, I attempted to make a UI with "pages".  However, I find the software renderer behaves improperly compared to the default X11/Wayland renderer used under Linux.  The issue seems to be related to component `visibility` changes and the SoftwareRenderer's caching.

The following UI does not render properly with the embedded renderer with `RepaintBufferType::ReusedBuffer` but does render properly with `RepaintBufferType::NewBuffer`.

Steps to reproduce:
1) Click one button,  the appropriate page is displayed.
2) Click other button,  the appropriate page is displayed.
3) Click first button from step 1. No further update occurs.

I upgraded to commit `b61877e3a0dda234bcd18840934e83a292c204df` in master but still see this issue.

Curiously, the `SoftwareRenderer::render` method doesn't see anything "dirty" after the initial drawing of each page. 

It also doesn't seem to matter if the two pages overlap or not. However, if they do not overlap, they end up both remaining visible.

```
export component MainWindow inherits Window {
    
    preferred-height: 500px;
    preferred-width:  500px;
    
    property <int> active-page : 0;

    // PAGE 1:
    Rectangle { 
        x: 0px;
        y: 0px;
        height: 100px;
        

        Text {
            font-size: 100px;
            text : "Page 1";
        }
        visible: parent.active-page == 1;
     }

     // PAGE 2:
     Rectangle { 
        x: 0px;
        y: 0px;
        height: 100px;        
        

        Text {
            font-size: 100px;
            text : "Page 2";
        }
        visible: parent.active-page == 2;
     }

     // Button 1
     Text { 
        x: 0;
        y: 200px;
        width: 200px;
        height: 200px;
        text: "One";
        font-size: 50px;        
        
        TouchArea { 
            clicked => { root.active-page = 1; }
        }
      }

    // Button 2
    Text { 
        x: 200px;
        y: 200px;
        width: 200px;
        height: 200px;        
        text: "Two";
        font-size: 50px;        
        
        TouchArea { 
            clicked => { root.active-page = 2; }
        }
      }
}
```

**Comment by tronical** [comment]
@A0lson does #2346 fix the issue for you?:)

**Comment by A0lson** [comment]
Thanks, that fix seems to work well!
