### ISSUE TITLE
Crash after adding animation

### ISSUE THREAD

**Issue by TheIndifferent** [slint-ui/slint#2274]
Hi there,

I found adding a simple animation basically copy-pasted from language reference results in crash on Windows 10 MSVC toolkit without Qt backend:
https://github.com/TheIndifferent/disk_usage/commit/f4c1dbadd3d298c35bee06125584bcc7accf01b8

Tell me if there is any additional information or diagnostics I could provide to make it easier to find the cause.

**Comment by ogoffart** [comment]
Looks like a case where to slint compiler thought the property should be const, while it isn't.

**Comment by TheIndifferent** [comment]
Thank you for reproducing it, @hunger ! I just learned about `RUST_BACKTRACE` from your comment, gonna post my possible future bugreports with backtrace 😎

**Comment by ogoffart** [comment]
The problem occurs when the condition of every state is known at compile time, and that there is a transition in one of the state. If you want to work around, make sure the state depends on a property that changes at compile time.
