### ISSUE TITLE
Incorrect TextEdit's width when enabled is set to false.

### ISSUE THREAD

**Issue by AllenDang** [slint-ui/slint#2281]
Two TextEdits inside a VerticalBox, one with enabled to true, another with enabled to false, second one's width is incorrect.

![截屏2023-02-24 11 06 38](https://user-images.githubusercontent.com/18550/221082526-815aa8d6-158d-475a-8156-be5122ce45a9.png)

System Info:
macOS v13.2.1
rust edition: 2021
slint: 0.3.5
backend: [Winit](https://crates.io/crates/winit) with [Femtovg](https://crates.io/crates/femtovg)

**Comment by ogoffart** [comment]
Maybe related to #2284

**Comment by ogoffart** [comment]
Would you be able to provide a small .slint file that reproduce that problem?

**Comment by AllenDang** [comment]
@ogoffart Like I mentioned in first post, it's just two text edit inside a vertical box, one with enabled to false, you can verify it in a second even with online editor.

```
import { VerticalBox, TextEdit } from "std-widgets.slint";
export component Demo {
    VerticalBox {
        TextEdit {
        }
        TextEdit {
            enabled: false;
        }
    }
}
```

Here is the screen shot.

<img width="1378" alt="截屏2023-02-25 10 46 15" src="https://user-images.githubusercontent.com/18550/221332298-a6e52975-0883-4f35-a3a7-8f6944fe5e30.png">
