### ISSUE TITLE
Window content needs to be refresh after move window to another monitor and move it back.

### ISSUE THREAD

**Issue by AllenDang** [slint-ui/slint#2282]
I have a Macbook Pro with a external monitor.

Repo steps:
1. Lanuch application from external monitor.
2. Drag and move the window to Macbook Pro's monitor.
3. Drag and move it back to external monitor.

![截屏2023-02-24 11 11 24](https://user-images.githubusercontent.com/18550/221083217-eb1117cd-13e3-4bb8-aad4-5546c5d810ce.png)

A small version of window content will appear at left bottom corner. It will disappear after change window's size.
Seems a redraw is required here.

**Comment by tronical** [comment]
Hm, I can't reproduce this, but this looks bad. Can you tell us a little more about your configuration? What version of Slint are you using? Do you know what Slint backend you have configured?

**Comment by AllenDang** [comment]
Slint 0.3.5
I don't specify any backend, and my system doesn't have qt, so second default backend should be it.

**Comment by tronical** [comment]
Thank you for the information! I can reproduce the bug now.

**Comment by tronical** [comment]
With FemtoVG I get the described effect, with Skia the window isn't re-rendered in its entirety. Resizing "fixes" it.

**Comment by tronical** [comment]
I suspect that while we may receive a dpi change event and re-render, we're not correctly resizing the underlying surface.
