### ISSUE TITLE
Default size of elements should be the preferred size when not in layouts

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2284]
The current default geometry pass assigns the default width and height according to different rules, either 100%, or implicit, or zero - depending on the native item type (declared in builtins.slint).

We want to control that in widgets, for example a Button should have a default size that equals its preferred size - when not in layouts.

So the pass should always use the preferred size.

This would break items that inherit from Rectangle/Empty and expect 100% fill. Therefore we need to extend LayoutInfo to have a preferred-size-percentage and these items should specify their 100% in their layout_info() function.

Between preferred-size and preferred-size-percentage, the layout engine should pick the value that is not zero. Setting both to a non-zero value is a bug.

While going through all the items (native, and our widgets) and reviewing their preferred sizes, we should also review their stretch factors.

For example the following breaking changes should be done: Path and TouchArea should have a stretch of 1 in both directions. Alternatively: We could default to as a stretch and then review where that should not be applied.

This should also end up fixing #2187.

**Comment by ogoffart** [comment]
Some attempt at documenting it in https://github.com/slint-ui/slint/pull/2386

**Comment by ogoffart** [comment]
Done in #2386
