### ISSUE TITLE
Detect absent properties

### ISSUE THREAD

**Issue by chvllad** [slint-ui/slint#2290]
Currently it's not possible to determine if property was set or not. It's possible to assign it some default value if it's absent, but it's not possible to distinguish between user set value and a default one. It would be nice to have a built-in function like `has-property` to detect if property is set or not. Like this:
```
struct Data {
  color: brush,
  text: string,
}

component MyComponent {
  in property <Data> data;

  if has-property(data): Text {
    color: root.data.color;
    text: root.data.text;
  }
}
```

**Comment by tronical** [comment]
Yes. That would be nice to have. I think I'd prefer this to be an annotation though, like "optional property ..." and then access requires the use of an if/let.

**Comment by ogoffart** [comment]
duplicated of #615
