### ISSUE TITLE
energy-monitor: make the wasm build responsive

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2295]
On mobile, the wasm build of the energy monitor should show the "mcu" version, and as the device profile becomes bigger, we should pick a bigger version of the monitor's ui.

The basic responsiveness support landed in #2293, but for wasm it's always on the small profile right now because of the size constraints specified on the window.

**Comment by ogoffart** [comment]
The preferred size on desktop (and on the web?) should be different.  Maybe the dashboard one?
On the web, the HTML could have a combobox to switch between different size though.

**Comment by tronical** [comment]
> The basic responsiveness support landed in https://github.com/slint-ui/slint/pull/2293, but for wasm it's always on the small profile right now because of the size constraints specified on the window.

The current version (including for wasm) defaults now to the mid size profile, which looks quite okay on desktop and mobile. Making it fully responsive turns out to be rather difficult. See #2434 for the workaround needed.

I'm closing this for now as I don't think anyone at this point plans further work on this. But we can re-open if needed of course :)
