### ISSUE TITLE
StandardListView's viewport-y will not be updated after add new item

### ISSUE THREAD

**Issue by AllenDang** [slint-ui/slint#2325]
I use following code to create a StandardListView which should auto-scroll-to-bottom after new item is added, but seems the viewport-y will not be updated.

Following code works both in ScrollView and TextEdit.

```
StandardListView { 
  height: 200px;
  model: root.logs;
  viewport-y: min(0px, self.visible-height - self.viewport-height);
}
```

Env info:
slint: 0.3.5
backend: winit+ femtovg
OS: macOS

**Comment by ogoffart** [comment]
The thing here is that viewport-y's binding will be erased when it is scrolled.
So that's why it doesn't work in this case.

You probably want to call a function that sets the viewport-y each time you add an item.

**Comment by AllenDang** [comment]
@ogoffart How can I call a `slint function` to set the viewport-y from rust side?
