### ISSUE TITLE
The knob of scroll bar is too small.

### ISSUE THREAD

**Issue by AllenDang** [slint-ui/slint#2347]
![截屏2023-03-08 15 57 37](https://user-images.githubusercontent.com/18550/223654889-38b121d7-ed83-4a07-a1b4-e74089612a65.png)

It's too small if the StandardListView has large amount of items. Better to remain a minimal size for look & feel.

**Comment by FloVanGH** [comment]
Thank you for the feedback. The problem should be fixed with #2353 2353
