### ISSUE TITLE
CMake: rename BUILD_TESTING cache variable to SLINT_BUILD_TESTING

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2362]
`api/cpp/CMakeLists.txt` enables building the `tests` sub-dir when the `BUILD_TESTING` cache variable is true.

When Slint is used via FetchContent, the application's CMake cache is shared with Slint, and if the application directly or indirectly enters the same variable into the cache, the Slint tests would be compiled. That may fail for totally unrelated reasons and should not happen.

We should rename the variable.

**Comment by ItsRoy69** [comment]
Can I work on this issue ?

**Comment by tronical** [comment]
Yes that would be awesome ❤️
