### ISSUE TITLE
the window at the no frame mode, how can custom close action max or min  and the window drag move 

### ISSUE THREAD

**Issue by xiangyuan** [slint-ui/slint#2367]
this is my custom button.

![image](https://user-images.githubusercontent.com/914843/224474963-3e9db4e6-bf8a-499e-9f97-431f37d8ea35.png)

**Comment by tronical** [comment]
Hi! I’m not entirely sure that I understand. Are you disabling the window frame but you’re still seeing those buttons along with a window frame? What window manager are you using?

**Comment by ogoffart** [comment]
I think this issue ask for a feature to be able to customize the title bar.
Right now, this could be achieve by connecting the button to native code.

Relevant is also #613 and #610

**Comment by xiangyuan** [comment]
> I think this issue ask for a feature to be able to customize the title bar. Right now, this could be achieve by connecting the button to native code.
> 
> Relevant is also #613 and #610

yes, I want to ask whether have a feature to be able to customize the title bar.

**Comment by chonwhite** [comment]
I also have a similar request, I don't want the title bar, but not entirely, on mac I still want the close/min/full-screen buttons.
![image](https://github.com/slint-ui/slint/assets/1076429/4777b455-b260-4f1c-b084-ec323f034d8c)

[https://developer.apple.com/documentation/uikit/mac_catalyst/removing_the_title_bar_in_your_mac_app_built_with_mac_catalyst?language=objc](https://developer.apple.com/documentation/uikit/mac_catalyst/removing_the_title_bar_in_your_mac_app_built_with_mac_catalyst?language=objc)
