### ISSUE TITLE
Add a method to obtain the changed parts.

### ISSUE THREAD

**Issue by Multi-Illusion** [slint-ui/slint#2389]
When using Slint on stm32f4, in order to achieve faster screen refresh rate, I need to use DMA and write as much data as possible at one time. 'render_by_line' is not efficient as it breaks up the data. Therefore, each time when refreshing the screen, I send all the data in the pixel_buffer to the screen (in fact, this method is more efficient than 'render_by_line').

For this reason, I hope to add a method to obtain only the part that has changed during each rendering. This way, I will only need to update the changed portion of the pixel_buffer to the screen, thereby improving the performance of Slint on stm32f4."

**Comment by ogoffart** [comment]
Thanks for filling an issue.

This is a valid request, this information would be usefull.

I wonder if this should be the return value of the render function, or something like that.

**Comment by Multi-Illusion** [comment]
> I wonder if this should be the return value of the render function, or something like that.

I think that would be okay.

**Comment by ogoffart** [comment]
I'm trying to draft a future-proof API.  And I'm thinking that in the future we would not just repaint rectangle, but it could be more complex regions.  So I was thinking adding a `slint::platform::software_renderer::Region` type and return that from the `SoftwareRenderer::render()` function.

It would just be an opaque type that just wrap the (private) PhysicalRect

In the future, it could become a more complex type that represents more complex region.

```rust

/// Represents the region of the screen that was repainted
#[derive(Clone, Debug)]
pub struct Region(PhysicalRect);

impl Region {
    /// Returns the size of the bounding box of this region
    pub fn bounding_size(&self) -> crate::api::PhysicalSize { todo!() }
    /// Returns the origin of the bounding box of this region
    pub fn bounding_origin(&self) -> crate::api::PhysicalPosition { todo!() }
}

```

@tronical  what do you think?

**Comment by tronical** [comment]
That makes exactly what I was thinking too. It will most likely be a bunch of rectangles and making it opaque seems like the right choice. In terms of name I'd prefer `PhysicalRegion` instead of `Region`.
