### ISSUE TITLE
Remove workaround for incorrect touch coordinates with winit on the web

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2424]
Once https://github.com/rust-windowing/winit/pull/2704 is merged and released, we can unpick winit in the winit backend and remove the workaround for fixing the coordinates of touch events in wasm builds.

**Comment by ogoffart** [comment]
The commit to revert is https://github.com/slint-ui/slint/pull/2302  (5879e1ec710b471d78012b99a188b1ac61d3c82e)
