### ISSUE TITLE
figma_import Error No Start node

### ISSUE THREAD

**Issue by vonnieda** [slint-ui/slint#2470]
I am testing out Slint, and I saw there was a Figma importer so I tried it out. I got an error:

Fetch document [hidden]...
Fetch 12 images ...
Error: Error("No start node")

I'm pretty new to Figma, so it's possible there's something wrong with my file but I searched around and couldn't find references to start node.

Here's the Figma file, if it helps. [music player.fig.zip](https://github.com/slint-ui/slint/files/11141297/music.player.fig.zip)

**Comment by ogoffart** [comment]
Thanks for reporting an issue


This happens when there is no start node in the figma project.
You can try to specify a node with the `--node` parameter
I made a commit to make the error message more explicit.

Please note that the figma importer is really experimental and not really maintained.

**Comment by ogoffart** [comment]
I'm going to close this since we now have a better error message for this particular case.
