### ISSUE TITLE
Failed to build Rust Example 

### ISSUE THREAD

**Issue by cjsmocjsmo** [slint-ui/slint#2472]
OS: ubuntu 22.10
Hardware: Raspberry Pi 4 (arm64)
Rust: rustc 1.68.0 (2c8cc3432 2023-03-06)

After running
- cargo new memory
- cd memory
- cargo add slint@1.0.0

And then placing this code in main.rs

> fn main() {
          MainWindow::new().unwrap().run().unwrap();
}

> slint::slint! {
     export component MainWindow inherits Window {
        Text {
            text: "hello world";
            color: green;
       }
   }
}

This is the output:

RUST_BACKTRACE=1 cargo run
   Compiling yeslogic-fontconfig-sys v3.2.0
   Compiling x11rb-protocol v0.10.0
   Compiling integer-sqrt v0.1.5
   Compiling gethostname v0.2.3
error: failed to run custom build command for `yeslogic-fontconfig-sys v3.2.0`

Caused by:
  process didn't exit successfully: `/media/charliepi/HD/rustpro/memory/target/debug/build/yeslogic-fontconfig-sys-d5efd17a2c6c1090/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=RUST_FONTCONFIG_DLOPEN
  cargo:rerun-if-env-changed=FONTCONFIG_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=FONTCONFIG_STATIC
  cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=\"1\" PKG_CONFIG_ALLOW_SYSTEM_LIBS=\"1\" \"pkg-config\" \"--libs\" \"--cflags\" \"fontconfig\"` did not exit successfully: exit status: 1\nerror: could not find system library 'fontconfig' required by the 'yeslogic-fontconfig-sys' crate\n\n--- stderr\nPackage fontconfig was not found in the pkg-config search path.\nPerhaps you should add the directory containing `fontconfig.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'fontconfig' found\n"', /home/charliepi/.cargo/registry/src/github.com-1ecc6299db9ec823/yeslogic-fontconfig-sys-3.2.0/build.rs:8:48
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
     2: core::result::unwrap_failed
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1790:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1112:23
     4: build_script_build::main
               at ./build.rs:8:9
     5: core::ops::function::FnOnce::call_once
               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5

but according to apt fontconfig is installed:

sudo apt-get install fontconfig
[sudo] password for charliepi: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fontconfig is already the newest version (2.13.1-4.4ubuntu1).
fontconfig set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

**Comment by tronical** [comment]
I think that you need libfontconfig-dev. Alternatively, while building you can set the RUST_FONTCONFIG_DLOPEN environment variable to the value 1

**Comment by tronical** [comment]
Marking as duplicate.

**Comment by cjsmocjsmo** [comment]
Thanks guys  that did the trick.  Would have been nice to have known about needing this  dependency before hand. :)

**Comment by tronical** [comment]
Yeah, it's a little unfortunate that there's no "configure" step or so to produce a good message. My objective with #2376 is to make the dependency optional at run-time instead of compile time.
