### ISSUE TITLE
Access globals on JavaScript/TypeScript

### ISSUE THREAD

**Issue by FloVanGH** [slint-ui/slint#2478]
At the moment it is not possible to access exported globals from JavaScript/TypeScript. For Rust and C++ it's possible.

An equivalent api could looks like this:

```typescript
my_window.global<MyAdapter>().text = "Hello global";
my_window.global<MyAdapter>().clicked.setHandler(() => console.log("clicked"));
```

**Comment by tronical** [comment]
I think a related question here is: How would the pure JavaScript API look like? (because that's what the implementation would have to use)

**Comment by FloVanGH** [comment]
Maybe what could work also in plan JS is something like.

```javascript
MyGlobal.text = "Hello global";
```

What do you think?

**Comment by tronical** [comment]
Hmm, but that would mean adding a `MyGobal` property to the Javascript global object. What if you use two .slint files that both have a different `MyGlobal`?

I think we need an API that's tied to the instance.

**Comment by FloVanGH** [comment]
> Hmm, but that would mean adding a MyGobal property to the Javascript global object. What if you use two .slint files that both have a different MyGlobal?

Is that not the same problem with the other languages. The type is used that is exported in the main slint file. 

```slint
export global MyGlobal {
    in property<string> text;
}
```

```javascript
let global = MyGlobal.instance();
global.text = "Hello global";
```

So we need to access the instance of the exported global.

**Comment by tronical** [comment]
The type can be namespaces, but `MyGlobal.text` is looking up `MyGlobal` as a property in the global object.

**Comment by FloVanGH** [comment]
done with #3815
