### ISSUE TITLE
Timer functions outside of main cannot trigger the timer

### ISSUE THREAD

**Issue by CarbonPool** [slint-ui/slint#2482]

**Comment by ogoffart** [comment]
Thanks for reporting a bug. 
We're just going to need a bit more information to be able to investigate the problem.
What programming language are you using, and on what operating system are you? Which of the Slint backend is active?

Would you have a sample code to explain what you're trying to do?

Thanks.

**Comment by FloVanGH** [comment]
Maybe the problem is located in the Node.Js port. I checked something and have figure out that the timer does not work with class methods but with class closure.

This works not (`Error: internal error in Neon module: Recursion in timer code`): 

```typescript
export class Hello {
    constructor() {
        slint.Timer.singleShot(500, this.sayHello);
    }

    sayHello(): void {
        console.log("hello");
    }
}
```

This works:

```typescript
export class Hello {
    constructor() {
        slint.Timer.singleShot(500, this.sayHello);
    }

    sayHello = () => void {
        console.log("hello");
    };
}
```

```

**Comment by CarbonPool** [comment]
> Maybe the problem is located in the Node.Js port. I checked something and have figure out that the timer does not work with class methods but with class closure.
> 
> This works not (`Error: internal error in Neon module: Recursion in timer code`):
> 
> ```ts
> export class Hello {
>     constructor() {
>         slint.Timer.singleShot(500, this.sayHello);
>     }
> 
>     sayHello(): void {
>         console.log("hello");
>     }
> }
> ```
> 
> This works:
> 
> ```ts
> export class Hello {
>     constructor() {
>         slint.Timer.singleShot(500, this.sayHello);
>     }
> 
>     sayHello = () => void {
>         console.log("hello");
>     };
> }
> ```

Sorry I'm a bit late, I wrote the example using rust, I added the code.

**Comment by CarbonPool** [comment]
`
mod stand;
use slint::{Timer, TimerMode, ComponentHandle};
fn main() {
    let app = stand::HelloWorld::new().unwrap();
    start_time_task();
    app.run().unwrap();
}

fn start_time_task() {
    let timer = Timer::default();
    timer.start(TimerMode::Repeated, std::time::Duration::from_secs(2), move || {
        println!("{:?}", 1);
    });
}
`

no message printed

**Comment by tronical** [comment]
I think the reason the timer never invokes is because it is dropped at the end of the function scope. I suggest to return it and thus move it into the main function.
