### ISSUE TITLE
panicked at 'invalid expression while evaluating'

### ISSUE THREAD

**Issue by jturcotte** [slint-ui/slint#2483]
```js
export Test := VerticalLayout {
    spacing: 1px;

    HorizontalLayout {
        Rectangle {
            // At first I didn't see that there was an HorizontalLayout in-between in the original code.
            width: parent.height - parent.spacing;
        }
    }
}
```

This is with slint-viewer/slint-lsp 0.3.5, I tried it in the 1.0 SlintPad and it seems to panic there as well.

**Comment by tronical** [comment]
AFAICS it's the `parent.spacing` that somehow turns into a `Expression::Invalid` and in the phase lowering to the LLR that panics (since Invalid is kind of hard to lower ;-)

When lowering the binding for width:

```rust
        tree_Expression::BinaryExpression { lhs, rhs, op } => llr_Expression::BinaryExpression {
            lhs: Box::new(lower_expression(lhs, ctx)),
            rhs: Box::new(lower_expression(rhs, ctx)), <-- rhs is Expression::Invalid
            op: *op,
        },
```

**Comment by ogoffart** [comment]
The viewer and LSP don't lower to LLR,  this is probably in the eval phase of the interpreter.  But if the LLR makes invalid code, this probably fails for the same reason.

**Comment by tronical** [comment]
Yes, the above is with slint-compiler, but with the interpreter it's exactly the same:

```rust
        Expression::BinaryExpression { lhs, rhs, op } => {
            let lhs = eval_expression(&**lhs, local_context);
            let rhs = eval_expression(&**rhs, local_context); <-- rhs is invalid

```
