### ISSUE TITLE
Text input widgets don't render entered text in no_std

### ISSUE THREAD

**Issue by medhefgo** [slint-ui/slint#2511]
Any of the text input widgets do not render any entered text when in no_std. Note that input is working properly as the text can be linked to a `Text` item where it will appear as it should. Also, the placeholder text in a `LineEdit` is rendered correctly.

Easy to reproduce with https://github.com/slint-ui/slint/pull/2509 (it already contains a `LineEdit` to use).

This snipped easily proves that input is still handled properly:
```
a:=TextEdit {}
b:=TextInput {}
c:=LineEdit {}
Text { text: a.text + b.text + c.text; }
```

**Comment by tronical** [comment]
Yes indeed, the software renderer's `draw_text_input` is empty right now. @FloVanGH is working on filling those bits :-)

**Comment by ogoffart** [comment]
The only remaining part is to do the highlight of the selection.

**Comment by ogoffart** [comment]
1.1 also has the selection. It's not perfect but good enough to be usable
