### ISSUE TITLE
Add support for MultiTouchArea

### ISSUE THREAD

**Issue by larry104** [slint-ui/slint#2532]
To be able to do gesture detection and to capture multi touch events a MultiTouchArea is needed so it can capture multiple events. Touch screens support typically up to 10 touch points so the MultiTouchArea should fire off events accordingly, (ref QML element MultiTouchArea)

**Comment by ogoffart** [comment]
We either need a MultiTouchArea, or we at least need to support multi touch in the same touch area.

Either way, i think it would also make sense for several TouchArea to handle (a dfferent) touch at the same time.  (so for example, one could press two buttons at the same time with two finger, or move two sliders.
