### ISSUE TITLE
Resizing todo example to minimal size breaks ListView

### ISSUE THREAD

**Issue by medhefgo** [slint-ui/slint#2545]
If the todo example is resized to minimal size, the ListView inside stops showing any items in it (including newly added). This only seems to happen with the native style.
![image](https://user-images.githubusercontent.com/7892635/231789662-d41c73c7-1803-41f6-9cf1-6fdf5994cb2f.png)
![image](https://user-images.githubusercontent.com/7892635/231789723-671ebb04-5c30-404d-b0ef-5a79db731b94.png)

**Comment by ogoffart** [comment]
Looks like the NativeStyle ListView's constraints are not properly set

**Comment by ogoffart** [comment]
Ah, there is something really buggy indeed, i can reproduce: all items disapear
