### ISSUE TITLE
Window size does not grow automatically in GNOME on Wayland

### ISSUE THREAD

**Issue by aneesahmedpro** [slint-ui/slint#2581]
## Steps to reproduce:

1.  Create a new Cargo project:
    ```sh
    cargo new slint-bug
    ```
1.  Add the `slint` dependency to the Cargo project:
    ```sh
    cargo add slint@1.0.0
    ```
1.  Make the `main.rs` look like this:
    ```rust
    slint::slint! {
        import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";

        export component AppWindow inherits Window {
            in-out property <int> button-count: 3;

            VerticalBox {
                HorizontalBox {
                    Button {
                        text: "ADD ONE";
                        clicked => { button-count += 1; }
                    }
                    Button {
                        text: "REMOVE ONE";
                        clicked => { button-count -= 1; }
                    }
                }

                for button[index] in root.button-count: Button {
                    text: "I am Button #" + index;
                }
            }
        }
    }

    fn main() {
        AppWindow::new().unwrap().run().unwrap();
    }
    ```
1.  Build and run (do NOT use QT backend or `native` style, use either `winit-femtovg` or `winit-skia` renderer):
    ```sh
    cargo run
    ```
1.  Press the "ADD ONE" button many times (e.g 10 times). Notice that the window does not grow in size. Bottom buttons are hidden.<br>
    Also, when trying to resize manually (using cursor), window suddenly jumps to the correct size before starting to respond to the cursor movement.

## Context

Operating System: Ubuntu 22.10, GNOME 43.1, Wayland
Slint version: 1.0.0
Rust version: 1.66.1

**Comment by tronical** [comment]
I can reproduce this, it seems specific to the winit backend.

**Comment by tronical** [comment]
Debugging this, I can see how we're calling `set_min_inner_size` on the `winit` window, but winit doesn't seem to apply it. If as a user I try to resize the window, then it'll "snap" into place.

**Comment by LoganDark** [comment]
> but winit doesn't seem to apply it

I don't think it's supposed to? The minimum size is for user input only. If you want the window to also change size to match, you have to do that manually.

**Comment by aneesahmedpro** [comment]
> I don't think it's supposed to?

In the grand scheme of things, it does feel like it's a "bug" on Wayland, because backends seem to be capable of auto-resizing on X11 just fine. Not that there is anything wrong in it; Wayland was designed to prefer security over features, after all. If this really is not possible on Wayland, it would be good get this documented officially though, so developers can get warned about it.

> If you want the window to also change size to match, you have to do that manually.

Is there a way to do this manually? I couldn't find anything in the docs. I hoped to find something like `app_window.auto_resize()` or something.

**Comment by LoganDark** [comment]
> Is there a way to do this manually? I couldn't find anything in the docs.

It's slint's job to do this with winit, this is a slint bug.

**Comment by tronical** [comment]
> > but winit doesn't seem to apply it
> 
> I don't think it's supposed to? The minimum size is for user input only. If you want the window to also change size to match, you have to do that manually.

I think you're right about that. I kind of missed that in my thinking and expected winit to apply it.

That sounds easily fixable on our side then.

**Comment by LoganDark** [comment]
> I think you're right about that. I kind of missed that in my thinking and expected winit to apply it.

On Windows, [AltSnap](https://github.com/RamonUnch/AltSnap) allows me to resize windows in any way I like regardless of any minimum or maximum sizes or even when resizing is completely disabled or the window is borderless.

Min/max sizes aren't actually invariants, at least on Windows. Therefore it is also probably the job of the program to make sure the window size is updated correctly if it wants to follow its own size constraints.

The existence of a platform (Wayland) that doesn't automatically update the window size in response to changing the minimum/maximum sort of confirms that.

So yeah, I'm pretty sure this would be most appropriately fixed in slint itself, by also explicitly setting the size of the window after changing the minimum size.
