### ISSUE TITLE
hi, I use linux and rust as backend. I want to open a filedialog to select a file in filesystem. slint provides any function to do this?

### ISSUE THREAD

**Issue by Heng30** [slint-ui/slint#2583]

**Comment by Vadoola** [comment]
I remember seeing a Discussion that answered this questions a few months ago: https://github.com/slint-ui/slint/discussions/1959

**Comment by ogoffart** [comment]
Hi,

Thanks @Vadoola for replying.
File dialog can indeed be done using the rfd crate.

Closing this issue as duplicate of #1959
