### ISSUE TITLE
Need methods getting monitor size to center window on screen.

### ISSUE THREAD

**Issue by Berrysoft** [slint-ui/slint#2596]
Although #723 is closed, we still cannot center window on screen because we don't know the screen size.

Winit provides methods to get all monitors.

**Comment by ogoffart** [comment]
I think at some point, we'll have to make backend public API and expose winit somehow.
Otherwise we'll end up having to duplicate almost the whole of winit API in Slint.

**Comment by tronical** [comment]
In https://github.com/slint-ui/slint/pull/2617 we added API to the i-slint-backend-winit crate that provides you with access to the event loop and the winit window, which means you can access monitor details and place windows accordingly. Can you give this a try?

**Comment by Berrysoft** [comment]
@tronical Thank you! It works well, but only after the window shown can I get the inner winit window. Anyway it solves my problem. Waiting for a new release including this API:)

**Comment by tronical** [comment]
Yes, that's indeed a limitation right now. We might be able to remove that limitation if we create the window initially hidden.

**Comment by Berrysoft** [comment]
Close because 1.0.2 is released.
