### ISSUE TITLE
Duplication and increase binary size when same image referenced with different paths

### ISSUE THREAD

**Issue by xgroleau** [slint-ui/slint#2608]
It seems when an image is referenced multiple times but with different paths (due to two files not begin in the same directory), causes the binary size.

For example, if one component uses `@image("images/some-image")` while another uses `@image("../images/some-image")` causes the increase in binary size.

See [here](https://github.com/xgroleau/slint/tree/issue/binary-size-image-duplication/examples/flash-usage-mcu) to reproduce. I've left the elf file to avoid compilation, but to reproduce, compile to stm32h7.
```
cargo build -p flash_usage_mcu --no-default-features  --features=mcu-board-support/stm32h735g --target=thumbv7em-none-eabihf
```

See [here](https://github.com/xgroleau/slint/blob/issue/binary-size-image-duplication/examples/flash-usage-mcu/ui/main-same-file.slint) the code where the image uses the same path.

See [here](https://github.com/xgroleau/slint/blob/issue/binary-size-image-duplication/examples/flash-usage-mcu/ui/main-other-file.slint) the code where the image uses different same path.

The code should be equivalent but when checking the size, the one with different path is greater
```
❯ arm-none-eabi-size main-no-image.elf
   text    data     bss     dec     hex filename
 615404     172  728128 1343704  1480d8 main-no-image.elf
❯ arm-none-eabi-size main-same-file.elf
   text    data     bss     dec     hex filename
 638276     172  728128 1366576  14da30 main-same-file.elf
❯ arm-none-eabi-size main-other-file.elf
   text    data     bss     dec     hex filename
 643132     172  728128 1371432  14ed28 main-other-file.elf
```

**Comment by tronical** [comment]
I can reproduce this. We fail to canonicalise the computed paths :(

**Comment by tronical** [comment]
I've got a patch up for review that fixes this. I get slightly different absolute numbers, but it looks correct to me in terms of duplication:

For main-other-file this is what I get:

```
before patch:

   text    data     bss     dec     hex filename
 628068     172  728128 1356368  14b250 ../../target/thumbv7em-none-eabihf/debug/flash_usage_mcu

after patch:

   text    data     bss     dec     hex filename
 620388     172  728128 1348688  149450 ../../target/thumbv7em-none-eabihf/debug/flash_usage_mcu
```
