### ISSUE TITLE
[ Slint vscode extension] Preview not updated

### ISSUE THREAD

**Issue by MahanBi** [slint-ui/slint#2616]
Slint LSP extension properties it's working but I can't see the live preview
![image](https://user-images.githubusercontent.com/68824365/233649256-c8762192-31ed-44c5-ab41-81f7edc132a0.png)

**Comment by MahanBi** [comment]
if you have this problem you can ctrl+shift+p.
after that type `slint` and restart the server

**Comment by ogoffart** [comment]
This usually mean there are error in the slint files.
These error should be in the "problems" tabs.

**Comment by MahanBi** [comment]
no doesn't show anything, when I restart the server everything is fixed but when I open the file after closing vscode indicate this error again

**Comment by rainbyte** [comment]
I also have that error with `Slint` extension, but I noticed it is not happening on `Slint (nightly)`

**Comment by MahanBi** [comment]
> I also have that error with `Slint` extension, but I noticed it is not happening on `Slint (nightly)`

thanks i will try it.

**Comment by ogoffart** [comment]
Might be related to #2632 

Is there something in the "Slint LSP" Output tab?

![image](https://user-images.githubusercontent.com/959326/234212235-7a97e865-5911-452c-8cf3-e61bccd8d338.png)

(If there is no "Slint LSP" entry there it means that it is empty.

**Comment by ogoffart** [comment]
Sorry, i meant https://github.com/slint-ui/slint/issues/2609
