### ISSUE TITLE
Image doesn't support texts in SVG.

### ISSUE THREAD

**Issue by Berrysoft** [slint-ui/slint#2646]
Now `slint-core` uses `resvg`, which simply ignore all texts in SVG.

**Comment by tronical** [comment]
You're right, it seems that this regressed with 69df22e2fb54a071f8baa4554e28fb1fe1f3ffe5 , which removed the `text` feature.

**Comment by Berrysoft** [comment]
Why don't we render the texts in our renderer? In that way, we can handle all texts and fonts together.
