### ISSUE TITLE
Sogou Input Method window cannot be located near the text box

### ISSUE THREAD

**Issue by alanthinker** [slint-ui/slint#2658]
When using Sogou Input Method in China, the input method window cannot be located near the text box and always appears at the bottom of the screen. 
Sogou Input Method has 530 million users in China, and we hope to make it compatible with this input method. 

The default setting for Sogou Input Method is for the input window position to follow the location of the input cursor. Maybe this input cursor is a concept in Windows, but I am not entirely sure.

Test in slint example: todo
Testing environment: Windows 10. slint 1.0.2

Sogou Input Method download: 
https://shurufa.sogou.com/

**Comment by alanthinker** [comment]
#https://github.com/rust-windowing/winit/issues/2780

**Comment by ogoffart** [comment]
Thanks for reporting the issue.
However, as you found out, this seems to be a bug in winit, and it appear we can't do much within Slint.
So I'm closing this issue as it is tracked in the winit issue.
