### ISSUE TITLE
Update xcb dependency

### ISSUE THREAD

**Issue by kivimango** [slint-ui/slint#2682]
Hello !
After updating to slint 1.0.2, re-running my app crashes immediately.
I was able to track down the source, looks like the ```xcb``` dependency had some misalligned pointer dereference error, which has been resolved as of https://github.com/rust-x-bindings/rust-xcb/pull/225

```cargo tree```:
i-slint-backend-selector v1.0.2
    │   ├── cfg-if v1.0.0
    │   ├── i-slint-backend-winit v1.0.2
    │   │   ├── cfg-if v1.0.0
    │   │   ├── const-field-offset v0.1.3 (*)
    │   │   ├── copypasta v0.8.1
    │   │   │   └── x11-clipboard v0.6.1
    │   │   │       └── xcb v1.2.0

Features:
```compat-1-0", "backend-winit-x11", "renderer-winit-software"```

Stack trace:
>thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x2 but is 0x7fff908a014b', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xcb-1.2.0/src/base.rs:253:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
   0:     0x55f2b15b56d1 - std::backtrace_rs::backtrace::libunwind::trace::hfc6a5774a285598b
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55f2b15b56d1 - std::backtrace_rs::backtrace::trace_unsynchronized::h072f54729cb03fbe
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f2b15b56d1 - std::sys_common::backtrace::_print_fmt::h90cd727091743039
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55f2b15b56d1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha69a7d6d7744182b
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55f2b15d8b1f - core::fmt::rt::Argument::fmt::h1c053c61e28a4a2c
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/fmt/rt.rs:138:9
   5:     0x55f2b15d8b1f - core::fmt::write::h707e377e40255013
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/fmt/mod.rs:1094:21
   6:     0x55f2b15b2d21 - std::io::Write::write_fmt::h06bf41bbac8dfb21
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/io/mod.rs:1712:15
   7:     0x55f2b15b54e5 - std::sys_common::backtrace::_print::h02d5472e5e75dcdd
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55f2b15b54e5 - std::sys_common::backtrace::print::haa13109f6fde1202
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55f2b15b69a7 - std::panicking::default_hook::{{closure}}::ha0df47df6da4e474
  10:     0x55f2b15b6794 - std::panicking::default_hook::hef982eb890cb84ba
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panicking.rs:288:9
  11:     0x55f2b15b6e41 - std::panicking::rust_panic_with_hook::hdb4ce4a14cdedead
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panicking.rs:691:13
  12:     0x55f2b15b6cf1 - std::panicking::begin_panic_handler::{{closure}}::h94ea044a275497a3
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panicking.rs:580:13
  13:     0x55f2b15b5b16 - std::sys_common::backtrace::__rust_end_short_backtrace::h6d526ec8e2ca61bd
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/sys_common/backtrace.rs:150:18
  14:     0x55f2b15b6aa2 - rust_begin_unwind
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panicking.rs:578:5
  15:     0x55f2b0f21403 - core::panicking::panic_nounwind_fmt::hf9001e4dbfe5da65
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/panicking.rs:96:14
  16:     0x55f2b0f214a7 - core::panicking::panic_nounwind::h5a0a526ad9e6614b
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/panicking.rs:126:5
  17:     0x55f2b0f21633 - core::panicking::panic_cannot_unwind::hb608469ac1150263
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/panicking.rs:188:5
  18:     0x55f2b11b61e8 - <u16 as xcb::base::WiredOut>::serialize::ha109abfae04531dc
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xcb-1.2.0/src/base.rs:224:13
  19:     0x55f2b11b1577 - <xcb::xproto::InternAtom as xcb::base::RawRequest>::raw_request::haceab93366f66be3
                               at /run/media/user/Adat/Projektek/Programming/orbutils/target/debug/build/xcb-a345a9a54521c716/out/xproto.rs:13317:9
  20:     0x55f2b118d3c4 - xcb::base::Connection::send_request::h450e402cbd453a04
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xcb-1.2.0/src/base.rs:1416:43
  21:     0x55f2b11a3683 - x11_clipboard::Atoms::intern_all::h6b134dac6a2885bf
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/x11-clipboard-0.6.1/src/lib.rs:32:25
  22:     0x55f2b11a421c - x11_clipboard::Context::new::he75efaf27bbdf290
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/x11-clipboard-0.6.1/src/lib.rs:114:21
  23:     0x55f2b11a44b3 - x11_clipboard::Clipboard::new::h9a4e23d9f58cbd90
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/x11-clipboard-0.6.1/src/lib.rs:128:22
  24:     0x55f2b0f8860e - copypasta::x11_clipboard::X11ClipboardContext<S>::nw::h141d13982971e00a
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/copypasta-0.8.1/src/x11_clipboard.rs:52:32
  25:     0x55f2b100e917 - i_slint_backend_winit::event_loop::create_clipboard::hb4d5c34c6bad4172
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.0.2/event_loop.rs:806:28
  26:     0x55f2b1007172 - i_slint_backend_winit::event_loop::NotRunningEventLoop::new::h696afa6ff3b77934
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.0.2/event_loop.rs:73:38
  27:     0x55f2b101018f - i_slint_backend_winit::event_loop::MAYBE_LOOP_INSTANCE::__init::hf7b8d73d45c216a7
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.0.2/event_loop.rs:145:90
  28:     0x55f2b101026a - i_slint_backend_winit::event_loop::MAYBE_LOOP_INSTANCE::__getit::{{closure}}::h4d786bc48502db46
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/sys/common/thread_local/fast_local.rs:102:25
  29:     0x55f2b0f9202a - std::sys::common::thread_local::lazy::LazyKeyInner<T>::initialize::h996c5618b2811d1f
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/sys/common/thread_local/mod.rs:49:25
  30:     0x55f2b0ff89a6 - std::sys::common::thread_local::fast_local::Key<T>::try_initialize::h754c2ed9381a260a
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/sys/common/thread_local/fast_local.rs:194:27
  31:     0x55f2b0ff8e46 - std::sys::common::thread_local::fast_local::Key<T>::get::h30463b14016c221b
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/sys/common/thread_local/fast_local.rs:177:25
  32:     0x55f2b1010207 - i_slint_backend_winit::event_loop::MAYBE_LOOP_INSTANCE::__getit::h4b34f19e195d5b04
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/sys/common/thread_local/fast_local.rs:94:21
  33:     0x55f2b0fb8fa9 - std::thread::local::LocalKey<T>::try_with::h6168ec621845a81c
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/thread/local.rs:269:32
  34:     0x55f2b0fb752d - std::thread::local::LocalKey<T>::with::h45c02611082c5740
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/thread/local.rs:246:9
  35:     0x55f2b1007d21 - i_slint_backend_winit::event_loop::with_window_target::hf2db36eb812dcb09
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.0.2/event_loop.rs:201:9
  36:     0x55f2b100ecc0 - <i_slint_backend_winit::renderer::sw::WinitSoftwareRenderer as i_slint_backend_winit::renderer::WinitCompatibleRenderer>::show::h97b844f9b4d2c2be
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.0.2/renderer/sw.rs:35:22
  37:     0x55f2b0faeaf6 - <i_slint_backend_winit::winitwindowadapter::WinitWindowAdapter<Renderer> as i_slint_core::window::WindowAdapterSealed>::show::{{closure}}::hf64df5725d6afc59
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.0.2/winitwindowadapter.rs:618:32
  38:     0x55f2b0f7aa5f - core::ops::function::FnOnce::call_once::h523b4ba2be4080ee
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/ops/function.rs:250:5
  39:     0x55f2b0fab7e7 - i_slint_backend_winit::winitwindowadapter::WinitWindowAdapter<Renderer>::call_with_event_loop::h9d3ac76a4940e74a
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.0.2/winitwindowadapter.rs:199:16
  40:     0x55f2b0fad25e - <i_slint_backend_winit::winitwindowadapter::WinitWindowAdapter<Renderer> as i_slint_core::window::WindowAdapterSealed>::show::hf6884c2fb1498d78
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-backend-winit-1.0.2/winitwindowadapter.rs:463:9
  41:     0x55f2b125d4d0 - i_slint_core::window::WindowInner::show::h3c61623dad585698
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.0.2/window.rs:651:9
  42:     0x55f2b11c6307 - i_slint_core::api::Window::show::hc610407b8178ac4c
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.0.2/api.rs:347:9
  43:     0x55f2b0f3dbb3 - <orblogin::generated_code::slint_generatedLoginWindow::LoginWindow as i_slint_core::api::ComponentHandle>::show::h519ea1e143a71f7b
                               at /run/media/user/Adat/Projektek/Programming/orbutils/target/debug/build/orblogin-13fb8bbe9a0175ca/out/login_window.rs:3552:14
  44:     0x55f2b0f3d9a7 - <orblogin::generated_code::slint_generatedLoginWindow::LoginWindow as i_slint_core::api::ComponentHandle>::run::h3cb563cffc5831b2
                               at /run/media/user/Adat/Projektek/Programming/orbutils/target/debug/build/orblogin-13fb8bbe9a0175ca/out/login_window.rs:3547:14
  45:     0x55f2b0f24f87 - orblogin::main::h5154e8e10b69b2b9
                               at /run/media/user/Adat/Projektek/Programming/orbutils/orblogin/src/main.rs:393:5
  46:     0x55f2b0f4601b - core::ops::function::FnOnce::call_once::h294b0eecc9dc03f1
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/ops/function.rs:250:5
  47:     0x55f2b0f288ce - std::sys_common::backtrace::__rust_begin_short_backtrace::hc96d2b2aeb79e684
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/sys_common/backtrace.rs:134:18
  48:     0x55f2b0f51931 - std::rt::lang_start::{{closure}}::hb5a4e6921be4b7ee
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/rt.rs:166:18
  49:     0x55f2b15af0a5 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h0fc4f6f8926d966b
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/ops/function.rs:284:13
  50:     0x55f2b15af0a5 - std::panicking::try::do_call::h71700b51bf280613
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panicking.rs:485:40
  51:     0x55f2b15af0a5 - std::panicking::try::h933b0ae7432cb23d
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panicking.rs:449:19
  52:     0x55f2b15af0a5 - std::panic::catch_unwind::h6bfc5d499ac75051
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panic.rs:140:14
  53:     0x55f2b15af0a5 - std::rt::lang_start_internal::{{closure}}::h6cff4dbb328c88a2
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/rt.rs:148:48
  54:     0x55f2b15af0a5 - std::panicking::try::do_call::h58e49ed3a0c7a030
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panicking.rs:485:40
  55:     0x55f2b15af0a5 - std::panicking::try::h8ff41684788e76af
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panicking.rs:449:19
  56:     0x55f2b15af0a5 - std::panic::catch_unwind::ha7bde1d13c811be4
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panic.rs:140:14
  57:     0x55f2b15af0a5 - std::rt::lang_start_internal::hdfc7057913a07cfe
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/rt.rs:148:20
  58:     0x55f2b0f5190a - std::rt::lang_start::hebac4ecb64b3b9cb
                               at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/rt.rs:165:17
  59:     0x55f2b0f2505e - main
  60:     0x7f003b13e790 - <unknown>
  61:     0x7f003b13e84a - __libc_start_main
  62:     0x55f2b0f21c55 - _start
  63:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.

**Comment by ogoffart** [comment]
You should run `cargo update` and it will automatically update dependencies.

**Comment by kivimango** [comment]
Thank you.
