### ISSUE TITLE
TabWidget example not working

### ISSUE THREAD

**Issue by xgroleau** [slint-ui/slint#2683]
It seems the `TabWidget` [example](https://slint-ui.com/releases/1.0.2/docs/slint/src/builtins/widgets.html#id30) on slint-pad is not working properly. Only the Tab Bar is displayed and the content of the tabs is not showing. An orange or pink  rectangle should show in the content of each tab.

Also it seems the documentation is not up to date when inspecting the properties, some properties like `tabbar-width` seems to be missing.

**Comment by ogoffart** [comment]
Thanks for reporting the bug!
The problem was that the TabWidget didn't expand correctly to the parent when not in a layout. This is now fixed.

> Also it seems the documentation is not up to date when inspecting the properties, some properties like tabbar-width seems to be missing.

`tabbar-width`  is an internal property that shouldn't be accessible to users.
