### ISSUE TITLE
Can't load image-url from disk / web URL

### ISSUE THREAD

**Issue by GaspardCulis** [slint-ui/slint#2697]
I have this code:
```slint
Image {
                source: GameAdapter.game_over ? @image-url("assets/img/restart.svg") : @image-url("https://raw.githubusercontent.com/GaspardCulis/slint-tetris/main/assets/img/play.svg");
                width: 100px;
                height: 100px;
}
```
([Here](https://github.com/GaspardCulis/slint-tetris/blob/4119a725004e6f277f1b21b9728bbe2b802b6fa9/ui/appwindow.slint#L81) Is the repo)

First for the web URL, It's valid, but I get the error:
`Cannot find image file https://raw.githubusercontent.com/GaspardCulis/slint-tetris/main/assets/img/play.svg"])`
Seems like it thinks its a file.

Then for the disk saved image:
```bash
error: couldn't read /home/gaspard/Programmation/rust/tetris-slint/target/debug/build/tetris-slint-de46ebbe9a62993d/out/assets/img/play.svg: No such file or directory (os error 2)
    --> /home/gaspard/Programmation/rust/tetris-slint/target/debug/build/tetris-slint-de46ebbe9a62993d/out/appwindow.rs:5642:58
     |
5642 |      static SLINT_EMBEDDED_RESOURCE_0 : & 'static [u8] = :: core :: include_bytes ! ("assets/img/restart.svg") ;
     |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: this error originates in the macro `::core::include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)
```
So Slint doesn't go to the right spot, it finds the file relative to the target's out directory. (but the Slint preview works)
So I tried this:
```css
@image-url("../../../assets/img/restart.svg")
```
This time the error comes from somewhere else:
```bash
error: failed to run custom build command for `tetris-slint v0.1.0 (/home/gaspard/Programmation/rust/tetris-slint)`

  error: Cannot find image file ../../../assets/img/restart.svg
```

Putting absolute file paths works, but it's not convenient

**Comment by tronical** [comment]
Note that https urls only work in Slintpad. For wasm and desktop builds, relative urls should work (and for wasm builds the images will be embedded so that they don't need to be deployed separately)

**Comment by tronical** [comment]
In other words: Always use relative paths and it should work everywhere.

In the future we might support loading images from the network also in regular builds.

**Comment by ogoffart** [comment]
It should be releative to the .slint file.  So I guess `@image-url("../assets/img/restart.svg")`  should be the right path.
It is strange that you get an error in include_bytes  though, the compiler should always try to resolve the absolute path.

**Comment by GaspardCulis** [comment]
> It should be releative to the .slint file. So I guess `@image-url("../assets/img/restart.svg")` should be the right path. It is strange that you get an error in include_bytes though, the compiler should always try to resolve the absolute path.

Yes makes sense, works now!  Web demo updated if you guys want to take a look, just minor changes

**Comment by tronical** [comment]
Lovely idea to add a start button. If you’re looking for more ideas: touch/mouse based controls. For example, click in the left lower quadran to move left, upper half to rotate, etc
