### ISSUE TITLE
Skia renderer panics when UAC shows.

### ISSUE THREAD

**Issue by Berrysoft** [slint-ui/slint#2707]
The skia renderer panics when a UAC dialog shows.

```
thread 'main' panicked at 'Error presenting d3d swap chain: 87a0001', C:\Users\Straw\.cargo\registry\src\github.com-1ecc6299db9ec823\i-slint-renderer-skia-1.0.2\d3d_surface.rs:168:13
```

I don't know why, maybe it should just fail there when UAC shows:)

**Comment by tronical** [comment]
The error code is `DXGI_STATUS_OCCLUDED`, which means we should try again later and ignore this, indeed.

**Comment by tronical** [comment]
Fixed in https://github.com/slint-ui/slint/commit/5d641a17f6628d83a4057551bbb1ece64582758a
