### ISSUE TITLE
VSC LSP crashed

### ISSUE THREAD

**Issue by Adancurusul** [slint-ui/slint#2709]
LSP crashes in multiple ways in VSC
Partial error reporting:

> 
> thread '<unnamed>' panicked at 'already borrowed: BorrowMutError', tools\lsp\server_loop.rs:379:54
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> [Info  - 8:14:28 AM] Connection to server got closed. Server will restart.
> The Slint Language Server crashed. This is a bug.
> Please open an issue on https://github.com/slint-ui/slint/issues
> [Error - 8:14:28 AM] Request textDocument/colorPresentation failed.
> Error: Connection got disposed.
![T8YS $Y$4IS)OK7JTZ$VFXR](https://github.com/slint-ui/slint/assets/54146249/632767ab-b58b-40c0-9bcf-b95e9b28264d)

![DD6ACF7CDACDC3120860159D2D397318](https://github.com/slint-ui/slint/assets/54146249/a2e3615a-758e-4c4f-bf90-ea57fce767e2)

There are many more crashes that I forgot to record。
Almost every time a .slint file is opened, an error is reported
Sometimes it crashes suddenly while using

**Comment by ogoffart** [comment]
I actually have been seeing this panic before. It usually happen when editing the import. I suspect this happens when the client is fetching the property while the server is awaiting to open files. We should keep a lock on the cache just like in the wasm version also for the non-wasm

**Comment by Adancurusul** [comment]
邮件已收到，谢谢

**Comment by ogoffart** [comment]
This should now be fixed by #2733
Could you try with the nightly extension tomorrow and report a problem if this is still not fixed?
Thanks for reporting the bug.
