### ISSUE TITLE
The compiler load files relative to Workdir if they are not found relative to the the file basedir

### ISSUE THREAD

**Issue by Adancurusul** [slint-ui/slint#2719]
When the compiler can find an import file relative to the include path or the current file, it fallback to a relative path relative to the workdir. (which usually happen to often be the manifest dir)

This is a problem because then the siles are loaded twice with different non cannonical path (absolute and relative) and cause duplicated global and the like.

Example, if  you have a file ui/page.slint  that import a "ui/theme.slint",  it will work despite one should really have written "theme.slint"

# Original description

The problem of not showing up when rendering as an image using the Plotters library.
A replication was done here:
PlotArea is a Plotters drawing displayed to Image similar to https://github.com/slint-ui/slint/blob/master/examples/plotter/plotter.slint
![SO3FL`UDH)6BKFL1JZ9~Z~W](https://github.com/slint-ui/slint/assets/54146249/198457a7-005c-4c78-b501-710064a2ad9c)

I call it in another Slint file in two ways （
![4Q%HQ8VZO8JX7S7BNZ_7Y%1](https://github.com/slint-ui/slint/assets/54146249/3e894af5-ac72-4129-81ea-56878095c177)
where CT_tablePage is implemented as follows
![6 GLR4`V@OH` U 10 YVR`S](https://github.com/slint-ui/slint/assets/54146249/7dbc6e59-92fc-4388-a185-732f7cdfc9e7)
The actual run results in only one image being rendered.The area below is successfully defined as a PlotArea because the mouse hover will change, but no image is displayed
![6PLA2OZX{GYC4D)TNE_R9$U](https://github.com/slint-ui/slint/assets/54146249/a3d88d10-ba56-4f7b-a624-5c7c43336245)

My solution is to define a previewPlot property for CT_tablePage and bind the property to Image

![Y`DN2$3R2(7Q5FV 023WBPI](https://github.com/slint-ui/slint/assets/54146249/e9524ba1-a55b-4541-b7f4-3ae064e0c52c)
![570D}${W2756MQH6FI49Q}R](https://github.com/slint-ui/slint/assets/54146249/291c294e-796f-492f-a809-69f604754b11)

Finally, I succeeded in displaying
![IG{GVUOTVBHK$3GNRT6SLRP](https://github.com/slint-ui/slint/assets/54146249/8363e40c-9573-4e90-a682-ffdea8c6ccad)

I was thinking that the initial failure to display was due to some feature I had overlooked?

**Comment by ogoffart** [comment]
Would you be able to send us some code that we can use to reproduce this?

**Comment by Adancurusul** [comment]
> Would you be able to send us some code that we can use to reproduce this?

I'm very sorry for not replying in time. I will send you the reproduced code shortly. (After my recent busy schedule is over)

**Comment by Adancurusul** [comment]
> Hi!
> 
> > The actual run results in only one image being rendered
> 
> Do you mean that `render_plot` was only called one single time, and not when you moved the mouse cursor?


I found that the problem is more like when I call ``export global CT_mainPageAdapter`` in another file, for example ``CT_main_page.slint``, only the initialized data is called. 

For example, when I use
 ```
export component CT_tablePage inherits Page {
    connectState : CT_mainPageAdapter.currentConnect;
``` 
such a call. will only copy the initialization data of ```CT_mainPageAdapter```. When ```CT_mainPageAdapter``` is modified in slint or by rust ``CT_table_page.slint`` the data called in the page will not be modified at the same time.


My final solution to the above situation was also strange, I utilized another file ```MainAdapter.slint``` which implements import and export 
```
import {CT_mainPageAdapter} from "ui/CT_main_page.slint";
export {CT_mainPageAdapter} 
```
Where the ``CT_mainPageAdapter`` is needed it works again by calling ``MainAdapter.slint``

```Plotters ``` not displaying properly is similar, ```<image>``` is defined here 
```
export global PlotterPageAdapter {
    in-out property <image> plot: render_plot(0, 0);
```
Causing another file to be unusable
What's even stranger is that some times it works again.

**Comment by Adancurusul** [comment]
> Hi!
> 
> > The actual run results in only one image being rendered
> 
> Do you mean that `render_plot` was only called one single time, and not when you moved the mouse cursor?

I found that the problem is more like when I call ``export global CT_mainPageAdapter`` in another file, for example ``CT_main_page.slint``, only the initialized data is called. 

For example, when I use
 ```
export component CT_tablePage inherits Page {
    connectState : CT_mainPageAdapter.currentConnect;
``` 
such a call. will only copy the initialization data of ```CT_mainPageAdapter```. When ```CT_mainPageAdapter``` is modified in slint or by rust ``CT_table_page.slint`` the data called in the page will not be modified at the same time.


My final solution to the above situation was also strange, I utilized another file ```MainAdapter.slint``` which implements import and export 
```
import {CT_mainPageAdapter} from "ui/CT_main_page.slint";
export {CT_mainPageAdapter} 
```
Where the ``CT_mainPageAdapter`` is needed it works again by calling ``MainAdapter.slint``

```Plotters ``` not displaying properly is similar, ```<image>``` is defined here 
```
export global PlotterPageAdapter {
    in-out property <image> plot: render_plot(0, 0);
```
Causing another file to be unusable
What's even stranger is that some times it works again.

**Comment by ogoffart** [comment]
What your describing sounds like a bug, but it is hard to understand exactly with these incomplete snippets.

Would you have something i can run to try it out?  
Would you be comfortable giving access to your repository?

**Comment by Adancurusul** [comment]
> What your describing sounds like a bug, but it is hard to understand exactly with these incomplete snippets.
> 
> Would you have something i can run to try it out? Would you be comfortable giving access to your repository?

In the project demo I got around these issues in the way I described above.
I'll try to reproduce the bug later and make the reproduced demo public.

**Comment by Adancurusul** [comment]
https://github.com/Adancurusul/slint_bug  Here's a demo of the problem I'm having and a temporary solution to it. Hope it helps

**Comment by ogoffart** [comment]
Thanks for making this repository.
Despite your very nice explanation and screenshot, i still don't understand the problem. 

I ran the example and I do see the graph. This is waht I get.

![image](https://github.com/slint-ui/slint/assets/959326/e148cd27-d509-4fa0-a762-4389fe19bc7c)

And even if i change stuff to be 
```
import {CT_mainPageAdapter} from "CT_main_page.slint";
```

I still see the plot.

How exactly should I reproduce the problem?

**Comment by Adancurusul** [comment]
> Thanks for making this repository. Despite your very nice explanation and screenshot, i still don't understand the problem.
> 
> I ran the example and I do see the graph. This is waht I get.
> 
> ![image](https://user-images.githubusercontent.com/959326/255143349-e148cd27-d509-4fa0-a762-4389fe19bc7c.png)
> 
> And even if i change stuff to be
> 
> ```
> import {CT_mainPageAdapter} from "CT_main_page.slint";
> ```
> 
> I still see the plot.
> 
> How exactly should I reproduce the problem?

![image](https://github.com/slint-ui/slint/assets/54146249/31688dc1-5b46-4776-974e-17930cbe673d)
Yes, the latest one is the one I fixed the bugs on.
The```  update bugA ```is the version with the bugs.
![image](https://github.com/slint-ui/slint/assets/54146249/1b809d60-d67c-4cbb-9484-946339cd3fb8)

Some modifications on top of ``update bugA`` to get a version without problems

**Comment by ogoffart** [comment]
Ah, yes, i can repduce it by cloning that repository.  Thanks a lot!  I'll see what i can do.

**Comment by ogoffart** [comment]
The problem is that you use 
```js
import {/*...*/} from "ui/plotter.slint";
```

from a file which is already in the  `ui` folder.

The correct way is to do like so:

```
import {/*...*/} from "plotter.slint";
```

relative to the path itself.


Due to a bug in the compiler, the import worked, but loaded the file twice in the project, resulting in duplicated globals and component.


What I'll try to do is to detect that and make sure that the same canonical path is still use.
I'll also make it a compiler warning.
(I can't make it an error yet as it could break existing codebase)

Thanks for reporting the bug!

**Comment by Adancurusul** [comment]
> The problem is that you use
> 
> ```js
> import {/*...*/} from "ui/plotter.slint";
> ```
> 
> from a file which is already in the `ui` folder.
> 
> The correct way is to do like so:
> 
> ```
> import {/*...*/} from "plotter.slint";
> ```
> 
> relative to the path itself.
> 
> Due to a bug in the compiler, the import worked, but loaded the file twice in the project, resulting in duplicated globals and component.
> 
> What I'll try to do is to detect that and make sure that the same canonical path is still use. I'll also make it a compiler warning. (I can't make it an error yet as it could break existing codebase)
> 
> Thanks for reporting the bug!

It appears that this issue was a misuse on my part. Thanks for helping me out with this!
