### ISSUE TITLE
Block click handling for overlapped elements

### ISSUE THREAD

**Issue by Nan1t** [slint-ui/slint#272]
Hi. I noticed that TouchArea handles click even if it overlapped by other elements. This can be problem to make modals, for example. Tested on GL backend.

**Comment by ogoffart** [comment]
Right now, only TouchArea blocks the click most other elements are "transparent" to click.  So if you want to do a modal, you need to have big TouchArea covering the screen or something like that.

Do I understand correctly that you think all elements should block clicks?

**Comment by Nan1t** [comment]
> Do I understand correctly that you think all elements should block clicks?

May be no. I think elements like layouts should be transparent for mouse events. I means stylable elements like Rectangle, Image, etc.
Anyway thanks for idea with covering it with TouchArea. I would not have guessed this)

**Comment by ogoffart** [comment]
This is interesting, this means we should document for each element whether they block the click or not. For example, by default, a Rectangle is transparent. But does a transparent rectangle also block clicks.
Se we would have: 

 - Block clicks: TouchArea (even if disabled?), Rectangle, Image (What if clicked on padding of a centered Image?), Text (even when not clicking on the text?), Flickable, the widgets.
 - Let click through: all the layouts, FocusScope, some internal elements.

Maybe then we need a name for an element which is like a transparent rectangle that let click through like an `Item`
Alternatively, we could have a bool property on each element: `intercept_input` or something like that whose default would depends on the element.

Or we could say that all element block the click, no matter which ones.

**Comment by Nan1t** [comment]
In any case, i think you already have an architecture planned for this. If not, i think the easiest way is to follow the design of most GUI tools, where the blocks on top always overlap mouse/touch events, unless otherwise indicated. This will make using your tool more intuitive. Unfortunately, i'm just starting to learn Rust, so i can’t make a good PR for this yet.

**Comment by ogoffart** [comment]
We will keep the behavior as it is now and only elements that intercepts event will block them.   Although we might want to allow each element to have a handler: #145
