### ISSUE TITLE
slint reported an error running on tina

### ISSUE THREAD

**Issue by kevin406972552** [slint-ui/slint#2753]
![image](https://github.com/slint-ui/slint/assets/25196508/d6410d3b-f842-4d9e-8d7f-3cece11f36c3)

Cross compilation is error-free

![image](https://github.com/slint-ui/slint/assets/25196508/2f85d386-2bc0-42a1-9e0a-611b5ba9b61b)

Solve the problem of dynamic library

![image](https://github.com/slint-ui/slint/assets/25196508/845f87ea-76c9-4bcc-bdde-afc859f15a97)

The futex facility returned an unexpected error code.Aborted

**Comment by tronical** [comment]
Interesting, I've never seen this error before. The discussion at https://github.com/rust-lang/rust/issues/93228 and https://bugs.gentoo.org/799878#c8 suggest that this message originates from the C library itself.

https://github.com/electron/electron/issues/24211 on the other hand suggests that you need to set DISPLAY , to reach the x server.

Are you running inside WSL by chance?

**Comment by kevin406972552** [comment]
This runs on embedded Linux devices

**Comment by tronical** [comment]
As far as searching on the internet takes me, this appears to be some kind of incompatibility between glibc and the kernel. I'm not sure there's anything we can do on the Slint side. Could you try a different glibc version or perhaps switch to musl?

**Comment by kevin406972552** [comment]
After switching to musl:

![image](https://github.com/slint-ui/slint/assets/25196508/1a0f6b8f-f627-475d-8373-b95478f50554)

**Comment by tronical** [comment]
Ouch, we do indeed require dlopen.  So musl is not an option:(.

**Comment by kevin406972552** [comment]
Now the problem seems to be yeslogic-fontconfig-sys

**Comment by tronical** [comment]
Yes. And after that glutin, Wayland, or xcb: we do call dlopen() for a few system libraries. That means we can’t support musl.

I think you may need to get in touch with your linux distro to find out why glibc doesn’t support futexes. Maybe it’s a kernel incompatibility?

**Comment by kevin406972552** [comment]
Would you like to know whether slint supports armv7-unknown-linux-gnueabi**hf** or armv7-unknown-linux-gnueabi

**Comment by kevin406972552** [comment]
Would you like to know whether slint supports armv7-unknown-linux-gnueabi**hf** or armv7-unknown-linux-gnueabi

**Comment by kevin406972552** [comment]
I wish slint would support framebuffer

**Comment by ogoffart** [comment]
> I wish slint would support framebuffer

That's tracked in https://github.com/slint-ui/slint/issues/423

Are there still any problem tracked by this issue? Has the original problem been solved?
