### ISSUE TITLE
Fullscreen mode howto

### ISSUE THREAD

**Issue by frehberg** [slint-ui/slint#2775]
Please document how to start an application on Linux in fullscreen mode, for example on a RasPi in kiosk mode. Or how can I define on command line the geometry of the main window?

It is possible to set in .slint file a static windows size, and disable the frame around the window. For example the following will be fullscreen on 800x600 screen But it would not be full screen on bigger screen.

```

export component AppWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;
    no-frame: true;
    
    in-out property<int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}

```

**Comment by frehberg** [comment]
I tried, but the slint rust template does not show up in full screen, maybe additional properties are required  to declare Window as  "expand"?
```
SLINT_FULLSCREEN=1 ./target/debug/slint-test
```

**Comment by tronical** [comment]
Argh, there's a bug - this regressed :-(. I'll look into it right away, that should be easy to fix.

**Comment by tronical** [comment]
@frehberg I landed #2776 . I tried against Weston and wayland. It worked for me in the 1.0.2 release, but it was broken in the master branch. Which version were you using?

**Comment by frehberg** [comment]
Hi, I used the slint-rust-template, defining depencency to "1.0"
https://github.com/slint-ui/slint-rust-template/blob/main/Cargo.toml

AFAICS, checking the cargo-build-env, the Cargo.lock did pin to version 1.0.2 

```
[[package]]
name = "i-slint-backend-winit"
version = "1.0.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "4d2d4c3bbf2c9f255b715ad38f84e0296638b22338cce8349b954baf85bf674f"
dependencies = [
 "cfg-if",
 "cfg_aliases",
 "cocoa",
 "const-field-offset",
 "copypasta",
 "derive_more",
 "glutin",
 "glutin-winit",
 "i-slint-common",
 "i-slint-core",
 "i-slint-core-macros",
 "i-slint-renderer-femtovg",
 "i-slint-renderer-skia",
```

**Comment by tronical** [comment]
Yep, ok! Then you need to switch to Slint git until we release a new version:

```toml
[dependencies]
slint = { version = "1.0", git = "https://github.com/slint-ui/slint", branch = "master" }

[build-dependencies]
slint-build = { version = "1.0", git = "https://github.com/slint-ui/slint", branch = "master" }
```

**Comment by JanDiederich** [comment]
When will we get the `show_fullscreen()` function?

**Comment by tronical** [comment]
In my opinion it makes sense to document the `SLINT_FULLSCREEN` environment variable. But we could also choose to say that it's internal (not public), then this could be closed.

**Comment by JanDiederich** [comment]
My current workaround is:
```rust
if options.is_fullscreen {
    std::env::set_var("SLINT_FULLSCREEN", "1");
}

let window = MainWindow::new().unwrap();
```

But this is no real solution, since I can't let the user decide to switch to fullscreen at will, _after_ the program started, the application always has to **_re_**-start. This is especially annoying when you know that enough frameworks have this exact call built in, like: https://doc.qt.io/qt-6/qwindow.html#showFullScreen.

**Comment by tronical** [comment]
The `SLINT_FULLSCREEN` variable is now documented for the [winit backend](https://slint.dev/releases/1.2.0/docs/slint/src/advanced/backend_winit] and the [Qt backend](https://slint.dev/releases/1.2.0/docs/slint/src/advanced/backend_qt).

**Comment by tronical** [comment]
As mentioned in https://github.com/slint-ui/slint/issues/2775#issuecomment-1680342020 the new API is tracked separately and this is documented now.
