### ISSUE TITLE
Inplace VS Code Slint Preview steals focus

### ISSUE THREAD

**Issue by FloVanGH** [slint-ui/slint#2869]
In the current nightly version if you use `Slint Preview` in VSCode in a tab and have a single focusable item within and you enter text in a text editor tab then the focus moves inside the preview tab.

**Comment by tronical** [comment]
I can't reproduce this on Linux or on macOS - based on previous reports I assume that what you're seeing is with the inline preview? Symptomatically it seems similar to #2414 , which I can reproduce but that's not using the inline preview. Can you confirm which one it is? (or perhaps record a little clip, if it's not #2414)

**Comment by FloVanGH** [comment]
I cannot reproduce it anymore with the current nightly.

**Comment by ogoffart** [comment]
Closing then.
