### ISSUE TITLE
I want to use asynchronous methods in on_clicked

### ISSUE THREAD

**Issue by 69bin** [slint-ui/slint#2876]
```rust
let window_weak_2 = main_window.as_weak();
main_window.global::<WatermarkGlobal>().on_download(move || {
    let _ = update_image(window_weak_2.clone());
});
``` 
I want to upload_ Image is an async method,I don't understand how to implement this here

**Comment by ogoffart** [comment]
Thanks for submitting an issue.
This has been asked before in #747
There is some work in progress to solves this in https://github.com/slint-ui/slint/pull/2845

Closing as duplicated of #747
