### ISSUE TITLE
@tr

### ISSUE THREAD

**Issue by estkae** [slint-ui/slint#2889]
I try to work with VSCode extension on the sample gallery but it does not work. the reasen ist @TR
            Button {
                text: @tr("Primary Button with Icon");
                icon: @image-url("../../thumbsup.png");
                enabled: GallerySettings.widgets-enabled;
                primary: true;
            }
So i go to your Homepage and see a verry big change in the button componet: The @tr is disappeard.
 Button {
                text: "Button with Icon";
                icon: @image-url("../../thumbsup.png");
                enabled: !GallerySettings.widgets-disabled;
            }
Where is the correct dokumentation of this Issue.

**Comment by ogoffart** [comment]
@tr is a new feature in the master branch too be released with Slint 1.1
The documentation is there: https://slint-ui.com/snapshots/master/docs/slint/src/concepts/translations
It is not working with the released version of the extension, but it is working with the nightly version.
