### ISSUE TITLE
Program crashes when GPU rendering cannot be initialized

### ISSUE THREAD

**Issue by tp971** [slint-ui/slint#2903]
I got this issue in a Windows 10 VM without GPU acceleration: I compiled a slint program with the `renderer-winit-software` feature enabled and when trying to start the program, I got:

```
thread 'main' panicked at 'called glCreateShader but it was not loaded.', C:\Users\Yannick\.cargo\registry\src\index.crates.io-6f17d22bba15001f\glow-0.12.2\src\gl46.rs:4571:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It works fine when setting the environment variable `SLINT_BACKEND` to `winit-software`, however I'd expect it to fallback to software rendering automatically.

**Comment by tronical** [comment]
Agreed. Thanks for filing this.
