### ISSUE TITLE
TouchArea: clicked is invoked when mouse was pressed outside the area

### ISSUE THREAD

**Issue by tp971** [slint-ui/slint#2918]
I expected `clicked` to be invoked when the mouse is pressed and released inside the TouchArea, but currently the mouse only needs to be inside the area when it is released. This affects all builtin widgets that use a TouchArea, e.g. buttons: when I press and hold the mouse on the window and release it on a button, the button is pressed, which is not something I would expect from any UI framework.

**Comment by ogoffart** [comment]
Thanks for reporting.  Attempted fix in #2940
