### ISSUE TITLE
Button stays "highlighted" when covered by another TouchArea

### ISSUE THREAD

**Issue by tp971** [slint-ui/slint#2919]
This came up while trying to implement a "modal dialog" using a transparent rectangle with a TouchArea covering the window: If a button is pressed and the `clicked` callback makes TouchArea visible that covers the point where the button was clicked, the button stays in a "highlighted" state. Here is a simplified example:

```rs
fn main() {
    MainWindow::new().unwrap().run().unwrap();
}

slint::slint! {
    import { Button } from "std-widgets.slint";

    export component MainWindow inherits Window {
        width: 200px;
        height: 200px;

        Button {
            x: 10px;
            y: 10px;
            text: "Open";
            clicked => { r.visible = true; }
        }

        r := Rectangle {
            width: parent.width;
            height: parent.height;
            visible: false;
            TouchArea {}
            Button {
                x: 100px;
                y: 100px;
                text: "Close";
                clicked => { r.visible = false; }
            }
        }
    }
}
```

It is pretty noticable in the `fluent-dark` style:

Before pressing the button:
![before](https://github.com/slint-ui/slint/assets/29186351/21894a47-fb5c-45f7-babd-fa9e3e1ca10e)

After pressing the button:
![after](https://github.com/slint-ui/slint/assets/29186351/884382b1-a7aa-45da-84bf-a9cee3733d33)

**Comment by ogoffart** [comment]
Thanks for the detailed report.

Could reproduce with 1.0.2, but this is fixed in master. (presumably fixed by https://github.com/slint-ui/slint/pull/2745 )
