### ISSUE TITLE
Linear gradient not applied when using global

### ISSUE THREAD

**Issue by kkettinger** [slint-ui/slint#2921]
When using a global for colors, the linear-gradient is not applied, only the first color is used.

This is working:
```rust
slint::slint!{
    export component App inherits Window {
        width: 600px;
        height: 400px;
        background: @linear-gradient(0deg, #ff00ff 0%, #00ff00 100%);
    }
}

fn main() {
    App::new().unwrap().run().unwrap();
}
```
![grafik](https://github.com/slint-ui/slint/assets/83078716/a95ed63e-d371-4951-bf71-3af6e5d0817e)

This not:
```rust
slint::slint!{

    global Palette {
        out property<color> background: @linear-gradient(0deg, #ff00ff 0%, #00ff00 100%);
    }
    export component App inherits Window {
        width: 600px;
        height: 400px;
        background: Palette.background;
    }
}

fn main() {
    App::new().unwrap().run().unwrap();
}
```
![grafik](https://github.com/slint-ui/slint/assets/83078716/5e6b1e70-8d6e-42e3-a3ac-0c5383cf6b83)

Tested against latest slint version (653b63a35e227c9f3caff33f62a4388bb8755bac).

**Comment by tronical** [comment]
The issue is that you're assigning a gradient `brush` to a `color` property, for which we take simply the first color of the gradient. If you change the property type to `brush` then it'll work:

```slint
slint::slint!{

    global Palette {
        out property<color> background: @linear-gradient(0deg, #ff00ff 0%, #00ff00 100%);
    }
    export component App inherits Window {
        width: 600px;
        height: 400px;
        background: Palette.background;
    }
}

fn main() {
    App::new().unwrap().run().unwrap();
}
```

I wonder if we should perhaps issue a warning in the compiler when doing this kind of direct literal assignment. @ogoffart what do you think?

**Comment by kkettinger** [comment]
Thank you!
