### ISSUE TITLE
Adapt docs front-page to new web design

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2922]
The docs landing page at

   http://slint.dev/snapshots/master/docs

needs to be adapted to the new website design.

In the repo it is located at docs/site/index.html

**Comment by tronical** [comment]
@hunger @aurindam Could one of you make those changes, or alternatively briefly explain what needs to be done and then I can try to do it?

**Comment by ogoffart** [comment]
Also the demo's index.html could get a new stylesheet.
