### ISSUE TITLE
about loyalty-free license: is the 'community mode' allowed to be used to develop proprietary app in a company?

### ISSUE THREAD

**Issue by jrdeng** [slint-ui/slint#2924]
I'm sure it is allowed for individual.

but not very clear about for a company.
can the 'community mode' be used in a company to develop proprietary app?

(what made me have this question is because: the community version of visual studio is not allowed.)

**Comment by tronical** [comment]
The [royalty-free desktop and web application license](https://github.com/slint-ui/slint/blob/master/LICENSES/LicenseRef-Slint-Royalty-free-1.0.md) makes no distinction between an individual developer or a company - it can be used by both as long as the conditions of the license are met.
