### ISSUE TITLE
Cannot input characters that depend on Alt Gr key on Windows

### ISSUE THREAD

**Issue by fnschmidt** [slint-ui/slint#2933]
Slint 1.0.2
Windows is affected, macOS is not. Linux is untested.

On the US layout, the Alt Gr key is being ignored and the other key generates its default character.
On the german layout, any Alt Gr combination generates no character.
On certain layouts like the german one, many important characters are bound to Alt Gr, like the '@' symbol.

Steps to reproduce: create a LineEdit and try to input Alt Gr combinations.

**Comment by greybaron** [comment]
I did not have Qt installed on the Windows machine, so I believe winit. Is there a way to check at compile/runtime?

**Comment by greybaron** [comment]
The issue is present on the Qt backend as well.
