### ISSUE TITLE
VC++2022: fail to build the project since linker refers to slint_cpp.dll instead of slint_cpp.dll.lib

### ISSUE THREAD

**Issue by teminian** [slint-ui/slint#2982]
Hello Slint team, I encountered a bug in Slint 1.0.2 which prevents me from building my pet project, which was built on Slint 0.3. The details are as follows:

- Architecture: Windows / 64bit / VC++ 2022 / using FemtoVG only (Qt is disabled)
- I built Slint as a prebuilt library and complete package is installed in `C:\Components\slint-1.0.2\installed`
- The error is as follows: `C:\Components\slint-1.0.2\installed\lib\slint_cpp.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x2C8`

During the investigation, I found this line in `installed/lib/cmake/Slint/SlintConfig.cmake`

```
set_target_properties(slint-cpp-shared PROPERTIES IMPORTED_NO_SONAME;1;IMPORTED_LOCATION;${_IMPORT_PREFIX}/lib/slint_cpp.dll;IMPORTED_IMPLIB;${_IMPORT_PREFIX}/lib/slint_cpp.dll.lib)
```

And if I change this line like following it works:
```
set_target_properties(slint-cpp-shared PROPERTIES IMPORTED_NO_SONAME;1;IMPORTED_LOCATION;${_IMPORT_PREFIX}/lib/slint_cpp.dll.lib;IMPORTED_IMPLIB;${_IMPORT_PREFIX}/lib/slint_cpp.dll.lib)
```

Since I'm not good at cmake I couldn't make a patch but still I think it's simple yet quite annoying for any Windows users who want to maintain custom Slint build. Any ideas on how to prevent this?

P.S:
Slint examples were built successfully without any linker complaints

**Comment by tronical** [comment]
> I built Slint as a prebuilt library and complete package is installed in

I tried the binary package from https://github.com/slint-ui/slint/releases/tag/v1.0.2 and the config file looks correct.

`IMPORTED_LOCATION` should point to the dll, and `IMPORTED_IMPLIB` should point to the import library.

What command are you using to build your pet project?

**Comment by teminian** [comment]
@hunger 
https://github.com/slint-ui/slint/issues/2982#issuecomment-1607258201
I built my custom one from the source code of 1.0.2
https://github.com/slint-ui/slint/issues/2982#issuecomment-1607336687
Let me try with trunk and see what happens from my side.

@tronical I have no idea but `set_target_properties()` from `SlintConfig.cmake` in official binary is far longer than my personal build. Maybe that's because I asked for Release build?

**Comment by teminian** [comment]
OK..... It looks like VC++ 2022 is to blame. I updated the compiler, clean-reconfigured cmake project, and it worked.
Sorry for disturbing you! Let me close the ticket.

**Comment by ogoffart** [comment]
Is that related to https://github.com/slint-ui/slint/issues/414 ?
