### ISSUE TITLE
Add support for importing Y-flipped OpenGL Textures

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#2986]
At the moment the API for importing an OpenGL texture into a `slint::Image` assumes that the origin of the texture is at the top-left. This is consistent with the coordinate system used in Slint, Vulkan, and generally what most people in computer graphics expect. However this may be inconvenient sometimes and it would be useful to have API that supports populating texture content with the origin being at the bottom-left (OpenGL default), by having a flag that tells slint to draw the texture y-flipped.

**Comment by bog-dan-ro** [comment]
Kindly ping :)

**Comment by tronical** [comment]
Yes, I'm aware of this issue and that it is not very difficult to implement. Personal time off (long needed vacation) and company all-hands are taking precedence right now over implementing this.

**Comment by tronical** [comment]
In terms of implementation, in the event that somebody wants to give it a try: The actual implementation in FemtoVG and Skia is easy. For the former there's a FLIP_Y image flag, and for the latter there's another origin enum variant that should take care of this. What's more work is to implement this perhaps using a texture builder pattern in Rust and C++, and to document it thoroughly.

**Comment by bog-dan-ro** [comment]
@tronical works great, thanks !

**Comment by tronical** [comment]
Excellent. Thanks for the quick check.
