### ISSUE TITLE
在linux or windows平台里，怎么实现选择文件或文件的弹出窗口功能

### ISSUE THREAD

**Issue by joyoes** [slint-ui/slint#3002]
在linux or windows平台里，怎么实现选择文件(choose file)或文件夹(dir)的弹出窗口(window)功能?
How do achieve choose file or dir of window in linux or windows(10)?

**Comment by ogoffart** [comment]
In the future, please use the dicussion tab (https://github.com/slint-ui/slint/discussions) for questions, the issues are for tracking bug. Also please try to write in English. Thanks

Assuming you are using rust, you can use the [`rfd` crate](https://docs.rs/rfd)
This is for example used by cargo-ui in https://github.com/slint-ui/cargo-ui/blob/fecf8666416953ac4d491e31e0ee80ebe8b13046/src/cargo.rs#L689
