### ISSUE TITLE
get current DPI of a window

### ISSUE THREAD

**Issue by bog-dan-ro** [slint-ui/slint#3003]
Right now there is no API to get the current DPI used by a `slint::Window`.

**Comment by tronical** [comment]
We generally don't expose the DPI, but we do track the device pixel ratio (we call it scale factor). This is exposed in Rust, but not in C++. I've made a PR for the C++ side.

**Comment by bog-dan-ro** [comment]
It will be nice if you'll expose also the DPI values .

**Comment by tronical** [comment]
Maybe we could have API to expose the physical dimension of the monitor (along with other monitor related information). I think with Qt that could be computed, but with winit we don't have access to that information.

Out of curiosity, what information do you need (horizontal or vertical dpi? logical or physical dpi?) and how would you use it?

**Comment by bog-dan-ro** [comment]
@tronical  Logical DPI is needed to render text using 3rdparty libs e.g. render a scene with some texts into a texture then use `Image::from_borrowed_gl_2d_rgba_texture` to display it ( after you'll fix #2986 :-p  ) .

I think Physical dimensions are also good to know, though right now I don't have a use-case for them.
