### ISSUE TITLE
Input method will be auto actived when enter TextEdit area

### ISSUE THREAD

**Issue by Decodetalkers** [slint-ui/slint#3007]
Seems it always active the first input method when enter the textedit area, without actived manually, this confused me a lot. it should not auto active input method

**Comment by ogoffart** [comment]
How should it be activated?

**Comment by Decodetalkers** [comment]
> How should it be activated?

If it is a new process, it should not active any input method, only if when we pressed shotcut key to active the input method, then the program will active and remember the choice , I think it is it, now when a slint program start, enter the text area, it will try to active the input method, I think it is a bug

**Comment by tronical** [comment]
On which operating do you see this behavior?

**Comment by Decodetalkers** [comment]
https://github.com/slint-ui/slint/assets/60290287/60452619-237d-43bc-ad33-ebb68891ac52

@tronical  when the focus is in text input area, the text input method is actived

**Comment by ogoffart** [comment]
Thank you for reporting the bug and providing an explanation. I appreciate your effort in bringing this issue to our attention. However, I'm not very familiar with input methods myself.

Our current implementation calls the winit function set_ime_allowed when the text edit area receives focus. (there: https://github.com/slint-ui/slint/blob/07f42afef3b73bac89adce34e6cf0d147525d596/internal/backends/winit/winitwindowadapter.rs#L619C22-L619C37 ) 
Do you think that's wrong?
Do we need to handle the shortcut ourselves, or if it's winit's responsibility or something else?

**Comment by Decodetalkers** [comment]
> Thank you for reporting the bug and providing an explanation. I appreciate your effort in bringing this issue to our attention. However, I'm not very familiar with input methods myself.
> 
> Our current implementation calls the winit function set_ime_allowed when the text edit area receives focus. (there: https://github.com/slint-ui/slint/blob/07f42afef3b73bac89adce34e6cf0d147525d596/internal/backends/winit/winitwindowadapter.rs#L619C22-L619C37 ) Do you think that's wrong? Do we need to handle the shortcut ourselves, or if it's winit's responsibility or something else?

oh. sorry, the impliment is good, it is mime.. I should set en to the first, sorry. there is no bug with slint
