### ISSUE TITLE
Possible Logical Position bug with Winit and Wayland

### ISSUE THREAD

**Issue by Vadoola** [slint-ui/slint#3032]
Platform Arch Linux
Language: Rust 1.70

I'm working on a program to learn Slint better. the program is using a frameless window and then creating the frame in Slint, this allows me to theme the title bar with the rest of the program.

While doing some testing on other aspects I discovered that I can't move the Window around using the Winit backend on Wayland. 

Using the Winit backend on X11 seems to work fine, and using the Qt backend on Wayland and X11 seems to work fine, using the Winit backend on Wayland however does not.

In my slint code I'm tracking on offset of when the mouse was clicked over the "title bar" and the mouse movements. In the Rust code I'm getting the logical position of the Window, and then setting the position using the mouse offset.

In my MVP I'm dumping the LogicalPosition to the terminal, when run with the Qt backend you can see the LogicalPosition updated, when run with the Winit backend it seems to be fixed at x = 0, y = 0.

This is the rust code in the call back to get the logical position:

```
let logical_pos = move_handle.window().position().to_logical(move_handle.window().scale_factor());
```

I've uploaded an MVP to github that can be seen at: https://github.com/Vadoola/brdles_winit_slint_test

and I'm attaching a screencast where I run the program with the Qt backend and the Winit backend. You can see with the Winit backend the window doesn't move around the Logical Position stays fixed at 0, 0.

[Borderless_window_issue.zip](https://github.com/slint-ui/slint/files/11935533/Borderless_window_issue.zip)

**Comment by ogoffart** [comment]
Unfortunately, this might not be possible.  The documentation documents it:

https://docs.rs/slint/latest/slint/struct.Window.html#method.set_position

> Note that on some windowing systems, such as Wayland, this functionality is not available.

The reason is that winit don't support it in `winit::Window::set_outer_position`

https://docs.rs/winit/latest/winit/window/struct.Window.html#method.set_outer_position

> **Wayland:** Unsupported

I don't know if it is a limitation of Winit, or a limitation iof the Wayland protocol

If you're using the internal i-slint-backend-winit crate directly,  maybe you can try something using https://docs.rs/winit/latest/winit/window/struct.Window.html#method.drag_window

**Comment by Vadoola** [comment]
I clearly overlooked that in the docs. Since I need to use the private api backend crate for minimizing and hiding the window anyway, the drag_window method could be an option, although it seems to have it's own caveats.

Since this confirms my suspicions that this is more of a winit issue, I'll go ahead and close this, as well as see if I can find out why set_outer_position isn't supported for Wayland.

Thank you for your help.

**Comment by Vadoola** [comment]
Leaving the below notes for future reference for anyone coming across this issue in the future.

As noted in the [Winit discussion thread ](https://github.com/rust-windowing/winit/discussions/2920); the reason set_outer_position is not supported under Wayland, is a Wayland "limitation" (there may be a valid reason this doesn't work in Wayland like security concerns, but I don't know).

In that discussion thread it was also suggested to use winit::drag_window.

So far in my testing this works well under all platforms.
If you look at the [2.0 Release tag](https://github.com/Vadoola/brdles_winit_slint_test/releases/tag/2.0) of my sample program, you can see a minimum working example of the same code using drag_window, that works under Windows, X11 and Wayland
