### ISSUE TITLE
Website: Breakpoints inline example looks broken on Windows/Chrome

### ISSUE THREAD

**Issue by anderslanglands** [slint-ui/slint#3035]
Looking through https://slint.dev/releases/1.1.0/docs/slint/src/recipes/recipes - the last recipe, "Breakpoints for Responsive User Interfaces" looks very broken for me on Windows 11 using latest Chrome:

![image](https://github.com/slint-ui/slint/assets/1935453/87c6d7a7-18ab-4a90-8681-012329b04cbd)

**Comment by ogoffart** [comment]
that example indeed doesn't play well with the preview, as there is no way to resize.

We should probably disable the preview for that example.  @FloVanGH , what do you think?

(we could also try to put a Splitter)

**Comment by FloVanGH** [comment]
Yes a splitter could help. I will check what I can do.

**Comment by ogoffart** [comment]
The splitter helps, but the preview is still way to big:

https://slint.dev/snapshots/master/docs/slint/src/recipes/recipes#breakpoints-for-responsive-user-interfaces

We need to reduce the size of the preview, or disable the auto-loading of the preview for this

Note @FloVanGH , if you use safary the preview might not load automatically, you can try other browser and see that it still looks like the screenshot above.
