### ISSUE TITLE
Wayland: Initial buffer rendered out of the window frame

### ISSUE THREAD

**Issue by jturcotte** [slint-ui/slint#3036]
I'm getting this weird issue after upgrading my application from 1.0.3 to 1.1.0, only for the first frame (it snaps back into the window after resizing):

![image](https://github.com/slint-ui/slint/assets/839935/d5ebdbf9-8b37-418d-8624-0809b1cd21a3)

This can reproduced with a simple scene with `slint-viewer --backend winit-femtovg test.slint`

```js
export component MainWindow inherits Window {
    title: "Test";
    background: red;
    width: 800px;
    height: 480px;
}
```

It happens with femtovg and skia backends but not with the Qt backend.

**Comment by ogoffart** [comment]
Could be related to https://github.com/slint-ui/slint/issues/1671

**Comment by jturcotte** [comment]
Ah yes, [looks like it](https://github.com/slint-ui/slint/issues/1671#issuecomment-1609628887).
