### ISSUE TITLE
manual input to SpinBox can't be accepted

### ISSUE THREAD

**Issue by asuper0** [slint-ui/slint#3047]
Platform: Windows 10, 
Rust: 1.67-x86_64-pc-windows-msvc
Slint: 1.1.0

The slint file looks like 
```
export component MainWindow inherits Window{
    callback button-set-font(int);
    public function set-font-weight(w : float) {
        root.default-font-weight = w;
    }

    HorizontalLayout {
        spin-font-weight := SpinBox { value: 100; minimum: 1; maximum: 10000;}
        Button {
            text: "Set font weight"; 
            clicked => {
                button-set-font(spin-font-weight.value);
            }
        }
    }
}
```

and with rust code
```
    let main_weak_font = main_window.as_weak();
    main_window.on_button_set_font(move |curr|{
        let weight = curr;
        rfd::MessageDialog::new().set_description(&format!("set weight to {}", weight)).show();
        main_weak_font.unwrap().invoke_set_font_weight(weight as _);
    });
```

Evetytime I input some number to the spinbox and click the button, the message box would show other number.

**Comment by ogoffart** [comment]
Yes indeed, editing the value of the text input doesn't work
@FloVanGH can you have a look?

**Comment by FloVanGH** [comment]
Sure.

**Comment by asuper0** [comment]
Also, I suggest to add a feature, that hold mouse down on the arrow would let the number increasing or decreasing quickly, just like other UI system do.

**Comment by FloVanGH** [comment]
> Thanks for your quick reply!
Also, I suggest to add a feature, that hold mouse down on the arrow would let the number increasing or decreasing quickly, just like other UI system do.

For this we will need something like a `press-and-hold` callback first. I will create two separate issues.

**Comment by FloVanGH** [comment]
Press and hold issue: https://github.com/slint-ui/slint/issues/3051

**Comment by FloVanGH** [comment]
For `fluent` and `material` style text input already works. I will implement it also for the `native` style.

**Comment by FloVanGH** [comment]
needs #112
