### ISSUE TITLE
SpinBox lacks an edit callback

### ISSUE THREAD

**Issue by nununoisy** [slint-ui/slint#3054]
Title is fairly self-explanatory - it'd be nice to add a callback binding to know when the value of a `SpinBox` changes.

**Comment by FloVanGH** [comment]
Thank you for your suggestion. I think it make totally sense to add an `edit` callback to `SpinBox`.

**Comment by darknight** [comment]
Hi, I'd like to have a try.

**Comment by FloVanGH** [comment]
The PR is merged now, thank you @darknight.

**Comment by tronical** [comment]
Please add an entry to the changelog and add documentation for this new callback. Thanks :)
