### ISSUE TITLE
Refactoring: declare builtins struct in a centralized place.

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#3056]
Currently, [builtin struct](https://slint.dev/docs/slint/src/builtins/structs) used in the .slint language are declared in many place: in the docs, in builtin.slints, in the interpreter, in the rust code.  This makes it hard to add or change them.  They should be declared in one place, like we do for the enums.

We should use the same thing for builtin structs as what we do with enums: 
 - We should declare in i-slint-common a macro just like we do for enums in https://github.com/slint-ui/slint/blob/master/internal/common/enums.rs
 - The rust structs can be declared similar to enums in https://github.com/slint-ui/slint/blob/69567b49ef56def5c18b742e048f8b91ad6680cc/internal/core/items.rs#L1437
 - We can then remove the structs from builtins.slint and add the struct to the type system in https://github.com/slint-ui/slint/blob/69567b49ef56def5c18b742e048f8b91ad6680cc/internal/compiler/typeregister.rs#L236 instead of load_builtins.rs
 - documentation generation, C++ bindings generation, rtti (interpreter) integration, and everything else can be done the same. One can just grep for `for_each_enums` and do the equivalent for structs.

**Comment by darknight** [comment]
Hi, I want to give a try.

**Comment by ogoffart** [comment]
This was done in #3137
