### ISSUE TITLE
winit: Add a way to filter arbitrary winit event

### ISSUE THREAD

**Issue by itribs** [slint-ui/slint#3066]
How to hide the window when it loses focus？
I need to get the "winit::event::WindowEvent::Focused(bool)" event,
but I didn't find the relevant window event。

**Comment by ogoffart** [comment]
Thanks for filling an issue.
This is currently not possible unfortunately.
We should add an API in the i-slint-backend-winit crate to be able to set a callback to filter winit events.

**Comment by itribs** [comment]
> Thanks for filling an issue. This is currently not possible unfortunately. We should add an API in the i-slint-backend-winit crate to be able to set a callback to filter winit events.

This is great!
Very much looking forward to this feature!

**Comment by ogoffart** [comment]
Similar to i_slint_backend_winit::Backend::window_builder_hook  we could have a hook that filter events
