### ISSUE TITLE
Default widget style for macOS

### ISSUE THREAD

**Issue by FloVanGH** [slint-ui/slint#3084]
The goal with this topic is to create an additional widget style that should replace the `native` widget style as default on macOS. An other goal of this is to create a style that does not look foreign on macOS and looks like close as possible to the native macOS controls.

**Comment by tronical** [comment]
Cupertino is now included in master and it is labelled experimental. But it's not the default yet for macOS and won't be in 1.2 - so removing the milestone for now.

**Comment by FloVanGH** [comment]
done
