### ISSUE TITLE
Add a reverse model

### ISSUE THREAD

**Issue by Guiguiprim** [slint-ui/slint#3120]
Add a reverse model that would allow for `O(1)` reversing of a given input model.

Step:
- [x] Add `ReverseModel`
- [x] Add `ModelExt::reverse`
- [x] Do the C++ part (done in https://github.com/slint-ui/slint/pull/3132)

Also would be nice to support this in slint such as `for data in reversed(root.model): Item { /.../ }`
operation on models is tracked at https://github.com/slint-ui/slint/issues/1328 although reversed doesn't need a lambda

**Comment by FloVanGH** [comment]
Would be also nice to have a C++ variant of the `ReverseModel` 😉.

**Comment by Guiguiprim** [comment]
> Would be also nice to have a C++ variant of the `ReverseModel` wink.

Indeed. But I haven't done C++ for a while (since I stopped using Qt), I'm not setup for it anymore and I do want to, so I will cowardly let someone else do it :p

**Comment by FloVanGH** [comment]
I can handle it ;-)
