### ISSUE TITLE
Add support for using Slint as esp-idf component

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#3131]
ESP-IDF's build system allows pulling in various software components into a project, by local path, by git repository, or from https://components.espressif.com/ . This is documented in the [IDF Component Manager](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-component-manager.html).

We should support using Slint through the IDF Component Manager.

This could be done by adding a `api/cpp/esp-idf` directory, placing a `Kconfig` and `CMakeLists.txt` file there, and optionally uploading that to the component registry.

One of the challenges for this is that for the xtensa rust toolchain there remain issues about the use of hardware-floating point code generation (miscompilations), requiring [this](https://github.com/slint-ui/slint/blob/master/examples/mcu-board-support/esp32_s3_box/cargo-config.toml) kind of workaround. We need to somehow integrate that workaround into the component so that it's automatically applied when targeting the affected toolchain(s) or make sure that the documentation for the esp-idf component includes instructions how to apply the workaround.

**Comment by ogoffart** [comment]
> - Tuning the license file so that it doesn't read "unknown" in the registry

I think it's fine, we should just improve the Readme so the license is clear there

**Comment by tronical** [comment]
Good idea, that's easy to do.

**Comment by tronical** [comment]
Alright, I think we're covered now. The release checklist is updated to ensure the last version check, the update of the `GIT_TAG`, and running the upload job.

I'm closing this as done.
