### ISSUE TITLE
Multi TextInput selected at the same time.

### ISSUE THREAD

**Issue by Guiguiprim** [slint-ui/slint#3136]
Platform: with `slint-viewer 1.1.1` on linux.

When multiple `TextInput` (`read-only: true`, in my case) are present in the same page, it is possible to have multiple text blocs (one by input) selected at the same time.

As a user I would expect the selection from the first input to be cleared when interacting with a second input (and probably when interacting with any other focus scope).

**Comment by Guiguiprim** [comment]
Even more: if I do a text selection and click inside the text input rectangle it gets cleared, if I click anywhere outside it does not get cleared, which is the expected behavior.

**Comment by tronical** [comment]
Agreed. When a `TextInput` looses focus to another item within the window, the selection should be cleared. When the window looses focus, the selection should be retained.

**Comment by tronical** [comment]
Minor tricky detail: On `FocusEvent::WindowLostFocus` we need to distinguish between the window loosing focus because another application received focus vs. a popup window of this application received focus (in the future: a context menu on a textedit, that should not clear the selection).

**Comment by tronical** [comment]
So the basic outline for fixing this is I think this:

1. Extend `input::FocusEvent` with a `WindowLostFocusToPopup` variant.
2. Change `WindowInner::show_popup` to send a `WindowLostFocusToPopup` event to the current focus item.
3. In `TextInput's` focus event handler, clear the selection if `FocusEvent::FocusOut`.
4. Send `WindowReceivedFocus` back to the window when the popup is closed.
