### ISSUE TITLE
 Unable to display Chinese normally

### ISSUE THREAD

**Issue by MoutainPL** [slint-ui/slint#3174]
it was normal when i use slint extension `v1.1.1`
I use nightly extension now.

![image](https://github.com/slint-ui/slint/assets/69339989/bb1ce478-42ba-46bc-b44c-54cc7d7f3a43)

**Comment by MoutainPL** [comment]
@hunger 
- OS: Windows11
my sourcecode is as follows 
[convert_panel.zip](https://github.com/slint-ui/slint/files/12184303/convert_panel.zip)

**Comment by ogoffart** [comment]
From the screenshot, it looks like this is the visual studio code preview in a tab.  So that's the wasm platform.

**Comment by ogoffart** [comment]
This is a duplicate of https://github.com/slint-ui/slint/issues/2563
Let's close this issue and track it there.  Thanks for the report nevertheless
