### ISSUE TITLE
Context menu on right click

### ISSUE THREAD

**Issue by JesperAxelsson** [slint-ui/slint#318]
Hi!

I am a bit unsure if this is a feature request or just help request.

How do you show a context menu on right click? There were a popup, but from what I could tell it was not quite the same thing. 
If there is an way to do this already it would be great to have an example in the gallery.

**Comment by ogoffart** [comment]
Hi, thanks for your comment.

Context menu is not yet implemented. But we are planning to do that: https://github.com/sixtyfpsui/sixtyfps/issues/38

We could simulate a context menu with a `PopupWindow` but we also don't have an API to intercept the right click.

**Comment by ogoffart** [comment]
Actually marking as duplicated as #38 which covers this and more details.
