### ISSUE TITLE
Uncapped FPS on QT backend

### ISSUE THREAD

**Issue by Vinegret43** [slint-ui/slint#3193]
Platform: Linux (EndeavourOS)
GPU: AMD Radeon RX 6600
Language: Tested this when running a program compiled with cargo and when previewing with slint-viewer. Issue is present in both cases
Slint version: Tested on 1.1.1 and git version, both have this issue

There are some cases I found when `backend-qt` may render more FPS than needed:
 - When using sliders in a ScrollView
 - When animating something using `animation-tick()`. In my use-case (Animating a `Path`) it sometimes renders up to a thousand frames per second without any seeming need to do so

This issue isn't present when using `backend-winit` with Skia or FemtoVG, on these backends FPS is capped to 60 and program doesn't try to render more, hence it almost doesn't have any footprint. When using QT backend, however, a noticeable amount of CPU and GPU is used by the program when rendering animations

### Example for reproducing this issue

1. Create a file with the following Slint code:
```
export component AppWindow inherits Window {
    width: 300px;
    height: 300px;
    Rectangle {
        height: 30px;
        width: 100px + 50px * Math.sin(animation-tick() / 10ms * 1deg);
        background: red;
    }
}
```

2. Run it with `SLINT_DEBUG_PERFORMANCE=refresh_lazy,overlay slint-viewer <FILE NAME>`

3. Observe how FPS starts pretty low and after a few seconds jumps to about 200-300

**Comment by tronical** [comment]
Thank you for the report. Are you using X11 or Wayland?

**Comment by Vinegret43** [comment]
I'm using X11. I just tested this issue on Wayland, though, and it's kinda interesting: Slint's built-in FPS meter still shows a ridiculous amount of FPS, but at the same time my GPU load meter stays at 0%, while on X11 it used to jump to about 10% when rendering hundreds of frames per second
