### ISSUE TITLE
Slint Memory Game Tutorial still shows SixtyFPS and not Slint

### ISSUE THREAD

**Issue by szabgab** [slint-ui/slint#3207]
Not a huge issue, but the tutorial (e.g. this page: https://slint.dev/releases/1.1.1/docs/tutorial/rust/getting_started ) still shows the old name.

**Comment by tronical** [comment]
Thanks for reporting - very valid issue indeed. The screenshots need a refresh :)

**Comment by tronical** [comment]
This is fixed now (on the website, where the images/clips referenced by the tutorial are stored)
