### ISSUE TITLE
Vertical/Horizontal Layouts should collapse spacing for empty items

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#3213]
Suppose a vertical layout contains an element that has a height of zero:

```slint
import { Button, VerticalBox } from "std-widgets.slint";
export component Demo {
    VerticalBox {
        alignment: start;
        Text {
            text: "Top";
        }
        Rectangle { height: 0px; } // comment in or out
        Text {
            text: "Bottom";
        }
        Text {
            text: "Another One";
        }
    }
}
```

If you comment out the Rectangle, you'll notice that the spacing between the two text element differs.

The desired "effect" could be implemented using a conditional, but then it's not possible to animate the height/appearance of the item. I think it would be better if there was no spacing applied when the height is zero.

**Comment by ogoffart** [comment]
I'm don't think the spacing should be collapsed.  If you animate the height, you would end up with a sudent jump.
The point of having an empty item may precisely be because this extra spacing is wanted.
But i see why some user may expect that.
I think we may want to re-think some of the layout behavior in this respect  anyway (with respect to margin with layouts in layouts and such)

**Comment by tronical** [comment]
> If you animate the height, you would end up with a sudent jump.

Fair point!

I wonder how to achieve an animated expanding item then that starts at a height of zero? Should this be written as `height: -parent.spacing;`?

**Comment by ogoffart** [comment]
> I wonder how to achieve an animated expanding item then that starts at a height of zero?

Maybe we want to have some special animation properties on the layout?


Also was thinking maybe some extra transitions on `if`
```
if condition: Element {
    transitions [ 
        disappear: { animate height { duration: 200ms; } }
        appear: { animate opacity { duration: 200ms; } }
    ]
}
```

**Comment by tronical** [comment]
> Maybe we want to have some special animation properties on the layout?

How would those look like?

> Also was thinking maybe some extra transitions on if

That looks like it would solve the issue I'm running into. Pre-defining transitions for that sounds like a good idea to me.

Shall we close this ticket then (since the layout behavior makes sense with regards to the spacing) and I create one for your transitions on conditionals idea?

**Comment by tronical** [comment]
Closing in favor of the more specific #3258
