### ISSUE TITLE
LSP: auto-complete properties in animations

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#3237]
The LSP currently don't complete anything in an animation.

example

```
component Foo {
    property <int> xx;
    animate xx {
        // cursor here
    }
}
```

It should auto-complete the `duration`, `easing` and other possible animation options.
Also, within the binding of these animation, it should auto-complete.

```
component Foo {
    property <int> xx;
    animate xx {
         easing: // cursor here
    }
}
```
 it should give me the different option for an easing curve.

**Comment by darknight** [comment]
Hi, I'll give it a try.

**Comment by ogoffart** [comment]
I guess you found out that there is code to do in the tools/lsp/completion.rs files in the `completion_at` function.
You'll have to find out what is the  `token.kind()` and `node.kind()` for that locations and fetch the completion from there.
I think it will be something like within a `SyntaxKind::PropertyAnimation`  which is not yet handled
