### ISSUE TITLE
Add API to get query the window visibility

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#325]
Currently the public API in Rust/C++/JavaScript only allows showing or hiding the window. This ticket tracks the availability of API in Rust, C++ and JavaScript to

1. Query whether the window is visible using a property/accessor function.
2. Allow developers to specify a callback in C++/Rust/JS that's invoked when the visibility changes.

**Comment by ogoffart** [comment]
maybe a `visible` property on the `Window` element, which the developer can choose to expose.
And a `close_event() -> EventResult` callback which could also prevent the window from being closed.

**Comment by dilawar** [comment]
Is it possible to get the `visible` property or something equivalent using some hacks?

**Comment by idipot** [comment]
will this change require adding new Variant to `WindowEvent`? I didn't find any existing property that can help indicate if the window is visible or not? How should i go about in implementing this?
cc @ogoffart @tronical

**Comment by ogoffart** [comment]
@idipot  
You would add a `fn is_visible(&self) -> bool`  (or should it actually be called `is_shown()`?)  to the `api::Window`  which then would forward that to a new function in the `WindowAdapterSealed`  trait, and then the backend can query the visibility of the window.

**Comment by ogoffart** [comment]
Done in 0.3.2
