### ISSUE TITLE
Window being constantly in front

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#3280]
### Discussed in https://github.com/slint-ui/slint/discussions/3252

<div type='discussions-op-text'>

<sup>Originally posted by **JanDiederich** August 10, 2023</sup>
I have an application with constantly animated text, that breaks the Winit backend and the Qt backend. I tested both, but the result stays the same. The window is a constant topmost application, which can't stay in the background and constantly, annoyingly, workflow-stopingly, pushes itself into the topmost front.

How can I fix that?

My systems: Ubuntu 20.04.6 LTS 64 Bit and Raspberry Pi OS 64 Bit latest version.

Edit: As soon as I disable the animation, the window behaves normal. The "redraw" call, caused by the animation, seems to trigger it.</div>

**Comment by JanDiederich** [comment]
I miss the label `a:backend-qt`. I had the bug also with the Qt backend. Please confirm that.

**Comment by tronical** [comment]
I can confirm that Qt is not affected. I download Qt 5.15 into the same VM and can confirm that the issue does not exist there. The code in Qt confirms this, too, as they do what this patch does for winit: Change the x11 atoms only if the state changes on the client side.
