### ISSUE TITLE
Slint should have a show_fullscreen() function

### ISSUE THREAD

**Issue by hunger** [slint-ui/slint#3283]
As discussed in #2775 about _documenting_ fullscreen mode:

We should have a `show_fullscreen()` API to `slint::Window` to control fullscreen mode programmatically.

Edit(@tronical): As outlined in #3331 , the acceptance criteria for this ticket should include `show_maximized` at the same time.

**Comment by JanDiederich** [comment]
It seems that both, most important window backends, Qt and Winit, have a native built in live go-to-fullscreen capability.

* Qt: https://doc.qt.io/qt-6/qwindow.html#showFullScreen.
* Winit, after a quick google: https://github.com/rust-windowing/winit/blob/master/examples/fullscreen.rs: `window.set_fullscreen(fullscreen);`

**Comment by ogoffart** [comment]
Implemented in https://github.com/slint-ui/slint/pull/4286
