### ISSUE TITLE
A strange problem about fullscreen

### ISSUE THREAD

**Issue by Horbin-Magician** [slint-ui/slint#3303]
Language: Rust
System: Windows11
Renderer：winit-skia-opengl

When I set my window to fullscreen, the monitor is abnormal. (blank screen, and can only reply if you start Task Manager)

My simplified code: 

```Rust
fn main() {
    let mask_win = MaskWindow::new().unwrap();
    mask_win.window().with_winit_window(|winit_win: &winit::window::Window| {
        winit_win.set_fullscreen(Some(winit::window::Fullscreen::Borderless(winit_win.current_monitor())));
    });
    mask_win.run().unwrap();
}
slint::slint! {
    export component MaskWindow inherits Window {
    }
}
```

or the same problem would arise:

```Rust
fn main() {
    let mask_win = MaskWindow::new().unwrap();
    mask_win.window().set_position( slint::PhysicalPosition::new(0, 0) );
    mask_win.run().unwrap();
}

slint::slint! {
    export component MaskWindow inherits Window {
        no-frame: true;
        width: 2560px / 1.5;     // the logical size of my monitor
        height: 1440px / 1.5;    // the logical size of my monitor
    }
}
```

**Comment by ogoffart** [comment]
I tried this code and i couldn't reproduce any bug.
That said, the window didn't go full screen either.

**Comment by Horbin-Magician** [comment]
> 

Maybe there is a system difference (Linux X11 and Windows11).

But I am surprised that my code does not have full screen on linux, can I ask what is the most robust full screen method?

**Comment by Horbin-Magician** [comment]
> Can this still be reproduced in the newer Slint that has the set_fullscreen API?

I failed to use the set_fullscreen API. 

My code:
```
    let main_window = MainWindow::new().unwrap();

    main_window.set_fullscreen(true);
```

Error:
```
     --> examples\todo\rust\main.rs:32:17
      |
32    |     main_window.set_fullscreen(true);
      |                 ^^^^^^^^^^^^^^ method not found in `MainWindow`
```

I just add a line in the todo example of slint's master branch.

**Comment by ogoffart** [comment]
It would be  `main_window.winrow().set_fullscreen(true)` and it was added in the master branch.

**Comment by Horbin-Magician** [comment]
Full screen now causes the entire screen to go black for about 2 seconds, then it seems to return to normal.
I think the new API works well, and I'll test it further in my project when version 1.4.0 comes out.
For now, I willI close this issue.
