### ISSUE TITLE
Root component without Window inheritance shows nothing when compiled

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#3318]
The following minimal test case shows up fine in the preview but when compiled in a Rust or C++ app, the window remains empty:

```
export component AppWindow {
    VerticalLayout {
        Text {
            text: "Hello World";
        }
    }
}
```

Changing `AppWindow` to inherit `Window` works around it.

**Comment by ogoffart** [comment]
`llr::inline_expressions::inline_simple_expressions`   inlines the with of the text to be 0.
