### ISSUE TITLE
Can you help me find the specs of fluent design?

### ISSUE THREAD

**Issue by cppdev123** [slint-ui/slint#3332]
I'm searching the web for fluent design specs with no success, I want to implement some widgets can you help me find those specs?

**Comment by ogoffart** [comment]
the spec are there: https://fluent2.microsoft.design/
The implementation of our widgets is in https://github.com/slint-ui/slint/tree/master/internal/compiler/widgets/fluent-base
slint docs on how to select the style: https://slint.dev/snapshots/master/docs/slint/src/advanced/style
