### ISSUE TITLE
Combobox in fluent style might not render items as they get out of the screen 

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#3345]
When a ComboBox is too high or too low in the window, its entries are not visible.

[Example](https://slintpad.com/?snippet=import+%7B+Button%2C+VerticalBox+%2C+ComboBox%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Demo+%7B%0A++++VerticalBox+%7B%0A++++++++ComboBox+%7B+model%3A+%5B%22First%22%2C+%22Second%22%2C+%22Third%22%2C+%22Fourth%22%2C+%22Fifth%22%2C+%22Sixth%22%2C+%22Seventh%22%5D%3B+%7D%0A++++++++Text+%7B%0A++++++++++++text%3A+%22Hello+World%21%22%3B%0A++++++++++++font-size%3A+24px%3B%0A++++++++++++horizontal-alignment%3A+center%3B%0A++++++++%7D%0A++++++++Image+%7B%0A++++++++++++source%3A+%40image-url%28%22https%3A%2F%2Fslint.dev%2Flogo%2Fslint-logo-full-light.svg%22%29%3B%0A++++++++++++height%3A+100px%3B%0A++++++++%7D%0A++++++++ComboBox+%7B+model%3A+%5B%22First%22%2C+%22Second%22%2C+%22Third%22%2C+%22Fourth%22%2C+%22Fifth%22%2C+%22Sixth%22%2C+%22Seventh%22%5D%3B+%7D%0A++++++++HorizontalLayout+%7B+alignment%3A+center%3B+Button+%7B+text%3A+%22OK%21%22%3B+%7D+%7D%0A++++++++Rectangle+%7B%7D%0A++++++++ComboBox+%7B+model%3A+%5B%22First%22%2C+%22Second%22%2C+%22Third%22%2C+%22Fourth%22%2C+%22Fifth%22%2C+%22Sixth%22%2C+%22Seventh%22%5D%3B+%7D%0A++++%7D%0A%7D%0A)

First entry is not visible 
![image](https://github.com/slint-ui/slint/assets/959326/3bce4862-160e-41cd-8cfd-50ba17c0df1a)

As discussed in https://github.com/slint-ui/slint/discussions/3172#discussioncomment-6815060

**Comment by tronical** [comment]
Perhaps we can solve this on the backend side somehow. The "hybrid" that a popup can sometimes be rendered inline and sometimes as real window is something that perhaps would ideally be abstracted away by the backend entirely.

To the run-time library ideally this is always a separate window and the backend takes care of placing it in a way that it's entirely visible on the screen and does not overlap with the micro-focus area (if possible).

**Comment by Guiguiprim** [comment]
I got hit by this today, with a combo-box in a dialog.
