### ISSUE TITLE
in .slint file,I can use @tr() macro to translate language, how to get translated strings in rust code?

### ISSUE THREAD

**Issue by ryanjackgit** [slint-ui/slint#3388]
For example,  use @tr("hello") in .slint file.  in rust code,how to do it?

**Comment by ogoffart** [comment]
There are a few crates that do it. For example with https://crates.io/crates/tr  you can use `tr!("hello")`

**Comment by ryanjackgit** [comment]
on windows 10, build gettext-sys error ,  #3307

**Comment by ogoffart** [comment]
Duplicate of https://github.com/woboq/tr/issues/10 and https://github.com/Koka/gettext-rs/issues/12 and #3307
