### ISSUE TITLE
linuxkms: Add support for software rendering

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#3390]
At the moment only the FemtoVG renderer and Skia with OpenGL and Vulkan are supported.

We should add support for allocating DUMB buffers and the ability to render into them using our software renderer as well as Skia's software renderer.

**Comment by tronical** [comment]
Skia fullscreen software support is implemented. Slint software renderer, and partial rendering support is not done yet.

**Comment by yaobo-lab** [comment]
> Skia fullscreen software support is implemented. Slint software renderer, and partial rendering support is not done yet.

When will this feature be supported? I'm really looking forward to this feature

**Comment by ogoffart** [comment]
This is implemented in master (for 1.7)

**Comment by igiona** [comment]
@ogoffart is there any documentation on how to use this with a framebuffer as output device like `/dev/fb0` ?
In QT I usually simply pass `-platform linuxfb` via command line arg when I start the application, and somehow the magic happens.
