### ISSUE TITLE
Changing tab in the Gallery demo unmaximizes the window

### ISSUE THREAD

**Issue by sdasda7777** [slint-ui/slint#3419]
Hi, I'm not sure why, but when testing the Gallery demo (`cargo run` in the `examples/gallery/`) every time I change the tab (on the left, Controls, ListView, etc.) the window unmaximizes and changes position to the position it had before being maximized (it does not move when not maximized):

![image](https://github.com/slint-ui/slint/assets/17746796/dc2c6526-fff1-4572-844d-a7578424a47b)

I don't believe this is intended to happen: if it is not, is it issue with the demo itself, or with Slint (or underlying libraries)? I am using Windows 10, if that helps in any way.

**Comment by ogoffart** [comment]
Thanks for the bug report.

I believe this is a duplicate of https://github.com/slint-ui/slint/issues/2904 which will be fixed with the next version of winit.

**Comment by sdasda7777** [comment]
Thanks, it really seems like it.
