### ISSUE TITLE
Open two different components

### ISSUE THREAD

**Issue by quiet-feifei** [slint-ui/slint#3429]
Sorry, my English is not very good,

How can I export two components in the main.slint file.
```
component TestWin inherits Window {
    
}

component TestWin1 inherits Window {
    
}


export { TestWin,TestWin1 }
```
But this only introduces the last component in main.rs.
```
 TestWin::new();
   |     ^^^^^^^^ use of undeclared type `TestWin`
```

**Comment by tronical** [comment]
Yes, sadly this is not possible at the moment :(

**Comment by tronical** [comment]
Duplicate of #784
