### ISSUE TITLE
Change default style on windows and mac

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#3431]
1. Rename "native" style to "qt" (#3514)
2. always default to "native" which would be an alias to:
   - "fluent" on windows
   - "cupertino" on mac 
   - "qt" on linux if the backend is there, "fluent" otherwise
   - ~~"material"~~ "fluent" on wasm 
   - "material" on android
3. Change the backend selector Cargo.toml to disable qt as the default backend on win and mac (but how?)

**Comment by ogoffart** [comment]
For 2. the current detection of whether the Qt is done:
 - For rust: through the `SLINT_DEFAULT_STYLE.txt` hack in the backend-selector, then slint-build/lib.rs and slint-macro/lib.rs read that file
 - For C++: this is done as the default value of SLINT_STYLE in CMakeLists.txt  (which depends if cmake detected Qt)
 - The interpreter use api in the backend selector to find out.

The problem is that i-slint-compiler doesn't depend on the runtime (obviously) so it is a bit hard to do all in one place. But under the new system i was thinking we could read SLINT_DEFAULT_STYLE (which we could rename to something else) to resolve the "native" alias around https://github.com/slint-ui/slint/blob/master/internal/compiler/typeloader.rs#L101  that would help with rust and the interpreter, but not with C++ as the compiler and the runtime are build in different targets. We'd need a way to tell the compiler what features are enabled.

**Comment by tronical** [comment]
Can you elaborate what information exactly the compiler needs in the C++ case that it currently doesn't have access to?

Currently, in C++ we pass `--style ${_SLINT_STYLE}` to the compiler.

**Comment by kekeimiku** [comment]
It would be great if you could use native theme styles without relying on Qt.

**Comment by ogoffart** [comment]
> It would be great if you could use native theme styles without relying on Qt.

That's the idea, on all platform but Linux.
Only on Linux we'll keep using the Qt style as a native style because Qt is native there (at least on KDE Plasma). If someone wants to write a GTK style, or an adwaita style ( https://github.com/slint-ui/slint/issues/2566 ) we could also use that.

**Comment by ogoffart** [comment]
@circlePulse This should be explained there: https://releases.slint.dev/1.6.0/docs/slint/src/advanced/style#selecting-a-widget-style-with-rust

(It's okay to ask here, but the best is to use the [GitHub discussions](https://github.com/slint-ui/slint/discussions) for questions)
