### ISSUE TITLE
raspi 3B+ build time rust crate 70 min

### ISSUE THREAD

**Issue by frehberg** [slint-ui/slint#3443]
Cross build of slint 1.2 for raspberry aarch64 (raspi 3b+)  fails with linker error, symbol memfd_create missing

Therefore I tried to compile on raspi 3b+ nativley. Due to 1GB memory limiations the build only succeeds using single thread, for release and without debug symbols, and takes 70 minutes

RUSTFLAGS='-C link-arg=-s' cargo build -j 1 --release

   Compiling i-slint-backend-selector v1.2.0
   Compiling slint-build v1.2.0
   Compiling slint-test v0.1.0 (/home/sysuser/slint-test)
   Compiling slint-macros v1.2.0
   Compiling slint v1.2.0
    Finished release [optimized] target(s) in 70m 21s
sysuser@raspberrypi:~/slint-test $ 

As workaround I plan to compile on raspi 4B with 8GB.

**Comment by ogoffart** [comment]
This has been reported before: https://github.com/slint-ui/slint/issues/3403 
Closing as duplicate. Thanks anyway for the report
