### ISSUE TITLE
 In Rust, the Slint third-party component library cannot be used.

### ISSUE THREAD

**Issue by Vjze** [slint-ui/slint#3451]
In Rust, the Slint third-party component library cannot be used. After use, the memory will be full and cannot be compiled. However, the slint plug-in in VSCode is displayed normally. Maybe this is a problem with rust-analyzer?
The third-party plug-in comes from SurrealismUI and can be found at https://madewithslint.com/. It is a very useful plug-in, but it cannot be used, which is a pity.

**Comment by Vjze** [comment]
Video address: https://youtu.be/T84-tgZMWPE

**Comment by ogoffart** [comment]
Thanks for reporting bugs.
I see you closed the bug so I assumed you fixed the problem locally.
Out of curiosity, what was the problem?

**Comment by Vjze** [comment]
> Thanks for reporting bugs. I see you closed the bug so I assumed you fixed the problem locally. Out of curiosity, what was the problem?

The Button control in the third-party component library SurrealismUI will cause memory overflow during Rust compilation. The author told me that the reason for the memory overflow is the built-in SURIcon in the SURButton component. Since SURIcon has 2658 built-in pictures that are judged and generated through a loop, the memory overflow occurs. The author has now solved this problem.
