### ISSUE TITLE
Vertical text alignment issue with word-wrap and elide

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#3481]
### Discussed in https://github.com/slint-ui/slint/discussions/3479

Given this Slint file:

```slint
export component StatusBox inherits Window  {
   preferred-width: 100px;   preferred-height: 100px;
   min-height: 64px;   min-width: 64px;
   
   Rectangle {
        height: 100%;
        width: 100%;

        Text {
            text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
            height: 100%;
            width: 100%;
            wrap: word-wrap;
            overflow: TextOverflow.elide;
            vertical-alignment: TextVerticalAlignment.center;
        }
    }
}
```

This is inconsistent across renderer:

Skia
![Skia](https://github.com/slint-ui/slint/assets/959326/cadfb23a-5518-4052-96fa-768baad9c092)

FemtoVG
![femtovg](https://github.com/slint-ui/slint/assets/959326/6f2abdb6-bd6d-4a8b-ba4f-49eb29a46eb6)

Software
![Software](https://github.com/slint-ui/slint/assets/959326/d1dd0618-2dfa-437a-b769-c6043b728bb7)

Qt
![Qt](https://github.com/slint-ui/slint/assets/959326/c4255d5f-1807-462f-991f-44d262777937)

Only Qt is correct.

**Comment by ogoffart** [comment]
Status: 

 -  FemtoVG has been fixed ✅
 
 - Skia got improved but is still not eliding properly
![image](https://github.com/slint-ui/slint/assets/959326/3d737b0c-7471-40c1-b6a5-ac2c15d9e582)

- Software is still broken

**Comment by jpnurmi** [comment]
> * Skia got improved but is still not eliding properly

My bad, the line height calculation was not correct in #3490 even though it looked like it helped on macOS. :) Here's a second attempt, this time tested on Linux too: #3594.
