### ISSUE TITLE
Checkboxes rendered inproperly with native style on KDE

### ISSUE THREAD

**Issue by dest1n1s** [slint-ui/slint#3482]
Hello, I'm a beginner to slint, and when I try to run the `todo` example on Arch Linux with KDE Plasma Desktop (The problem exists in both X11 and Wayland backend), I found the native style of the checkboxes rendered inproperly, as the following video shows:

https://github.com/slint-ui/slint/assets/13075143/6603b224-dfdc-4721-88bc-66f9bcb29d0d

It seems that the re-rendering is delayed to the next action (the next click, cursor flash, window resizing, etc.). And problem in #2598 is also observed.

**Comment by dest1n1s** [comment]
This is the latest version of the master branch. I've also tried to specify the slint version to 1.2, but it produced the same result.

**Comment by ogoffart** [comment]
I can reproduce the problem.  This is actually caused by #3075 which now make animations, but somehow we don't get update for all animation because some styles don't work properly

**Comment by ogoffart** [comment]
It seems like the breeze style do quite complicated operations with the widgets (render into pixmap to trnasition)  and then use update() for animation.  But since the widget that we draw are in fact invisible, the update() call do nothing and we are not notified when there is an animation
