### ISSUE TITLE
Reset animations [was:  infinite loop animation error]

### ISSUE THREAD

**Issue by syf20020816** [slint-ui/slint#3494]
Root cause is that the animation gets stopped at some value between 0 and 360° and animates from that (random) value to 360°.

We should have a way to cleanly reset animations in use-cases like this one. -- @hunger

Original report follows:

----

# My Goal
I want to write a loading component , when this component show the loading icon will rotate in an infinite loop
## error video
The icon in the component can rotate normally during the first run, but after multiple runs, the animation shows an exception

https://github.com/slint-ui/slint/assets/92167095/ee874119-876b-4d22-a6f2-e4db73659e1a

## Source Code Repo
loading.slint : https://github.com/syf20020816/SurrealismUI/tree/main/src/loading/loading.slint
test : https://github.com/syf20020816/SurrealismUI/blob/main/tests/src/loading.slint
### Code
```
import { SURPopup } from "../popup/index.slint";
import { SURText } from "../text/index.slint";
import { SURCard } from "../card/index.slint";

import {ROOT_STYLES,Themes,PaddingSize,PaddingItem,Shadows,Borders,BorderItem,IconSources} from "../../themes/index.slint";
export component Loading inherits Window {
  height: 100%;
  width: 100%;
  padding: 0;
  padding-bottom: 0;
  padding-left: 0;
  padding-right: 0;
  padding-top: 0;
  always-on-top:true;
  opacity: 1;
  visible: is-show;
  z: 1000;
  in property <image> loading-icon : IconSources.icons.Loading;
  in property <duration> duration : 1200ms;
  in property <string> content : "Loading ...";
  in-out property <bool> is-show:false;
  in property <Themes> theme : Dark;
  callback open();
  callback close();
  open => {
    self.is-show = true;
    // do animation
    loading-icon.rotation-angle = 360deg;
  }
  close => {
    self.is-show = false;
    loading-icon.rotation-angle = 0deg;
  }
  mask:=SURCard {
    z: 100;
    height: 100%;
    width: 100%;
    theme: root.theme;
    drop-shadow-blur: 0;
    drop-shadow-offset-x: 0;
    drop-shadow-offset-y: 0;
    opacity: 100%;
    border: None;
    clip: true;
    VerticalLayout {
      alignment: center;
      width: 50%;
      spacing: ROOT-STYLES.sur-font.font-size;
      Rectangle {
        height: loading-icon.height;
        width: parent.width;
        loading-icon:=Image {
          height: ROOT-STYLES.sur-font.font-size * 2;
          width:  ROOT-STYLES.sur-font.font-size * 2;
          source: root.loading-icon;
          animate rotation-angle {
            easing: ease-in-out;
            iteration-count: -1;
            duration: root.duration;
          }
        }
      }
      Rectangle {
        height: loading-txt.height;
        width: parent.width;
        loading-txt:=SURText {
          theme: root.theme;
          content: root.content;
        }
      }
    }
  }
  TouchArea {
    z: 110;
  }
}
```
### test code
```
import {SURLoading,SURButton,SURCard} from "../../index.slint";

export component TestLoading inherits Window {
    height: 600px;
    width: 400px;
    SURButton {
      y: 100px;
      content: "show";
      clicked => {
        p.open();
      }
    }
    SURButton {
      y: 160px;
      content: "close";
      clicked => {
        p.close();
      }
    }
    SURCard{
      y: 260px;
      clip: true;
      card-height: 260px;
      card-width: 180px;
      p:=SURLoading { }
    }
}
```

**Comment by syf20020816** [comment]
Thank you for providing the case, but after my inspection, it seems that the problem lies in the issue of loop animation failure when using the `visible` property to hide the component

**Comment by syf20020816** [comment]
https://github.com/slint-ui/slint/assets/92167095/80cbf111-18f0-4f2a-94dc-9138f8b5cf4f

**Comment by ogoffart** [comment]
The `animate rotation-angle { ... }` means it animates from the current position to the new position in that amount of time.
So if you set `rotation-angle = xyz;` it will animate from the current value to `xyz`.  But if you call it twice, the current value depends on the animation, so the behavior is correct.

The truth is that iteration-count is not a great way to get continuously rotating animation. 
For this kind of usecase, you are better off with animation-tick.

For example: [Link](https://slintpad.com/?snippet=import+%7B+Button+%2C+VerticalBox%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+TestLoading+inherits+Window+%7B%0A++++height%3A+600px%3B%0A++++width%3A+400px%3B%0A%0A++++property%3Cduration%3E+loading_animation_duration%3A+1000ms%3B%0A++++property%3Cbool%3E+animating%3B%0A%0A%0A++++VerticalBox+%7B%0A++++++++Button+%7B%0A++++++++++++height%3A+50px%3B%0A++++++++++++text%3A+%22Start%22%3B%0A++++++++++++clicked+%3D%3E+%7B%0A++++++++++++++++root.animating+%3D+true%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++++++Button+%7B%0A++++++++++++height%3A+50px%3B%0A++++++++++++text%3A+%22Reset%22%3B%0A++++++++++++clicked+%3D%3E+%7B+%0A++++++++++++++++root.animating+%3D+false%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++++++%0A++++++++Rectangle%7B%0A++++++++++++p%3A%3D+Image+%7B%0A++++++++++++++++source%3A+%40image-url%28%22https%3A%2F%2Fslint.dev%2Flogo%2Fslint-logo-full-light.svg%22%29%3B%0A++++++++++++++++rotation-angle%3A+%21animating+%3F+0deg+%3A+360deg+*+animation-tick%28%29%2Floading_animation_duration%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D)

```
rotation-angle: !animating ? 0deg : 360deg * animation-tick()/loading_animation_duration;
```

(this doesn't have an easing curve, but you can get one with some math in the binding)
