### ISSUE TITLE
Invalid documentation about translation

### ISSUE THREAD

**Issue by Guiguiprim** [slint-ui/slint#3531]
The language documentation does not reflect the added support for translation.

- Blog post: https://slint.dev/blog/translation-infrastructure
- current documentation: https://slint.dev/releases/1.0.0/docs/slint/src/recipes/recipes#translations `Slint doesn’t currently offer built-in support for translations.`

**Comment by ogoffart** [comment]
The link is from the 1.0.0 version.
The documentation for the latest version no longer have this: https://slint.dev/releases/1.2.1/docs/slint/src/recipes/recipes
The documentation about translation is there: https://slint.dev/releases/1.2.1/docs/slint/src/language/concepts/translations

**Comment by Guiguiprim** [comment]
My bad I did not see the version number in the link. (the new doc does include a very visible version number which is good !)

Sorry for this.
