### ISSUE TITLE
Global keyboard input events don't fire in Rust while Slint window is open 

### ISSUE THREAD

**Issue by Tartarus762** [slint-ui/slint#3537]
Hi,

I'm using Slint with Rust on Windows 11 and am trying to listen for global keyboard events, however, while a Slint window is open, keyboard events don't fire. All mouse events still work.

Window clode:
```
slint::slint!{
    import { Button } from "std-widgets.slint";

    export global MainWindowLogic {
        callback button_pressed();        
    }

    export component MainWindow inherits Window {
        Button { 
            text: "Click";
            clicked => {MainWindowLogic.button-pressed()}
         }
    }
}
```

UI in it's own thread:
```
thread::spawn(move || {
    let main_window = MainWindow::new().unwrap();  
    main_window.global::<MainWindowLogic>().on_button_pressed(move | | 
    {            
        //Do something here
    });  
    main_window.run().unwrap();
});
```

Listen for keyboard events:
```
if let Err(error) = listen(callback) {
    println!("Error: {:?}", error)
}
```

Callback:
```
fn callback(event: Event){
    println!("My callback {:?}", event);
    match event.name {
        Some(string) => println!("User wrote {:?}", string),
        None => (),
    }
}
```

When I run this, I get all mouse events as follows:
```
My callback Event { time: SystemTime { intervals: 133399861769472960 }, name: None, event_type: MouseMove { x: 322.0, y: 168.0 } }
My callback Event { time: SystemTime { intervals: 133399861787986457 }, name: None, event_type: ButtonPress(Left) }
```

Keyboard inputs don't cause any callback invocations, however if I close the window, they begin working again:
```
My callback Event { time: SystemTime { intervals: 133399861804840192 }, name: Some("h"), event_type: KeyPress(KeyH) }
```

Not sure if this is intended or if it is something to do with how keyboard events work in Rust. Please let me know if there is a way to do what I'm after while still using Slint.

**Comment by Tartarus762** [comment]
I forgot to mention that I am using libraries to handle the events.

I have tried both [Rdev](https://github.com/Narsil/rdev/tree/main) as well as [InputBot](https://github.com/obv-mikhail/InputBot/tree/develop) and they both have the same issue.

I'm not super experienced with Rust but it looks like they're using slightly different methods to me.

**Comment by ogoffart** [comment]
Would you have a reproducible example?
Are you using the winit or the qt backend?
We don't really listen to the event ourselves, this is delegated to libraries such as winit, and I think this may just conflict with whatever library you are using to listen the events?

What is your usecase? why are you listening to the event.  What you can probably do is to forward the event from Slint back to your app with callback

**Comment by Tartarus762** [comment]
I'll paste an example here:
```
use std::thread;
use rdev::{listen, Event};

slint::slint!{
    import { Button } from "std-widgets.slint";

    export global MainWindowLogic {
        callback button_pressed();        
    }

    export component MainWindow inherits Window {
        Button { 
            text: "Click";
            clicked => {MainWindowLogic.button-pressed()}
         }
    }
}


fn main() {
    //If I have this here, inputbot binding no longer works
    thread::spawn(|| {
        let main_window = MainWindow::new().unwrap();  
        main_window.global::<MainWindowLogic>().on_button_pressed(move | | 
        {            
            //Do something
        }
        );  
        main_window.run().unwrap();
    });

    if let Err(error) = listen(callback) {
        println!("Error: {:?}", error)
    }
    
}

fn callback(event: Event){
    println!("My callback {:?}", event);
    match event.name {
        Some(string) => println!("User wrote {:?}", string),
        None => (),
    }
}
```

In this particular example you would need to add Rdev (cargo add rdev). Rdev is a library for listening to events globally.

My usecase is that I was the program to do something when I press a certain key combination, but the application will not be in focus. Not sure if Slint accepts inputs while not in focus, but passing it back could be a possibility.

**Comment by ogoffart** [comment]
(Can't reproduce on X11, must then be a Windows problem)

What backend are you using? Qt or winit? (I assume winit)
Does other rust application using winit work?

**Comment by ogoffart** [comment]
I believe this is just that winit and inputbot are incompatible
