### ISSUE TITLE
`GroupBoxes` in `ScrollView` cause visual glitches 

### ISSUE THREAD

**Issue by FireFragment** [slint-ui/slint#3541]
When using the native style, the following slint code causes visual glitches when scrolling:

```slint
import { VerticalBox, ScrollView, GroupBox } from "std-widgets.slint";
export component GroupBoxesAndScrollView {
    VerticalLayout {
        Text {
            text: "Groupoxes and scrollviews aren't friends";
            font-size: 20px;
        }
        ScrollView {
            height: 200px;
            VerticalLayout {
                GroupBox { height: 100px; Text { text: "Box #1"; } }
                GroupBox { height: 100px; Text { text: "Box #2"; } }
                GroupBox { height: 100px; Text { text: "Box #3"; } }
                GroupBox { height: 100px; Text { text: "Box #4"; } }
                GroupBox { height: 100px; Text { text: "Box #5"; } }
            }
        }
    }
}
```

https://github.com/slint-ui/slint/assets/55660550/043dac37-d7d3-4ea0-b69a-1ab1aa68b761

As seen in the video, `GroupBox`es overflow the `ScrollView`.

With other styles, it works correctly

Platform: KDE, Linux, X11

**Comment by ogoffart** [comment]
Thanks for the bug report.  I can reproduce the problem with the breeze style.

At first glance, it looks liked the breeze style don't respect the "clip" on the QPainter.  We probably will have to add another workaround

**Comment by ogoffart** [comment]
Actually the problem is even in the QCommonStyle, which reset the clip instead of intersecting it: https://github.com/qt/qtbase/blob/6ca2008d6e1e02e85f39faab28d5c8a0c0dad082/src/widgets/styles/qcommonstyle.cpp#L3833
