### ISSUE TITLE
Focus on `StandardListView` isn't visible

### ISSUE THREAD

**Issue by FireFragment** [slint-ui/slint#3548]
Focused `StandardListView` is indistinguishable from an unfocused one, making it impossible to tell, whether a list is focused. This happens with all three styles (fluent, material, and native). 

### Video

Here is a video of how the code below behaves:

https://github.com/slint-ui/slint/assets/55660550/1e83a75f-7fc0-40b0-8fe2-e78b43b5f246

### To reproduce

Launch the following code and repeatedly press the TAB key. You can see, that buttons and checkbox are highlighted correctly when focused, while the list is not.

```

import { Button, CheckBox, VerticalBox, StandardListView, HorizontalBox} from "std-widgets.slint";
export component Test {
    height: 250px;
    VerticalBox {
        StandardListView {
            model: [
                {text: "Item 1"},
                {text: "Item 2"},
                {text: "Item 3"},
            ];
        }
        HorizontalBox {
            Button {
                text: "Button 1";
            }
            Button {
                text: "Button 2";
            }
            Button {
                text: "Button 3";
            }
        }
        CheckBox {
            text: "A checkbox";
        }
    }
}
```

[Launch on SlintPad](https://slintpad.com/?snippet=%0Aimport+%7B+Button%2C+CheckBox%2C+VerticalBox%2C+StandardListView%2C+HorizontalBox%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Test+%7B%0A++++height%3A+250px%3B%0A++++VerticalBox+%7B%0A++++++++StandardListView+%7B%0A++++++++++++model%3A+%5B%0A++++++++++++++++%7Btext%3A+%22Item+1%22%7D%2C%0A++++++++++++++++%7Btext%3A+%22Item+2%22%7D%2C%0A++++++++++++++++%7Btext%3A+%22Item+3%22%7D%2C%0A++++++++++++%5D%3B%0A++++++++%7D%0A++++++++HorizontalBox+%7B%0A++++++++++++Button+%7B%0A++++++++++++++++text%3A+%22Button+1%22%3B%0A++++++++++++%7D%0A++++++++++++Button+%7B%0A++++++++++++++++text%3A+%22Button+2%22%3B%0A++++++++++++%7D%0A++++++++++++Button+%7B%0A++++++++++++++++text%3A+%22Button+3%22%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++++++CheckBox+%7B%0A++++++++++++text%3A+%22A+checkbox%22%3B%0A++++++++%7D%0A++++%7D%0A%7D%0A)

Platform: KDE, Linux, X11

**Comment by FloVanGH** [comment]
@FireFragment thank you very much for your report. That's true at the moment a visual focus state for the `StandardListView` is missing.

**Comment by FloVanGH** [comment]
Behavior regarding to the design specifications:

### Fluent (Windows winui)

On fluent on a focused `ListView` the first item got a focus border. The border can be moved down by array down and up by arrow down. To change selection you have to press enter on the focused `ListView`.

### Cupertino (macOS)

There is no dedicated visual representation of a focused `ListView`. Behavior on a focused `ListView` is arrow down, selects the next item, arrow up selects previous item.  

### Material (Android)

On material `ListView` does not have a focus state, instead by press `tab` the next item in the list is focused. On enter the item got selected.

**Comment by FloVanGH** [comment]
I would like to implement the fluent focus behavior for all styles to have a common behavior. But I have one problem if the `ListView` got focus the focus should be set on the first item and the `ListView` should scroll to it if it is not visible. But for this I need to detect when the `ListView` got focus, for this I would need something like a  `on-got-focus` event / callback or a property change handler for `has-focus` #112.
