### ISSUE TITLE
LSP Previewer UI Todos

### ISSUE THREAD

**Issue by hunger** [slint-ui/slint#3558]
## MVP in feature/lsp_preview_ui

* [x] Fix codespaces again... They do not use the WASM preview.
* [x] Decide on the features we want for this: Maybe use `preview-api`? The description matches nicely :-)
* [x] Make the UI takes the entire available space in WASM mode and have a OK size in native mode.
* [x] Do not panic when ask_editor_to_show_document errors out
* [x] Test that images work properly for every possible combination of LSP and Previewer
  * [x] Fix URL mapping?
* [x] Test to make sure slintpad still works :-)
* [x] Test the native LSP use case in VIM to make sure this does not try to talk to non-existing WASM Previewers which might confuse editors.
* [x] when you close vscode, the LSP no longer quit and the preview window stay visible
* [x] "Restart server" in vscode no longer works

## In general

* [x] Add a background of the right color behind the ComponentContainer
  * [x] Use the styles expected background color when displaying a window (#3117)
  * [ ] Show the checkerboard when displaying a random component
* [x] Add a style dropdown into the preview UI
* [x] Allow changing the size of the preview area (by mouse;-)
* [x] Allow setting icon and window title for windows
* [x] Make the UI pretty(er)
* [x] Figure out why the Qt backend fails to bring up the native UI the second time round

**Comment by ogoffart** [comment]
> Add a background of the right color behind the ComponentContainer

This is https://github.com/slint-ui/slint/issues/3117 : the Window doesn't print its own background when used as a child.
To fix it we could either:
 * ask the compiler to add a Rectangle with the background when use as a child. (But in the case of the ComponentContainer it's not used as a child, so we need an option to the compiler to make it do that anyway)
 * Have the WindowItem actually render a rectangle in its render function. And let the renderer actually skip the root item when rendering (we don't want to do double rendering of the background of the window)

> Allow changing the size of the preview area (by mouse;-)

If you want inspiration for Sub window in slint code, have a look at the fancy_demo

https://slintpad.com/preview?load_url=https://raw.githubusercontent.com/slint-ui/slint/master/examples/fancy_demo/main.slint
