### ISSUE TITLE
Error layout on macOS14

### ISSUE THREAD

**Issue by LeeeSe** [slint-ui/slint#3579]
https://github.com/slint-ui/slint/assets/44465325/33bfcdb3-d013-4876-951a-fff0056a10a5

**Comment by LeeeSe** [comment]
#3484

**Comment by ogoffart** [comment]
Thanks for the bug report.
Maybe this is releated to the winit sizing issue?  Can you try once more with Slint 1.2.2 ?

**Comment by LeeeSe** [comment]
I'm sorry I made that cheap mistake.
