### ISSUE TITLE
[ComboBox] setting index to -1 does not clear ComboBox text

### ISSUE THREAD

**Issue by marcothaller** [slint-ui/slint#3628]
Changing a ComboBox's index changes the text shown in the widget.
In case current-index is set to -1...
... expected behavior: current-text is reset.
... actual behavior: current-text remains unchanged

Example to reproduce issue:
https://slintpad.com/?snippet=import+%7B+Button%2C+VerticalBox+%2C+ComboBox%2C+SpinBox%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Demo+%7B%0A++++VerticalBox+%7B%0A++++++++Text+%7B%0A++++++++++++text%3A+%22SpinBox+value+%27-1%27+does+not+reset+ComboBox+text.%22%3B%0A++++++++++++font-size%3A+24px%3B%0A++++++++++++horizontal-alignment%3A+center%3B%0A++++++++%7D%0A++++++++combo-box+%3A%3D+ComboBox+%7B%0A++++++++++++model%3A+%5B%22Zero%22%2C%22One%22%2C%22Two%22%5D%3B%0A++++++++%7D%0A++++++++SpinBox+%7B%0A++++++++++++minimum%3A+-1%3B%0A++++++++++++maximum%3A+combo-box.model.length+-+1%3B%0A++++++++++++edited+%3D%3E+%7B%0A++++++++++++++++combo-box.current-index+%3D+self.value%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A

**Comment by FloVanGH** [comment]
Needs #112
