### ISSUE TITLE
Is it possible for slint to automatically switch the background color when switching between darkmode and lightmode?

### ISSUE THREAD

**Issue by LeeeSe** [slint-ui/slint#3649]
I'm writing a hover window for my app, in order to use slint to achieve buttomless effect (no-frame removes the window border completely, window rounded corners disappear), I have to customize the transparent background, but the consequence of this is that when switching between darkmode and lightmode, the background color can't be switched automatically like slint default style. Is there some way I can switch the background color automatically? I tried to explore the slint documentation, but no luck.
![CleanShot 2023-10-11 at 17 53 08](https://github.com/slint-ui/slint/assets/44465325/1ca49de5-aa8d-4bfd-b630-158d2046d0d4)

**Comment by FloVanGH** [comment]
Hello,

in line 13 you can do:

```slint
background: StyleMetrics.dark-color-scheme ? black : white;
```

You need to import StyleMetrics

```slint
import { StyleMetrics } from "std-widgets.slint";
```

**Comment by LeeeSe** [comment]
Thanks for the quick reply, it's working now, sorry to bother you guys with such a simple question, I'm really enjoying writing GUIs with slint!

**Comment by FloVanGH** [comment]
No problem, I am glad that I was able to help 🙂. Nice to hear, thank you.
