### ISSUE TITLE
C++ interpreter cross-compilation from 64-bit host to 32-bit target broken

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#3653]
Cross-compiling with cmake on 64-bit host to 32-bit target and enabling the interpreter breaks the build complaining that `ValueOpaque` is missing.

The generated `slint_interpreter_internal.h` is indeed missing the 32-bit variant:

```cpp
#if defined(SLINT_TARGET_64)
struct ValueOpaque {
    uintptr_t _0[7];
};
#endif

```

In `ffi.rs` this is how it is declared:

```rust
#[repr(C)]
#[cfg(target_pointer_width = "64")]
pub struct ValueOpaque([usize; 7]);
#[repr(C)]
#[cfg(target_pointer_width = "32")]
#[repr(align(8))]
pub struct ValueOpaque([usize; 9]);
/// Asserts that ValueOpaque is as large as Value and has the same alignment, to make transmute safe.
const _: [(); std::mem::size_of::<ValueOpaque>()] = [(); std::mem::size_of::<Value>()];
const _: [(); std::mem::align_of::<ValueOpaque>()] = [(); std::mem::align_of::<Value>()];
```

cbindgen is configured to emit based on the `target_pointer_width`, which works for many types we emit. But somehow the `#[repr(align(8))]` breaks that. If I remove it (and comment out the assertion), then the generated header file is correct.

**Comment by ogoffart** [comment]
I'm thinking we should put C++ Value on the heap.
The current situation is hard to maintain and may even depend on the rust version or something.

**Comment by tronical** [comment]
Sounds good to me. Thanks for the suggestion .
