### ISSUE TITLE
Property reference for x position doesn't work if the referenced component has an opacity value set

### ISSUE THREAD

**Issue by FoundationKen** [slint-ui/slint#3699]
If you have the `x` value of the second text component below set to use the same position as the `text1`, it doesn't work if the `opacity` property is set to a specific value.

If you omit the `opacity` property from `text1`(comment it out below), then the `x` property is set in the second text component as expected.

```
export component Demo {
    width: 200px;
    height: 100px;

    text1 := Text {
        x: 20px;
        y: 15px;
        text: "Hello 1";
        font-size: 24px;
        opacity: 1;   // Comment out this line and the code works
    }
    Text {
        x: text1.x;   // Make the x values the same
        y: 60px;
        text: "Hello 2";
        font-size: 24px;
    }
}
```

(SlintPad demo: https://tinyurl.com/4h2cta34)

**Comment by ogoffart** [comment]
Thanks for the bug report!

This is actually an already known issue: #1072
I'm closing this as a duplicate, but thanks for the report anyway.

Now that we have refactored the compiler to dissociate the item geometry from their node, it should be possible to fix that.
