### ISSUE TITLE
ListView model shows invalid - outdated items, after replacing entire model

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#3711]
1.3.0 - https://github.com/slint-ui/slint/tree/olivier/fix-3700

After removing items from listview(done via replacing entire model), I still see old items state.

Steps to reproduce:
- select some items
- delete them via delete button - internally this will filter non selected items and create new model only from selected(checked) items
- see that checkboxes are still selected
- scroll a little to hide elements and show them again
- see that checkboxes are not selected

[czkawka_slint_gui.zip](https://github.com/slint-ui/slint/files/13047118/czkawka_slint_gui.zip)

https://github.com/slint-ui/slint/assets/41945903/4e59d69f-53a3-4602-9f1e-d60365778052

**Comment by ogoffart** [comment]
Thanks for your bug report.
This is  https://github.com/slint-ui/slint/issues/2598 , so i'm closing it as duplicated. (but thanks anyway for reporting)
