### ISSUE TITLE
Create a repo and/or website to keep widgets built by other

### ISSUE THREAD

**Issue by sudipghimire533** [slint-ui/slint#372]
Sixtyfps is cool. It would be more nice If we have a repo or a website containing reusable component and widgets which can be simply copied/downloaded and used in new project.

**Comment by ogoffart** [comment]
We can have contribution in this repository.
If someone want to publish their widget or component in a different repository, they can also do that and we'll hapily link to them

**Comment by sudipghimire533** [comment]
I meant to have a central place where anyone with reusable individual component can publish their `.60` ui

**Comment by ogoffart** [comment]
Similar to https://github.com/slint-ui/slint/issues/154
We should add links to 3rd party component library from our documentation.
