### ISSUE TITLE
Values are not properly set, when listview is not at beginning  

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#3740]
From issue https://github.com/slint-ui/slint/issues/2598#issuecomment-1773863372 - looks that this is different problem

Tested on latest 1.3.0 branch with applied 78d273e59956a6df2642ebb501a3d9465d7e035d(this fixed problem with invalid internal state btw)

When using [slintpad link](https://slint.dev/releases/1.2.2/editor/?snippet=import+%7B+Button%2C+VerticalBox+%2C+HorizontalBox%2C+TabWidget%2C+ListView%2C+StandardListView%2C+StandardTableView%2C+CheckBox%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+SelectableTableView+inherits+Rectangle+%7B%0A++++in+property+%3C%5Bstring%5D%3E+columns%3B%0A++++in-out+property+%3C%5B%7Bchecked%3A+bool%2C+header_row%3A+bool%2C+selected_row%3A+bool%2C+val%3A%5Bstring%5D%7D%5D%3E+values%3B%0A%0A++++private+property+%3C%5Blength%5D%3E+column_sizes%3A+%5B30px%2C+100px%2C+100px%2C+100px%5D%3B%0A++++private+property+%3Cint%3E+column_number%3A+4%3B%0A%0A++++in-out+property+%3Cint%3E+selected_item%3A+-1%3B%0A%0A++++VerticalBox+%7B%0A++++++++padding%3A+5px%3B%0A++++++++list_view+%3A%3D+ListView+%7B%0A++++++++++++min-width%3A+100px%3B%0A++++++++++++for+r%5Bidx%5D+in+root.values+%3A+Rectangle+%7B%0A++++++++++++++++height%3A+30px%3B%0A++++++++++++++++background%3A+r.header-row+%3F+%23888888+%3A+%28touch-area.has-hover+%3F+%28r.selected_row+%3F+%23cccccc+%3A+%23dddddd%29+%3A+%28r.selected_row+%3F+%23cccccc%3A+%23dddddd%29%29%3B%0A++++++++++++++++%2F%2F+background%3A+touch-area.has-hover+%3F+%28selected+%3F+%23333333+%3A+%23222222%29+%3A+%28selected+%3F+%23333333%3A+%23222222%29%3B%0A%0A++++++++++++++++touch_area%3A%3D+TouchArea+%7B%0A++++++++++++++++++++clicked+%3D%3E+%7B%0A++++++++++++++++++++++++debug%28%22Selected-id%22%2C+root.selected-item%2C%22+----+current+item+%22%2C+idx%2C+%22+----+was+row+selected%22%2C+r.selected-row%29%3B%0A++++++++++++++++++++++++if+%28%21r.header_row%29+%7B%0A++++++++++++++++++++++++++++debug%28%22Selection+is+reversed+for+current+row+because+is+not+header+row%22%29%3B%0A++++++++++++++++++++++++++++r.selected_row+%3D+%21r.selected_row%3B%0A++++++++++++++++++++++++++++debug%28%22Current+row+value+-+should+be+reversed+than+at+beginning%22%2C+r.selected_row%29%3B%0A++++++++++++++++++++++++++++if+%28root.selected-item+%3D%3D+-1%29+%7B%0A++++++++++++++++++++++++++++++++debug%28%22Nothing+is+selected+-+selected-id+%22%2B+root.selected-item%29%3B%0A++++++++++++++++++++++++++++++++root.selected-item+%3D+idx%3B%0A++++++++++++++++++++++++++++++++debug%28%22After+selecting+-+selected-id+%22%2B+root.selected-item%29%3B%0A++++++++++++++++++++++++++++%7D+else+%7B%0A++++++++++++++++++++++++++++++++if+%28r.selected_row+%3D%3D+true%29+%7B%0A++++++++++++++++++++++++++++++++++++debug%28%22Item+is+already+selected%2C+previous+id+%22%2C+root.selected-item%2C+%22was+selected%3F+%28should+be%29+-%22%2C+root.values%5Broot.selected-item%5D.selected_row%29%3B%0A++++++++++++++++++++++++++++++++++++root.values%5Broot.selected-item%5D.selected_row+%3D+false%3B%0A++++++++++++++++++++++++++++++++++++debug%28%22Deselected+item+%22%2C+root.selected-item%2C+%22is+selected%3F+%28should+not+be%29+-%22%2C+root.values%5Broot.selected-item%5D.selected_row%29%3B%0A++++++++++++++++++++++++++++++++++++root.selected-item+%3D+idx%3B%0A++++++++++++++++++++++++++++++++++++debug%28%22Current+selected+item%22%2C+root.selected-item%29%3B%0A++++++++++++++++++++++++++++++++%7D+else+%7B%0A++++++++++++++++++++++++++++++++++++debug%28%22Was+selected+%22%2C+root.selected-item%2C+%22so+deselecting+it%22%29%3B%0A++++++++++++++++++++++++++++++++++++root.selected-item+%3D+-1%3B%0A++++++++++++++++++++++++++++++++++++debug%28%22Was+selected%2C+and+now+is+not+selected+%22%2C+root.selected-item%29%3B%0A++++++++++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++debug%28%22%22%29%3B%0A++++++++++++++++++++++++debug%28%22%22%29%3B%0A++++++++++++++++++++%7D%0A++++++++++++++++%7D%0A%0A++++++++++++++++HorizontalLayout+%7B%0A++++++++++++++++++++padding%3A+5px%3B%0A++++++++++++++++++++spacing%3A+5px%3B%0A++++++++++++++++++++%2F%2Fwidth%3A+root.column_sizes%5Bidx%5D%3B%0A%0A++++++++++++++++++++CheckBox+%7B%0A++++++++++++++++++++++++%2F%2Fmin-width%3A+200px%3B%0A++++++++++++++++++++++++visible%3A+%21r.header-row%3B%0A++++++++++++++++++++++++checked%3A+r.checked+%26%26+%21r.header-row%3B%0A++++++++++++++++++++++++width%3A+root.column-sizes%5B0%5D%3B%0A++++++++++++++++++++++++toggled+%3D%3E+%7B%0A++++++++++++++++++++++++++++r.checked+%3D+self.checked%3B%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++%2F%2F+preferred-width%3A+root.column-sizes%5B0%5D%3B%0A++++++++++++++++++++%7D%0A%0A++++++++++++++++++++HorizontalLayout+%7B%0A++++++++++++++++++++++++spacing%3A+5px%3B%0A++++++++++++++++++++++++for+f%5Bidx%5D+in+r.val+%3A+Text+%7B%0A++++++++++++++++++++++++++++width%3A+root.column-sizes%5Bidx+%2B+1%5D%3B%0A++++++++++++++++++++++++++++text%3A+f%3B%0A++++++++++++++++++++++++++++font-size%3A+12px%3B%0A%0A++++++++++++++++++++++++++++vertical-alignment%3A+center%3B%0A%0A++++++++++++++++++++++++++++overflow%3A+elide%3B%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++%7D%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A%0Aexport+component+MainWindow+inherits+Window+%7B%0A++++in-out+property+%3C%5B%7Bchecked%3A+bool%2C+header_row%3A+bool%2C+selected_row%3A+bool%2C+val%3A%5Bstring%5D%7D%5D%3E+empty_folder_model%3A+%5B%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+true%2C+val%3A+%5B%22kropkarz%22%2C+%22%2FXd1%22%2C+%2224.10.2023%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+false%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22witasphere%22%2C+%22%2FXd1%2FImagerren2%22%2C+%2225.11.1991%22%5D%7D+%2C%0A++++++++%7Bchecked%3A+true%2C+selected_row%3A+false%2C+header_row%3A+false%2C+val%3A+%5B%22lokkaler%22%2C+%22%2FXd1%2FVide2%22%2C+%2201.23.1911%22%5D%7D%0A++++%5D%3B%0A%0A++++min-width%3A+200px%3B%0A++++VerticalBox+%7B%0A++++++++HorizontalBox+%7B%0A++++++++++++%2F%2F+min-width%3A+600px%3B%0A++++++++++++preferred-height%3A+300px%3B%0A%0A++++++++++++SelectableTableView+%7B%0A++++++++++++++++min-width%3A+200px%3B%0A%0A++++++++++++++++columns%3A+%5B%22Selection%22%2C+%22Folder+Name%22%2C+%22Path%22%2C+%22Modification+Date%22%5D%3B%0A++++++++++++++++values+%3C%3D%3E+empty-folder-model%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D) or 
[slint-rust-template.zip](https://github.com/slint-ui/slint/files/13072747/slint-rust-template.zip)

selecting and deselecting elements when listview is not scrolled works fine, but start to break when items are scrolled

https://github.com/slint-ui/slint/assets/41945903/ff0c6fcb-6232-4a0d-bb45-22548cd139ca

At video:
- first time without scrolling
- selecting 4,5 element
- in debug logs is visible that item was not selected and after clikcing `r.selected_row = !r.selected_row`  properly converted `r.selected_row = false` into `r.selected_row = true`

- second time with scrolling
- selecting 4,5 element
- in debug logs is visible that item was not selected and after clikcing `r.selected_row = !r.selected_row`  shows that `r.selected_row = false`not changed value to true, but should

**Comment by ogoffart** [comment]
Thanks for the bug report. 
I can reproduce the problem:  The ListView track the model data at the wrong index when scrolled.
