### ISSUE TITLE
Support icon fonts as collections of images

### ISSUE THREAD

**Issue by hunger** [slint-ui/slint#3773]
We should have convenient support for icon fonts, treating them as a collection of (SVG) images.

A nice way to handle icon fonts would be something along the lines of:

```slint
Button {
    icon: @font("NAME", \u3242);
}
```

where @font would return some image/svg/etc. based on glyph \u3242 in font NAME that renders in the current foreground test color if available.

@font would need to return an image type (SVG only? TTF fonts can embed those). The compiler can do the hard work of extracting that data and maybe embed the SVG data into the binary. If no "foreground text color" we can default to some color and have the user adapt that using the existing image API.

The benefit is that we treat icon fonts as collection of images, that can get used wherever images are required.

In a second step, we could generate sets of constants using scripts from the icon font data provided by different vendors. These would wrap the [`@font("MaterialSymbolsOutline", 0xe3b8)`](https://fonts.google.com/icons?icon.query=colorize&query=icon) in a more convenient form, which could look like: E.g. `@material-colorize` or maybe `Material.colorize`.

**Comment by ogoffart** [comment]
Font icons is really useful on the web because you can use text everywhere and use font tags or css. But it's hard to support in Slint. I'm afraid if you want to use images from a font collection you would first need to export the icons into svg assets and then use that.
