### ISSUE TITLE
Feature Request: Add more easing formulas

### ISSUE THREAD

**Issue by FoundationKen** [slint-ui/slint#3783]
There are many additional "standard" easings that would be good to add:

  https://easings.net/

In particular, I think easeOutElastic would be a great one to add, so if there are reasons not to add them all, that's the one I think is the best to focus on:

  https://easings.net/#easeOutElastic

I'd be up to put together a PR on this if it's something you'd help review and accept.

Let me know!

**Comment by ogoffart** [comment]
Thanks for the report.
More easing formula is tracked in #3783.
(Closing this issue as duplicate)

> I'd be up to put together a PR on this if it's something you'd help review and accept.

That'd be awesome.

**Comment by ogoffart** [comment]
I meant #2665
