### ISSUE TITLE
Add support for tiled images

### ISSUE THREAD

**Issue by FoundationKen** [slint-ui/slint#3784]
It would be useful for images to be able to tile (repeat) to create large background from small image tiles.  There could be the following repeat options.

- Horizontally / x
- Vertically / y
- Both horizontally & vertically / x-y
- No repeat (default)

In addition, this type of feature usually also has an x and y offset to let you position the background.

The repeat setting could be implemented as an `image-fit` mode:

```
Image {
    source: @image-url("mytile.svg");
    image-fit: repeat-x;   // or repeat-y or repeat-xy
    repeat-offset-x: 5px;
    repeat-offset-y: 10px;
}
```

Alternatively, the CSS-like way might be to put the repeat on a `Rectangle` (sort of like a div):

```
Rectangle {
    background-image: @image-url("mytile.svg");
    background-repeat: repeat-x;   // or repeat-y, repeat-xy, repeat-none (default)
    background-position-x: 5px;
    background-repeat-position-y: 10px;
}
```

**Comment by ogoffart** [comment]
Comparison with other APIs:

Web: https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat
The `background-repeat` for each direction, the background can either be not repeated, repeated, "round" or "space". IT also play with the packground-position property to set an offset. The image can also be scaled with background-size

QML: https://doc.qt.io/qt-6/qml-qtquick-image.html#fillMode-prop
It supports fillMode with `Tile`, `TileHorizontally`, `TileVertically`. In addition one can also set the horizontalAlignment and verticalAlignment property to change the position. (arbitrary pixel position or scaling would need to apply a transform and clip). 

Flutter: https://api.flutter.dev/flutter/widgets/Image-class.html / https://api.flutter.dev/flutter/painting/ImageRepeat.html
An image can be repeated on each direction. One can also give it an AlignmentGeometry which support pixel alignment in different direction. Image can also be scaled.
The Flutter Image  also has a centerSlice for the 9 patch

**Comment by ogoffart** [comment]
We discussed this issue with @tronical and decided to implement the following API:

Add the following enums:

```
enum ImageTiling { 
   none,
   repeat,
   round,
   // space   // can be added later.
}

enum ImageHorizontalAlignment {  center, left, right, start, end }
enum ImageVerticalAlignment { center, top, bottom }

// Add preserve to image fit as an equivalent to css's object-fit: none.
enum ImageFit {
    fill, contains, cover,  // existing ones
    preserve, // add 
}

```

Add the following property to Image:

```
     in property <HorizontalAlignment> horizontal-alignment;
     in property <VerticalAlignment> vertical-alignment; 
     in property <ImageTiling> horizontal-tiling;
     in property <ImageTiling> vertical-tiling;
     // sets both horizontal-tiling and vertical-tiling at the same time.
     in property <ImageTiling> tiling; 
```

Our enum are all equivalent to the CSS background-repeat and image-fit property.
the alignment is kind of similar to background-position, but doesn't allow for explicit number value. (if one really need that, one can clip the image, i guess).


We also change the default value of image fit which is currently "contain" in layout and "fit" otherwise  to be "preserve" if the tiling property is set.
