### ISSUE TITLE
Error rendering SVG: SVG has an invalid size

### ISSUE THREAD

**Issue by d3im** [slint-ui/slint#3790]
I used Slint v 1.2.2 with Rust.
I included SVGs (200x200px) on some buttons.
On Windows and Gentoo Linux (X.org) it's OK.
On one PC with Gentoo Linux I get this message (no SVG icon is rendered):
**Error rendering SVG: SVG has an invalid size**
I think the only difference could be modified DPI of X.org but this is only PC where Slint application doesn't work well.
Thanks for help in advance.

**Comment by tronical** [comment]
Could you attach one of those SVGs in this issue, please? Then we can try to reproduce it.

**Comment by d3im** [comment]
yes, there:
![ok](https://github.com/slint-ui/slint/assets/17542229/bd8a419e-5d53-43fb-9d66-757378a915a9)

**Comment by d3im** [comment]
correction of issue: it's 256x256px (but it should not make difference for vector graphics ;-) )

**Comment by qarmin** [comment]
I have same error, even without using any svg, but only when using `SLINT_SCALE_FACTOR=0.1`

Project - [slint-rust-template.zip](https://github.com/slint-ui/slint/files/13203797/slint-rust-template.zip)


https://github.com/slint-ui/slint/assets/41945903/185b0075-04b9-4706-8b42-de70b42ac541

**Comment by d3im** [comment]
SLINT_SCALE_FACTOR=0.01 results in the same error in my application also

**Comment by ogoffart** [comment]
What backend and renderer are you using.
Maybe it is a problem if the size at which we are rendering the SVG reaches 0

**Comment by d3im** [comment]
How can be backend and renderer determined? I have installed both GTK and QT5.
Tried on affected PC several SLINT_SCALE_FACTOR but it wrote the same error message each time.

**Comment by ogoffart** [comment]
I can reproduce the problem with the printerdemo:

```
SLINT_BACKEND=winit SLINT_SCALE_FACTOR=0.01 cargo run -p printerdemo
```
