### ISSUE TITLE
Wayland warning: `destroyed while proxies still attached:`

### ISSUE THREAD

**Issue by flukejones** [slint-ui/slint#3794]
```
warning: queue 0x7f8558000d00 destroyed while proxies still attached:
  wl_data_offer@4278190081 still attached
  wl_data_device@21 still attached
  wl_seat@20 still attached
  wl_data_device_manager@19 still attached
  wl_registry@17 still attached
```

I'm not sure where exactly to file this bug sorry. Maybe in winit? In either case, SDL2 solves the warnings with [this](https://github.com/libsdl-org/SDL/commit/132b88749c284e4d51d93f1e08f5bb0ff9d705dc) commit.

**Comment by ogoffart** [comment]
Thanks for the report.

This was already reported in https://github.com/slint-ui/slint/issues/2728 and i'm closing this as a duplicated.
Even though #2728  is already closed, as mentioned in the last comment, i do not believe there is much we can do about it.
If anything it would be in winit or event more upstream deps ( https://github.com/rust-windowing/winit/issues/2761 )
