### ISSUE TITLE
Feature Request: Add callbacks when a component becomes focused or unfocused

### ISSUE THREAD

**Issue by FoundationKen** [slint-ui/slint#3798]
It would be useful to be able to specify a callback function whenever a component becomes focused or unfocused.

My particular use case is that when an edit component is focused, I want to slide the keyboard up from the bottom of the screen, but the keyboard is a system view, not part of the same Slint application.  Similarly, when the edit loses focus, the keyboard should close.

**Comment by ogoffart** [comment]
Seems quite similar to https://github.com/slint-ui/slint/discussions/3767
What backend are you using?

**Comment by FoundationKen** [comment]
Sorry...didn't realize eupn had also posted!  We can close this one.
