### ISSUE TITLE
cannot find -lQt5Core: No such file or directory

### ISSUE THREAD

**Issue by swanv** [slint-ui/slint#3802]
when run `cargo build`  on windows 11 , there was error!

= note: D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Core: No such file or directory
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Gui: No such file or directory
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5Widgets: No such file or directory
          collect2.exe: error: ld returned 1 exit status

**Comment by ogoffart** [comment]
The qmake spac says `QMAKE_SPEC:win32-msvc` which is MSVC.
But it seems the linker used is from mingw.
What is the rust target you're using?  
Is it x86_64-pc-windows-gnu or x86_64-pc-windows-msvc ?

**Comment by swanv** [comment]
I use the x86_64-pc-windows-gnu

**Comment by ogoffart** [comment]
With the new release of qttypes that contains https://github.com/woboq/qmetaobject-rs/pull/304 , the incompatibility will be detected and the qt backend not build
