### ISSUE TITLE
ListView uses strange internal margins for scrollbar

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#3830]
Slint 1.2.2, 1.3.0 - master branch

[CODE](https://slint.dev/releases/1.2.2/editor/?snippet=import+%7B+Button%2C+VerticalBox+%2C+ListView%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Demo+%7B%0A++++width%3A+500px%3B%0A++++height%3A+300px%3B%0A++++in-out+property+%3C%5Bstring%5D%3E+values%3A+%5B%22AA%22%2C+%22BB%22%2C+%22CC%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%2C+%22DD%22%5D%3B%0A%0A++++Rectangle+%7B%0A++++++++width%3A+root.width%3B%0A++++++++height%3A+root.height%3B%0A++++++++background%3A+red%3B%0A++++%7D%0A++++list_view+%3A%3D+ListView+%7B%0A++++++++width%3A+parent.width%3B%0A++++++++padding-bottom%3A+0px%3B%0A++++%0A++++++++%0A++++++++for+r%5Bidx%5D+in+root.values+%3A+Rectangle+%7B%0A++++++++++++border-radius%3A+5px%3B%0A++++++++++++height%3A+20px%3B%0A++++++++++++background%3A+green%3B%0A%0A++++++++++++Text+%7B%0A++++++++++++++++text%3A+r%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A++++%0A%7D%0A)

Gtk - as you can see, scrollbar is visible on data - there is no special margin for scroll-bar

![Screenshot from 2023-11-01 21-15-52](https://github.com/slint-ui/slint/assets/41945903/8e81d48a-65ac-4a69-bf5e-50a770aa952b)
![Screenshot from 2023-11-01 21-16-02](https://github.com/slint-ui/slint/assets/41945903/bbc5b9f0-6709-4c5e-b865-f34de45406e2)

Slint - strange margin, that cannot be removed
![Screenshot from 2023-11-01 21-13-23](https://github.com/slint-ui/slint/assets/41945903/9ea9336a-fafd-45c7-b753-0c3e7941b927)
![Screenshot from 2023-11-01 21-17-12](https://github.com/slint-ui/slint/assets/41945903/15dd9b21-244e-4ec6-9d1f-31df7d2838d4)

**Comment by qarmin** [comment]
I "fixed" it with such changes:

![Screenshot from 2023-11-06 16-57-24](https://github.com/slint-ui/slint/assets/41945903/39a144a6-7aaa-40ca-97a0-3d3178f3c605)

the problematic is that I cannot use slint with such changes - i don't want to use custom slint build, because I want to publish app on crates.io

So problematic are two things here:
- A lot of properties are internal - I wanted to copy widget code that use Icons and Palette widget, but I found that this two are not exported, so I need to manually implement them 
- General widgets like ListView are not customizable - adding option like `show_scrollbar_on_data` or `internal_margin` would help a lot when customizing widgets

**Comment by FloVanGH** [comment]
Hi,

thank you for your report. I will investigate this issue and check what solution we can provide here.

**Comment by FloVanGH** [comment]
I have done an PR to fixes the issue.
