### ISSUE TITLE
SlintPad: Hello World does not combine well with dark mode

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#3853]
In dark mode, slintpad's preview the hello world is "hard to see":

1. It's hard to see where the example preview's bounds
2. The slint logo's text is unreadable

<img width="907" alt="Screenshot 2023-11-06 at 09 31 15" src="https://github.com/slint-ui/slint/assets/1486/9f7713da-9fc7-42af-90a6-f89abe12f928">

**Comment by tronical** [comment]
1. Maybe that's a bug? The layout suggests a maximum size, so why is sized different than in https://slint.dev/releases/1.2.2/editor/ ?

**Comment by tronical** [comment]
Briefly discussed with Tobias: The preview follows the size of the canvas as that's what we discussed should happen and also happens on desktop with the vs code extension and a separate preview window.

**Comment by ogoffart** [comment]
maybe use a logo with a background?
