### ISSUE TITLE
Some dependencies crates could be updated 

### ISSUE THREAD

**Issue by Guiguiprim** [slint-ui/slint#3922]
In `slint 1.3.0` some dependencies are duplicated as some of them could be updated:

- `cocoa 0.24.1`  (`0.25.0` tracked from `softbuffer`)
- `femtovg 0.7.1` (`0.8.0` is available, this cause `lru` duplication)
- `fontdb 0.14.1` (`0.16.0` is available, this cause `memmap2` duplication)

**Comment by FloVanGH** [comment]
Hi and thank you!

**Comment by tronical** [comment]
I've updated those dependencies. The next big wave will be raw-window-handle 0.6 related. softbuffer has caught up, and I guess glutin will have to be next.
