### ISSUE TITLE
mouse-cursor doesn't work anymore in slint-viewer 1.3.0

### ISSUE THREAD

**Issue by Guiguiprim** [slint-ui/slint#3928]
Following the release of slint `1.3.0` I updated `slint-viewer` (with `cargo install -f slint-viewer`), since then `mouse-cursor: pointer` is not respected when using it.

**Comment by ogoffart** [comment]
I cannot reproduce the problem: it works form me on Linux/X11 with all backend.
What platform / backed are you using?  Is it also failing with the rust-based app?

**Comment by Guiguiprim** [comment]
My app is working as expected when build for Windows.

I have the issue on `Linux mint` with `X11`, I haven't set ab backend so the default one.

**Comment by ogoffart** [comment]
I can open this file with the viewer just fine on X11 and the cursor shows the correct cursor (the hand with a finger)

```slint
export component W {
    TouchArea {
        mouse-cursor: pointer;
    }
}
```

**Comment by Guiguiprim** [comment]
I tested on `1.3.0` tag I have the bug with our minimal case. But on master (commit: `cc3691524`) I do not have the bug. So fixed somehow.

**Comment by ogoffart** [comment]
I cannot reproduce the problem with either the tag nor master.
Perhaps this was a bug in a dependency? (but why wouldn't I see it?)

But without way to reproduce it, I'll close it if it is fixed for you.
