### ISSUE TITLE
LSP uses dashes even if property uses underscores

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#3935]
When creating and modifying slint files, I see that lsp always hint to use properties with style `property-name` instead `property_name.

![Screenshot from 2023-11-14 19-23-41](https://github.com/slint-ui/slint/assets/41945903/89b30f9c-47b1-4996-b011-c3d699a4803b)

Most programming languages do not allow to use dashes in names, so it is natural for me to use underscores everywhere.

Also rust bindings are using(probably are forced to use) _ everywhere.

I know that current solution was discussed and implemented in https://github.com/slint-ui/slint/issues/382, https://github.com/slint-ui/slint/pull/400, but I don't think that this is optimal.

For now properties in my code are mixed, so refactoring by replacing names of properties is harder, because I need to replace 2 names instead 1.

If defaults cannot not be changed, maybe will be good to add option to allow to choose user a style of names?
Or maybe auto completion should use same style like is in property defintion?

Slint-fmt should allow to unify style across codebase.

**Comment by ogoffart** [comment]
> maybe auto completion should use same style like is in property defintion?

I think this makes sense and we should do that.
