### ISSUE TITLE
Mouse cursor persists while cursor is not within the TouchArea

### ISSUE THREAD

**Issue by bkinman** [slint-ui/slint#4007]
Programming Language: Rust
Platform: Ubuntu 22.04
Slint Version: 1.3.0

It seems that when I set the `TouchArea` `mouse-cursor` property, the cursor persists even when my cursor is not in the TouchArea.

Below is my slint file. The mouse cursor is change is associated with the resize handle.

Please let me know if there is any more information I can provide, thanks!
```
export component MainWindow inherits Window {
    width: 500px;
    height: 500px;
    background: lightgray;
    Rectangle {
        width: 100px;
        height: 50px;
        background: darkgrey;
        border-width: 1px;
        border-color: black;
        border-radius: 10px;
        drop-shadow-blur: ta.has_hover ? 5px : 0px;
        drop-shadow-color: blue;
        drop-shadow-offset-x: 0;
        drop-shadow-offset-y: 0;

        l := VerticalLayout {
            padding: 5px;
            alignment: stretch;

            Text {
                text: "Block Name";
                horizontal-alignment: center;
                color: black;
            }

        ta := TouchArea {
            width: parent.width;
            height: parent.height;
            moved => {
                parent.x += self.mouse-x - self.pressed-x;
                parent.y += self.mouse-y - self.pressed-y;
            }
        }
        resize-handle := TouchArea {
            width: 15px;
            height: 15px;
            x: parent.width - self.width;
            y: parent.height - self.height;
            mouse-cursor: MouseCursor.crosshair;

            moved => {
                if (self.pressed) {
                    parent.width = parent.width + self.mouse-x - self.pressed-x;
                    parent.height = parent.height + self.mouse-y - self.pressed-y;
                }
            }

            Path {
                stroke-width: 2px;
                stroke: black;
                viewbox-height: 1.2; viewbox-width: 1.2;

                MoveTo { x: 0; y: 1; }
                LineTo { x: 1; y: 0; }
                MoveTo { x: 0.4; y: 1; }
                LineTo { x: 1; y: 0.4; }
                MoveTo { x: 0.8; y: 1; }
                LineTo { x: 1; y: 0.8; }
            }
        }
    }
}
```

**Comment by ogoffart** [comment]
Thanks for the bug report.

I pasted [your code there](https://slintpad.com/?snippet=export+component+MainWindow+inherits+Window+%7B%0A++++width%3A+500px%3B%0A++++height%3A+500px%3B%0A++++background%3A+lightgray%3B%0A++++Rectangle+%7B%0A++++++++width%3A+100px%3B%0A++++++++height%3A+50px%3B%0A++++++++background%3A+darkgrey%3B%0A++++++++border-width%3A+1px%3B%0A++++++++border-color%3A+black%3B%0A++++++++border-radius%3A+10px%3B%0A++++++++drop-shadow-blur%3A+ta.has_hover+%3F+5px+%3A+0px%3B%0A++++++++drop-shadow-color%3A+blue%3B%0A++++++++drop-shadow-offset-x%3A+0%3B%0A++++++++drop-shadow-offset-y%3A+0%3B%0A%0A++++++++l+%3A%3D+VerticalLayout+%7B%0A++++++++++++padding%3A+5px%3B%0A++++++++++++alignment%3A+stretch%3B%0A%0A++++++++++++Text+%7B%0A++++++++++++++++text%3A+%22Block+Name%22%3B%0A++++++++++++++++horizontal-alignment%3A+center%3B%0A++++++++++++++++color%3A+black%3B%0A++++++++++++%7D%0A++++++++%7D%0A%0A++++++++ta+%3A%3D+TouchArea+%7B%0A++++++++++++width%3A+parent.width%3B%0A++++++++++++height%3A+parent.height%3B%0A++++++++++++moved+%3D%3E+%7B%0A++++++++++++++++parent.x+%2B%3D+self.mouse-x+-+self.pressed-x%3B%0A++++++++++++++++parent.y+%2B%3D+self.mouse-y+-+self.pressed-y%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++++++resize-handle+%3A%3D+TouchArea+%7B%0A++++++++++++width%3A+15px%3B%0A++++++++++++height%3A+15px%3B%0A++++++++++++x%3A+parent.width+-+self.width%3B%0A++++++++++++y%3A+parent.height+-+self.height%3B%0A++++++++++++mouse-cursor%3A+MouseCursor.crosshair%3B%0A%0A++++++++++++moved+%3D%3E+%7B%0A++++++++++++++++if+%28self.pressed%29+%7B%0A++++++++++++++++++++parent.width+%3D+parent.width+%2B+self.mouse-x+-+self.pressed-x%3B%0A++++++++++++++++++++parent.height+%3D+parent.height+%2B+self.mouse-y+-+self.pressed-y%3B%0A++++++++++++++++%7D%0A++++++++++++%7D%0A%0A++++++++++++Path+%7B%0A++++++++++++++++stroke-width%3A+2px%3B%0A++++++++++++++++stroke%3A+black%3B%0A++++++++++++++++viewbox-height%3A+1.2%3B+viewbox-width%3A+1.2%3B%0A%0A++++++++++++++++MoveTo+%7B+x%3A+0%3B+y%3A+1%3B+%7D%0A++++++++++++++++LineTo+%7B+x%3A+1%3B+y%3A+0%3B+%7D%0A++++++++++++++++MoveTo+%7B+x%3A+0.4%3B+y%3A+1%3B+%7D%0A++++++++++++++++LineTo+%7B+x%3A+1%3B+y%3A+0.4%3B+%7D%0A++++++++++++++++MoveTo+%7B+x%3A+0.8%3B+y%3A+1%3B+%7D%0A++++++++++++++++LineTo+%7B+x%3A+1%3B+y%3A+0.8%3B+%7D%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A%0A)  (had to add a missing `}` ) 
But i can't reproduce the problem.  The crosshair is visible only on the mouse area. (unless the mouse is grabbed)
Could you describe how to reproduce?

**Comment by ogoffart** [comment]
Has anyone been able to reproduce it?

**Comment by ogoffart** [comment]
Cannot reproduce.
Please reopen with more info if you can reproduce.
