### ISSUE TITLE
VerticalLayout do not update scrollbar/scroll offset when resizing window

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#4023]
Slint 1.3.0

[CODE](https://slint.dev/releases/1.3.0/editor/?snippet=import+%7B+AboutSlint%2C+Button%2C+VerticalBox+%2C+ListView%2C+ScrollView%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Demo+%7B%0A++++in-out+property+%3Clength%3E+h%3A+120px%3B%0A++++VerticalLayout+%7B%0A++++++++ScrollView+%7B%0A++++++++++++VerticalLayout+%7B%0A++++++++++++++++Rectangle+%7B%0A++++++++++++++++++++height%3A+root.h%3B%0A++++++++++++++++++++background%3A+red%3B%0A++++++++++++++++%7D%0A++++++++++++++++Rectangle+%7B%0A++++++++++++++++++++height%3A+root.h%3B%0A++++++++++++++++++++background%3A+blue%3B%0A++++++++++++++++%7D%0A++++++++++++++++Rectangle+%7B%0A++++++++++++++++++++height%3A+root.h%3B%0A++++++++++++++++++++background%3A+black%3B%0A++++++++++++++++%7D%0A++++++++++++++++Rectangle+%7B%0A++++++++++++++++++++height%3A+root.h%3B%0A++++++++++++++++++++background%3A+green%3B%0A++++++++++++++++%7D%0A++++++++++++++++Rectangle+%7B%0A++++++++++++++++++++height%3A+root.h%3B%0A++++++++++++++++++++background%3A+gray%3B%0A++++++++++++++++%7D%0A++++++++++++++++Rectangle+%7B%0A++++++++++++++++++++height%3A+root.h%3B%0A++++++++++++++++++++background%3A+yellow%3B%0A++++++++++++++++%7D%0A++++++++++++++++Rectangle+%7B%0A++++++++++++++++++++height%3A+root.h%3B%0A++++++++++++++++++++background%3A+greenyellow%3B%0A++++++++++++++++%7D%0A++++++++++++++++Rectangle+%7B%0A++++++++++++++++++++height%3A+root.h%3B%0A++++++++++++++++++++background%3A+antiquewhite%3B%0A++++++++++++++++%7D%0A++++++++++++++++Rectangle+%7B%0A++++++++++++++++++++height%3A+root.h%3B%0A++++++++++++++++++++background%3A+aqua%3B%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++%7D%0A++++++++Rectangle+%7B%0A++++++++++++height%3A+200px%3B%0A++++++++++++background%3A+darkmagenta%3B%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native)

When scrolling down ScrollView widget and resizing window, view may contain empty space outside allowed area and scroll bar may not be visible/be visible in wrong position.

When clicking at scroll bar, instantly it moves to correct position.

https://github.com/slint-ui/slint/assets/41945903/fc1bb646-3a9f-4a02-aad1-4a97ee7b8e49

Resizing window, should instantly change properties of scrollview, just like gtk do:

https://github.com/slint-ui/slint/assets/41945903/00fbaa7a-6b68-4480-b1f6-5055d1795f4f

**Comment by ogoffart** [comment]
Thanks for the bug report.
I think this is the same as https://github.com/slint-ui/slint/issues/2227
