### ISSUE TITLE
The edited callback of LineEdit doesn't work in Slint 1.3.1

### ISSUE THREAD

**Issue by Horbin-Magician** [slint-ui/slint#4027]
Using: WIn11, Rust, Slint 1.3.1

Simple demo:
```
import { VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    VerticalBox {
        LineEdit {
            edited(str) => {
                debug("input edited: ", str);
            }
        }
    }
}
```
There is no output when I input anything. But in version 1.3.0 everything is fine.

**Comment by Horbin-Magician** [comment]
PS: As the version was updated, almost all the features of my program were broken one by one. Maybe I'm a BUG black hole. :(

**Comment by Horbin-Magician** [comment]
I'm just making a simple complaint. I genuinely enjoy using Slint and deeply appreciate your team. Each update to Slint has pleasantly surprised me, and I hope that you'll maintain this momentum until Slint reaches its full potential.

Personally, I find these two aspects very unfavorable:
1) It appears that the Slint experience on Linux and embedded systems is prioritized over its performance on Windows, resulting in a relatively poor experience on the latter (e.g., https://github.com/slint-ui/slint/issues/3303).
2) Many of the issues I encountered (e.g., https://github.com/slint-ui/slint/issues/3911 and https://github.com/slint-ui/slint/discussions/3961) were attributable to the upstream libraries (e.g., winit), leaving me feeling powerless.

These issues may require some time to resolve. In the meantime, I think I should learn more and try to solve some problems by myself.

**Comment by ogoffart** [comment]
Thanks a lot for your feedback.
And thanks for reporting this issue. We'll have it fixed as soon as possible. Hopefully we'll do better next release.

And you're right that our experience on the desktop platform is not as good as we'd like.  Good support for desktop is a very big undertaking, and we're struggling to do it properly with our limited resources. But I think it will take time but we'll hopefully get there eventually.
