### ISSUE TITLE
Preview doesn't work for @image-url in the getting started "memory" game example

### ISSUE THREAD

**Issue by vikky999** [slint-ui/slint#4045]
The documentation says:
"When using the slint! macro, the path is relative to the folder in which the Cargo.toml is located. When using .slint files, it's relative to the folder of the .slint file containing it. "

This is from this URL
https://slint.dev/releases/1.3.1/docs/tutorial/rust/memory_tile

The sample code looks like this
```rust
fn main() {
    MainWindow::new().unwrap().run().unwrap();
}

slint::slint! {
component MemoryTile inherits Rectangle {
    width: 64px;
    height: 64px;
    background: #3960D5;

    Image {
        source: @image-url("icons/bus.png");
        width: parent.width;
        height: parent.height;
    }
}

export component MainWindow inherits Window {
    MemoryTile {}
}
}
```

As per the documentation, since we are using the slint! macro, the icons should be in the folder memory/icons/

And that works as expected

However, if you don't cargo run, but instead try to live preview. It throws this error:
Please open an issue on https://github.com/slint-ui/slint/issues
Error loading image from /Users/vivek/work/rust/memory/src/icons/bus.png: No such file or directory (os error 2)

Why is it looking in the src directory ?

Shouldn't the live preview use the same relative path as running the code directly with cargo run, this is inconsistent and confusing.

**Comment by ogoffart** [comment]
We already have logic to take care of this in https://github.com/slint-ui/slint/blob/768084b68e18c8d5320eb78b756e33a1f8e136ad/internal/compiler/typeloader.rs#L705
(that's the solution 1)
And it works for me. (Linux)


> For the behavior of the macro to use the cargo manifest directory, I wonder if it would be possible to make slint::slint! be a wrapper that uses file!

No, the macro would just see the `file!` token that's not usefull. I'm afraid there is no way to find out what's the file name.

**Comment by ogoffart** [comment]
Proposed fix in  https://github.com/slint-ui/slint/pull/4057
