### ISSUE TITLE
Entering values directly in Spinbox does not work on MacOS

### ISSUE THREAD

**Issue by oswald2** [slint-ui/slint#4058]
This is present in a cross-platform application, but is also present in the Gallery example (so it can be reproduced simply in the Gallery):

The SpinBox on the "Controls" page in the Gallery can be spinned with the arrow buttons, but when directly entering numbers via keyboard, the SpinBox acts as if the up-arrow button was clicked. Also, backspace does only shift the cursor left and increases the number by 1. 

This was observed on MacOS Sonoma 14.1.1 on a MacBook Air M1, application is written in Rust and compiled with the current Rust 1.74.0 and slint 1.3.1. 

The SpinBox of the same application (and also the Gallery) work perfectly fine on Windows 10 and Linux (Ubuntu 22.04).

**Comment by FloVanGH** [comment]
Hi,

thank you for your report. I have done a PR that should fix this issue.
