### ISSUE TITLE
`if` statements shouldn't require both parentheses and curly braces

### ISSUE THREAD

**Issue by jturcotte** [slint-ui/slint#4062]
My understanding is that having neither can't be properly parsed, but that having either parentheses or curly braces make it unambiguous where the conditional expression ends.

Requiring both, however, feels unnecessary and clutters the code.

Right now [this works](https://slint.dev/releases/1.3.2/editor/?snippet=export+component+Demo+inherits+Text+%7B%0A++++text%3A+%22NOT+PRESSED%22%3B%0A++++TouchArea+%7B%0A++++++++pointer-event%28e%29+%3D%3E+%7B%0A++++++++++++if+%28e.kind+%3D%3D+PointerEventKind.down%29+%7B%0A++++++++++++++++%2F%2F+Let%27s+pretend+that+this+triggers+a+backend+callback.%0A++++++++++++++++parent.text+%3D+%22PRESSED%22%3B%0A++++++++++++%7D+else+%7B%0A++++++++++++++++parent.text+%3D+%22NOT+PRESSED%22%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native):

```js
pointer-event(e) => {
    if (e.kind == PointerEventKind.down) {
        root.down();
    } else {
        root.up();
    }
}
```

but I think that it would be cleaner and more consistent to allow either of these:

```js
pointer-event(e) => {
    if e.kind == PointerEventKind.down {
        root.down();
    } else {
        root.up();
    }
}
```

### OR

```js
pointer-event(e) => {
    if (e.kind == PointerEventKind.down)
        root.down();
    else
        root.up();
}
```

Because the conditional element `if` doesn't require parentheses [anymore](https://github.com/slint-ui/slint/issues/466), it would probably be better to enable the former, if any.

**Comment by ogoffart** [comment]
Yes, I'd be in favor of making the parentheses optional.

(IIRC, the parentheses are required because back in 2020 when we started, we weren't all quite used to the rust syntax and didn't want to close to the possibility of conditionally omit the braces.  But if the parentheses are optional, we can never make the curly braces optional otherwise parsing would be ambiguous.)

**Comment by Chen1Plus** [comment]
I would like to solve this problem.

**Comment by Chen1Plus** [comment]
> If anyone wants to make a PR for that, it is just about changing code around this line:
> 
> https://github.com/slint-ui/slint/blob/223d629e3c69e3d896e727e22c8424c22e7eaeb3/internal/compiler/parser/statements.rs#L71
> 
> Instead of `expect` we can use `test`. Or perhaps it is enough to just remove it and parse_expression would allow parenthesis there.

Hi @ogoffart, removing it would cause incorrect formatting. I think it's the problem of formatter, but I've no idea how would it happenned.

https://github.com/slint-ui/slint/blob/a46b70833ad48f5a8e71a98ed7310275fd4ce00d/tools/fmt/fmt.rs#L1139-L1153

**Comment by ogoffart** [comment]
I see, the formatter expect a perentheses.
If we remove it to exprect just an expression, it should work:
https://github.com/slint-ui/slint/blob/43d1f62fb113e432ebfa7e9fb8a033ae1788e566/tools/fmt/fmt.rs#L535

**Comment by Chen1Plus** [comment]
Sorry for misleading. I had also removed these and similar things for else if, but the code such as below can't be formatted.
```
if   abc{nothing}
```
I think some **skip_whitespaces causing "if" cannot be identify**; however, there's no idea how to solve it. The behavior of skipping whitespace directly effects lots of things.

And just curious, I think both compiler and formatter should be based on same parser instead of working seperately.

**Comment by ogoffart** [comment]
@Chen1Plus  I forgot to say it in my previous message, but thanks for working on this.

Maybe you can already do a PR so I can see what's going on.

The formatter use the same parser as the compiler, but then tries to add whitespace between the different token of a parsed node, arguably the formatter should be more resilient to see token it doesn't expect in a node.

That said, the formatter is not really working well as of now anyway.

**Comment by Chen1Plus** [comment]
resolve #4417
