### ISSUE TITLE
Compile error on esp32c3 in rust esp-idf-hal

### ISSUE THREAD

**Issue by zhangzqs** [slint-ui/slint#4064]
Maybe same problem, I use std
https://github.com/taks/esp32-nimble/issues/46
![image](https://github.com/slint-ui/slint/assets/34616640/53fb3862-9c6b-4989-8016-c8bf83df4948)

**Comment by zhangzqs** [comment]
https://github.com/slint-ui/slint/pull/4065/

**Comment by zhangzqs** [comment]
#4066

**Comment by ogoffart** [comment]
Should be fixed with https://github.com/matklad/once_cell/pull/251
