### ISSUE TITLE
@image-url still not working after the latest fix 

### ISSUE THREAD

**Issue by vikky999** [slint-ui/slint#4068]
Picked up the latest changes from master using Cargo.toml
[package]
name = "memory"
version = "0.1.0"
edition = "2021"

[dependencies]
#slint = "1.3.2"
slint = { git = "https://github.com/slint-ui/slint" }

In the memory example, show preview still doesn't show the bus , instead get some weird icon 

![Screenshot 2023-12-02 at 9 20 20 PM](https://github.com/slint-ui/slint/assets/2762144/3d563e0e-121d-488e-877d-394fec828551)

**Comment by vikky999** [comment]
This is what it should be i figure, same as cargo run 

![Screenshot 2023-12-02 at 9 25 38 PM](https://github.com/slint-ui/slint/assets/2762144/98715851-7893-4ec8-8c5e-7e7d4c5156a9)

**Comment by ogoffart** [comment]
The little black squares are the resize handle

**Comment by vikky999** [comment]
oh, didn't know what those were. thanks for letting me know

but the behaviour of preview hasn't changed. it is still looking for the icon's in a different place than the code does. is that to be expected ?

as you can see, cargo build fails, but preview works. and vice versa. this is on a macbook pro, with everything updated.

![Screenshot 2023-12-02 at 11 26 02 PM](https://github.com/slint-ui/slint/assets/2762144/99ef9734-9d36-49b5-9583-dc982f6b876a)

**Comment by vikky999** [comment]
the only way to make the code and preview both work is to copy the icons folder in both the root and src directories. which is fine by me, just request updating the documentation accordingly. confused me thoroughly when i was trying to go through the getting started tutorial
thx !

**Comment by ogoffart** [comment]
Do you use the self compiled extension? Or the nightly build?   
(The patch was only merged today, so the nightly extension will have the fix tomorrow)

**Comment by vikky999** [comment]
Self compiled. I just added the git repo to cargo as shown in the first comment

**Comment by vikky999** [comment]
Nevermind. I see what you mean. You probably mean the vscode extension. No guess not. I'll try again tomorrow

**Comment by vikky999** [comment]
Closing
