### ISSUE TITLE
"last statement is returned" broken for functions

### ISSUE THREAD

**Issue by jturcotte** [slint-ui/slint#4070]
Returning values from functions without an explicit `return` seems broken in some cases since 1.3.0. See the following code, I would expect every "Click me!" to change to "worked" but the first one returns `reject` even though the code runs through the `accept` code path.

[SlintPad](https://slint.dev/releases/1.3.2/editor/?snippet=export+component+Test+inherits+Rectangle+{%0A++++background%3A+salmon%3B%0A++++function+broken(event%3A+string)+-%3E+EventResult+{%0A++++++++if+(event+%3D%3D+%22a%22)+{++}%0A++++++++else+if+(event+%3D%3D+%22s%22)+{++}%0A++++++++else+{%0A++++++++++++debug(%22returning+reject%22)%3B%0A++++++++++++return+reject%3B%0A++++++++}%0A++++++++debug(%22returning+accept%22)%3B%0A++++++++accept%0A++++}%0A++++%2F%2F+Works+because+of+the+explicit+return%0A++++function+works1(event%3A+string)+-%3E+EventResult+{%0A++++++++if+(event+%3D%3D+%22a%22)+{++}%0A++++++++else+if+(event+%3D%3D+%22s%22)+{++}%0A++++++++else+{%0A++++++++++++debug(%22returning+reject%22)%3B%0A++++++++++++return+reject%3B%0A++++++++}%0A++++++++debug(%22returning+accept%22)%3B%0A++++++++return+accept%3B%0A++++}%0A++++%2F%2F+Works+because+of+the+missing+%22else+if%22%0A++++function+works2(event%3A+string)+-%3E+EventResult+{%0A++++++++if+(event+%3D%3D+%22a%22)+{++}%0A++++++++else+{%0A++++++++++++debug(%22returning+reject%22)%3B%0A++++++++++++return+reject%3B%0A++++++++}%0A++++++++debug(%22returning+accept%22)%3B%0A++++++++accept%0A++++}%0A%0A++++VerticalLayout+{%0A++++++++Text+{%0A++++++++++++text%3A+%22Click+me!%22%3B%0A++++++++++++TouchArea+{%0A++++++++++++++++clicked+%3D%3E+{%0A++++++++++++++++++++parent.text+%3D+broken(%22a%22)+%3D%3D+EventResult.accept+%3F+%22worked%22+%3A+%22BROKEN%22%3B%0A++++++++++++++++}%0A++++++++++++}%0A++++++++}%0A++++++++Text+{%0A++++++++++++text%3A+%22Click+me!%22%3B%0A++++++++++++TouchArea+{%0A++++++++++++++++clicked+%3D%3E+{%0A++++++++++++++++++++parent.text+%3D+works1(%22a%22)+%3D%3D+EventResult.accept+%3F+%22worked%22+%3A+%22BROKEN%22%3B%0A++++++++++++++++}%0A++++++++++++}%0A++++++++}%0A++++++++Text+{%0A++++++++++++text%3A+%22Click+me!%22%3B%0A++++++++++++TouchArea+{%0A++++++++++++++++clicked+%3D%3E+{%0A++++++++++++++++++++parent.text+%3D+works2(%22a%22)+%3D%3D+EventResult.accept+%3F+%22worked%22+%3A+%22BROKEN%22%3B%0A++++++++++++++++}%0A++++++++++++}%0A++++++++}%0A++++}%0A}%0A&style=native)

```js
export component Test inherits Rectangle {
    background: salmon;
    function broken(event: string) -> EventResult {
        if (event == "a") {  }
        else if (event == "s") {  }
        else {
            debug("returning reject");
            return reject;
        }
        debug("returning accept");
        accept
    }
    // Works because of the explicit return
    function works1(event: string) -> EventResult {
        if (event == "a") {  }
        else if (event == "s") {  }
        else {
            debug("returning reject");
            return reject;
        }
        debug("returning accept");
        return accept;
    }
    // Works because of the missing "else if"
    function works2(event: string) -> EventResult {
        if (event == "a") {  }
        else {
            debug("returning reject");
            return reject;
        }
        debug("returning accept");
        accept
    }

    VerticalLayout {
        Text {
            text: "Click me!";
            TouchArea {
                clicked => {
                    parent.text = broken("a") == EventResult.accept ? "worked" : "BROKEN";
                }
            }
        }
        Text {
            text: "Click me!";
            TouchArea {
                clicked => {
                    parent.text = works1("a") == EventResult.accept ? "worked" : "BROKEN";
                }
            }
        }
        Text {
            text: "Click me!";
            TouchArea {
                clicked => {
                    parent.text = works2("a") == EventResult.accept ? "worked" : "BROKEN";
                }
            }
        }
    }
}
```

**Comment by ogoffart** [comment]
thanks for the bug report.
We changed the code generation in presence of `return` in 1.3.0 so maybe a bug sneaked in.
