### ISSUE TITLE
Panic in the preview

### ISSUE THREAD

**Issue by Adancurusul** [slint-ui/slint#4081]
Here 's the output
```
thread 'main' panicked at D:\a\slint\slint\internal\core\properties.rs:486:9:
Recursion detected
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 3:33:01 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
```

**Comment by Adancurusul** [comment]
System: Windows 10
Software: vscode
Extension： Slint v1.3.2

**Comment by FloVanGH** [comment]
Hi and thank you for your report.

Can you provide a code example?

**Comment by Adancurusul** [comment]
> Hi and thank you for your report.
> 
> Can you provide a code example?

Code is in https://github.com/Adancurusul/slint_bug
By the way, thanks for the "coop_widget" , it works great!

**Comment by FloVanGH** [comment]
> By the way, thanks for the "coop_widget" , it works great!

I'm glade you like it.

Can you shortly explain the steps to reproduce the error?

**Comment by Adancurusul** [comment]
I just click the “Show Preview” in Vscode
![image](https://github.com/slint-ui/slint/assets/54146249/f8619b12-d689-47fe-8357-c2c3dc3e9b24)
![image](https://github.com/slint-ui/slint/assets/54146249/999bcb3f-1a23-46f7-afff-7d514c8acdf5)
And then the question arose.
![image](https://github.com/slint-ui/slint/assets/54146249/99ac59ea-65f5-4b5b-bcd3-2c6d9e3ef1f6)
![image](https://github.com/slint-ui/slint/assets/54146249/1938269f-4d87-4fdb-941d-3662b669a52a)

**Comment by FloVanGH** [comment]
Thank you. I can reproduce it. At @hunger can you take a look?

**Comment by ogoffart** [comment]
Is it the same as #3989 ?
