### ISSUE TITLE
Mouse wheel handling in ComboBox seems backwards

### ISSUE THREAD

**Issue by bjorn** [slint-ui/slint#4090]
Linux (Fedora), Rust, Slint 1.3.2

Recently, mouse wheel handling was added to the ComboBox widget for all styles. However, in trying it the direction of the change in selected items seems backwards.

**Current behavior**
Scrolling "down" (pulling finger towards you) selects items further up the list.

**Expected behavior**
It selects items further down the list.

Before opening this issue I've tried to check the behavior on macOS and Microsoft Fluent widgets, however, combo boxes in macOS settings (and probably in macOS in general) are not sensitive to wheel events at all. Similarly, in the [Fluent Combobox](https://learn.microsoft.com/en-us/fluent-ui/web-components/components/combobox?pivots=typescript) example I found, it is also not possible to interact with the wheel (it just scrolls the website). I'll leave it up to you to decide if this means the behavior should also be disabled in the respective Slint styles.

In Qt, the QComboBox is also not sensitive to wheel events on macOS when using the native style. For the Fusion style though, the direction behaves as expected.

**Comment by FloVanGH** [comment]
Hi bjorn,

thank you for your report.

This behavior was requested in #1466 and added with #3648.

To fix the scroll direction is easy.
