### ISSUE TITLE
Could add showcase gallery in issues then pinned like project egui and iced?

### ISSUE THREAD

**Issue by zhouhang95** [slint-ui/slint#4095]
![Snipaste_2023-12-07_13-10-04](https://github.com/slint-ui/slint/assets/15245678/dc094a03-dbc9-4261-b579-296065694b9a)
![Snipaste_2023-12-07_13-09-25](https://github.com/slint-ui/slint/assets/15245678/f4fd6619-0374-4f09-9880-0007753b5f60)

**Comment by FloVanGH** [comment]
Hi,

thank you for your request. We don't have that yet but we have a website where you can find different showcase projects from community and commercial https://madewithslint.com/. It is also possible to submit your project.
