### ISSUE TITLE
feat: disable interaction for some components

### ISSUE THREAD

**Issue by MicroCBer** [slint-ui/slint#4124]
like css `pointer-events: none;`, it's useful for animations sometimes

**Comment by ogoffart** [comment]
Thanks for your request: There is a `enabled` property on TouchArea and most widgets.

There is a tracking issue to have properties that propagate that would make sense for enabled https://github.com/slint-ui/slint/issues/2338

**Comment by ogoffart** [comment]
Although enabled also change the look of widget to make them visibly enabled.

Another option would be to have a TouchArea on top which intercept the event while animating?

**Comment by MicroCBer** [comment]
That would be painful...  the enabled property also doesn't meet my need, as it also controls the visibility of the components

**Comment by ogoffart** [comment]
Having components that are disabled without any indication is weird.
You can do what you want with a TouchArea on top of the component that intercept the events that you can make visible when you want to disable it.

```
component MakeDisable {
   in property <bool> disabled;
   @children
   if disabled: TouchArea {}
}
```
