### ISSUE TITLE
Old version of LSP being picked up by the vscode extension

### ISSUE THREAD

**Issue by MicroCBer** [slint-ui/slint#4127]
![image](https://github.com/slint-ui/slint/assets/66859419/8d21c80c-156f-42c1-bc20-626c4837385d)

slint version: 1.3.2

**Comment by MicroCBer** [comment]
Compiling works however

**Comment by FloVanGH** [comment]
Hi and thank you for your report.

It looks like you are using `VSCode` right? What is the version of your installed Slint extension?

**Comment by ogoffart** [comment]
Spinner was added in Slint 1.3.0, it appears that your version of the vscode extension is older than that.
Make sure to upgrade your extension.

**Comment by MicroCBer** [comment]
the stable slint plugin with version tag 1.3.2 is also tested. same error.

**Comment by MicroCBer** [comment]
hm so what happened to my plugin... I first used slint last week and there's no way that I installed an outdated plugin

**Comment by ogoffart** [comment]
This is really strange. 
It really  looks like you're using an old version of the LSP thought.
Have you done anything special?

When vscode is running, could you see with the task manager what slint-lsp binary is being run?  
For example, for me, it is `/home/olivier/.vscode/extensions/slint.slint-nightly-2023.12.1011/bin/slint-lsp-x86_64-unknown-linux-gnu`

**Comment by MicroCBer** [comment]
> This is really strange. 
> It really  looks like you're using an old version of the LSP thought.
> Have you done anything special?
> 
> When vscode is running, could you see with the task manager what slint-lsp binary is being run?  
> For example, for me, it is `/home/olivier/.vscode/extensions/slint.slint-nightly-2023.12.1011/bin/slint-lsp-x86_64-unknown-linux-gnu`

 I figured it out... Although the last update time of slint(nightly) shown in vscode market is December, the actual update time is October... That's pretty strange and misleading. Can you check the market if the plugin's also outdated on ur machine?

**Comment by ogoffart** [comment]
What is your platform and your version of vscode?  Are you using the official market, or the [open-vsx](https://open-vsx.org/) ?

**Comment by MicroCBer** [comment]
> What is your platform and your version of vscode?  Are you using the official market, or the [open-vsx](https://open-vsx.org/) ?

windows10, official market

**Comment by ogoffart** [comment]
Could you double check the path it uses for the slint-lsp process. Is it really using the slint-lsp binary which is bundled in the extension?

**Comment by issy** [comment]
I had a similar issue with vscode, where it would only install extension version `1.2.2` despite `1.3.2` being released. It turns out I had an older vscode version, so the newer extensions were incompatible. It's a bit annoying that vscode didn't surface an error or anything like that, but I got to the bottom of it eventually.
> [!TIP]
> Update vscode

**Comment by ogoffart** [comment]
Ah indeed, commit ef39adce30d33b86634e5359db03a18d521a9bc8 increased the requirement to vscode 1.82 (that was required because of some dependencies update in 8311533cb197dd319ad7fb375af2aa3964730970)

@issy:  thanks for figuiring that out, this is good to know that this happens.

I'll close this issue because i don't think we can do anything about that. And 1.82 being from august last year I think we won't try to support older version at this point.
But we'll be conservative next time we update that version.

**Comment by issy** [comment]
Yes, that's a good idea. To be fair, this only happened in my case because I hadn't used vscode in months (I usually use JetBrains IDEs) and I opened it specifically to write Slint. I doubt most people are daily driving an outdated IDE 😄

**Comment by MicroCBer** [comment]
> Could you double check the path it uses for the slint-lsp process. Is it really using the slint-lsp binary which is bundled in the extension?

No, it's working now and I cannot reproduce the issue anymore.

**Comment by MicroCBer** [comment]
> Yes, that's a good idea. To be fair, this only happened in my case because I hadn't used vscode in months (I usually use JetBrains IDEs) and I opened it specifically to write Slint. I doubt most people are daily driving an outdated IDE 😄

VSCode actually has a auto update functionality, so I guess for most people it's up to date.

But that doesn't work for me for some reason...

**Comment by MicroCBer** [comment]
I suggest checking if the lsp version and slint version matches before starting it. By giving an alert if the version doesn't match well, the user can at least address the issue.
