### ISSUE TITLE
Documentation for various structs is missing

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#4153]
This affects the documentation of the following types in the Node.js API:

 - Brush
 - Diagnostic
 - DiagnosticLevel
 - RgbaColor

In [1.3.0](https://slint.dev/releases/1.3.0/docs/node/interfaces/Brush) the fields are visible and documented.
Starting with [1.3.1](https://slint.dev/releases/1.3.1/docs/node/variables/Brush) the documentation is empty and there are no more documented fields.

This is a regression.

**Comment by FloVanGH** [comment]
This is what is changes related to this four types from 1.3.0

```ts
export {
    Diagnostic,
    DiagnosticLevel,
    RgbaColor,
    Brush
} from "./rust-module";
```

to 1.3.1

```ts
const {
    Diagnostic,
    DiagnosticLevel,
    RgbaColor,
    Brush
} = napi;

export {
    Diagnostic,
    DiagnosticLevel,
    RgbaColor,
    Brush
};
```

This could cause the trouble with the documentation. It was change in this commit https://github.com/slint-ui/slint/commit/84fd6dc08cb71b13d5b8f26a2a83405177e5c8b6

**Comment by tronical** [comment]
Yes indeed, I introduced this regression.
