### ISSUE TITLE
Introduce local variables for functions

### ISSUE THREAD

**Issue by FloVanGH** [slint-ui/slint#4157]
Local variables in functions would be a great benefit to the Slint language. At the moment what you can do as workaround is to use private properties instead:

```slint
export global Adapter {
      callback get-text() -> string;
}
export component MyComponent {
      out property <string> result;
      property <string> my-local-text;
      
      public function do-something() {
           my-local-text = Adapter.get-text();
           
           if (my-local-text == "") {
               result = "Error: text empty";
           } else {
               result = "The result is: " + my-local-text;
           }
      }
}
```

This has some disadvantages. 
* Properties are in the scope of the component and not limited to the function itself. So for example it can be e used by mistake on other functions or bindings. 
* You have to write more code. 
* The memory for the property is used as long as the component is in memory
* I think most people expecting there is support for local variables, because it's common in other languages.

How it could looks like:

```slint
export global Adapter {
      callback get-text() -> string;
}
export component MyComponent {
      out property <string> result;
      
      public function do-something() {
           let my-local-text = Adapter.get-text();
           
           if (my-local-text == "") {
               result = "Error: text empty";
           } else {
               result = "The result is: " + my-local-text;
           }
      }
}

**Comment by tronical** [comment]
I think that this may be a Duplicate of #2752

**Comment by FloVanGH** [comment]
Ah yes right sorry. So I can close this.
