### ISSUE TITLE
assert when using `%` sizes in Flickable

### ISSUE THREAD

**Issue by csavels** [slint-ui/slint#4163]
Hello,

I'm having a problem compiling my Rust application after upgrading to Rust+Slint without modifying the code.
I was using the "Slint 1.2" version before the update. Now the application no longer compiles and returns the error:

>   index.crates.io-6f17d22bba15001f/i-slint-compiler-1.3.2/passes/default_geometry.rs:281:9:
>   assertion `left == right` failed
>     left: Invalid
>    right: LogicalLength

### Config: 

**OS**: macOS 14.1.1 (23B81)
**Language**: Rust 1.74.1
**Slint**: 1.3.2
**Slint-build** : 1.3.2

What differences between the two versions could cause this?
(app code is really too big to be shared).

Thanks already.

**Comment by tronical** [comment]
Thanks for the report - this looks indeed like a bug.

> What differences between the two versions could cause this?

That's a good question...

This would happen if an element uses a percentage width or height binding (`width: 30%;`) and the parent has a width/height property that however has a type that's not length. I can't think of any built-in element that could cause this, nor can I reproduce it using an empty base or an attempt at overriding width/height.

Do you have any percentage width/height bindings? Could you check what the surrounding code looks like? (and paste it here, if possible - just an excerpt)

@ogoffart Do you have any idea what could cause this?

**Comment by ogoffart** [comment]
A lot changed in 1.3 with regards to height and width properties.

But it would be useful to have some code that reproduce the issue so we can debug it.

**Comment by ogoffart** [comment]
In order to be able to debug this issue, i'd need to access some code that reproduces the issue.
Would you be able to share (even privately) that code?

**Comment by ian373** [comment]
I ran into the same error in slint 1.3.1, and here's an example to illustrate it:

- OS: win11 22H2
- rustc: 1.73.0 (cc66ad468 2023-10-03)

cargo.toml
```toml
[package]
name = "xxx"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.3.1"
[build-dependencies]
slint-build = "1.3.1"
```

main.rs
```rs
slint::include_modules!();

fn main() {
    MainWindow::new().unwrap().run().unwrap();
}
```

appwindow.slint
```slint
import { ListView } from "std-widgets.slint";
component ShowResult inherits Rectangle {
    width: 50%;
    height: 100%;

    VerticalLayout {
        ListView {
            for file[idx] in [1,2,3]:Rectangle {
                height: 20px;
                // width: parent.width;    // change to this line compiles fine
                width: 100%;  // An error occurred!!!
            }
        }
    }
}
export component MainWindow inherits Window {
    width: 326px;
    height: 326px;

    HorizontalLayout {
        width: 100%;
        height: 100%;

        ShowResult {}
    }
}
```

error:
![tw](https://github.com/slint-ui/slint/assets/58252781/84c8413a-3968-4013-a198-f1b70871f2a3)

**Comment by csavels** [comment]
Hello,
Sorry for the delay in responding.

My UI is composed of more than 100 files, so it's hard to share, but my code is similar to the one copied as an example by "ian373".

Why does the percentage no longer work? 
Without the percentage, padding was ignored in previous versions of Slint, which is why I used it everywhere.

**Comment by csavels** [comment]
Another tip: the Slint preview is still working, but I can't compile the code.

**Comment by ogoffart** [comment]
It works with the preview because this is a debug_assert failing and the preview is compiled in release.

The failling code can be reduced to this:
```
  Flickable { Rectangle { width: 100% } }
``` 

What should the 100% be relative to? To the viewport or to the flickable?
`parent.width` is relative to the flickabled
But by the time we try to compute the size of 100%, there is a viewport inbetween. 
The assert is

```
debug_assert_eq!(
            parent.borrow().lookup_property(property).property_type,
            Type::LogicalLength
        );
```

And this fails for the Flickable viewport because `lookup_property` does't check the reserved builtin property for a ElementType::Native  (which the viewport is)
