### ISSUE TITLE
Resizing a window

### ISSUE THREAD

**Issue by Pilyushkin** [slint-ui/slint#4171]
Hello. How to subscribe to a window change event in code?

**Comment by ogoffart** [comment]
You can use bindings to the width and height properties.

But there is currently no way to get change event. This is issue https://github.com/slint-ui/slint/issues/112
Not yet implemented but https://github.com/slint-ui/slint/issues/112#issuecomment-1065866865 has an ugly workaround.

Closing as duplicated of #112
