### ISSUE TITLE
Document the rough steps to get Slint working in C++ MCU environments

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#4180]
We recently had a user who managed to get Slint running on an STM32U5 with C++. We ended up sorting everything out on Mattermost, but it became apparent that the documentation is missing a guide here:

 * Figure out the right Rust target and then set `-DRust_CARGO_TARGET=` (for example to `thumbv7em-none-eabihf`).
 * Set `-DSLINT_FEATURE_FREESTANDING=ON` to not require std.
 * Set `-DBUILD_SHARED_LIBS=OFF` to build a static lib (no shared libs on mcu).
 * Set `-DSLINT_FEATURE_RENDERER_SOFTWARE=ON`
 * Set `-DDEFAULT_SLINT_EMBED_RESOURCES=embed-for-software-renderer`

**Comment by ogoffart** [comment]
imho we still need a better guide on how to implement a platform for an MCU. 
https://slint.dev/releases/1.3.2/docs/cpp/api/namespace_slint__platform is not too bad, but could be improved.
