### ISSUE TITLE
`clicked` / `double-clicked` TouchArea signal reacts only on left mouse click

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#4213]
Slint 1.3.2/nightly

It is strange that `clicked` signal is only emitted for mouse left click

In https://slint.dev/releases/1.3.2/docs/slint/src/language/builtins/elements#toucharea - I don't see any info about this behavior.

For single click the easiest workaround is to use pointer-event instead, but I have problem with `double-click` signal, which is not fired when double clicking at item with right mouse button.

**Comment by ogoffart** [comment]
I think `clicked` actually means left click. 
Currently in order to handle other click, one have to use the pointer-event callback.
The problem is that this doesn't contains the click count for the double click.

But the documentation of clicked should mention that.
