### ISSUE TITLE
Optimize usage of `is_dir`/`is_file`

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#4219]
When enumerating on dir entries, `is_dir`/`is_file` executed on Path, gather metadata from disks, which sometimes may be slow.

So
```
for style in read_dir(library_dir)?.filter_map(Result::ok) {
        let path = style.path();
        if !path.is_dir() {
            continue;
        }
}
```
could be written as
```
    for entry in read_dir(library_dir)?.into_iter().flatten() {
        let Ok(file_type) = entry.file_type() else {
           continue
        };
        if !file_type.is_dir() {
            continue;
        }

        let path = entry.path();
    }
```

When reviewing the code, I didn't notice this being used in performance-critical parts, but it would still be rather good to change it where possible

Example usage - 
https://github.com/slint-ui/slint/blob/d1529af3cc079c724fcbe1a4101a14013eda8b76/internal/compiler/build.rs#L47-L50
https://github.com/slint-ui/slint/blob/d1529af3cc079c724fcbe1a4101a14013eda8b76/internal/compiler/build.rs#L26-L30

**Comment by ogoffart** [comment]
Thanks a lot for the hint.

Done in commit 5aa6b424e3fd2029130a88bf787e76de6646e8df
