### ISSUE TITLE
Wayland: Window::hide doesn't hide the window

### ISSUE THREAD

**Issue by flukejones** [slint-ui/slint#4225]
On Linux, using Wayland (Gnome). Issue seems universal across desktops. I have not tried xorg as I don't have any requirement for it for the last few years.

To illustrate the issue I created a minimal example [here](https://gitlab.com/flukejones/slint-bg-proc-and-tray) which is a heavily cut down version of what I have working using egui. Of note however is that if I update egui at all I then have the same issue where if I try to keep the app running as a background process but close the main window, the window is just frozen.

The issue may be in winit but I think maybe we can confirm first?

(click on the tray icon to open app window then try close the window).

**Comment by flukejones** [comment]
There are now a few branches using different styles to try and achieve this:
- slint-lsp-style
- simplified
- initial-try

`slint-lsp-style` is where I've tried to copy the way the lsp-preview does things but I've not been successful. I have found that I *do* require the `Option<App>` so I can take and drop the App window and make it actually close. Otherwise `show()`/`hide()` don't appear to remove the window at all (but it does stop responding on hide).

If I try to narrow things down I think I get this:
1. `window().hide()` does not hide the window, but it does stop reacting (an `Option<App>` `.take()` is required)
2. `window().show()` makes the window react again
3. after dropping the window I can't recreate it as it isn't in the right thread...

If I could solve for 3, then I think everything I need follows on - for example creating multiple windows from different threads. I see there are several similar issues, but none address the threaded case.

**Comment by tronical** [comment]
`window().hide()` not hiding the window seems odd to me. We pretty quickly call `winit_window.set_visible(false);`, but the event loop is kept alive (in your example). 

I've tried your example and I think that this is a winit/wayland bug. I'm running this against Gnome with Wayland, and out of the box the show/hide menu items in the tray menu don't do anything. If I unset `WAYLAND_DISPLAY` (and keep `DISPLAY`) and let the app run against xwayland, then it seems to work.

Do you observe the same?

**Comment by flukejones** [comment]
I'm not actually able to get this running with xwayland: `Other("Winit backend failed to find a suitable renderer. Last failure was: Error creating OpenGL display (Xlib(\n    XlibDisplayHandle {\n        display: 0x0000555d0c46d950,\n        screen: 0,\n    },\n)) with glutin: provided display handle is not supported")`

**Comment by ogoffart** [comment]
I suspec t

**Comment by flukejones** [comment]
For what it's worth, this seems to also be a bug in winit, so likely the issue isn't slint at all. (I also had the same issue in egui).

I'm now using the same style of "app thread run, window app close" as the LSP and with the latest git pull it seems to work pretty well for my purposes... ([this branch of example](https://gitlab.com/flukejones/slint-bg-proc-and-tray/-/tree/slint-lsp-style?ref_type=heads))

It should be noted that the issue seems to be quite specific, after trying a few things using winit multi-window. That is, if there is one last window and the main thread for it is still running it will not close, but all other windows will do so fine. Looks related to a drop change in winit actually.

**Comment by flukejones** [comment]
Appears not to be an issue with winit v0.29.10 now

**Comment by tronical** [comment]
Ahh, that explains it! I was trying your example last week and I saw the same effect, that hide() didn't just do anything at all. Explains it, when it's not working under Wayland.

Looks like at the least we need to document this :(

**Comment by tronical** [comment]
Agreed

**Comment by flukejones** [comment]
> Found [rust-windowing/winit#2388](https://github.com/rust-windowing/winit/issues/2388) (the reporter looks familiar :-) )

Ha.. I don't know who that is.

> This means we'll have to keep the winit Window in a RefCell and destroy it and re-create it all the time the user wants it to have it hidden.

Will this not result in unexpected side-effects? I've not used `.hide()` on any other systems so I'm not sure how it reacts, but if it retains position/state then doing a drop erases that, right?

**Comment by ogoffart** [comment]
> Will this not result in unexpected side-effects? I've not used .hide() on any other systems so I'm not sure how it reacts, but if it retains position/state then doing a drop erases that, right?

This will be about destroying the winit::Window, not not the Slint component.
That said, this is a bit complicated because right now, the skia and femtovg renderer holds pointer to the opengl surface that would also vanish. So we'll have to find a solution for that.

**Comment by tronical** [comment]
> > This means we'll have to keep the winit Window in a RefCell and destroy it and re-create it all the time the user wants it to have it hidden.
> 
> Will this not result in unexpected side-effects? I've not used `.hide()` on any other systems so I'm not sure how it reacts, but if it retains position/state then doing a drop erases that, right?

Yes, that's a problem. We'd have to save/restore that manually.

My feeling is that if we work around this, we should limit the workaround to wayland. The downside though is that that means the code path will receive a lot less testing, as hiding a window is probably not that common.

**Comment by flukejones** [comment]
> My feeling is that if we work around this, we should limit the workaround to wayland. The downside though is that that means the code path will receive a lot less testing, as hiding a window is probably not that common.

I can assure you that this is a critical feature for asusctl/rog-control-center so it will receive continuous testing.

**Comment by ryanabx** [comment]
Ah, I wish I hadn't spent hours trying to figure out what I was doing wrong, haha :sweat_smile: 

I'll try using drop like fluke mentioned...

Also, hey @flukejones , nice to see you in yet another place!

**Comment by flukejones** [comment]
@ryanabx my rog-control-center demonstrate it well.
