### ISSUE TITLE
Add property `read-only` to `Switch` and `Checkbox`

### ISSUE THREAD

**Issue by asuper0** [slint-ui/slint#4227]
It's useful to have the property `read-only` while many other widgets have. Currently `Switch` and `Checkbox` have `enabled` which could affect the display behavior.
I could contribute if you agreed.

**Comment by ogoffart** [comment]
Thanks for filling an issue.

To better understand your use case, could you provide specific scenarios where a `read-only` property would be beneficial in these widgets?

I'm asking because from an UX point of view, a read-only checkbox might go against user expectations. Users generally expect checkboxes to be interactive and mutable. Making them read-only might go against the common use and understanding of checkboxes.

Also other framework (eg, HTML) don't provide this.

**Comment by asuper0** [comment]
I am writing a tool to config ip, see the picture below.

![Snipaste_2024-01-03_18-56-07](https://github.com/slint-ui/slint/assets/41113804/79514741-f881-45ca-8d39-6e8dddf55439)


Right area is read only, which show the system current ip setting of each adapter, or the saved settings. Left area is editable, the values could be loaded from right area.
The switch "is up" and "dhcp on" in right area are set to read only, which means they are showing the system state, and should not be changed. Currently I make them read only by masking them with a empty `TouchArea`.

**Comment by tronical** [comment]
Thanks for the example. I'm curious, if you say that you'd like those check boxes on the right hand side panel to be enabled but read-only, could you then elaborate how you'd style them in the Fluent Style?

As far as I can see, the Fluent 2 design for the web specifies the following states for a CheckBox's appearance: Rest, Hover, Pressed, Focus, and Disabled.

This is in contrast to an InputField (our LineEdit), which has: Rest, Hover, Pressed, Focused, Error, Disabled, _and_ Read only.

(Reference: Figma toolkit linked from https://fluent2.microsoft.design/components/web/react/ )

**Comment by asuper0** [comment]
I can't answer the question, because I am not familiar with Fluent 2 as well as web technics. One of the reasons I choose Slint is, it's not web based.

**Comment by tronical** [comment]
Similarly for the Windows UI 3 components for the Fluent Design (at https://fluent2.microsoft.design/components/windows ), I don't see a read-only state for the CheckBox, only disabled. (fwiw, it merges read-only and disabled of text input fields)

I suggest to use `enabled: false;` in your UI.

**Comment by asuper0** [comment]
OK, thanks for your advise.

**Comment by tronical** [comment]
I'll close this as not planned the, but I'm all in favour of re-opening this if somebody has an idea how to concrete visually represent this new state :)
