### ISSUE TITLE
Vim/Neovim (/Tree Sitter) support

### ISSUE THREAD

**Issue by RustemB** [slint-ui/slint#429]
Can we have `The .60 Markup Language` support for Neovim Tree-Sittrer?

**Comment by hunger** [comment]
Somebody needs to write and maintain the required treesitter library. Contributions are of course welcome, but since the language is still evolving (usually in a source-compatible way;-),a potential maintainer would need to be prepared to occasionally invest the time needed to update to newer versions of the language.

There is a LSP provided for `.60` files, which you should be able to integrate into neovim nicely, but there is no support for that one in `lsp-config.nvim` as far as I know. It would rock if somebody with the required lua skills could step up and add that!

I expect the situation to be similar for the ALE and CoC (== LSP on vim)): It should not be too hard to make the LSP work there, but there is no code in place to help users actually do it.

**Comment by RustemB** [comment]
https://github.com/neovim/nvim-lspconfig/pull/1166

**Comment by hunger** [comment]
Thank you for looking into this topic, @RustemB!

**Comment by RustemB** [comment]
https://github.com/RustemB/sixtyfps-vim

**Comment by samyak-jain** [comment]
This is great. I would be happy to help with improving the docs here. The way I have made my setup so far:
1. Use https://github.com/RustemB/sixtyfps-vim, as mentioned, for syntax highlighting
2. Use sixtyfps-lsp for LSP. I've packaged it in the AUR: https://aur.archlinux.org/packages/sixtyfps-lsp/. For my nvim-lspconfig, I use this:

````lua
local configs = require 'lspconfig/configs'
local util = require 'lspconfig/util'

local server_name = 'sixtyfps'
local bin_name = 'sixtyfps-lsp'

configs[server_name] = {
  default_config = {
    cmd = { bin_name },
    filetypes = { 'sixtyfps' },
    root_dir = util.root_pattern('*.60'),
  },

  docs = {
    description = [[
https://github.com/sixtyfpsui/sixtyfps/tree/master/tools/lsp
`sixty-fps` can be installed via `cargo`:
```sh
cargo install sixtyfps-lsp
```
]],
    default_config = {
      root_dir = [[root_pattern('*.60')]],
    },
  },
}

````

I can then just do ```nvim_lsp["sixtyfps"].setup{}```

**Comment by RustemB** [comment]
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#sixtyfps

🙂

**Comment by ogoffart** [comment]
Nice!
I added links to that from the LSP readme at the end of the vim section:
https://github.com/sixtyfpsui/sixtyfps/blob/master/tools/lsp/README.md#vim

I was not sure what to write so I just put the links without much description.

**Comment by RustemB** [comment]
Anyway, I'll add some description by myself later

**Comment by hunger** [comment]
Can we build binaries of the LSP at some point? Then that could be added to the relevant plugins in neovim for auto-installation and setup.

**Comment by RustemB** [comment]
I think it will be good idea

**Comment by ogoffart** [comment]
> Can we build binaries of the LSP at some point? Then that could be added to the relevant plugins in neovim for auto-installation and setup.

That's #569

There is already some code that generates the binery for the sixtyfps-viewer in 
https://github.com/sixtyfpsui/sixtyfps/blob/master/.github/workflows/sixtyfps_viewer_binary.yaml
the same could be done for the lsp

**Comment by hunger** [comment]
Now that there is a LSP build: https://github.com/hunger/nvim-lsp-installer has a fork of nvim-lsp-installer with support for "dot60" that will grab those binaries.

Please test!

I am not sure I want to send this to upstream for inclusion with talk about renaming everything in the air. Maybe it makes sense to wait till after that?

**Comment by RustemB** [comment]
Also, started working on tree-sitter module, but I'm new to this technology, maybe I can't to to much. If someone know how write tree-sitter modules (or at least grammers), so welcome to RustemB/tree-sitter-sixtyfps or make your own
This can be helpful not only for neovim but for other cool stuff, like web integration

**Comment by jrmoulton** [comment]
Hmmm somehow I never saw this tracking issue when I was writing the tree-sitter module. I figure at this point this issue can probably be closed though
