### ISSUE TITLE
Add Key.Space to Key namespace

### ISSUE THREAD

**Issue by trobanga** [slint-ui/slint#4303]
Of course Key.Space can be substituted with " ", but I think it can make the code more readable.

**Comment by ogoffart** [comment]
Thanks for your suggestion. I think this makes senses.
The key codes are defined in https://github.com/slint-ui/slint/blob/master/internal/common/key_codes.rs

**Comment by tronical** [comment]
After adding it there, this code in winit could be removed: https://github.com/slint-ui/slint/blob/2efd2bc3c8d14a94dd80b12bc0eea123721fdba8/internal/backends/winit/event_loop.rs#L290
