### ISSUE TITLE
Qt backend does not check if the current platform supports the selection clipboard

### ISSUE THREAD

**Issue by nununoisy** [slint-ui/slint#4306]
Qt does support the selection clipboard, but it isn't available on all platforms (notably Windows). Slint does not check for this support in the Qt backend which leads to some undesirable behavior when there is no support:
- A warning is printed to the console by Qt: `Data set on unsupported clipboard mode. QMimeData object will be deleted.`
- There is a noticeable delay whenever text is selected for the first time, which causes animation jank and sometimes cancels the selection, which can be a bit frustrating.

The fix would be to call [`QClipboard::supportsSelection()`][qtdoc] to determine if there is support before operating on the selection clipboard.

[qtdoc]: https://doc.qt.io/qt-6/qclipboard.html#supportsSelection

**Comment by ogoffart** [comment]
Thanks for the bug report. 
Fixed in commit afb8a666031764bba3a234f877f1b81edffc13e5
