### ISSUE TITLE
Javascript: equivalent to run_event_loop_until_quit

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#4316]
Rust and C++ for keeping the event loop alive was added in #1499
But this is missing from the javascript API

**Comment by ogoffart** [comment]
I was thinking the same.
Or
```
run_event_loop({ quit_on_last_window_closed: false });
```

But run_event_loop can already take a callback, so that'd be the second parameter then? or another field in that object?

**Comment by tronical** [comment]
Yep, probably easiest to merge the parameters. I’ll tag this as good first issue:)

**Comment by tronical** [comment]
Solving this requires using a typescript enum to extend the existing signature at https://github.com/slint-ui/slint/blob/a3bb47550082896e57d9939946977e2ee31fa47a/api/node/index.ts#L942 based on the above discussion to optionally take a object instead that can have the callback as well as the event loop quit property.

The implementation needs to call into a helper function in https://github.com/slint-ui/slint/blob/master/api/node/src/lib.rs that in then can do what we do in the rust api: https://github.com/slint-ui/slint/blob/a3bb47550082896e57d9939946977e2ee31fa47a/api/rs/slint/lib.rs#L244
