### ISSUE TITLE
TODO example app...

### ISSUE THREAD

**Issue by Resonanz** [slint-ui/slint#4348]
...works nicely but the window redraw is really slow on Windows 11.

Demo: Grad the bottom RHS corner and move it about to resize the window.

**Comment by ogoffart** [comment]
Did you compile in debug or release mode?

**Comment by Horbin-Magician** [comment]
https://github.com/slint-ui/slint/assets/46142827/a1f6319c-53e0-4963-9c8e-1e750bf0dfdc

I have tried the example on Windows 11 in debug.
It works well. This may be related to CPU's performance.

**Comment by ogoffart** [comment]
We'd need more information to be able to act on this issue.
We'll re-open if more information is provided.
