### ISSUE TITLE
Allow for multiple `PopupWindow`s to exist at once

### ISSUE THREAD

**Issue by BrandonXLF** [slint-ui/slint#4356]
From what I can tell, there can only be one active `PopupWindow` at a time. In my use case, I need to open a second `PopupWindow` when the first `PopupWindow` is right-clicked.

**Comment by SuchAFuriousDeath** [comment]
I have the same issue.

**Comment by SuchAFuriousDeath** [comment]
@ogoffart Any progress on this? Why isn't this currently possible? What would it take to implement?

**Comment by ogoffart** [comment]
@SuchAFuriousDeath thanks for proposing to help. In this case, I thought it would be better if I implement it myself in #6690
