### ISSUE TITLE
Linear gradient broken in 1.4.0/dev

### ISSUE THREAD

**Issue by abique** [slint-ui/slint#4459]
Hi,

The following gradient is kaput for me: `background: @linear-gradient(0deg, Colors.green 0%, Colors.green 60%, Colors.yellow 80%, Colors.orange 85%, Colors.red 89%, Colors.red 100%);`.

This is a regression from 1.3.2.

Cheers,
Alex.

**Comment by tronical** [comment]
1.3.2: [Slintpad](https://slintpad.com/?snippet=import+%7B+AboutSlint%2C+Button%2C+VerticalBox+%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Demo+inherits+Window+%7B%0A%0Abackground%3A+%40linear-gradient%280deg%2C+Colors.green+0%25%2C+Colors.green+60%25%2C+Colors.yellow+80%25%2C+Colors.orange+85%25%2C+Colors.red+89%25%2C+Colors.red+100%25%29%3B%0A++++width%3A+300px%3B%0A++++height%3A+300px%3B%0A%7D%0A&style=native)
Master: [Slintpad](https://slint.dev/snapshots/master/editor/?snippet=import+%7B+AboutSlint%2C+Button%2C+VerticalBox+%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Demo+inherits+Window+%7B%0A%0Abackground%3A+%40linear-gradient%280deg%2C+Colors.green+0%25%2C+Colors.green+60%25%2C+Colors.yellow+80%25%2C+Colors.orange+85%25%2C+Colors.red+89%25%2C+Colors.red+100%25%29%3B%0A++++width%3A+300px%3B%0A++++height%3A+300px%3B%0A%7D%0A&style=native)

Looks the same to me - broken with both?

**Comment by abique** [comment]
Did you try on winit + skia + macOS?

**Comment by abique** [comment]
I'll screenshot tomorrow.

**Comment by ogoffart** [comment]
I can reproduce it, it happens when the rectangle is not square

**Comment by abique** [comment]
[Indeed](https://slint.dev/snapshots/master/editor/?snippet=import+%7B+AboutSlint%2C+Button%2C+VerticalBox+%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Demo+inherits+Window+%7B%0A%0ARectangle+%7B%0Awidth%3A+20px%3B%0Aborder-radius%3A+3px%3B%0Abackground%3A+%40linear-gradient%280deg%2C+Colors.green+0%25%2C+Colors.green+60%25%2C+Colors.yellow+80%25%2C+Colors.orange+85%25%2C+Colors.red+89%25%2C+Colors.red+100%25%29%3B%0A%7D%0A++++width%3A+300px%3B%0A++++height%3A+300px%3B%0A%7D%0A&style=native)
