### ISSUE TITLE
TouchArea's pointer event callback seems to never receive the right button click when using winit

### ISSUE THREAD

**Issue by abique** [slint-ui/slint#4461]
Hi,

it seems that the pointer event callback never receives the event for the right click button when performing a right click.

Using slint 1.3.2 on macOS.

Cheer,
Alex.

**Comment by tronical** [comment]
@abique can you clarify?

The following test case shows that `pointer-event` is called on right click:

```
export component MainWindow inherits Window {
    TouchArea {
        pointer-event(event) => {
            if (event.kind == PointerEventKind.up && event.button == PointerEventButton.right) {
                root.background = Colors.red;
            }
        }
    }
}
```

**Comment by tronical** [comment]
I looked into @abique 's code and this is not a Slint issue.
