### ISSUE TITLE
1.4.0 regression horizontal gradient reversed

### ISSUE THREAD

**Issue by abique** [slint-ui/slint#4495]
I think slint 1.4.0 regressed and horizontal gradient are painted the way around.

[sample](https://slintpad.com/?snippet=import+%7B+AboutSlint%2C+Button%2C+VerticalBox+%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Demo+inherits+Rectangle+%7B%0A++++background%3A+%40linear-gradient%2890deg%2C+Colors.green+0%25%2C+Colors.green+60%25%2C+Colors.yellow+80%25%2C+Colors.orange+85%25%2C+Colors.red+89%25%2C+Colors.red+100%25%29%3B%0A%7D%0A&style=native)

Maybe 1.4.0 is correct and 1.3.2 was wrong, but it changed.

**Comment by ogoffart** [comment]
Argh, you're right. If the angle is exactly equal to 90deg, the gradient is reversed.
