### ISSUE TITLE
PopupWindow.close() panics "called `Option::unwrap()` on a `None` value"

### ISSUE THREAD

**Issue by Youngsie1997** [slint-ui/slint#4500]
**I am using Arch Linux with the Hyprland wm using the stable version of rust-lang with slint 1.4.0. with what I believe to be the qt back-end**

I copied the example from the TODO app for opening a PopupWindow the window displays fine and is what I want except invoking PopupWindow.close() causes the following error.
thread 'main' panicked at /home/REDACTED/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-core-1.4.0/window.rs:1038:44:
called `Option::unwrap()` on a `None` value

I ran the todo example and the same behaviour happens when you click no on the dialogue prompt.  The yes button doesn't crash as it is linked to a callback that closes the main window instead.

If there is a better way to display the user a error message in the form of a typical message Box I would be glad to hear of it.

Thank you

**Comment by wolfseifert** [comment]
I have the same problem on Linux with KDE using Wayland:
<pre>
slint/examples/todo/rust$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `/home/wolfgang/rust/slint/target/debug/todo`
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
thread 'main' panicked at internal/core/window.rs:1041:44:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</pre>
The same is true for examples/gallery's combobox.

It works using X11.
It works when compiled with SLINT_NO_QT.
It works on Windows.

So the qt-backend seems to be broken for Wayland.

**Comment by ogoffart** [comment]
thank you both for the bug report.
I can reproduce with weston in the gallery

**Comment by wolfseifert** [comment]
After doing a git-pull and building with slint-1.4.1:

When closing the window and click "No" in the confirmation dialog I still get
<pre>
$ cargo run --bin todo
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `/home/wolfgang/rust/slint/target/debug/todo`
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
</pre>
This is an "aesthetic" issue only (no crash). Also examples/gallery's combobox is working now.
