### ISSUE TITLE
Add `icon` property to line edit.

### ISSUE THREAD

**Issue by FloVanGH** [slint-ui/slint#4505]
Mostly to show the context of a text input without describing it with a label, text input provides a leading icon e.g. for displaying it is a search or a password input element. To provide this in the  `std-widgets` LineEdit it would be good to have an `icon` property and a `colorize` property similar to `Button`.

**Comment by ogoffart** [comment]
Regarding the eye icon to show the hidden password: This should be builtin in the LineEdit for native style that do it. It should not be an icon property.

Regarding the feature in general, is that something that is present in the design system of the style we support?

**Comment by tronical** [comment]
The material design spec has a compelling example at the top (the zip code warning icon that's app specific) and it outlines the icon as an optional feature of the text input field (our LineEdit): https://m3.material.io/components/text-fields/specs

**Comment by FloVanGH** [comment]
I think we should go with the icon property. The icon should not be connected to other logic e.g. the input type. The developer / designer should be able to choose which icon to show and also to choose to not display an icon. And I think the Icon property from api side is clear how to use it and is consistent e.g. with the icon property of the button.

**Comment by ogoffart** [comment]
I've looked at the Fluent and Material style guide, and Here is what i've seen in fluent that we don't implement:

### Fluent

 - Each LineEdit field that has text and focus should have a "x" icon to clear the text (in addition, there is a search icon that can be on the right or on the left)
![image](https://github.com/slint-ui/slint/assets/959326/150a73ba-937d-491d-9799-283b7ee427db) 
![image](https://github.com/slint-ui/slint/assets/959326/e5cf46c5-36f5-4410-90c6-86c939e17926)
![image](https://github.com/slint-ui/slint/assets/959326/05a54099-4021-4447-b3f4-56542f9462ea)

 - there is a variant with an arror that doesn't have a search icon

![image](https://github.com/slint-ui/slint/assets/959326/5353cfe2-8386-44af-a54d-a8986cc49437)


 - Password LineEdit have a eye icon
  
![image](https://github.com/slint-ui/slint/assets/959326/e8e8b748-e6f6-4e60-91d4-50c2ed1fb971)

I can't see an API to add a custom Icon.


### Material

Material has icons on both sides.
It also usually has a clear icon, but not always. Or a "mandatory" icon.

![image](https://github.com/slint-ui/slint/assets/959326/6a8fab2c-5e65-4702-aa03-424f6892eb96)

**Comment by FloVanGH** [comment]
> I've looked at the Fluent and Material style guide, and Here is what i've seen in fluent that we don't implement:
> ### Fluent
> 
>     * Each LineEdit field that has text and focus should have a "x" icon to clear the text (in addition, there is a search icon that can be on the right or on the left)
>       ![image](https://private-user-images.githubusercontent.com/959326/301504857-150a73ba-937d-491d-9799-283b7ee427db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTIyMzUsIm5iZiI6MTcwNjc5MTkzNSwicGF0aCI6Ii85NTkzMjYvMzAxNTA0ODU3LTE1MGE3M2JhLTkzN2QtNDkxZC05Nzk5LTI4M2I3ZWU0MjdkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMjUyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmJkOWRiZjYwM2FkZWFhNjBjYTlmOGYxMzQ4NmNkYzU3ZmJlNTJhM2I1MzU2YThjYmUxMDU3YTVlMDI5OWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HEU7k5l99tfHcXl0fP1VvMp621nBX4IbT_gg21dMw6I)
>       ![image](https://private-user-images.githubusercontent.com/959326/301504527-e5cf46c5-36f5-4410-90c6-86c939e17926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTIyMzUsIm5iZiI6MTcwNjc5MTkzNSwicGF0aCI6Ii85NTkzMjYvMzAxNTA0NTI3LWU1Y2Y0NmM1LTM2ZjUtNDQxMC05MGM2LTg2YzkzOWUxNzkyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMjUyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjdkMTViYTAwMzRmZWU3NWNkYTFlZDQ3NTg3NTM4YzEwNjNlOGJkNTRmNThjMWQzNThhNDAxYTUzMGFhYzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.37sp0F9o4cGxOqKW-k5ZN9qSJqfrN3Mv7vN3FbmCKqM)
>       ![image](https://private-user-images.githubusercontent.com/959326/301504757-05a54099-4021-4447-b3f4-56542f9462ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTIyMzUsIm5iZiI6MTcwNjc5MTkzNSwicGF0aCI6Ii85NTkzMjYvMzAxNTA0NzU3LTA1YTU0MDk5LTQwMjEtNDQ0Ny1iM2Y0LTU2NTQyZjk0NjJlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMjUyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTM0NmI5NmU4NTkzOGEyYTYyZjdiNmUyZDgwNGE1NmMwYjgwOTQyNWE0ZDVkOTQyM2JkZTJiNDA5ZWI5ZmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v_M9fb6rS_VQECsc02BXm3PVq5nPVSnTWFBCiigCtEE)
> 
>     * there is a variant with an arror that doesn't have a search icon
> 
> 
> ![image](https://private-user-images.githubusercontent.com/959326/301505653-5353cfe2-8386-44af-a54d-a8986cc49437.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTIyMzUsIm5iZiI6MTcwNjc5MTkzNSwicGF0aCI6Ii85NTkzMjYvMzAxNTA1NjUzLTUzNTNjZmUyLTgzODYtNDRhZi1hNTRkLWE4OTg2Y2M0OTQzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMjUyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Njc0ZTVlNjMzMDAyMTc4YWM4ODNhMWJjNWY3MzJhMjcyODEwNzk4Yjg0NWQ3Y2VhODQ3NTQwYmViNzY4YmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ovm31unr18aqUvmv9DiYxPO17NTfDikIm6v_sSc2esU)
> 
>     * Password LineEdit have a eye icon
> 
> 
> ![image](https://private-user-images.githubusercontent.com/959326/301505359-e8e8b748-e6f6-4e60-91d4-50c2ed1fb971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTIyMzUsIm5iZiI6MTcwNjc5MTkzNSwicGF0aCI6Ii85NTkzMjYvMzAxNTA1MzU5LWU4ZThiNzQ4LWU2ZjYtNGU2MC05MWQ0LTUwYzJlZDFmYjk3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMjUyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTNhYmM0MGYwYjUxYmIzMjgyODdlOTA3MjkyZjk4ZDkwMWUyOGI4ODdlNGY1NjI0NGI0YmVkODEyYmEyYzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H-qf5POEt2991SELtTrQzfQRRSi9tcRmv2us43Xtzj4)
> 
> I can't see an API to add a custom Icon.
> ### Material
> 
> Material has icons on both sides. It also usually has a clear icon, but not always. Or a "mandatory" icon.
> 
> ![image](https://private-user-images.githubusercontent.com/959326/301507521-6a8fab2c-5e65-4702-aa03-424f6892eb96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTIyMzUsIm5iZiI6MTcwNjc5MTkzNSwicGF0aCI6Ii85NTkzMjYvMzAxNTA3NTIxLTZhOGZhYjJjLTVlNjUtNDcwMi1hYTAzLTQyNGY2ODkyZWI5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMjUyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmI3Y2VlZWFjN2VmZDM0OGIyNTQwMDlmZTU3Mzg5MDg1ZTRjZjQwNWVhYTIyMGFkZDZjMDAyNDExN2MzMzcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bVpyjq9-tk70DD8fwQQ6IoGhF082Hi17bo82hY4Wt74)

I have a good picture of all the style guides. I worked with them all. We need a solution that works for all our styles and what works good with Slint. And it should be easily to use and flexible for developers / designers.

**Comment by tronical** [comment]
> I think to add something like icon-clicked in the future is ok.

I agree with you.

**Comment by ogoffart** [comment]
> I have a good picture of all the style guides. I worked with them all. We need a solution that works for all our styles and what works good with Slint. And it should be easily to use and flexible for developers / designers.

Exactly, and the proposed solution doesn't seem to work with all style, because if every user has to hardcode, say, the "clear" or the "view password" or the "search" icon in their app, it's not going to be the right icon for all styles.


What is exactly the problem you're trying to solve?  
Is this icon which is not one of the builtin icon so common?

**Comment by FloVanGH** [comment]
From experience I had many different use cases for different icons for text input controls and I think it is not uncommon. Without it the developer / designer has no possibility to define it without doing a custom widget. But maybe that is ok. If a custom icon make not enough sense against to define the icon input-type base, that's ok. I can close the PR and keep the branch, I think from layout perspective it can also be used to develop the input base solution.

**Comment by FloVanGH** [comment]
I close this in favor of #4518
