### ISSUE TITLE
Can't set array property in function slint::invoke_from_event_loop

### ISSUE THREAD

**Issue by tao-a-man** [slint-ui/slint#4523]
hii Slint team, I have a issue when i try set a property is array in  function `slint::invoke_from_event_loop ` (picture 2), This error make IOT app crash (picture 1)
![Screenshot 2024-02-02 142415](https://github.com/slint-ui/slint/assets/92592956/71146faa-bf9e-4d5b-a21b-8cb2580f79e2)
)
![Screenshot 2024-02-02 142314](https://github.com/slint-ui/slint/assets/92592956/5ea04bee-6f19-4790-aaea-af081416f882)

**Comment by tao-a-man** [comment]
hii @ogoffart  have a nice day sir, plss help me check this case if i set array property `ListNodeEnabel` by `ui->set_ListNodeEnabel(nodelists)` everythings oke but UI not re-render, then i set array property `ListNodeEnabel` as above I get issue :(((, I declare `ListNodeEnabel` like `in-out property <[INode]> ListNodeEnabel;`

**Comment by tronical** [comment]
I'm closing this as it's not evident that this is a bug. Happy to re-open if it turns out to be a Slint issue :)

**Comment by tao-a-man** [comment]
It worked Sir thank you for help, I really respect that ❤️
