### ISSUE TITLE
i-slint-backend-android-activity: build.rs use wrong way to call d8 on windows

### ISSUE THREAD

**Issue by Jhonfunk** [slint-ui/slint#4524]
https://github.com/slint-ui/slint/blob/1e58930d7eeaf53b7622994a80bf12a838d1e294/internal/backends/android-activity/build.rs#L62

On windows there is no `d8.exe` only `d8.bat`. and the parameters are passed differently.
![sdfs](https://github.com/slint-ui/slint/assets/78594391/4b76f4d2-1aae-49e1-a3c7-ae0dbb1d98ef)

**Comment by ogoffart** [comment]
Thanks for filling a bug.

I'm not familiar with Android development on windows.
Would you be able to provide a PR that fixes the issue?

**Comment by ogoffart** [comment]
Actually, @tronical already made a PR https://github.com/slint-ui/slint/pull/4530
