### ISSUE TITLE
[Feature Request] `Slider`: Add step property that affect keyboard action, and foucs with mouse clicking

### ISSUE THREAD

**Issue by asuper0** [slint-ui/slint#4549]
When focus the slider and press left or right arrow, the value is change by the step, which is hard-coded to 1. This is not good when `maximum - minimum != 100`. So I suggest to add a `step` property, which determine the step of a key press action.

On the other hand, I found the only way to focus a slider is pressing Tab key multi times. It would be better to select it by mouse clicking.

**Comment by tronical** [comment]
That sounds like a good idea to me.
