### ISSUE TITLE
slint-viewer fails to convert KeyEvent (and others) into string

### ISSUE THREAD

**Issue by Tmpod** [slint-ui/slint#4553]
## Reproducer

`foo.slint`
```slint
export component Foo inherits Window {
    callback bar(KeyEvent);

    FocusScope {
        key-released(event) => { bar(event); accept }
    }
}
```

```sh
$ slint-viewer --on bar 'echo' foo.slint
```

## Current behaviour

It outputs an error like this for each callback invocation:
```
Error: Cannot convert argument to string: Value::Struct(Struct({"text": Value::String("l"), "repeat": Value::Bool(false), "modifiers": Value::Struct(Struct({"control": Value::Bool(false), "meta": Value::Bool(false), "shift": Value::Bool(false), "alt": Value::Bool(false)}))}))
```

## Expected behaviour

`KeyEvent`s (and other structs) are converted into strings and passed as arguments.

**Comment by ogoffart** [comment]
We cannot serialize everything to String.
In particular, right now, we only support number, string, bool, and image that have a paths

It's unclear how we should convert struct or enums or models. We could do json.  But it's a bit strange that a string is not in json though.

**Comment by Tmpod** [comment]
I don't think JSON would be a bad idea, to be honest. Tools like jq have become quite widespread and are really useful when doing shell scripts.

**Comment by ogoffart** [comment]
This should not be hard to implement, by handling the Value::Struct and value::Model in https://github.com/slint-ui/slint/blob/5325f7234cb0662c23e0bdb6aa4731cca0ec7971/tools/viewer/main.rs#L409 to convert to json.
Note that there is already code that convert these to json in the same file (the `to_json` function that can be moved to the global scope)
