### ISSUE TITLE
Image::load_from_path doesn't reload the image if the path is in the cache, even if it has changed on disk

### ISSUE THREAD

**Issue by sloganking** [slint-ui/slint#4599]
```rust
main_window.on_render(move || {
    let main_window = main_window_weak.unwrap();

    // ...

    println!("rendered img!");

    sage_image(img, Path::new("./output.png"), Discard).unwrap();
    let slint_img = slint::Image::load_from_path(Path::new("./output.png")).unwrap();
    main_window.set_display_image(slint_img);
    println!("set display image!");
});
```
I have a slint application that will load the requested image once but not twice. I am writing new data to the same image file before re-rendering it with `image::load_from_path()` and `main_window.set_display_image(slint_img);` . 

I am not sure if `image::load_from_path()` is not working when run on the same file a second time, or if `main_window.set_display_image(slint_img);` is faulty after one successful run.

Does `image::load_from_path()` do some caching behind the scene, based on path? If so then that is the cause of this issue, and I suggest Slint store "last modified time" with it's cached files and actually re-read them if they have been modified since the file was last cached.

**Comment by tronical** [comment]
This was fixed in 386710cd6d31193e03e4215abc2dc14a5cb0a214
