### ISSUE TITLE
Inability to build slint-cpp

### ISSUE THREAD

**Issue by themistocles-0** [slint-ui/slint#4617]
I am trying to use slint with cpp on debian 12. I have created a simple cmake project to see if I can build slint-cpp within my project. I extracted the latest release of slint in my source directly and included the cpp project in my cmake build file.
![Screenshot from 2024-02-14 20-13-56](https://github.com/slint-ui/slint/assets/74494183/c1ff808a-e09d-4bbe-b6c7-13b860769e40)
Everything builds but when it gets to slint-cpp everything simply freezes, looking at the task monitor, everything that should be building my project is stuck sleeping seemingly indefinitely, it has been like that for an hour.
![Screenshot from 2024-02-14 20-21-24](https://github.com/slint-ui/slint/assets/74494183/e9a8d022-6f2a-47ff-9e8b-d82950626c56)
![Screenshot from 2024-02-14 20-16-53](https://github.com/slint-ui/slint/assets/74494183/b42e6c8b-0d45-4487-b1cb-e735c323a111)
![Screenshot from 2024-02-14 20-17-55](https://github.com/slint-ui/slint/assets/74494183/cf8f9e32-3fc3-4a02-8fd2-192a99cd340f)
The only process that is running as slint-cpp is building cannot even tell what is going on.
![Screenshot from 2024-02-14 20-26-01](https://github.com/slint-ui/slint/assets/74494183/fa1be773-3d9a-4071-8983-0e39c955d81b)
How long should it take to build slint-cpp cause for me it seems to take forever. I can't tell if it's stuck building one file as it does not show which file it is compiling.

**Comment by ogoffart** [comment]
It compiles Slint from rust. That can take some time. But shouldn't take forever.
I'd say it should just take a few minutes.
The build-script-build process is a process that creates the internal .h based by parsing the .rs datastructures, but that process doesn't seem to be running.
The cargo process that is running is doing `cargo metadata`  I don't know exactly why it does that. Could you check what is the process tree and see what is the parent process? It is not using much CPU either so it seems blocked. It is possible that it needs to access the network to download the crate index. Do you know what is your version of Rust?

As a workaround, you can try using the [binary packages](https://slint.dev/releases/1.4.1/docs/cpp/cmake#install-binary-packages)

**Comment by ogoffart** [comment]
I found out that cbindgen used by the buildscript is running cargo metadata: https://github.com/mozilla/cbindgen/blob/master/src/bindgen/cargo/cargo_metadata.rs#L234
That explains why it is running, but not why it hangs.
I suspect it is checking the network for the index, could that be?
But it shouldn't take long since the previous cargo invocation should have already cached the relevant data. (although it will include more features)

**Comment by themistocles-0** [comment]
> Do you know what is your version of Rust?
rustc 1.76.0 (07dca489a 2024-02-04)
> As a workaround, you can try using the [binary packages](https://slint.dev/releases/1.4.1/docs/cpp/cmake#install-binary-packages)
I strictly want an in-tree build, where I manually manage most of the dependencies I use.

**Comment by themistocles-0** [comment]
> That explains why it is running, but not why it hangs. I suspect it is checking the network for the index, could that be? But it shouldn't take long since the previous cargo invocation should have already cached the relevant data. (although it will include more features)

I am not sure, I had quite the slow internet connection yesterday, will try again today.

**Comment by themistocles-0** [comment]
I suppose this was a networking issue. There was a download at the time slint-cpp was being built. the network monitor showed this. I suppose that's what was preventing the download from completing.

**Comment by ogoffart** [comment]
Assuming it was a glitch at the time in cargo and not something we can do anything about in Slint.
