### ISSUE TITLE
Cannot find arial font on Windows(Hirens Boot PE version) even if exists in OS folder

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#4634]
Slint 1.4.1

Probably every single one app crashes with message
```
thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\i-slint-common-1.4.1\sharedfontdb.rs:160:13:
Unable to determine default font. Failed to locate font for family Arial
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
```

Maybe this is problem of special version of OS or maybe problem happens, because by default X:/ is not recognize as system drive

![Screenshot from 2024-02-18 20-31-22](https://github.com/slint-ui/slint/assets/41945903/8b494d42-083a-4b3a-b28c-f1ce532a6ecc)

I don't want to install windows on disk, so that is why I wanted to test portable version of this OS

**Comment by tronical** [comment]
This is I believe a bug in fontdb. https://github.com/RazrFalcon/fontdb/pull/64 should fix that.

**Comment by tronical** [comment]
Fontdb 0.16.2 was published. cargo update should suffice to make this also work with the latest slint release.
