### ISSUE TITLE
is there any plan for slint-ui 's designer software ?

### ISSUE THREAD

**Issue by sky5454** [slint-ui/slint#4652]
A designer software is really important for a GUI library, so is there any plan for designer software like QT designer for Slint-UI ?

**Comment by ogoffart** [comment]
Yes there is.  This is already tracked in https://github.com/slint-ui/slint/issues/695

(We're making some progress on this. You can set the `SLINT_ENABLE_EXPERIMENTAL_FEATURES=1` env variable and run the nightly vscode extension or the slint-lsp from master, The preview will have a "design" mode where you can drag and drop widgets)
