### ISSUE TITLE
vsc-extension: libinput.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ji-soft** [slint-ui/slint#4666]
hey, im trying to get started with slint demo and vscode, but i cant get it to run.
slint extension cant find libinput but its installed and also in my env path.
my os is rocky linux 9.2
`libinput --version
1.19.3
`
`ldconfig -p | grep libinput.so.10
	libinput.so.10 (libc6,x86-64) => /lib64/libinput.so.10
`
when i use cargo run manually, it works fine, but i need to run it everytime i make changes in the slint file.

**vscode logs:**

[Error - 13:03:55] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 13:03:55] Slint LSP client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 13:03:55] Connection to server got closed. Server will restart.
true
/home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libinput.so.10: cannot open shared object file: No such file or directory
[Error - 13:03:55] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 13:03:55] Slint LSP client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 13:03:55] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 13:03:55] Connection to server got closed. Server will restart.
true
/home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libinput.so.10: cannot open shared object file: No such file or directory
[Error - 13:03:55] Client Slint LSP: connection to server is erroring. Shutting down server.
[Error - 13:03:55] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/ji/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at processTicksAndRejections (node:internal/process/task_queues:95:5)
	at runNextTicks (node:internal/process/task_queues:64:3)
	at process.processImmediate (node:internal/timers:447:9)
[Error - 13:03:55] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 13:03:55] Slint LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 13:03:55] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Info  - 13:03:55] Connection to server got closed. Server will restart.
true
/home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libinput.so.10: cannot open shared object file: No such file or directory
[Error - 13:03:55] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 13:03:55] Slint LSP client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 13:03:55] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 13:03:55] Connection to server got closed. Server will restart.
true
/home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libinput.so.10: cannot open shared object file: No such file or directory
[Error - 13:03:55] Client Slint LSP: connection to server is erroring. Shutting down server.
[Error - 13:03:55] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/home/ji/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 13:03:55] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 13:03:55] Slint LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 13:03:55] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Error - 13:03:55] The Slint LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
/home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/bin/slint-lsp-x86_64-unknown-linux-gnu: error while loading shared libraries: libinput.so.10: cannot open shared object file: No such file or directory

**Comment by tronical** [comment]
It looks like some incompatibility caused due to the linuxkms backend being enabled in the LSP. Could you try running the following command and paste the output here?

```sh
readelf -d /lib64/libinput.so.10 | grep SONAME
```

**Comment by ji-soft** [comment]
`readelf -d /lib64/libinput.so.10 | grep SONAME ==>  0x000000000000000e (SONAME)             Library soname: [libinput.so.10]`

**Comment by ji-soft** [comment]
should i try to deactivate linuxkms Backend and install an older version of libinput?

**Comment by tronical** [comment]
Could you try to see if installing an older or newer version fixes it? What do you see when you run `strace -e file  /home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/bin/slint-lsp-x86_64-unknown-linux-gnu` ?

**Comment by ji-soft** [comment]
it shows:
`execve("/home/ji/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/bin/slint-lsp-x86_64-unknown-linux-gnu", ["/home/ji/.var/app/com.visualstud"...], 0x7fff5c5783f0 /* 46 vars */) = 0
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=49359, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libxkbcommon.so.0", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=281456, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libudev.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=200152, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libinput.so.10", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=348632, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/opt/amdgpu/lib64/libgbm.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=76128, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=2306456, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libfontconfig.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=324200, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libfreetype.so.6", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=811240, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=15464, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=108136, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=15480, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=904680, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=2387200, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libmtdev.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=24320, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libevdev.so.2", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=123744, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libwacom.so.2", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=53744, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/opt/amdgpu/lib64/libdrm.so.2", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=102896, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/opt/amdgpu/lib64/libwayland-server.so.0", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=111472, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libexpat.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=197952, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libxcb-randr.so.0", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=73336, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libxml2.so.2", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=1640704, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libbz2.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=76800, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libpng16.so.16", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=225600, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=102552, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libharfbuzz.so.0", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=861504, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libbrotlidec.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=53056, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libgudev-1.0.so.0", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=53200, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libgobject-2.0.so.0", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=375136, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libglib-2.0.so.0", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=1302992, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libffi.so.8", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=44784, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libxcb.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=174272, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libXau.so.6", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=20136, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/liblzma.so.5", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=178744, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libgraphite2.so.3", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=133432, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libbrotlicommon.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=138728, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libpcre.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=489744, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=49359, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libX11.so.6", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=1354904, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=49359, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/lib64/libX11-xcb.so.1", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=14904, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "/proc/self/maps", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0444, st_size=0, ...}, AT_EMPTY_PATH) = 0
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
`

**Comment by tronical** [comment]
> what is that /etc/ld.so.preload

I think that's fine.

> openat(AT_FDCWD, "/lib64/libinput.so.10", O_RDONLY|O_CLOEXEC) = 3 newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=348632, ...}, AT_EMPTY_PATH) = 0

It looks like it finds it, but it's not happy about it, some how.

Could you also try `ldd /home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/bin/slint-lsp-x86_64-unknown-linux-gnu`?

**Comment by ji-soft** [comment]
that shows:
	linux-vdso.so.1 (0x00007fff47fb7000)
	libxkbcommon.so.0 => /lib64/libxkbcommon.so.0 (0x00007f0bcdf1b000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007f0bcdee3000)
	libinput.so.10 => /lib64/libinput.so.10 (0x00007f0bcbdab000)
	libgbm.so.1 => /opt/amdgpu/lib64/libgbm.so.1 (0x00007f0bcdecb000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f0bcba00000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f0bcbd5b000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f0bcbc93000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f0bcdec3000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f0bcbc73000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0bcdebb000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f0bcb923000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f0bcb600000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0bcdf73000)
	libmtdev.so.1 => /lib64/libmtdev.so.1 (0x00007f0bcdeb3000)
	libevdev.so.2 => /lib64/libevdev.so.2 (0x00007f0bcbc53000)
	libwacom.so.2 => /lib64/libwacom.so.2 (0x00007f0bcbc43000)
	libdrm.so.2 => /opt/amdgpu/lib64/libdrm.so.2 (0x00007f0bcb90b000)
	libwayland-server.so.0 => /opt/amdgpu/lib64/libwayland-server.so.0 (0x00007f0bcb8f3000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f0bcb8bb000)
	libxcb-randr.so.0 => /lib64/libxcb-randr.so.0 (0x00007f0bcbc2b000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007f0bcb473000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f0bcb8a3000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f0bcb86b000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f0bcb84b000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f0bcb3a3000)
	libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007f0bcb83b000)
	libgudev-1.0.so.0 => /lib64/libgudev-1.0.so.0 (0x00007f0bcb82b000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f0bcb343000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f0bcb203000)
	libffi.so.8 => /lib64/libffi.so.8 (0x00007f0bcb81b000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f0bcb1d3000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f0bcb813000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f0bcb1a3000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f0bcb17b000)
	libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007f0bcb153000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f0bcb0db000)

**Comment by tronical** [comment]
Ok, great, so that also works and finds libinput. I suppose if you run `/home/user/.var/app/com.visualstudio.code/data/vscode/extensions/slint.slint-1.4.1/bin/slint-lsp-x86_64-unknown-linux-gnu --version` you'll get a version as output?

**Comment by ji-soft** [comment]
=>  `slint-lsp 1.4.1`
hmmm what deos that mean?

**Comment by tronical** [comment]
That means that your system can run the binary fine, so that's good.

That leaves us with the question why when the same binary is run from VS code, it fails to run.

Is VS code running inside some kind of container by chance? How did you install VS code on your system?

**Comment by ji-soft** [comment]
i installed it via the preinstallled gnome software manager. should i install from terminal and dnf/yum?

**Comment by tronical** [comment]
> i also noticed that the "code ." command is not working via terminal

What error you do get when you do that?

**Comment by ji-soft** [comment]
`[user@controllplane kubyplexer]$ code .
bash: code: command not found...
[user@controllplane kubyplexer]$ bash code .
bash: code: Datei oder Verzeichnis nicht gefunden
`
i just cant find it. maybe its just not in my env path

**Comment by ji-soft** [comment]
so i logged out and switched from x11 to waylend, but its still the same error. is that somehow important to use wayland display server?

**Comment by ji-soft** [comment]
anyway: huge thanks for the good support! <3
with your help i could limit the source of error.
ill report how i solved it!
Grüße aus berlin wedding brudi!

**Comment by tronical** [comment]
That's good - glad you solved it. Greetings from Pankow ;-)
