### ISSUE TITLE
Slint apps constantly steal focus on Linux using winit on X11

### ISSUE THREAD

**Issue by hunger** [slint-ui/slint#4678]
While showing the live preview in VSCode, each keypress in the editor makes the Slint preview window focus. That makes the live preview pretty unusable in combination with VSCode.

This happens on Linux using winit. WAYLAND_DISPLAY is unset, DISPLAY is set, so it should use X11.

It does not happen in these setups:

 * Linux using winit. WAYLAND_DISPLAY is set, so that it should use wayland.
 * Linux using the qt backend
 
Disabling the accessibility layer in the winit backend does not fix the issue either.

I think this is a upstream bug, but have not found any matching issue in winit.

**Comment by tronical** [comment]
Does this happen with _any_ kind of slint code you're previewing (say just a `Rectangle {}`) or does this happen in particular when there are focusable elements present?

**Comment by tronical** [comment]
Ok, what about `fn input_method_request`?

Can you reproduce this also with `slint-viewer` and `--auto-reload`?

**Comment by ogoffart** [comment]
I have the feeling this might be related to the recent maximise/minimise feature. We might call too often to winit when the window attributes changes, even if it didn't change

**Comment by ogoffart** [comment]
I cannot reproduce the issue on plasma.  What are the step to reproduce?
Does it also happen with the viewer?

**Comment by ogoffart** [comment]
I can reproduce the problem. This is only on Gnome Xwayland (wayland compositor, but using X11 from Slint)
As I suspected, this is related to minimize, as the problem disappear when commenting this line:
https://github.com/slint-ui/slint/blob/3969e09d5bb15f9593ab3e1b9c5cb005c29d078a/internal/backends/winit/winitwindowadapter.rs#L492

Maybe we want to do something like this to workaround:

```rust
let value = properties.is_minimized();
if winit_window.is_minimized() != value {
    winit_window.set_minimized(value);
}
```

And the same for maximized.

This is a shame.

Alternative would be to remember in the winitwindowadapter which value was sent.

**Comment by tronical** [comment]
> This is a shame.

That's true :(

> Alternative would be to remember in the winitwindowadapter which value was sent.

I think that we may have to do that.

I noticed two things on the Wayland side here (from reading the winit code):

1. On wayland, you can't programmatically un-minimize a window.
2. On wayland, `fn is_minimized()` always returns None, to indicate that it's not know to the client if the compositor changed the state.

This is also mentioned in the protocol docs at https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_minimized:

> There is no way to know if the surface is currently minimized, nor is there any way to unset minimization on this surface.

All this leads me to believe that the primary use of the programmatic API for these states is to set them once on startup. After that all bets are off in a cross-platform environment.
