### ISSUE TITLE
many, many "non-local `impl` definition" warnings

### ISSUE THREAD

**Issue by martinellison** [slint-ui/slint#4706]
I am getting lots and lots of lint messages `warning: non-local impl definition, they should be avoided as they go against expectation ` on my Rust builds. It is also referring to an `expansion of ItemTreeVTable_static!` (at `i-slint-core-1.4.1/item_tree.rs:40:1`) and of `#[derive(sp::FieldOffsets)]`. This used to not produce these messages. This is using Rust; all versions should be latest. 

These are just warnings, and my code still builds and seems to be working. The files are very long and I cannot tie the messages to any specific code, so I'm not including the source.

**Comment by ogoffart** [comment]
Thanks for filling an issue.
This is a warning produced by Rust nightly. This is only going to be stable with Rust 1.78 in May.
