### ISSUE TITLE
Running Slint C++ project using pre-built binary packages fails due to missing Qt dlls (Windows 11)

### ISSUE THREAD

**Issue by GameDotPlay** [slint-ui/slint#4707]
Following along with the [Set Up Development Environment](https://slint.dev/releases/1.4.1/docs/cpp/cmake) page to set up my dev environment by using the pre-built sources [here](https://github.com/slint-ui/slint/releases), building the Memory Game and C++ Template projects succeeds but both fail at launch due to Qt dlls missing:
Qt6Core.dll
Qt6Widgets.dll
Qt6Gui.dll

Building these projects using Slint sources does not result in this error.

Is there something I'm missing by using the pre-built binaries? This probably needs to be documented better on that page or have the the pre-built binaries include the missing Qt dlls.

**Comment by tronical** [comment]
Unfortunately there was a bug in the way that we've made the packages in the last release that caused this :(. Olivier fixed this in https://github.com/slint-ui/slint/pull/4641 . Meanwhile, what you could do is grab the packages from our nightly builds:

1. Navigate to https://github.com/slint-ui/slint/actions/workflows/nightly_snapshot.yaml.
2. Pick the last green build.
3. Scroll down to the Artifacts section.
4. Download `cpp_bin-windows` and extract it.
