### ISSUE TITLE
Feature: Additional slint color type methods

### ISSUE THREAD

**Issue by flukejones** [slint-ui/slint#4735]
More often than not I'm finding I need to make callbacks to be able to do other kinds of manipulations for slint `color` type. For example:

```rust
    ui.global::<AuraPageData>().on_blend_colour(|c1, c2, f| {
        let c1: RgbaColor<f32> = RgbaColor::from(c1);
        let c2: RgbaColor<f32> = RgbaColor::from(c2);
        RgbaColor {
            alpha: 0.0,
            red: c1.red + (c2.red - c1.red) * f,
            green: c1.green + (c2.green - c1.green) * f,
            blue: c1.blue + (c2.blue - c1.blue) * f,
        }.into()
    });
```

It would also be very handy to have direct access to a `<color>.red()` so that some other kinds of ops can be done in slint code itself, plus being able to pull individual channels out.

**Comment by flukejones** [comment]
Something else I'd really like to see is a conversion to/from hex string.

**Comment by tronical** [comment]
Sounds like a good idea to me (color channel accessors).

**Comment by tronical** [comment]
Duplicate of #911

**Comment by flukejones** [comment]
I'll close in favour of the linked issue.

**Comment by tronical** [comment]
Since we support a conversion from hex to a color in the language itself, it seems like it might make sense to also offer this as a run-time API. I've created a separate ticket for it (as the description of this relates to #911 ): https://github.com/slint-ui/slint/issues/4745

**Comment by tronical** [comment]
Ah, our paths crossed - thanks for closing :)
