### ISSUE TITLE
Provide an option to make the lsp binary without depending on QT

### ISSUE THREAD

**Issue by VlaDexa** [slint-ui/slint#4783]
As of now, the binary always includes slint for the "preview-engine feature", which, as far as I understand, can be only used within QtCreator. I think it's ok to leave it to be compiled by default and distribute the binary with this enabled. I think for use inside nvim, for example, where this feauture cannot be accessed, being dependent on Qt is kinda overkill and I would like to be able to recompile the lsp without including it.

**Comment by tronical** [comment]
The preview feature works in any IDE by creating a new top-level window, it also works in nvim.

If you would like to install `slint-lsp` without a dependency to Qt on Windows, then you can install it like so:

```bash
SLINT_NO_QT=1 cargo install slint-lsp
```

**Comment by ogoffart** [comment]
Are you talking about the binary that we provides, or the ones that you build yourselves.
And what platform  specifically?

Anyway, there is the `SLINT_NO_QT=1` option, and also you can change the features with 

```
cargo install slint-lsp --no-default-features --features=preview,backend-winit,renderer-femtovg
```
