### ISSUE TITLE
ComboBox and key navigation

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#4826]
Tested the native combobox on windows and Linux

In a ComboBox:

"Space" should open the ComboBox if pressed while it has the focus.
(On Windows "Enter" also open the ComboBox, but not on Linux)

Once the combobox is open:
 - the arrow should change the selected item in the menu, but not yet change the selected item in the combobox itself.
 - "Enter" accepts the item, and "Esc" reset to the previous item
 - Tab should, either do nothing (Linux) or accept the value and switch the foxus (Windows) 

(Also pressing keys "searches" the contents)

**Comment by FloVanGH** [comment]
@ogoffart the current behavior is kind of a workaround. The keyboard interaction does not work well right now with `PopupWindow`, I have an alternative workaround on the `ContextMenu` for coop but it's really hacky has also issues and therefore I don't think we should use it.
