### ISSUE TITLE
Windows 10: Lags in UI.

### ISSUE THREAD

**Issue by Kesanov** [slint-ui/slint#483]
I have tested the sliding puzzle and printer example.

Both get laggy under medium workload.

- The shuffling in puzzle makes it pause for .5 sec about every 3 seconds. 
- The widgets in printer get unresponsive when used repeatedly until other widgets are used. Mainly:
    - increment buttons
    - scrolling lists

**Comment by tronical** [comment]
I suspect that this is the same case as #418

**Comment by Kesanov** [comment]
In the case of sliding puzzles: yes.
However, the problems in printer seem to be something else.
Steps to reproduce:
Click 20x on a button in quick succession.
Then repeat it for other buttons.
Sooner or later one of the buttons stops being responsive, even when the mouse is moved.
Switching tabs makes the button responsive again.

**Comment by ogoffart** [comment]
What button do you click on?

**Comment by ogoffart** [comment]
Are you in release or in debug mode?

**Comment by Kesanov** [comment]
Release.
Start copying.
Copies.
Turbo mode.
Elephant.png (makes scroll unresponsive).

**Comment by tronical** [comment]
Commit 575665994aa348abec097178f3cc0b57333c110e fixes the freeze - I verified with the printer demo and slide puzzle before and after. After that it worked but the printer demo became a bit slow in debug builds when adding many copy jobs. With current git it works also faster in debug builds (Windows, GL backend). Closing this, but please re-open if you still see this with current Slint.
