### ISSUE TITLE
crash due to unchecked `unwrap()` on `Model::row_data()`

### ISSUE THREAD

**Issue by abique** [slint-ui/slint#4839]
According to the interface, `Model::row_data()` returns an `Option`, so it **can** be `None`.

<img width="1496" alt="Screenshot 2024-03-13 at 21 19 06" src="https://github.com/slint-ui/slint/assets/31200/79f9f598-60be-46cc-8646-2e6b6020fb29">

Here is the current documentation on 1.4.1:
```rust
    /// Returns the data for a particular row. This function should be called with `row < row_count()`.
    ///
    /// This function does not register dependencies on the current binding. For an equivalent
    /// function that tracks dependencies, see [`ModelExt::row_data_tracked`]
    fn row_data(&self, row: usize) -> Option<Self::Data>;
```

Maybe you want to update the documentation instead.

**Comment by ogoffart** [comment]
Indeed, we should probably not unwrap there.

That said, you should only return None if row is out of bounds.

But I'm not quite sure what the behavior should be if the model return None.
Options:
 1. Keep is as it was before. (Do not update the data within the created ItemTree)
 2. ~~default contructed data~~. (We currently don't have a `Default` bound on the data)
 3. Keep that ItemTree dirty so it is going to be called again later for each frame.
 4. Don't create the ItemTree for this row.

**Comment by ogoffart** [comment]
I think i'll go with the first option as this is the easier

**Comment by abique** [comment]
What If I have a key/value map?

**Comment by ogoffart** [comment]
> What If I use the Model as a key/value map?

That's not what a Model is.
What would the key be in your case?

**Comment by abique** [comment]
> > What If I use the Model as a key/value map?
> 
> That's not what a Model is. What would the key be in your case?

This is only a theoretical thing.
It could be an `uint32_t id`.
