### ISSUE TITLE
LSP Format OOM Crash

### ISSUE THREAD

**Issue by HookedBehemoth** [slint-ui/slint#4850]
Trying to format this snippet with the LSP causes a sharp incline of memory usage until OOM. Tried the latest pre- and release versions.
`
export component LspCrashMvp {
    states [
        active: {
        }
        inactive: {
        }
    ]
}
`
Expected behavior: don't crash 😄

**Comment by ogoffart** [comment]
Thanks for the bug report.
I can reproduce.
