### ISSUE TITLE
Feature Request : modulo in slint lang supported arithmetic operations

### ISSUE THREAD

**Issue by jbousquie** [slint-ui/slint#4862]
Coding with Slint in Rust 1.5 on Linux Ubuntu 22.02

As mentioned in the documentation here https://slint.dev/releases/1.5.0/docs/slint/src/language/syntax/expressions  the supported arithmetic operations are currently +,-,*,/

It would be  nice please to have the modulo added  so we could, for instance, make the background color switch according to an index of a `for` loop : 
```
// file.slint

for line[index] in anArray: Rectangle {
  background: index mod 2 > 0 ? blue : green;
}
```

Thank you for all your work so far :-)

**Comment by ogoffart** [comment]
This is actually already existing:
https://slint.dev/releases/1.5.0/docs/slint/src/language/builtins/namespaces#mod-t-t-t

So this should work:
```slint
for line[index] in anArray: Rectangle {
  background: mod(index, 2) > 0 ? blue : green;
}
```

**Comment by jbousquie** [comment]
Thank you,
I just couldn't find it in the doc, sorry
:-)
