### ISSUE TITLE
Button does not have option for custom color

### ISSUE THREAD

**Issue by learncodingforweb** [slint-ui/slint#4878]
Button does not have option for custom color. Eleven i tried using
Rectangle
```
Rectangle {
        Text {text: title; color: white;}
        background: #047857;
    }
```
But it does not look like button as it does not have show elevated option

**Comment by ogoffart** [comment]
Thanks for filling an issue.

There is no plan to add styling properties like brushes, font settings and spaces to the std-widgets. Instead two alternatives are planned to make widget customization easier: https://github.com/slint-ui/slint/issues/4371 https://github.com/slint-ui/slint/issues/4372

As of now, if you want a custom looking button, you can create a custom component for it.
There are example here: https://slint.dev/docs/slint/src/recipes/recipes#custom-button

**Comment by jgardona** [comment]
> Thanks for filling an issue.
> 
> There is no plan to add styling properties like brushes, font settings and spaces to the std-widgets. Instead two alternatives are planned to make widget customization easier: [#4371](https://github.com/slint-ui/slint/issues/4371) [#4372](https://github.com/slint-ui/slint/issues/4372)
> 
> As of now, if you want a custom looking button, you can create a custom component for it. There are example here: https://slint.dev/docs/slint/src/recipes/recipes#custom-button

The url is broken

![Image](https://github.com/user-attachments/assets/e3053bb5-922e-493d-a3f5-eb5e368dab98)

**Comment by ogoffart** [comment]
Here is a permalink to the old docs: https://releases.slint.dev/1.8.0/docs/slint/src/recipes/recipes#custom-button

**Comment by jgardona** [comment]
> Here is a permalink to the old docs: https://releases.slint.dev/1.8.0/docs/slint/src/recipes/recipes#custom-button

Hello. Good afternoon. Helps me a lot. Thank you.
