### ISSUE TITLE
Slint 1.5.1 autoformatter deletes space after comma between parameter declaration in functions

### ISSUE THREAD

**Issue by HitecExports** [slint-ui/slint#4892]
Hello!

Slint 1.5.1 autoformatter deletes space after comma between parameter declaration in functions.

If function has more then one parameter, then Slint LSP autoformatter deletes space after comma before next parameter.

```
function foo(x: length,y: length) -> length {
   1px
}
```

**Comment by ogoffart** [comment]
Thanks for filling an issue.
