### ISSUE TITLE
Live Preview: Updating the file through LSP shouldn't reset the size to `preferred_width`/`preferred_height`

### ISSUE THREAD

**Issue by jturcotte** [slint-ui/slint#492]
### To reproduce
- load this UI through LSP's "Show preview":
  ```js
  MainWindow := Window {
      preferred_width: 800px;
      preferred_height: 480px;
      Rectangle { background: red; }
  }
  ```
- Resize the preview window
- Change the color

### Expected
The size given to the preview window remains so that I can test the UI at that size.

### Actual
The preview window size is reset to the value of preferred_width and preferred_height.

**Comment by ogoffart** [comment]
Done
