### ISSUE TITLE
Update file workflow link in CONTRIBUTING.md 

### ISSUE THREAD

**Issue by jeevikasirwani** [slint-ui/slint#4927]
please if u could update CONTRIBUTING.md ( the corresponding workflow defined in the rust.yaml file.) It shows 404 error while trying to access the rust.yaml file
![Screenshot (223)](https://github.com/slint-ui/slint/assets/83456541/d5572605-13df-4134-89a1-4dc85c19e05d)

**Comment by ogoffart** [comment]
Thanks for reporting the issue.
I've edited the file in commit b13c03b2a6358eb94967d00473b6413a5dedd9b9 
the file had been renamed ci.yaml.
