### ISSUE TITLE
Rectangle: Add support for overflow property

### ISSUE THREAD

**Issue by bub-bl** [slint-ui/slint#4931]
```
overflow: hidden;
overflow: visible;
```

![image](https://github.com/slint-ui/slint/assets/66354328/ed97dff1-2af4-44fb-92ad-d06793949286)

CSS Reference: 
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

Windows 11, Rust

**Comment by ogoffart** [comment]
Thanks for filling an issue.

I believe what you're looking for is `clip : true`

But i'm not sure I understand the screenshot. Could you explain what you expect and how it behave differently?

**Comment by bub-bl** [comment]
Imagine you have circle with a rectangle of the same size inside of them. If you set the overflow to hidden, the rectangle will be "clipped" and the corners of the rectangle will not be visible anymore

(I have not tested yet the "clip" property)

**Comment by ogoffart** [comment]
Right, this is exactly what clip:true does

**Comment by bub-bl** [comment]
> Right, this is exactly what clip:true does

In CSS, the "clip" property is used to clip from a shape. This is the reason why we use the "overflow" property on the parent to clip childs inside.

I don't know if the features bellow is already added or planned:
https://developer.mozilla.org/fr/docs/Web/CSS/clip

**Comment by ogoffart** [comment]
We plan to support the `clip` feature on Path rather than havin the same thing as CSS.

I'm going to close this issue because what you're trying to do is done with the `clip` property on the rectangle.
