### ISSUE TITLE
Container components always place children at the end

### ISSUE THREAD

**Issue by sgued** [slint-ui/slint#4935]
```silnt
component Wrapper {
    HorizontalLayout {
        @children
        Text {
            text: "After";
        }
    }
}
export component Demo {
    Wrapper {
        Text {
            text: "Before";
        }
    }
}
```

gives ![image](https://github.com/slint-ui/slint/assets/51865119/ae0b5fcc-e093-4075-9b72-431035ba99b8) where I expected it to give ![image](https://github.com/slint-ui/slint/assets/51865119/75640059-7246-44e1-bd70-a1ac492617c6).

The correct behaviour can be obtained by wrapping the `@children` in a `Rectangle`:

```slint
component Wrapper {
    HorizontalLayout {
        Rectangle {
            @children
        }
        Text {
            text: "After";
        }
    }
}
export component Demo {
    Wrapper {
        Text {
            text: "Before";
        }
    }
}
```

Tested with version 1.5.1 on Linux. This also reproduces [on slintpad](https://slintpad.com/?snippet=component+Wrapper+%7B%0A++++HorizontalLayout+%7B%0A++++++++%40children%0A++++++++Text+%7B%0A++++++++++++text%3A+%22After%22%3B%0A++++++++%7D%0A++++%7D%0A%7D%0Aexport+component+Demo+%7B%0A++++Wrapper+%7B%0A++++++++Text+%7B%0A++++++++++++text%3A+%22Before%22%3B%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native).

**Comment by ogoffart** [comment]
Thanks for the bug report.

@hunger : this is about the `@children` not behaving as it should. Not about the dnd in the preview.
