### ISSUE TITLE
Previewer and compiler crash when aliasing a callback to itself

### ISSUE THREAD

**Issue by sgued** [slint-ui/slint#4938]
This simple code, which should fail to compile, instead crashes `slint-viewer`

```slint
export component Test inherits Window {
    callback test <=> test;
}
```

Error message:

```
thread 'main' panicked at internal/compiler/passes/resolving.rs:1522:29:
assertion failed: diag.has_error()
```

Version 1.5.1 on linux.

**Comment by ogoffart** [comment]
Thanks for the bug report!
Fixing in https://github.com/slint-ui/slint/pull/4946
