### ISSUE TITLE
Widgets react to all mouse buttons when using Qt backend

### ISSUE THREAD

**Issue by notfirefox** [slint-ui/slint#4975]
**Steps to reproduce**
The issue can be reproduced on Linux using the example gallery application.

1. `git clone https://github.com/slint-ui/slint`
2. `cd examples/gallery`
3.  `cargo run`

**Expected behavior**
Components such as

- Button 
- Checkbox
- LineEdit
- SpinBox
- Tab

should not react with the _primary_ action when someone presses any mouse button that is not 
the left mouse button, e.g. the Button widget is not supposed to be clicked when someone right clicks. 

**Actual behavior**
One can activate the Button using right click, one can select a Checkbox using mouse button 5, etc.

**Platform**
Fedora Linux 40, Rust, Qt Backend, Wayland

**Comment by ogoffart** [comment]
Thanks for filling a bug report.
Indeed in the Qt Widget we don't check the MouseEvent's button as we should in the input_event function.  For example for Button, in this function
https://github.com/slint-ui/slint/blob/0e01068ff52c2135363bdbfa59f145cd56beea11/internal/backends/qt/qt_widgets/button.rs#L246
