### ISSUE TITLE
slint is not working on dietpi OS on Raspberry pi 4 with 8GB RAM

### ISSUE THREAD

**Issue by learncodingforweb** [slint-ui/slint#4979]
I am not able to run slint based app on dietpi.  while same app is working fine os ubuntu and windows 10. Dietpi is based on debian os. Getting error as

```
Running `target/debug/learn`
thread 'main' panicked at /home/dietpi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xkbcommon-dl-0.4.2/src/x11.rs:59:28:
Library libxkbcommon-x11.so could not be loaded.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Even i have installed following dependencies.

```
sudo apt install libxcb-shape0-dev libxcb-xfixes0-dev
sudo apt install libxkbcommon-dev libfontconfig-dev
sudo apt install clang libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev libavdevice-dev libasound2-dev pkg-config
```

as per documentation
[Requirement](https://github.com/slint-ui/slint/blob/master/docs/building.md)

**Comment by learncodingforweb** [comment]
resolved after install sudo apt install libxkbcommon-x11-dev. please update in docs

**Comment by ogoffart** [comment]
We already have an issue open to update the docs about the dependencies https://github.com/slint-ui/slint/issues/1234
