### ISSUE TITLE
StandardListView and StandardTableView always show scroll bars when using Qt backend

### ISSUE THREAD

**Issue by notfirefox** [slint-ui/slint#4996]
**Steps to reproduce**
The issue can be reproduced on Linux using the example gallery application.

1. `git clone https://github.com/slint-ui/slint`
2. `cd examples/gallery`
3.  `cargo run`

**Expected behavior**
Scroll bars are only shown when necessary and hidden individually when the content fits into the visible area.

**Actual behavior**
The scroll bars are shown both horizontally and vertically, even though there is no content to be scrolled
(as everything fits into the visible area).

![image](https://github.com/slint-ui/slint/assets/138280734/2530b4f2-67f0-4a63-952b-baf24ae51b5a)

**Platform**
Fedora Linux 40, Rust, Qt Backend, Wayland

**Comment by FireFragment** [comment]
This is duplicate of this my issue: #3552 

The scrollbars there quite tick me off :)

**Comment by notfirefox** [comment]
Oh thanks I wasn't aware that there is already an issue open for that. Let's continue tracking there then.
