### ISSUE TITLE
Broken links to tutorial/quickstart

### ISSUE THREAD

**Issue by freethebee** [slint-ui/slint#5018]
Hi,
The link to the tutorial in de docs appears to have been renamed to quickstart with the link pointing at 
https://releases.slint.dev/1.5.1/docs/quickstart/rust

whereas the tutorial is still located at https://releases.slint.dev/1.5.1/docs/tutorial/rust/

The same goes for the node and c++ versions.

**Comment by aurindam** [comment]
Thanks for reporting. The links have now been fied.
