### ISSUE TITLE
Tutorial "Slint Memory Game Tutorial" is out of date

### ISSUE THREAD

**Issue by Dangerise** [slint-ui/slint#5019]
for example , code from [here](https://archive.slint.dev/0.2.0/docs/tutorial/rust/getting_started)

```
fn main() {
    MainWindow::new().run();
}

slint::slint! {
    MainWindow := Window {
        Text {
            text: "hello world";
            color: green;
        }
    }
}
```

![image](https://github.com/slint-ui/slint/assets/88434542/d078082d-5e40-4eb8-a68c-fe986c16ff85)

**Comment by ogoffart** [comment]
Thanks for filling an issue.

This is a old documentation. The latest one is at this URL: https://releases.slint.dev/1.5.1/docs/tutorial/rust/getting_started

This is indeed confusing that the old documentation doesn't have a warning. You're not the first one to get caught by that. I've filled another issue https://github.com/slint-ui/slint/issues/5020 so we can improve things. And I'm going to close this issue.
