### ISSUE TITLE
Make guide for setting up Kate more clear

### ISSUE THREAD

**Issue by FireFragment** [slint-ui/slint#5022]
I like that you give steps to set up Slint development in Kate. However, in the guide [here](https://github.com/slint-ui/slint/blob/master/editors/README.md), it's not quite clear at the first glance, that the syntax highlighting has to be installed for the LSP server to work in the first place. This could be made more clear (I spent some time wondering why doesn't the LSP server work for me before realizing this).

**Comment by ogoffart** [comment]
Thanks for filling an issue.
I've reworded the section in commit 6522ddb3ba2b600818e5b73f84f32f667b291f27.
I hope this is clear enough.
