### ISSUE TITLE
Incorrect font italicizing

### ISSUE THREAD

**Issue by LaoLittle** [slint-ui/slint#5056]
Hi.

I'm currently trying to display texts in different style at the same time.

The code is below:
```rust
slint::slint! {
    export component Main inherits Window {
        height: 500px;
        width: 500px;

        HorizontalLayout {
            Text {
                text: "ABCD";
                font-italic: true;
                font-size: 20px;
            }
            Text {
                text: "EFGH";
                font-italic: false;
                font-size: 20px;
            }
        }
    }
}

fn main() {
    Main::new().unwrap().run().unwrap();
}

```

What I expected is that the text on the left is italic while that on the right is non-italic.
However, the result is:
<img width="612" alt="Screenshot 2024-04-14 at 22 23 33" src="https://github.com/slint-ui/slint/assets/93422095/b48ce732-9e4a-4549-8b4b-2c9f79f9f894">

**Comment by tronical** [comment]
Thank you for the bug report. I think that this is indeed a bug in the femtovg renderer, not taking the style into account in the cached mapping to femtovg fonts.
