### ISSUE TITLE
Interactive animations

### ISSUE THREAD

**Issue by dumblob** [slint-ui/slint#506]
One of the quality measures of a UI library is how well it handles **layout in time**.

The best example is interactive animations with **mutually** influencing behavior - e.g. https://github.com/vlang/ui/issues/7#issuecomment-576256637 . Or imagine you'd need to "use sixtyfps app as *export format* for [Wick](https://www.wickeditor.com/#/ )".

Do you think it's possible? And what are the shortcommings (performance? any missing functionality? verbosity? ...)?

**Comment by hunger** [comment]
SixtyFPS definitely needs a UI editor! That should be perfectly doable.

What to base such a UI editor on is a open topic at this point.

**Comment by dumblob** [comment]
Sounds good to me. Though that'll be a lot of work (judging based on my experience with seeing the development of animations editors from Wick, Synfig, OpenToonz, etc.).

So I'd say let's start low. Could you maybe first prepare another *demo example* only focusing on this problem and showcasing advanced interactive animated behavior I outlined in the comment https://github.com/vlang/ui/issues/7#issuecomment-576256637 and then more e.g. from the Red Spaces (see below)?

Basically this can be viewed as generic capability to represent efficiently (both code size wise and performance wise) a game-like 2D fully interactive animated application with fully destroyable & constructible widget/entity instances.

I always like to show how such only moderately advanced examples e.g. from the project https://gitlab.com/hiiamboris/red-spaces might look like (advanced interaction like animated drag & drop, advanced mutually influencing animations, etc.).

**Comment by ogoffart** [comment]
As hunger said, we do plan to write a UI editor and it will have animations.  
I'm closing this issue because it is inactionable.

The GUI editor is tracked in https://github.com/slint-ui/slint/issues/695
