### ISSUE TITLE
is it possible to express a tree in this type system?

### ISSUE THREAD

**Issue by srgtmshnk** [slint-ui/slint#5098]
I am trying to implement some kind of tiling window manager in slint for my internal widgets. My rust code will determine the layout, so i need to have a tree type to express something like this:

<img width="1280" alt="Screenshot 2024-04-18 at 21 19 22" src="https://github.com/slint-ui/slint/assets/64617713/fe2bee62-ec91-4977-ab4a-163a0e8414fa">

in Elm, i would just write a simple recursive sum type:
```elm
type Orientation
    = Vertical
    | Horizontal


type Layout a
    = One a
    | Two Orientation (Layout a) (Layout a)
```

but in slint, i have literally no idea how to do this. i couldnt find a nullable type (Option in rust), i couldnt find a way to make recursive structs, and even if i somehow express a tree, idk if there will be a way to traverse it to draw the grid. What should I do in this situation?

**Comment by ogoffart** [comment]
This is currently not yet supported.
This is already tracked in issue https://github.com/slint-ui/slint/issues/4218
Closing as duplicated, but thanks anyway for reporting the issue
