### ISSUE TITLE
Path: Can't parse commands containing scientific notation

### ISSUE THREAD

**Issue by MohaBeacon** [slint-ui/slint#5100]
d_1-1393 := Path { /* Vector */
                    width: 16.163153px;
                    height: 4.441632px;
                    x: 45.07733px;
                    y: 28.728516px;
                    commands: "M1.92124 0.571029C2.05063 0.32349 2.21378 0.0309423 2.52321 0C2.81857 0.092827 2.95921 0.385375 3.0858 0.641352C3.69339 1.90999 4.31505 3.17018 4.92546 4.43601C4.64416 4.43601 4.36568 4.42757 4.0872 4.42194C3.89592 4.01125 3.69339 3.609 3.49367 3.20113C2.9142 3.19269 2.33193 3.1955 1.75246 3.1955C1.88186 2.93671 2.01688 2.68073 2.15752 2.42757C2.47257 2.43601 2.79043 2.43882 3.10548 2.43882C2.89733 2.01407 2.68354 1.58931 2.46976 1.16737C1.90717 2.25598 1.37834 3.36146 0.80169 4.44163C0.53446 4.43601 0.267229 4.43319 0 4.43319C0.632911 3.14205 1.27708 1.85935 1.91843 0.57384M5.76653 0.0281311C5.98031 0.0281311 6.19409 0.0281311 6.40788 0.0281311C6.41069 1.49649 6.40788 2.96484 6.40788 4.43319C6.19128 4.43319 5.9775 4.43319 5.76371 4.43319L5.76371 0.0281311M7.63151 0.0281311C8.60478 0.0421958 9.57806 1.63053e-06 10.5513 0.0478216C11.2743 0.0872028 11.8875 0.711675 11.8987 1.44023C12.0056 2.16315 11.5696 2.86639 10.9001 3.13361C11.2658 3.56399 11.6287 4 11.9887 4.43601C11.6737 4.43601 11.3615 4.43601 11.0464 4.43601C10.706 4.0225 10.3685 3.61182 10.0253 3.20113C9.56962 3.20113 9.11392 3.20113 8.66104 3.20394C8.65823 2.94796 8.65542 2.6948 8.65542 2.44163C9.33896 2.4135 10.0309 2.50633 10.7089 2.391C11.4149 2.21097 11.4205 0.984529 10.6892 0.846695C9.8903 0.759494 9.08298 0.832631 8.27848 0.810128C8.27848 2.01969 8.27848 3.23207 8.27848 4.44163C8.06188 4.44163 7.8481 4.44163 7.63432 4.44163C7.63432 2.97328 7.63432 1.50492 7.63432 0.0365696M12.9958 0.0281311L16.1632 0.0281311C16.1632 0.286922 16.1632 0.54571 16.1632 0.804501C15.3221 0.804501 14.481 0.804501 13.6399 0.804501C13.6399 1.75527 13.6399 2.70605 13.6399 3.65964C14.481 3.65964 15.3221 3.65964 16.1632 3.65964C16.1632 3.91561 16.1632 4.17159 16.1632 4.43038C15.1055 4.43882 14.0506 4.43319 12.993 4.43601L12.993 0.0281311M13.9044 1.80872L15.9831 1.80872C15.9831 2.06751 15.9831 2.3263 15.9831 2.58509C15.2911 2.58509 14.5992 2.58509 13.9072 2.58509C13.9072 2.3263 13.9044 2.06751 13.9072 1.80872";
                    fill-rule: nonzero;
                    stroke-width: 1px;
                    fill: #636467ff;
                }

not able to view this but in general svg command same values are working fine

**Comment by ogoffart** [comment]
The error is
```
Error parsing SVG commands (Line 0 Column 818: Expected number, got "e-06".)
```

I think this may be an issue with the figma importer that it generates number like `1.63053e-06`

**Comment by ogoffart** [comment]
Well, this is actually verbatim what comes out of figma.
So maybe it's a problem with the SVG parser in Slint.

**Comment by ogoffart** [comment]
Submitted an issue to the upstream crate we use for path parsing:
https://github.com/nical/lyon/issues/895
