### ISSUE TITLE
A bug with booleans, rust slint.

### ISSUE THREAD

**Issue by Sorinca** [slint-ui/slint#5132]
Hi, this is on a windows intel machine, I am codding in rust. When I write this bit of code it throws this error
------------------------------------------------------------------------------------------------------------------------------------------------------
init => { 
            if Intermediar-elev.new==true{
                Intermediar-elev.new=false;
            }
            if Intermediar-elev.new==false{
                Intermediar-elev.state==false;
            }
        }

------------------------------------------------------------------------------------------------------------------------------------------------------
error[E0605]: non-primitive cast: `()` as `bool`
    --> C:\Users\sami2\Desktop\da\da\biblioteca\target\debug\build\biblioteca-6a35604a473275b1\out\appwindow.rs:8087:22
     |
8087 | /                      ({
8088 | |                          }
8089 | |                     ) as _ }
     | |__________________________^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object
------------------------------------------------------------------------------------------------------------------------------------------------------
I use the bools elsewhere and its fine and after deleting is inside the init it compiles ok. I am up to provide more information if asked. 
Sorry for my bad english.
Thanks.

**Comment by Sorinca** [comment]
It was because I was using the "==" instead of "=" on "Intermediar-elev.state==false;". I am stupid.

**Comment by Sorinca** [comment]
yap

**Comment by ogoffart** [comment]
Thanks for reporting a bug. 
Compilation error in the generated code is a bug in Slint because it should have either been a compilation error in the Slint code, or be accepted.
In this case, this bug was already fixed in commit 028d075199515464373540ee5eeff182560f1c19 (issue #4942)
But thanks anyway for reporting.
