### ISSUE TITLE
Android: default-font-family not work

### ISSUE THREAD

**Issue by Heng30** [slint-ui/slint#5143]
- platform: Android
- Android target sdk version: 32
- language: Rust
- slint version: v1.5.1
- style: material
- code snippets. It works on Linux, but not works on Android
```
import "./fonts/SourceHanSerifCN.ttf";

export global Theme  {
    in-out property<length> default-font-size: 20px;
    in-out property<string> default-font-family: "SourceHanSerifCN";
}

export component AppWindow inherits Window {
    default-font-size: Theme.default-font-size;
    default-font-family: Theme.default-font-family;
}
```

**Comment by ogoffart** [comment]
Thanks for filling a bug.

default-font-family works for me on android. (I did not tried with that specific font, but I confirmed that it worked with the Plaster from the slide_puzzle demo)
I can't think of any reason why it wouldn't work.
Do you have more details on why it is not working? Is there any log that could be helpful to debug the issue?

**Comment by Heng30** [comment]
I try the Plaster font and it work fine. So I think the promble is from the font name. I use the ` fc-scan` tool to extract the font information and find that I set the `postscriptname` for the `slint-ui font-family` . This wrong setting work fine on linux, but no for android. After I set the correct  font-family, the problem has been solved.

**Comment by tronical** [comment]
Do I understand correctly that when using the correct font name it works for you now on Linux as well as Android?

**Comment by tronical** [comment]
Thanks for confirming :)
