### ISSUE TITLE
Text blurry with femtovg renderer

### ISSUE THREAD

**Issue by CryZe** [slint-ui/slint#5177]
I just tried slint for the first time. In general I judge the usability of a GUI framework based on how well it handles text, and while I noticed a few problems, it seems like font fallback and some IME support is there, which surprised me positively. Nevertheless one of the most common issues with text is unclear rendering. Turns out that it's particularly bad here in slint with the default femtovg renderer.

I however already figured out the problem. It turns out that the text is not aligned to the pixel grid. So when femtovg blits the glyphs from its glyph atlas, it uses a bilinear filter. So if the text is off by half a pixel you essentially get two source pixel averaged together per target pixel, meaning you effectively reduce the resolution of the text by half.

![image](https://github.com/slint-ui/slint/assets/1451630/02059925-aeff-41f5-ba3e-b182ece2b2ad)

The left is the default text rendering with femtovg and the right is me having patched femtovg to use nearest neighbor for their glyph atlas (you can do so via the `ImageFlags` [here](https://github.com/femtovg/femtovg/blob/4e40a61f824a8ea1bd361b4d227a2187e912124a/src/text.rs#L1164)).

Now I don't know if that's the actual solution, but it at least worked around the problem for the most part. There's still some rare edge case where the two triangles making up each glyph end up blitting the texture off by 1 pixel respectively.

**Comment by tronical** [comment]
Great summary and analysis - makes a lot of sense to me. We can fix that in FemtoVG. I wonder though if it should be unconditionally nearest neighbour or if linear filtering may be desirable in some scenarios (say when blitting with a transformation). But perhaps for now flipping the default is the choice that makes the default much better and can be adjusted later if needed.

**Comment by tronical** [comment]
I can confirm that your proposed fix works. This indeed also fixes #4868

**Comment by tronical** [comment]
Thanks again @CryZe ❤️
