### ISSUE TITLE
Updating the `model` of a `ComboBox` does not change the currently displayed text

### ISSUE THREAD

**Issue by kyp44** [slint-ui/slint#5214]
Changing the `model`, i.e. the list of options, in a `ComboBox` does not also change affect the `current-index` or the `current-value`. [Here](https://slintpad.com/?snippet=import+%7B+Button%2C+VerticalBox%2C+ComboBox+%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Demo+%7B%0A++++VerticalBox+%7B%0A++++++++combo+%3A%3D+ComboBox+%7B%0A++++++++++++model%3A+%5B%22Ex+1%22%2C+%22Ex+2%22%2C+%22Ex+3%22%2C+%22Ex+4%22%5D%3B%0A++++++++%7D%0A++++++++Button+%7B%0A++++++++++++text%3A+%22Change%22%3B%0A++++++++++++clicked+%3D%3E+%7B%0A++++++++++++++++combo.model+%3D+%5B%22Test+1%22%2C+%22Test+2%22%2C+%22Test+3%22%5D%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native) is an demonstration of the issue in SlintPad.

In particular, the text in the box still shows the selected value from the previous model. Clicking the box and selecting one of the new items will fix the issue. Closing the selection box without making a new selection results in the text from the old model still being displayed.

It is possible that this is the intended behavior, but it seems to me that changing the model should also do the following:
1. Set the `current-value` to the text of first item in the new model so it at least is consistent with the new model.
2. Set the `current-index` either to 0 (the first new item) or  -1 (no item selected).

For what it's worth, I am using Rust in both Windows and Linux, and this issue occurs on all platforms (including SlintPad). For now I have a workaround that performs the above steps, but it is a bit hacky and manual, but will made easier and more automatic once [this feature](https://github.com/slint-ui/slint/issues/112) is fully implemented and released.

**Comment by FloVanGH** [comment]
Hi and thank you for your report. This is definitively a bug and should work out of the box. We should now able to fix it with #5159.
