### ISSUE TITLE
Android: LineEdit indicator can not hide

### ISSUE THREAD

**Issue by Heng30** [slint-ui/slint#5233]
- Android
- Rust
- Slint v1.6
- Reproduce: 
> tap the LineEdit input area, it will show the indicator. I don't input any word and call the `clear-focus ()`. The LineEdit would lost the focus, but the indicator not hide.

![default](https://github.com/slint-ui/slint/assets/14201585/7bb26a3d-f205-444e-8a09-a24cac19ac4b)

**Comment by ogoffart** [comment]
Thanks for the bug report!

Fixed in commit https://github.com/slint-ui/slint/commit/a1e7f85892e98aefb7284aca64256f6815375ce7
