### ISSUE TITLE
OpenGL Underlay in Skia Backend Leads to Font Bugs and Rendering Issues

### ISSUE THREAD

**Issue by axojhf** [slint-ui/slint#5282]
I am programming in C++ on Windows 10 22H2.

I attempted to integrate a video player by referring to the 'opengl_underlay' project in the examples. I noticed that under the condition where SLINT_BACKEND is set to 'winit-skia-opengl', the font rendering appears as follows, while it becomes normal when switched to 'winit-femtovg'.

winit-skia-opengl:
![winit-skia-opengl](https://github.com/slint-ui/slint/assets/20625305/e6ebdc58-6f82-46fc-9f5b-374776da73c0)

winit-femtovg:
![image](https://github.com/slint-ui/slint/assets/20625305/1ed723f7-2124-4cfa-b75d-c7d7ce4d50ce)

Additionally, I have observed that the images rendered under 'winit-skia-opengl' exhibit more jagged edges.
I apologize that English is not my native language; some expressions may not be precise enough.

**Comment by tronical** [comment]
Are you using Windows inside a virtual box virtual machine by chance?

**Comment by axojhf** [comment]
No, I am running it on my laptop with an Intel UHD 620 GPU.
When OpenGL Underlay is not used, the font rendering is normal.

**Comment by tronical** [comment]
Ahh thanks. I missed that. If you see this issue then your OpenGL underlay isn’t restoring the OpenGL state exactly as it was when finished. For example, are to changing the current VAO?

**Comment by axojhf** [comment]
Thank you, the text display has become normal after I modified the code in the following way:
```c++
glGetIntegerv(GL_TEXTURE_BINDING_2D,&texture);
render();
glBindTexture(GL_TEXTURE_2D,texture);
```

**Comment by tronical** [comment]
👍👍
