### ISSUE TITLE
Qt backend clipping issue with StandardTableView

### ISSUE THREAD

**Issue by InakiBF** [slint-ui/slint#5285]
I have a problem in rust and linux. The text in the odd rows is mounted between columns in the StandardTableView.
![image](https://github.com/slint-ui/slint/assets/168820205/1ce63242-40db-4fdf-9c52-55f1af385498)

**Comment by InakiBF** [comment]
The same problem with the repository gallery example:
![image](https://github.com/slint-ui/slint/assets/168820205/3f1ce40f-0eac-438a-98b7-0da19a047c18)

**Comment by FloVanGH** [comment]
Hi, thank you for your report. It looks like the `qt` style. I cannot reproduce it with qt style on macos. Have you the same issue with an other style? Can you try to run the gallery with `SLINT_STYLE=fluent cargo run -p gallery`

**Comment by InakiBF** [comment]
With Fluent style no problem
![imagen](https://github.com/slint-ui/slint/assets/168820205/193e2a00-bacf-4d54-bc9a-6aa92b0c2351)

**Comment by ogoffart** [comment]
This is a problem in the Qt backend, looks like the cells are not properly clipped.
