### ISSUE TITLE
Live preview window is not closeable in vscodium (KDE)

### ISSUE THREAD

**Issue by plazmoid** [slint-ui/slint#5314]
Steps to reproduce:
- clone example repo: https://github.com/slint-ui/slint-rust-template
- open preview window using "Show preview" button
- close window via mouse or alt+f4
Window hangs and stops responding until the next "Show preview" click. Only able to close it with closing vscoduim first.

Environment:
Arch linux 6.9.1-arch1-2
KDE Plasma 6.0.4
VSCodium 1.85.2
Slint extension for vscode 1.6.0 https://open-vsx.org/extension/Slint/slint
Rust 1.78.0

**Comment by ogoffart** [comment]
Thanks for filling a bug.
This is a known issue with wayland. It is a side effect of https://github.com/slint-ui/slint/issues/4225 
I'm going to close this as a duplicate, but thanks anyway for reporting.
