### ISSUE TITLE
slint winit: unrecognized renderer skia, falling back to FemtoVG

### ISSUE THREAD

**Issue by wang-zhichuang** [slint-ui/slint#5330]
1、win11 $Env:SLINT_BACKEND="winit-skia" 
2、cargo run
3、slint winit: unrecognized renderer skia, falling back to FemtoVG

What do I need to configure to use the skia backend

**Comment by sdegongzuo** [comment]
So how to solve this problem?

**Comment by tronical** [comment]
You need to add `renderer-skia` to your feature flags with the `slint` crate in your `Cargo.toml`. Similar to this: `slint = { version = "1.8.0", features = ["renderer-skia"] }`

**Comment by sdegongzuo** [comment]
> You need to add `renderer-skia` to your feature flags with the `slint` crate in your `Cargo.toml`. Similar to this: `slint = { version = "1.8.0", features = ["renderer-skia"] }`您需要使用`Cargo.toml`中的`slint`crate将`renderer-skia`添加到特性标志中。类似于： `slint = { version = "1.8.0", features = ["renderer-skia"] }`

thanks
