### ISSUE TITLE
Stabilize full-screen rotation in the renderer

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#5372]
We've had an implementation of full screen rotation in the software renderer since Slint 1.3 (IIRC) but it remained experimental.
It's time to stabilize it.

### Use cases
 - Have the screen rotated when the shared buffer is in shared memory and there is no hardware rotation
 - On low-level hardware with line by line renderer, it is possible to instruct the renderer to render from left to right or right to left or bottom to top, so that it is possible to simulate a transition between screen in the right direction.
 
### Current API

 - Rust RenderingRotation enum
 
https://github.com/slint-ui/slint/blob/318c80b4f24c1196cb25180d74484146147d1876/internal/core/software_renderer.rs#L70-L85

 - Getter an setter in `SoftwareRenderer`

```rust
impl SoftwareRenderer {
    /// Set how the window need to be rotated in the buffer.
    ///
    /// This is typically used to implement screen rotation in software
    pub fn set_rendering_rotation(&self, rotation: RenderingRotation) { ... }

    /// Return the current rotation. See [`Self::set_rendering_rotation()`]
    pub fn rendering_rotation(&self) -> RenderingRotation { ... }
}
```

 - Similar API in C++  (in class SoftwareRenderer)
 
 https://github.com/slint-ui/slint/blob/318c80b4f24c1196cb25180d74484146147d1876/api/cpp/include/slint-platform.h#L724-L741

 - The FemtoVG and Skia renderer also have support for rotation, but it's different:
 
 https://github.com/slint-ui/slint/blob/318c80b4f24c1196cb25180d74484146147d1876/internal/renderers/femtovg/lib.rs#L567-L574

### Options

We could stabilize the API as is. But the questions are:

#### Should the rotation be a property of the Window instead of the Renderer?

It would make sense to have that a property of the Window. In that case, the physical size might be the transposed of the logical size. But this also make the conversion of a physical point to logical point more difficult for the event handler and such as they need to know not only the scale factor, but the rotation and size of the window.

Right now with the current experimental API, it's impossible to implement rotation in the winit back-end for example, because the physical size of the window has to match what's reported to the window manager. and therefore that's the size of the buffer. But the Slint's width and height are linked to the window's logical size and must be transposed.

A proposed API would be:
 - A WindowEvent to rotate the window
 - The conversion between physical and logical size/position needs to take a window reference instead of a scale factor.
 - A getter in the window for the rotation
 
Then the renderer would use the window rotation when rendering.

This is a bit more complicated than the current implementation (bugger API surface change).
The question is whether this is something we want to support (rotation on backend that have a window manager and need to also rotate between physical and logical window coordinate). Every use is limited for backend with full screen rotation where the window don't really play a role.

#### Should the rotation be an option given in an overload to the `render` function instead of as a state in the renderer?

Since we need to give the right kind of buffer to the render function (height×width instead of width×height), it is really a property of the render function rather than a state in the renderer. itself. We could have an overload with a RenderOptions struct (but not sure what else would go in there. buffer age? extra dirty region? extra clip?). Or a `render_with_rotation` 
The statefull API means we need to use interior mutability and that the user must ensure that the right state when doing rotation. But it is otherwise easy to use.

Does that mean we'll also do the same for femtovg and skia if we stabilize that?

**Comment by tronical** [comment]
We discussed this and concluded that we'll keep the `RenderingRotation` enum and in the software renderer keep the `set_rendering_rotation()/rendering_rotation()` functions.
