### ISSUE TITLE
Placing @children in PopupWindow doesn't work

### ISSUE THREAD

**Issue by floers** [slint-ui/slint#5375]
Platform: Linux, WASM
Language: Slint (Rust)

When using `@children` inside a `PopupWindow` the children aren't placed inside the popup window. This worked in 1.5 but doesn't work in 1.6 anymore.

Here is a slintpad with an code example: [example](https://slintpad.com/?snippet=component+Dropdown+inherits+Rectangle+%7B%0A%0A++++in-out+property+%3Cstring%3E+text%3B%0A%0A++++height%3A+2rem%3B%0A++++width%3A+10rem%3B%0A++++border-color%3A+black%3B%0A++++border-width%3A+1px%3B%0A%0A++++popup+%3A%3D+PopupWindow+%7B%0A++++++++x%3A+0px%3B%0A++++++++y%3A+2.1rem%3B%0A++++++++width%3A+10rem%3B%0A++++++++Rectangle+%7B%0A++++++++++++border-color%3A+black%3B%0A++++++++++++border-width%3A+1px%3B%0A++++++++++++VerticalLayout+%7B%0A++++++++++++++++padding%3A+0.5rem%3B%0A++++++++++++++++%40children%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%0A++++Text+%7B%0A++++++++text%3A+text%3B%0A++++%7D%0A%0A++++t+%3A%3D+TouchArea+%7B%0A++++++++clicked+%3D%3E+%7B%0A++++++++++++popup.show%28%29%0A++++++++%7D%0A++++%7D%0A%7D%0A%0Aexport+component+Demo+%7B%0A++++width%3A+400px%3B%0A++++height%3A+300px%3B%0A%0A++++VerticalLayout+%7B%0A++++++++alignment%3A+start%3B%0A%0A++++++++Dropdown+%7B%0A++++++++++++text%3A+%22foo%22%3B%0A++++++++++++Text+%7B%0A++++++++++++++++text%3A+%22Option+1%22%3B%0A++++++++++++%7D%0A++++++++++++Text+%7B%0A++++++++++++++++text%3A+%22Another+Option%22%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native)

And here is just the code example:
```
component Dropdown inherits Rectangle {

    in-out property <string> text;

    height: 2rem;
    width: 10rem;
    border-color: black;
    border-width: 1px;

    popup := PopupWindow {
        x: 0px;
        y: 2.1rem;
        width: 10rem;
        Rectangle {
            border-color: black;
            border-width: 1px;
            VerticalLayout {
                padding: 0.5rem;
                @children
            }
        }
    }

    Text {
        text: text;
    }

    t := TouchArea {
        clicked => {
            popup.show()
        }
    }
}

export component Demo {
    width: 400px;
    height: 300px;

    VerticalLayout {
        alignment: start;

        Dropdown {
            text: "foo";
            Text {
                text: "Option 1";
            }
            Text {
                text: "Another Option";
            }
        }
    }
}
```

The 1.6.0 release notes mention some work on placing `@children` in https://github.com/slint-ui/slint/issues/4935. Maybe this is related.

**Comment by Vadoola** [comment]
I might have encountered this bug as well. I had some rough code for adding tooltips in my program. It used `@children` inside of a popup window.

When I upgraded to 1.6 this seemed to partially break. However the code wasn't fully functional to begin with, so I just commented it out and went to work on other things without digging too deep.

**Comment by ogoffart** [comment]
Thanks both for reporting the issue.

I bisected the change and this is caused by commit 12d904a71ca31f947bfe983e7dbfe745b2439b74

Indeed, the change does change the order between PopupWindow "extraction" and children inlining. So the @children is now in the wrong place.

This could be fixed. However it is still a bit akward to put children in a PopupWindow. It sould be borbidden for the same reason that it should be forbidden to put them in `if` or `for` as you get the error from bug https://github.com/slint-ui/slint/issues/4438 when trying to access properties of that element.

**Comment by floers** [comment]
I feared that you would mark this as forbidden. I could create a Dropdown like above either with a fixed data model or if it's enough by just adding a vec of strings for entries. But it is very nice to have composability like before. A dropdown is much more generic that way as each consumer can define how options look like. Similar to what TailwindCSS's [Headless UI](https://headlessui.com/) does. For me these patterns are a huge productivity booster.

So if it's out of scope today I can relate but being able to do smth like would elevate slint soo much above other frameworks for me.
