### ISSUE TITLE
[FEATURE REQUEST] ability to add structs as fields of structs

### ISSUE THREAD

**Issue by Areopagitics** [slint-ui/slint#5414]
Would it be possible to do something like this? 
Thank you! Keep up the good work!

```
export struct File {
    name: string,
    parent_folder: Folder,
    file_path: string,
    checked: bool,
    file_id: int,
}

export struct Folder {
    name: string,
    file_children: [File],
    folder_path: string,
    checked: bool,
}
```

**Comment by kanashimia** [comment]
This is basically two feature requests:
1. Allow to use structures before they are defined.
2. Add recursive data structures.

Second one is a duplicate of https://github.com/slint-ui/slint/issues/4218
You can work around this by storing indices to an array instead, like you do in rust.

**Comment by ogoffart** [comment]
Thanks for filling an issue and thanks @kanashimia for already replying.
I'm going to close this as a duplicate of #4218
