### ISSUE TITLE
renderer-software vs software-renderer

### ISSUE THREAD

**Issue by Murmele** [slint-ui/slint#5520]
In this file the feature is called `software-renderer` but looking at some documentation (https://github.com/slint-ui/slint/blob/02c43c66bdd8a5b119266e9083fcfb84b3e9ca19/api/rs/slint/mcu.md?plain=1#L32) it is called `renderer-software`. Is this intended?
https://github.com/slint-ui/slint/blob/02c43c66bdd8a5b119266e9083fcfb84b3e9ca19/internal/core/lib.rs#L45

**Comment by ogoffart** [comment]
The public feature in the `slint` public crate is called `renderer-software` by compatibility with the other `renderer-*` features.

But it enable a private feature called software-renderer

https://github.com/slint-ui/slint/blob/02c43c66bdd8a5b119266e9083fcfb84b3e9ca19/api/rs/slint/Cargo.toml#L156

**Comment by Murmele** [comment]
Thanks for the clarification
