### ISSUE TITLE
Windows 10 window resize and maximize wonky

### ISSUE THREAD

**Issue by L0uisc** [slint-ui/slint#554]
I don't know if it is related or similar, but I have the following issue with window resizing with the memory game tutorial:

![sixtyFPS_bug](https://user-images.githubusercontent.com/38226392/136283456-ec3d6157-0a9b-438b-886d-3bf60a883e94.gif)

I cannot resize, but the window does not become invisible when I try.

The window does not get maximized when clicking the "maximize" button. Instead, it is resized to the screen size, but not positioned correctly. Part of the window is thus off-screen. When I then click Maximize again, it does get maximized. Restoring down then also works normally.

OS: Windows 10
sixtyFPS: 0.1.3
rustc: 1.54

_Originally posted by @L0uisc in https://github.com/sixtyfpsui/sixtyfps/issues/553#issuecomment-937146128_

**Comment by L0uisc** [comment]
Ok no, your tutorial only leaves a rather large margin around the right and bottom of the tiles. I made the main window dimensions 286px and the tiles fit snugly as expected.

**Comment by ogoffart** [comment]
Fixed by https://github.com/slint-ui/slint/pull/642
