### ISSUE TITLE
Auto disable maximize button when window resize is disabled

### ISSUE THREAD

**Issue by teknalb** [slint-ui/slint#5565]
Currently when ```width``` and ```height``` properties of the ```Window``` are set, resizing is automatically disabled, this is expected behavior. what is not expected is the maximize button stays enabled which defies the purpose of setting hard window dimensions.

**Comment by ogoffart** [comment]
Thanks for filling a bug.
We should be disabling the resizing in winit if the width and height property are set: 
https://github.com/slint-ui/slint/blob/882cbd15413c271e6fc80fdfb314a706dad38747/internal/backends/winit/winitwindowadapter.rs#L844

This should, in turn, (accoding to the issue you pointed out in winit) disable the maximize button.  I don't know why it doesn't work

**Comment by ogoffart** [comment]
What platform are you using? And if linux, is it x11 or wayland?

**Comment by dmaluev** [comment]
Looks like it is broken in 1.12.1. Maximize button is active in Windows 10.

**Comment by teknalb** [comment]
@dmaluev 

It's already fixed for the next release, see the [changelog](https://github.com/slint-ui/slint/blob/958a4b0f4c1e3e149f47ec3263865f3263b195de/CHANGELOG.md?plain=1#L10)
