### ISSUE TITLE
use backend-linuxkms and renderer-software error

### ISSUE THREAD

**Issue by yaobo-lab** [slint-ui/slint#5579]
My development board is linux arm64, using slint1.6 with rust as the backend。

Running the program failed：
`[clap_builder::parser::validator]Validator::validate_required: is_exclusive_present=false
[clap_builder::parser::arg_matcher]ArgMatcher::get_global_values: global_arg_vec=[]
main init
HorizontalLayout init
gbm: failed to open any driver (search paths /usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/rockchip_dri.so: cannot open shared object file: No such file or directory
failed to load driver: rockchip
gbm: failed to open any driver (search paths /usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory
failed to load driver: kms_swrast
gbm: failed to open any driver (search paths /usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory
failed to load swrast driver
thread 'main' panicked at src/main.rs:32:24:
called `Result::unwrap()` on an `Err` value: Other("Error creating gbm device: Success (os error 0)")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted`

![image](https://github.com/slint-ui/slint/assets/21329253/0dcb0367-b478-41c0-a04c-43f20bf2044f)

Cargo.toml ：

`[package]
name = "helloslint"
version = "0.1.0"
authors = [""]
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.5.7", features = ["derive", "debug"] } 
serde = { version = "1.0.203", features = ["derive"] }
serde_derive = "1.0.203" 
slint = "1.6"
lazy_static = "1.4.0"

[target.'cfg(target_os = "windows")'.dependencies]
slint = "1.6"

[target.'cfg(target_os = "linux")'.dependencies] 
slint = {version = "1.6", default-features = false,  features = ["compat-1-2", "backend-linuxkms-noseat", "renderer-software"] }

[build-dependencies]
slint-build = "1.6"
chrono = "0.4.38"
`

**Comment by tronical** [comment]
I think that your system is lacking gbm drivers:

```
init gbm: failed to open any driver (search paths /usr/lib/dri)
```

For OpenGL rendering we require GBM. For Vulkan based rendering we require Vulkan drivers with KHR_display extension support.

How did you configure your system's OpenGL driver?

**Comment by yaobo-lab** [comment]
> I think that your system is lacking gbm drivers:
> 
> ```
> init gbm: failed to open any driver (search paths /usr/lib/dri)
> ```
> 
> For OpenGL rendering we require GBM. For Vulkan based rendering we require Vulkan drivers with KHR_display extension support.
> 
> How did you configure your system's OpenGL driver?

I use the backend as： backend-linuxkms-noseat and render as： renderer-software ,if normal. These libraries are not needed。

here is my Cargo.toml config:
[target.'cfg(target_os = "linux")'.dependencies]
slint = {version = "1.6", default-features = false, features = ["compat-1-2", "backend-linuxkms-noseat", "renderer-software"] }

**Comment by tronical** [comment]
Ok, with that combination of features you should not see the error about gbm. When I try to set up a project like that, I also don't see the gbm crate in the dependencies.

Could you try running `cargo tree` and see if `gbm` shows up in the output for you?

Thanks :)

**Comment by yaobo-lab** [comment]
> Ok, with that combination of features you should not see the error about gbm. When I try to set up a project like that, I also don't see the gbm crate in the dependencies.
> 
> Could you try running `cargo tree` and see if `gbm` shows up in the output for you?
> 
> Thanks :)

Sorry, it was my Cargo.toml config error that caused it:
![image](https://github.com/slint-ui/slint/assets/21329253/8342cc19-a250-43bb-baf7-f5be83c2db0a)

But after I rebuilt it, another error：
```

[clap_builder::parser::validator]Validator::validate_required: is_exclusive_present=false
[clap_builder::parser::arg_matcher]ArgMatcher::get_global_values: global_arg_vec=[]
main init
HorizontalLayout init
thread 'main' panicked at src/main.rs:40:25:
called `Result::unwrap()` on an `Err` value: Other("No renderer configured")
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
/userdata #
```

It seems that the UI has already been initialized
![image](https://github.com/slint-ui/slint/assets/21329253/d20430b2-3a8a-4421-8e65-517055e6d452)

**Comment by tronical** [comment]
Thanks for the clarification, now I can see what's going on. You're using Slint 1.6 with the linuxkms backend and the slint software renderer enabled. Unfortunately, Slint 1.6 does not support the slint software renderer on linuxkms. That is a feature (#4334) that exists only in the master branch and will be part of the upcoming 1.7 release. At this point you have two options:

- You can switch to the git builds of Slint, by including the following in your `Cargo.toml`:
```
[patch.crates-io]
slint = { git = "https://github.com/slint-ui/slint" }
slint-build = { git = "https://github.com/slint-ui/slint" }
```
- Enable `renderer-skia` as a feature, which includes support for software rendering with Skia. This is already in the 1.6 release.

I'll close this issue as there's nothing actionable as far as I can see, but of course we can keep discussing here :)

**Comment by yaobo-lab** [comment]
> Thanks for the clarification, now I can see what's going on. You're using Slint 1.6 with the linuxkms backend and the slint software renderer enabled. Unfortunately, Slint 1.6 does not support the slint software renderer on linuxkms. That is a feature (#4334) that exists only in the master branch and will be part of the upcoming 1.7 release. At this point you have two options:
> 
> * You can switch to the git builds of Slint, by including the following in your `Cargo.toml`:
> 
> ```
> [patch.crates-io]
> slint = { git = "https://github.com/slint-ui/slint" }
> slint-build = { git = "https://github.com/slint-ui/slint" }
> ```
> 
> * Enable `renderer-skia` as a feature, which includes support for software rendering with Skia. This is already in the 1.6 release.
> 
> I'll close this issue as there's nothing actionable as far as I can see, but of course we can keep discussing here :)

That's great. Thank you very much
