### ISSUE TITLE
ComboBox: Popup height is not adjusting to items count

### ISSUE THREAD

**Issue by teknalb** [slint-ui/slint#5646]
![1](https://github.com/user-attachments/assets/f213311b-1294-4f4b-9391-4cf8ece80e92)

![2](https://github.com/user-attachments/assets/c71d4516-9170-42f6-a638-b33a1a15c48f)

Slint v1.7.0

**Comment by ogoffart** [comment]
Thanks for reporting a bug.

Can be reproduced with all the styles.

![image](https://github.com/user-attachments/assets/e4ae5794-a253-4aaa-a888-72c0e87bc2d4)
