### ISSUE TITLE
When using EmbedForSoftwareRenderer, cannot compile.

### ISSUE THREAD

**Issue by jonahnm** [slint-ui/slint#5684]
I get an error of ``` thread 'main' panicked at /home/sora/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-compiler-1.7.0/passes/embed_glyphs.rs:278:67:
 called `Option::unwrap()` on a `None` value```
System is GNU/Linux Arch.

**Comment by tronical** [comment]
Thanks for the report. I think I can see how this could happen, now that we support multiple windows.

**Comment by tronical** [comment]
Reproducer:

```slint
import "/path/to/NotoSans-Regular.ttf";
import "/path/to/NotoSans-Bold.ttf";

export component Diag inherits Window {
    default-font-family: "Noto Sans";
}

export component App inherits Window {
    default-font-family: "Noto Sans";
}
```

run with ` cargo run -p slint-compiler -- --embed-resources=embed-for-software-renderer /path/to/testcase.slint`

**Comment by jonahnm** [comment]
That was fast! Thanks!
