### ISSUE TITLE
LineEdit widget wrongly 100%

### ISSUE THREAD

**Issue by AXCWG** [slint-ui/slint#5694]
If I tried to fill the entire row using LineEdit widget it looks like this: 
<img width="612" alt="Screenshot 2024-07-26 at 12 06 12" src="https://github.com/user-attachments/assets/2f10ca13-8794-409e-8cb1-7761f20f9048">
At first I thought maybe that it was affected by padding or the percentage width of the groupbox but it still goes over when the width of the groupbox is set to 50% and removed line about padding: 
<img width="683" alt="Screenshot 2024-07-26 at 12 08 56" src="https://github.com/user-attachments/assets/aa780a0b-2368-4050-8c6a-1f8a698cb76e">

This is the AppWindow Code overview: 

    export component AppWindow inherits Window {
        preferred-width: 500px;
        preferred-height: 400px;
        GridLayout {
            padding: 10px;
            Row{
                HorizontalLayout {
                    GroupBox {
                        width: 49%;
                        title: "Java Options";
                        
                        VerticalLayout {
                            CheckBox {
                                text: "Use ZGC";
                            }
                            CheckBox {
                                text: "";
                            }
                            Rectangle {}
                            Text {
                                text: "Java Args";
                            }
                            
                                LineEdit {
                                    width: 100%;
                                    enabled: false;
                                    horizontal-alignment: TextHorizontalAlignment.left;
                                    input-type: InputType.text;
                                    placeholder-text: "None";
                                }
    
                            
                            
                        }
                    }
                    Rectangle {
    
                    }
                    
                    GroupBox {
                        title: "Client Options";
                        width: 49%;
                        
                        VerticalLayout {
                            Text {
                                text: "";
                            }
                        }
                    }
                }
            }
            Row{
                Rectangle {
                    background: blue;
                }
            }
        }
    }

**Comment by AXCWG** [comment]
btw, the slint preview can be pretty messed up in this scenario for some reason:
 
<img width="549" alt="Screenshot 2024-07-26 at 12 21 37" src="https://github.com/user-attachments/assets/c01b418d-daf9-48ad-9c7b-2d41cbd21587">

**Comment by ogoffart** [comment]
Thanks for filling an issue.

I think in general, there is a confusion as to what `%` sizes means when in layout.
`100%` means the size is the same size of the parent. If you have some padding, that's not really possible anymore. You probably shouldn't set the width because it should be set automatically.

The orther issue is that there is indeed a bug in size computation. This already has been reported as #3346. So i'm going to close this issue as Duplicated of #3346

But thanks anyway for reporting. And in your case I'd simply remove the width:100% when in layout and it should behave correctly.
