### ISSUE TITLE
Drag-and-drop editor can generate invalid .slint code on first insertion

### ISSUE THREAD

**Issue by mitchgrout** [slint-ui/slint#5695]
Start with a source file containing the following:

```js
export component ExportedComponent {
    
}
```

Using the graphical editor, drag a `Flickable` element onto the component. The `Flickable { }` node will be placed _outside_ the definition of `ExportedComponent`:

```js
export component ExportedComponent {
    
}
    Flickable { }
```

Interestingly, after manually removing this element, following insertions will occur in the correct place.
This can be triggered on both the LSP editor and SlintPad v1.7.1.

Edit: Reverting to LSP v1.7.0, this behaviour does not seem to occur. Further, it doesn't appear to be exclusive to `Flickable`; both `AboutSlint` and `Button` triggered the same issues.

**Comment by ogoffart** [comment]
Thanks for filling an issue.  I can reproduce the problem: it seems the problem happens if the closing brace is the last character of the file (without any newline or space or comment)
