### ISSUE TITLE
Opacity does not work on Image with Skia renderer

### ISSUE THREAD

**Issue by abalogstromer** [slint-ui/slint#5706]
I found an odd issue while trying to set opacity on the `Image` component. It would not change, did not matter what value I would set, it would always show like it was set to 1. 

I remembered that it worked in some other small examples I have done before. I retried them with latest Slint version and it still worked. After trying to reduce differences between main project and example, the only one remaining was the difference in renderer. After I set it to `Skia` also for the examples, it had the same behavior, the opacity would not change at all.

You can take any simple example with an Image inside and set the renderer to `Skia`, it would not work both in live preview and standalone app. Here is what I used:
```
export component MainWindow inherits Window {
    width: 400px;
    height: 400px;
     Image {
        source: @image-url("image.svg");
        opacity: slider.value ;
    }
    slider := Slider {
        y: parent.height - self.height;
        width: 200px;
        height: 25px;

        value: 0.0;
        minimum: 0.0;
        maximum: 1.0;
    }
}
```

And set `SLINT_FEATURE_RENDERER_SKIA=ON` and  `SLINT_FEATURE_RENDERER_FEMTOVG=OFF`.

**Comment by tronical** [comment]
Indeed. When skipping the layer for opacity (because only one child item), then the alpha is applied to the current state's alpha on the item renderer. That alpha is applied in brush_to_paint but not when drawing images 🤦‍♂️. This should be easy to fix :)
