### ISSUE TITLE
Cannot poll Tokio futures from Slint event loop

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#5733]
We document the lack of compatibility with Tokio at https://releases.slint.dev/1.7.1/docs/rust/slint/fn.spawn_local.html#compatibility-with-tokio-and-other-runtimes but it's unfortunately very easy to run into this and it complicates the use-case of updating the UI based on what a future provides much harder.

Example:

```rust
slint::slint! {
export component Dummy inherits Window {}
}

#[tokio::main]
async fn main() -> Result<(), slint::PlatformError> {
    // create a dummy to ensure a slint event loop works.
    let _dummy = Dummy::new()?;

    let (sender, mut receiver) = tokio::sync::mpsc::channel(2);

    tokio::spawn(async move {
        let mut count = 0;
        loop {
            if sender.send(count).await.is_err() {
                break;
            }
            count += 1;
        }
    });

    slint::spawn_local(async move {
        loop {
            let count = receiver.recv().await.unwrap();
            eprintln!("{count}");
            if count > 1024 {
                eprintln!("ok");
                break;
            }
        }
    })
    .unwrap();

    slint::run_event_loop_until_quit()
}
```

(run `cargo add slint` and `cargo add tokio --features full` in a new project)

This loop doesn't terminate after reaching the count 1024, instead it will hang at a value in-between.

As far as I can see from the back-traces, whenever we poll the tokio future in the callback invoked from `invoke_from_event_loop` from `FutureRunner::wake`, it first calls `wake()` _again_ on our `FutureRunner` and then returns `Pending`. This creates an infinite loop.

If there was a way to make this work, either out of the box or via some additional integration, then it would be much easier to write business logic that delivers data from tokio futures and update the UI directly within the future provided to `slint::spawn_local`. The documented alternative requires the use of `invoke_from_event_loop()` or `upgrade_in_event_loop()`.

Reproduced on macOS (winit) and Linux (with Qt and winit loop).

**Comment by ogoffart** [comment]
Indeed I can reproduce the bug.
I'm not quite sure why this works at the beginning. I'm not so familiar with the internals for the tokio runtime.
I think one should clearly not use `#[tokio::main]`. I mean, running the event loop in a thread managed by tokio can't work.
One could use tokio::main and then make slint in a thread, but that won't work.

What we document using `tokio_runtime.spawn` works:

```rust
fn main() -> Result<(), slint::PlatformError> {
    // create a dummy to ensure a slint event loop works.
    let _dummy = Dummy::new()?;

    let (sender, mut receiver) = tokio::sync::mpsc::channel(2);

    let tokio_runtime = tokio::runtime::Runtime::new().unwrap();
    tokio_runtime.spawn(async move {
        let mut count = 0;
        loop {
            if sender.send(count).await.is_err() {
                break;
            }
            count += 1;
        }
    });

   slint::spawn_local(async move {
        loop {
            let count = receiver.recv().await.unwrap();
            eprintln!("{count}");
            if count > 1024 {
                eprintln!("ok");
                break;
            }
        }
    })
    .unwrap();

    slint::run_event_loop_until_quit()
}

``` 

> If there was a way to make this work, either out of the box

I think running a the slint event loop in a tokio thread will never work.
(Unless the custom platform uses tokio itself for its event loop, but it will not work with winit backend AFAIK)

> box or via some additional integration

We could try to have some integration just to detect the problem and print a warning in the console. I don't know how we could implement that though.


I think the best we can do is to improve the docs and clearly state to not use `#[tokio::main]`

**Comment by tronical** [comment]
> > If there was a way to make this work, either out of the box
> 
> I think running a the slint event loop in a tokio thread will never work. (Unless the custom platform uses tokio itself for its event loop, but it will not work with winit backend AFAIK)

I agree that the slint event loop running in a tokio thread is out of scope. But it doesn't seem that the use of `#[tokio::main]` triggers that - quite in contrary. So if there was a way of "advancing" Tokio's tasks from our event loop, then there might be a way to make this work out of the box.
 
> > box or via some additional integration
> 
> We could try to have some integration just to detect the problem and print a warning in the console. I don't know how we could implement that though.

Would you oppose to depending on tokio weakly and detecting the presence of a run-time in the thread, and warning?
 
> I think the best we can do is to improve the docs and clearly state to not use `#[tokio::main]`

Given that this keeps happening I'm interested in something better - at least detection.

**Comment by tronical** [comment]
Ah, I guess it's not possible to "weakly" depend on tokio and detect its availability :(

**Comment by tronical** [comment]
I've found a solution. I'll document it first and make a separate PR for the integration feature.
