### ISSUE TITLE
Incorrect `SampleComponent` docs

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#5742]
Your [`SampleComponent` Rust docs](https://releases.slint.dev/1.7.1/docs/rust/slint/docs/generated_code/struct.samplecomponent) suggest that generated components implement `Send` and `Sync` (as well as `UnwindSafe` and `RefUnwindSafe`). But when running `cargo doc` on my project with a .slint file, my `struct MainWindow` shows `!Send`, `!Sync` etc. under "Auto Trait Implementations".

PS: [`Weak`](https://releases.slint.dev/1.7.1/docs/rust/slint/struct.weak) being `Send` is correct, right?

**Comment by tronical** [comment]
Good catch, thanks for the report :).

Yes, `Weak` being `Send` is correct and intentional.
