### ISSUE TITLE
`SLINT_DEBUG_PERFORMANCE` overlay not working with Skia

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#5764]
I'm on Windows 10 using Rust.

With FemtoVG it works, but with Skia setting the env var `SLINT_DEBUG_PERFORMANCE=refresh_full_speed,overlay,console` before executing `cargo run` renders no overlay at all. The console prints happen, though (they look a bit different: FemtoVG adds `details from last frame: [0 layers created]`).

**Comment by tronical** [comment]
I can confirm. This used to work, but that was before the FontMgr changes.
