### ISSUE TITLE
Animations stop when resizing or moving windows

### ISSUE THREAD

**Issue by XiongDa457** [slint-ui/slint#5791]
I made a my app have a custom GridLayout-like behavoir for displaying an arbitrary number of objects (since `GridLayout` doesn't support `for`). And I noticed that if I add animations to the objects, they stop moving until window resizing is over or the window stops being dragged.

No animations:

https://github.com/user-attachments/assets/402e1c4e-21c8-4e30-9272-5273f492ca75

With animations:

https://github.com/user-attachments/assets/59f15c74-7768-44ca-aa79-d7edf5421b1b

It might be slightly hard to tell, but when I start resizing or moving the window, the animation essentially freezes (but the it seems to still be progressing in the background), then when I let go the animation just resumes at a further point.

**Comment by Vadoola** [comment]
It's hard to tell from your video and you don't mention, are you running this on Windows?

If so I'm wondering if it's related to this bug: https://github.com/slint-ui/slint/issues/5720
I just added an animation tick example to my [sample repo](https://github.com/Vadoola/win_slint_event_loop_issue) and notice the same behavior when click the title bar or moving the window on the animation tick  example as I do on the event loop timer. I imagine it's all part of an issue with the event loop.

If you are running it on Windows have you tried on Linux? I don't seem to have this issue Linux.

**Comment by XiongDa457** [comment]
Sorry for not mentioning it earlier but yeah, I'm running on Windows. I don't have a Linux system to test this on so I can't really say anything about that.

I took a look at the issue you linked and it does seem like the same problem. I'm also manually recreating a title bar, and it seems like the event loop hangs whenever the window manager is involved, whether its moving, resizing, or right clicking the titlebar.

**Comment by Vadoola** [comment]
Maybe chime in on that bug and mention the resizing, so the information is all in the same place for whoever looks into fixing it.

**Comment by ogoffart** [comment]
Thanks for filing the issue. I'm going close this one as duplicated of #5720 which itself is a bug in winit.
