### ISSUE TITLE
flatpak zed and vscode report `slint::include_modules!();` rust-analyzer: failed to load file `UNRESOLVED_ENV_VAR`

### ISSUE THREAD

**Issue by xiaguangbo** [slint-ui/slint#5793]
err form `slint::include_modules!();`
only flatpak platform have this question. if install form `.deb``.rpm``.tar.gz` will normal.

**Comment by ogoffart** [comment]
thanks for filing a bug report, but i'm going to need more info. What error are you seeing exactly.

**Comment by xiaguangbo** [comment]
@ogoffart 
![screenshot-2024-08-08-07-19-28](https://github.com/user-attachments/assets/70123daf-57c0-48ea-84e6-45f2e2675a0f)

**Comment by xiaguangbo** [comment]
`cargo build` is can work, only editer software show err.

**Comment by ogoffart** [comment]
the include_modules uses an environment variable which is set through the slint-build crate that must be set in the build.rs.  Do you call slint_build::compile in your build.rs. Maybe that is failing. There is perhaps logs from rust analyzer somewhere.

**Comment by ogoffart** [comment]
right, so this should export the env variable used by the include_modules macro. run-analyzer should have run the build script. It is possible that it fails though. Maybe rust-analyzer has a log with the result of the build script.

**Comment by xiaguangbo** [comment]
@ogoffart

**Comment by Enyium** [comment]
Running the VS Code command palette command "Developer: Reload Window" fixed this for me.

**Comment by bluezheng** [comment]
Running Zed command palette command "workspace: reload" also fixed it
