### ISSUE TITLE
LSP: diagnostics from dependencies are not refreshed when something changes

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#5797]
Consider this case:

bar.slint:
```slint
export component Bar { }
```

reexport.slint:
```slint
export { Bar } from "bar.slint";
```

foo.slint:
```slint
import { Bar } from "reexport.slint";
export component Foo {
   Bar { hello: 42; } 
}
```

Of course, there there is an error in `hello:42` because that property don't exist.
Then add the property to bar.slint to fix the error with `in property <int> hello;`
but that doesn't fix the error. One must manually do dummy edits to both reexport.slint AND foo.slint to get the error to disappear.

**Comment by hunger** [comment]
I had hoped this was fixed by the improved handling of file versions, but it is not :-/

**Comment by ogoffart** [comment]
😟 maybe we can check in the language thread that the version is the latest before sending the diagnostic

**Comment by hunger** [comment]
This is about the parser not revisiting the files that did not change themselves.

**Comment by ogoffart** [comment]
I think what should be done here is that we need to maintain a graph of all the dependencies from one file to another file.
When a file is being updated, we need to reload all direct dependencies of that file.

I think it should be done asynchronously (queue all dependencies that needs reloading, and process that in a different "iteration" (try to poll the other futures, including the one that receive command from the client, between each file being reloaded). So that it doesn't cause too much delay when editing a file (and the whole world would need to be reloaded).
But cache cleaning could be done synchronously
