### ISSUE TITLE
panic when pressing Tab on a rolled-down ComboBox

### ISSUE THREAD

**Issue by meithecatte** [slint-ui/slint#5826]
1. `cargo run --release --bin slint-viewer -- examples/7guis/booker.slint`
2. click on the combo-box saying "one-way flight"
3. while the options are being shown, press Tab

```
thread 'main' panicked at internal/core/item_tree.rs:530:25:
Got an Item, expected a repeater!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

**Comment by ogoffart** [comment]
Thanks for taking the time to report an issue.
I can reproduce on Linux with the fluent style and the Qt backend (but not the winit backend)
