### ISSUE TITLE
Callback "edited" in TextEdit does not work

### ISSUE THREAD

**Issue by progzone122** [slint-ui/slint#5848]
Сallback “edited” does not work in TextEdit, but it works in LineEdit. It looks like a bug.

#### My PC info
**slint and slint-build version: 1.7.2**

![1723652657_grim](https://github.com/user-attachments/assets/8fed64a6-c8d1-4f9b-9b43-05f178d99920)

#### It's working:
```
LineEdit {
    edited(text) => {
         debug(text);
    }
}
```
![1723652308_grim](https://github.com/user-attachments/assets/289927a7-074f-450a-83df-a7e976293ebf)

#### Doesn't work:
```
TextEdit {
    edited(text) => {
         debug(text);
    }
}
```

![1723652515_grim](https://github.com/user-attachments/assets/26fe535c-ba59-4c07-97ae-ca78383baac4)

**Comment by rock16** [comment]
when are we expecting this "bug fix". it seems it has been fixed already or do I need to build from source for now.

**Comment by progzone122** [comment]
> when are we expecting this "bug fix"? it seems it has been fixed already or do I need to build from source for now.

Has already been fixed, but the release has not yet been published. If necessary, build from source code.
