### ISSUE TITLE
Allow printing enums (convert enum to string)

### ISSUE THREAD

**Issue by JakubKoralewski** [slint-ui/slint#5918]
I am checking enum exhaustibility in if statement, and would like to print out an enum. Something like Rust's #[derive(Default)] functionality would be nice.

Currently getting an error `cannot convert enum EnumName to string` when attempting to print the enum as a value in interpolated string.

```slint
enum EnumName {
    X
}
export component Demo {
    property <EnumName> e: EnumName.X;
    init() => {
        debug("\{e}");
    }
}
```

**Comment by ogoffart** [comment]
Thanks for the suggestion.
For debugging purposed, you can already do `debug(e)` , or `debug("the value is", e)`
But I don't know if it makes sense to convert enum to string (`Text { text: e; }`)

**Comment by JakubKoralewski** [comment]
Cool! Thanks. Should have checked it. That fulfills my use case then. Feel free to close at your discretion.
