### ISSUE TITLE
Preview: when clicking "show preview" the size of the preview adjust but not the frame

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#5954]
In the master branch only.

For example with this simple slint code:
```
component Bar {
    width: 100%;
    height: 100%;
    Rectangle { background: lime; }
}

export component Foo {
    Bar {}
}
```

Resize the preview to some random size.
Click "show preview" 
The preview resizes (to match a preferreed size which isn't set) (OK).
But the frames doesn't follow immediatly.

### Original comment

Right, the master branch SlintPad you linked doesn't have this error. However, there's the following succession of previews:

After first pasting the code:

![1](https://github.com/user-attachments/assets/64a8122f-4108-463e-83f3-c5f455632663)

After pressing "Show Preview" on `Bar` and then on `Foo`:

![2](https://github.com/user-attachments/assets/4fe4b5ba-b541-42a1-a8ce-99c97856794c)

After again pressing "Show Preview" on `Foo`:

![3](https://github.com/user-attachments/assets/f49dc06e-d7d0-44df-a6f7-9fd249fd3017)

_Originally posted by @Enyium in https://github.com/slint-ui/slint/issues/5949#issuecomment-2310379818_

*Edit*: Updated the code example to include Foo and Bar.

**Comment by hunger** [comment]
That's an interesting issue: In the middle picture the resize handles are in the right place, but the box that goes with those is not.
