### ISSUE TITLE
Have Math.atan2

### ISSUE THREAD

**Issue by NigelBreslaw** [slint-ui/slint#5998]
As the world of 2D graphics and slint often has minus values for x, y positions you have to be a bit more knowledge to deal with the output from Math.atan. Having atan2 where you can just put in both the x and y values to get an answer would be great.

**Comment by ogoffart** [comment]
Marked as a good first issue, because one can basically grep add a `BuiltinFunction::ATan2`. One can grep for `BuiltinFunction::ATan` to see all the place that needs changing.

**Comment by ogoffart** [comment]
Fixed in https://github.com/slint-ui/slint/pull/6004
