### ISSUE TITLE
StandardTableView hangs with high CPU usage when scrolling down in a large table

### ISSUE THREAD

**Issue by ezschemi** [slint-ui/slint#6007]
Using Rust on macOS 14.6.1 on a M3 MacBook Air with Slint 1.7.2.

I am currently evaluating Slint for usage in EDA software. One of the main features we need is giant tables with a few dozen columns but many millions of rows. The table cells won't need functions or anything, just a single character + background colors.

According to https://github.com/slint-ui/slint/issues/5041 this should be fixed in 1.7, but I still see it. 
As per https://github.com/slint-ui/slint/issues/5476 I disabled accessibility features, which did not help:
```
slint = { version = "1.7.2", default-features = false, features = ["backend-winit", "compat-1-2", "renderer-femtovg"] }
```

The data is programmatically filled from loading files. The sample application fills in dummy data instead:
```
let row_data: Rc<VecModel<slint::ModelRc<StandardListViewItem>>> = Rc::new(VecModel::default());
for r in 1..max_rows {
        let items: Rc<VecModel<StandardListViewItem>> = Rc::new(VecModel::default());

        items.push(slint::format!("{}", r).into());
        items.push("1".into());
        items.push("P".into());
        items.push("0".into());
        items.push("0".into());

        row_data.push(items.into());
    }
    main_window.global::<TableViewPageAdapter>().set_row_data(row_data.clone().into());
```

**Expected Behavior**
Scrolling works fine. A slight delay is fine as the number of rows is large.

**Actual Behavior**
With a Release build when scrolling, my simple application hangs with high CPU usage and does not recover.

Renderers used:
1. Skia: does not build on macOS for me
2. renderer-femtovg: hangs around 22M rows when scrolling
3. renderer-software: hangs around 16M rows when scrolling

Rust Project:

[rs-slint-2.tar.gz](https://github.com/user-attachments/files/16803041/rs-slint-2.tar.gz)

**Comment by ogoffart** [comment]
I think this is the same as https://github.com/slint-ui/slint/issues/3700
The problem here is that we use floating point for coordinate. And when you scroll past millions of pixels, the coordinate within the virtual viewport get so big that they can no longer represent the coordinate without too much innacuracy.
This causes bug in the llistview layout  where doing things like y + height would sill be == y and so it would loop infinitely recreating the same items.

**Comment by ezschemi** [comment]
I hadn't seen #3700. Looks like there is no easy fix for this.

**Comment by ogoffart** [comment]
Closing as duplicated of #3700 but thanks anyway for reporting the issue.
