### ISSUE TITLE
Math.mapRange()

### ISSUE THREAD

**Issue by NigelBreslaw** [slint-ui/slint#6018]
A common UI use case that needs a little bit of math and maybe too much math for UX people is mapping ranges. Say I want to map the x position of an animated items that move across the screen. I then want to translate this into an opacity value between 0 and 1 so the item fades away depending on how far over it is. 

These functions take in 5 arguments:
a) The incoming value. Say the X position of an image.
b) input start  e.g. 20.
c) input end e.g. 40.
d) output start e.g. 0.0
e) output end e.g. 1.0

In this situation the return value would be: 
if x is 20 or below return 0.
if x is 40 or over return 1.0.
if x is between 20 and 40 return the eqivelant point between 0 and 1.0. If x was 30 that would be 0.5.

In the short term this just working with floats would be enough, but it would be great if it did the right thing with various types.

**Comment by ogoffart** [comment]
Reminds me a bit of https://github.com/slint-ui/slint/pull/5317
But I don't know if this really warrant a function. I think the math to do that is simple enough. And it can be implemented in pure slint.

**Comment by NigelBreslaw** [comment]
I will close this. I will add it to the examples and my own UX bag of tricks functions. Let's see later if anything more is needed explicitly in Slint.
