### ISSUE TITLE
Color issues when using slint with ESP32-S3

### ISSUE THREAD

**Issue by metehus** [slint-ui/slint#6019]
Hello! I just got slint working on my esp32s3 project and it's amazing and looking very promissing! But there is a issue on it:
For context, I'm running on windows and using the GC9A01 display driver. The code is [here](https://github.com/metehus/esp32s3-slint-demo)

The thing is that the colors are very wrong. On the slint preview, it shows like this:
![image](https://github.com/user-attachments/assets/dbb026dd-d49b-4ba5-9c42-7aba4a23083f)
I've seen the issue about something similar. I've tried both but no success either. With `color_swap_16` as false:
<img src="https://github.com/user-attachments/assets/e5c7dca7-758e-4495-b283-b708dce83b9b" width=300/>

And with it set to true:
<img src="https://github.com/user-attachments/assets/773c08f6-db8a-4351-a2b9-82a4a72d2252" width=300/>

**Comment by metehus** [comment]
update: tried to change this value to `LCD_RGB_ELEMENT_ORDER_BGR` but no success
```cpp
            .rgb_ele_order = LCD_RGB_ELEMENT_ORDER_RGB,
```

**Comment by ogoffart** [comment]
I don't really explain it.
It looks like the wrong colorspace for sure.
I see that the sdkconfig constains `CONFIG_SOC_LCD_SUPPORT_RGB_YUV_CONV=y`, maybe that's related.
Could it be a difference between RGB555 and RGB565?

**Comment by metehus** [comment]
changing `CONFIG_SOC_LCD_SUPPORT_RGB_YUV_CONV` to `n` didn't change anything. In fact, it's red in the menuconfig, so I don't know if it's enabled or not. And what do you mean by this difference?

Also, I've seen that `esp_lcd_panel_dev_config_t` has a `data_endian` parameter, changing to `LCD_RGB_DATA_ENDIAN_BIG` or `LCD_RGB_DATA_ENDIAN_LITTLE` has also not worked

**Comment by metehus** [comment]
Got it! apparently this display driver needs to invert the colors. This worked:
```cpp
    const esp_lcd_panel_dev_config_t panel_config = {
            .reset_gpio_num = -1,      // Set to -1 if not use
            .rgb_ele_order = LCD_RGB_ELEMENT_ORDER_BGR,
            .data_endian = LCD_RGB_DATA_ENDIAN_BIG,
            .bits_per_pixel = 16,
    };

    ESP_ERROR_CHECK(esp_lcd_panel_invert_color(panel_handle, true));

    slint_esp_init(SlintPlatformConfiguration {
            .size = slint::PhysicalSize({ EXAMPLE_LCD_H_RES, EXAMPLE_LCD_H_RES }),
            .panel_handle = panel_handle,
            .buffer1 = buffer1,
            .color_swap_16 = true });
```

![image](https://github.com/user-attachments/assets/186ec97e-c878-4fdb-9a47-8c82b93b7f2a)
