### ISSUE TITLE
Incoherent default text color on software renderer

### ISSUE THREAD

**Issue by metehus** [slint-ui/slint#6035]
I noticed an issue regarding the default text color on software renderer. For example, I have this simple component with a text without defining the color. The text coloris white by default:
```slint
export component MainWindow inherits Window {
    width: 240px;
    height: 240px;
    background: blue;

    Text {
        text: "Hello world!";
        font-size: 25px;
    }
}
```
<img src="https://github.com/user-attachments/assets/7874d07f-34d7-4a7f-aa4c-c7367cd2c9cd" width=300 />

when rendering on the MCU, the text is black as default:
<img src="https://github.com/user-attachments/assets/610763c6-8b1e-4f0d-b8a4-db4340e6542e" width=300 />

When changing the color to white works, but I think the default color logic should match for both renderers

**Comment by ogoffart** [comment]
I'm pretty sure the problem here is because of light vs dark style.
On desktop, the default style will use the theme from the desktop environment.
I suggest forcing it to 'fluent-light' on both desktop and the device.

**Comment by metehus** [comment]
oh yeah that makes sense. my bad!
