### ISSUE TITLE
Add support for five pointing-device buttons

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6043]
Currently, `PointerEventButton` only supports three specific buttons. Others like the fourth and fifth are grouped together under `other`, rendering you unable to distinguish them. The Windows OS has built-in support for up to five buttons. It would be great to have access to all of them in Slint to support functionality like "back" and "forward". I propose the new variants `fourth` and `fifth`.

**Comment by ogoffart** [comment]
Makes sense.
The enum is declared there: https://github.com/slint-ui/slint/blob/e79dcc4bec7d099dd8b4ba96cf7ecaef38981e72/internal/common/enums.rs#L149
Then the backend need to emit these value from winit: https://github.com/slint-ui/slint/blob/e79dcc4bec7d099dd8b4ba96cf7ecaef38981e72/internal/backends/winit/event_loop.rs#L454 or qt: https://github.com/slint-ui/slint/blob/e79dcc4bec7d099dd8b4ba96cf7ecaef38981e72/internal/backends/qt/qt_window.rs#L591 or linuxkms https://github.com/slint-ui/slint/blob/e79dcc4bec7d099dd8b4ba96cf7ecaef38981e72/internal/backends/linuxkms/calloop_backend/input.rs#L212
