### ISSUE TITLE
Add support for obtaining font metrics for `Text` elements

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#6047]
`Text` element could expose a `font-metrics` property that holds a structure with metrics from the font that's used, scaled to the font size used and of course taking the weight, etc. into account.

```slint
struct FontMetrics {
    ascent: length,
    descent: length,
    x-height: length,
    cap-height: length,
}
```

**Comment by NigelBreslaw** [comment]
This would be super useful. Maybe we create another issue where I create a pure slint demo that looks like this. I don't mean literally this imags that has extra properties, just the slint ones above. So some nice big text with lines (slint one pixel height rectangles) overlaid showing where the lines map to based on the metrics. 
![glyph_metrics](https://github.com/user-attachments/assets/5fef0f35-7ab9-40b3-9f2c-26a245c4fd30)

**Comment by hunger** [comment]
I was wondering whether we could set a "measurement text" on text fields and use that text for size calculations.

If I wanted to have a float falue with a precision of 2 digits bigger than -1000.00 and smaller than 1000.00, then the measurement text could be `-MMM.MM` to make sure the widget will not resize at some point (assuming arabic numbers and probably more;-).

**Comment by tronical** [comment]
Yes, that might be interesting in the longer run.

**Comment by Hammerklavier-cn** [comment]
> This would be super useful. Maybe we create another issue where I create a pure slint demo that looks like this. I don't mean literally this imags that has extra properties, just the slint ones above. So some nice big text with lines (slint one pixel height rectangles) overlaid showing where the lines map to based on the metrics. ![glyph_metrics](https://github.com/user-attachments/assets/5fef0f35-7ab9-40b3-9f2c-26a245c4fd30) 

It seems that we cannot set `Line gap (leading)` in a `Text` component, right?

**Comment by tronical** [comment]
That's right. This could be a feature of Text.
