### ISSUE TITLE
Amazing memory footprint

### ISSUE THREAD

**Issue by Vzz1c** [slint-ui/slint#6072]
https://github.com/slint-ui/slint-rust-template
slint 1.7.2
windows 10
cargo build --release

There were no code changes, I'm just stretching the window size, the memory footprint is way too much!

**Comment by Vzz1c** [comment]
![image_2](https://github.com/user-attachments/assets/fc4411a8-7e79-46b2-bb75-23bc73bff436)

**Comment by tronical** [comment]
Yes, and the bigger the window becomes, the higher the memory usage. And if you shrink the window, it may or may not go down. The memory usage that you're seeing is not Slint's memory usage, it's the memory allocated by the graphics driver for the back and front-buffers. Sadly, I don't think that there's much that we can do about this. But what you could do is enable the `renderer-skia` feature in your `Cargo.toml` and set the `SLINT_BACKEND=winit-skia-software` environment variable. That will avoid allocating two buffers permanently and instead blit to the window front buffer that's not accounted for in the task manager's memory usage. You'll see a little bit of change/growth, but it's a fraction.

**Comment by Vzz1c** [comment]
After adding renderer-skia, the memory usage is more stable, there is about 40 memory usage, but after adding environment variable `SLINT_BACKEND=winit-skia-software`, the memory usage is very small, so, for the efficiency of running, which way is the fastest?

**Comment by Vzz1c** [comment]
> Yes, and the bigger the window becomes, the higher the memory usage. And if you shrink the window, it may or may not go down. The memory usage that you're seeing is not Slint's memory usage, it's the memory allocated by the graphics driver for the back and front-buffers. Sadly, I don't think that there's much that we can do about this. But what you could do is enable the `renderer-skia` feature in your `Cargo.toml` and set the `SLINT_BACKEND=winit-skia-software` environment variable. That will avoid allocating two buffers permanently and instead blit to the window front buffer that's not accounted for in the task manager's memory usage. You'll see a little bit of change/growth, but it's a fraction.

After adding renderer-skia, the memory usage is more stable, there is about 50 memory usage, but after adding environment variable `SLINT_BACKEND=winit-skia-software`, the memory usage is very small, so what is the fastest way to set the value of `SLINT_BACKEND` in terms of running efficiency?

**Comment by ogoffart** [comment]
Skia is better. It's not the default because it is harder to compile
