### ISSUE TITLE
live-preview: Droping widget that extand to the parent shouldn't add `x` and `y` property

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#6098]
Preview an empty document:
```
component Demo {
}
```
Resize it to some meaningful size.
In edit mode, drag a `AboutSlint` on the empty area.
It has x and y and is placed wierdlt while if it didn't have x and y it would nicely fill the window or be centered.

![image](https://github.com/user-attachments/assets/fc9c4343-2720-4421-b263-982dde02d9bb)

AboutSlint is a component that has a `preferred-height: 100%; preferred-width: 100%;`

The code that tries to detect if it extends to parent should take that into account.

I suggest that we actually assume it extend to the parent unless we detect otherwise.
Then by default it would always be centered.

**Comment by szecket** [comment]
if I understand right if there is no content and no defined width/height dropping a component anywhere should fill that component.  If that is what you mean, I think that makes sense

**Comment by ogoffart** [comment]
It depends on the widgets: Some widget (eg, a button) have a defined size. In that case it would not fill the parent. If we don't set the x and y position it will be placed in the center.
On the other hand, a ListView will fill the parent, then we should definitively not set the x and y position (that's the bug from this issue)

One question is if we should actually set x and y at all for the first category or just let it be dropped always in the center.

**Comment by szecket** [comment]
I kind of like the not setting x/y at all personally as right now i'm having a hard enough time getting it to drop into the right container...
I would be in favour of a ctrl/drag for x/y placement.   (can we include that in the status message when dragging? that way as you're dragging it says 'press <ctrl> to specify x and y coordinates when dropping'
I also get @hunger comment to "place it in a layout if you want it to do a certain thing" but I also don't think of the layout until it does the wrong thing.
