### ISSUE TITLE
macOS: expose Winit's `EventLoopBuilderExtMacOS::with_activation_policy`

### ISSUE THREAD

**Issue by PaulDance** [slint-ui/slint#6103]
Dear maintainers,

I'm currently trying to port a Rust Slint application from Windows to macOS using Winit. It is specifically designed to remain in the background and stay reachable from a systray entry. Under macOS, due to the OS' design, all applications have a Dock entry opened by default and remaining even when their last window is closed, which does not fit my case very well.

In order to change this, it is possible to set [`LSUIElement`](https://developer.apple.com/documentation/bundleresources/information_property_list/lsuielement?language=objc) in the application bundle's `Info.plist`. It is also possible to achieve this during runtime using [`TransformProcessType`](https://developer.apple.com/documentation/applicationservices/1462420-transformprocesstype?language=objc).

However, calling `slint::run_event_loop` after either of these overwrites it and restores the default. This is reproducible with https://github.com/slint-ui/slint-rust-template/, Winit selected as a backend, and the `ui.run()?` in the main function replaced with:

```rust
ui.show()?;
std::thread::sleep(dbg!(std::time::Duration::from_secs(5)));
slint::run_event_loop()?;
```

With `LSUIElement` not set in the `Info.plist`, one can observe the Dock entry appearing and five seconds later the application window. With the option set however, one can observe no Dock entry appearing at first, but then five seconds later, both the Dock and the window appear. This was ran under macOS 14.6.1.

In short, this seems to be https://github.com/rust-windowing/winit/issues/261: Winit always sets an [`NSApplicationActivationPolicy`](https://developer.apple.com/documentation/appkit/nsapplicationactivationpolicy?language=objc), with [`NSApplicationActivationPolicyRegular`](https://developer.apple.com/documentation/appkit/nsapplicationactivationpolicy/nsapplicationactivationpolicyregular?language=objc) used by default, which seems to be a third way to control the desired behavior. Winit exposes it using [`EventLoopBuilderExtMacOS::with_activation_policy`](https://docs.rs/winit/latest/winit/platform/macos/trait.EventLoopBuilderExtMacOS.html#tymethod.with_activation_policy) and setting [`ActivationPolicy::Accessory`](https://docs.rs/winit/latest/winit/platform/macos/enum.ActivationPolicy.html#variant.Accessory) should fix the problem.

Winit's issue apparently being considered resolved due to its exposed API, I therefore come here in order to try finding a proper solution: would it for example be possible to somehow expose access to this lower-level API? It could also be generalized to accessing the backend event loop and allowing its mutation. I'm open to other solutions of course, this was just the first I could think of.

In the meantime, the following can serve as a workaround:

```rust
type OsStatus = i32;

#[repr(C)]
struct ProcessSerialNumber {
    high: u32,
    low: u32,
}

impl From<ReservedPsn> for ProcessSerialNumber {
    fn from(psn: ReservedPsn) -> Self {
        Self { high: 0, low: psn as _ }
    }
}

#[repr(u32)]
enum ReservedPsn {
    None = 0,
    System = 1,
    Current = 2,
}

#[repr(u32)]
enum ProcessApplicationTransformState {
    Foreground = 1 << 0,
    Background = 1 << 1,
    UiElement = 1 << 2,
}

#[link(name = "ApplicationServices", kind = "framework")]
extern "C" {
    #[link_name = "TransformProcessType"]
    fn transform_process_type(
        psn: *const ProcessSerialNumber,
        transform_state: ProcessApplicationTransformState,
    ) -> OsStatus;
}

fn make_ui_element() -> Result<(), OsStatus> {
    // SAFETY: parameters are constant.
    match unsafe {
        transform_process_type(
            &ReservedPsn::Current.into(),
            ProcessApplicationTransformState::UiElement,
        )
    } {
        0 => Ok(()),
        res => Err(res),
    }
}

#[cfg(target_os = "macos")]
std::thread::spawn(|| {
    while make_ui_element().is_err() {
        std::thread::sleep(std::time::Duration::from_millis(1));
    }
});
```

put just before starting the event loop, with `LSUIElement` set in the `Info.plist`, will basically race with the [`[NSApplication setActivationPolicy:]`](https://developer.apple.com/documentation/appkit/nsapplication/1428621-setactivationpolicy?language=objc) call made by Winit and overwrite it: calling `TransformProcessType` with parameters that don't differ from the current situation results in the [`-50` error](https://www.osstatus.com/search/results?platform=all&framework=all&search=-50).

Cheers,
Paul.

**Comment by tronical** [comment]
That's a very reasonable request. I did something similar the other day. Let me clean up the API a little and then this will be resolved.

**Comment by PaulDance** [comment]
I was able to test this directly with the application I'm porting and everything worked just fine on the (almost) first try. Many thanks for the quick response!
