### ISSUE TITLE
Inter font weights are not recognized

### ISSUE THREAD

**Issue by LoganDark** [slint-ui/slint#614]
I installed the desktop weighted version of the Inter font family, but sixtyfps seems to only recognize regular and bold:

![image](https://user-images.githubusercontent.com/4723091/138612391-048ad3df-4ea0-4757-b7a4-4189fb55120f.png)

**Comment by tronical** [comment]
This fortunately works now, with Qt (naturally), FemtoVG (thanks to fontdb matching), as well as Skia (thanks to use of CoreText).
