### ISSUE TITLE
`Timer::set_interval()` doesn't work in timer callback

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6141]
I have a use case where I have a repeating `Timer` that needs a new random interval on every callback call. But `set_interval()` in the `Timer`'s callback just doesn't apply the new interval.

Minimal example to reproduce the problem: [timer-set-interval-bug.zip](https://github.com/user-attachments/files/17000723/timer-set-interval-bug.zip)

**Comment by ogoffart** [comment]
Thanks for filing a bug.

I think this is a regression in 471bef422dcfe093fdd369aed7ac206671e8ac0e

in `TimerList::set_interval`:
```diff
-        if matches!(timer.mode, TimerMode::SingleShot) {
+        if !matches!(timer.callback, CallbackVariant::MultiFire { .. }) {
```

but timer.callback is removed as it is borrowed while being called and so the wrong branch is taken.
