### ISSUE TITLE
Property "default-font-family" is not effective by using slint-lsp 

### ISSUE THREAD

**Issue by gy0801151351** [slint-ui/slint#6143]
Hello! During my tests, I found the property "default-font-family" of Window can affect other widgets font.
But when I preview it by slint-lsp, it doesn't work.

The version of slint is "1.7.2".

**Comment by tronical** [comment]
Yes, this is unfortunately a Duplicate of #4298

**Comment by tronical** [comment]
Duplicate of #4298
