### ISSUE TITLE
It's currently impossible to check if a property is defined

### ISSUE THREAD

**Issue by LoganDark** [slint-ui/slint#615]
This library's behavior when it comes to undefined properties is impossible to deal with at best. Let's say I have a logo component and I want to switch to a monochrome version of the logo when a `colorize` property is passed to the root. How will I do that?

Cause this won't work:

```60
Image {
	source: root.logo-color
		? @image-url("logo_mono.svg")
		: @image-url("logo.svg");
}
```

Can't convert brush to boolean, that's cool. There is _no way_ to check if this property is present. There is only a way to check this property's value.

If I specifically do not assign a default value, `property<brush> logo-color;`, two things should happen:

1. I should be able to check if the property has been defined from above, in a ternary condition or in `states`.
2. If the property is not defined for whatever reason, any declarations that depend on the property should also be undefined. For example, if I pass `colorize: root.logo-color;` on that Image, `colorize` should be completely undefined if `logo-color` is also undefined. `states` can be used to provide fallbacks if a property is undefined, by checking for the property using whatever solution is enacted for number 1.

**Comment by ogoffart** [comment]
For this use case, you can rely that the default value (if unset) of a color is transparent. So by checking if it is transparent with `!= #0000` 

(See this example)[
https://sixtyfps.io/releases/0.1.4/editor/?snippet=Hi+%3A%3D+Rectangle+%7B%0A++property+%3Ccolor%3E+logo-color%3B++++%0A++Image+%7B%0A++++y%3A+50px%3B%0A++++source%3A+logo-color+%3D%3D+%230000+%3F%0A++++++%40image-url%28%22https%3A%2F%2Fsixtyfps.io%2Fresources%2Flogo_scaled.png%22%29%0A+++++++%3A+%40image-url%28%22https%3A%2F%2Fsixtyfps.io%2Fimages%2Frust_logo.svg%22%29%3B%0A++++colorize%3A+logo-color%3B%0A+++%7D%0A%7D%0A%0Aexport+Demo+%3A%3D+Window+%7B%0A++Hi+%7B%0A++++%2F%2Flogo-color%3A+red%3B%0A++%7D%0A%7D%0A]

Un-commenting the logo-color changes the image.

**Comment by LoganDark** [comment]
That actually works for this case, thanks. For other cases - what if the difference between "transparent" and "undefined" is significant for some reason? Just extract into two widgets `WhateverWithColorize` and `WhateverWithoutColorize`?

**Comment by ogoffart** [comment]
Yes.  When the difference between transparent and undefined is important, it probably is important at compile time already, so having a binding will not really be helpful. 
We would need to look at actual use-case and attempt to see if this feature is really needed.

**Comment by mgunyho** [comment]
I came across this while trying to implement a button that enables / disables the `colorize` property on an image. For me it's fine if `#0000` means "no value", but it should be documented, the [docs](https://docs.slint.dev/latest/docs/slint/src/language/builtins/elements#image) say "When set, ...", but don't explain how to unset it. Looking up the [type docs](https://docs.slint.dev/latest/docs/slint/src/language/syntax/types), the default value for a brush is "transparent", but it's unclear whether any color with zero alpha means "unset" for colorize.

Similarly, I was wondering how to unset the `source` of an image, I'm still not sure how to construct an empty `image` value.
