### ISSUE TITLE
Add C++ equivalents for `from_rgb{a}8{_premultiplied}` to `sixtyfps::Image` 

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#616]
The Rust API for `sixtyfps::Image` allows for the creation of image objects from pixel buffers. We need API offering the same functionality for the C++ API.

**Comment by ogoffart** [comment]
We also need to have good documentation, for both Rust and C++ on how to generate image integrated with a sixtyfps ui

**Comment by DaMilyutin** [comment]
Waiting eagerly! 😃
Can you provide some estimation on when this feature will be implemented?

**Comment by ogoffart** [comment]
Done in #2378
