### ISSUE TITLE
slint-viewer: image loading support via save-data/load-data

### ISSUE THREAD

**Issue by ianhattendorf** [slint-ui/slint#6169]
It would be helpful to be able to load images via `slint-viewer --load-data`. Without this, it's hard to test components without hardcoding properties in `.slint` files. The same syntax as `@image-url()` would be enough IMO.

`test.slint`
```
export struct TestData {
    image: image,
}

export component Test inherits Rectangle {
    in property <TestData> test_data: {
        image: @image-url("./test.jpg")
    };

    Image {
        source: test_data.image;
    }
}
```
```
$ slint-viewer test.slint --style fluent --save-data test.json
```
`test.json`
```
{}
```
Expected:
```
{
  "test_data": {
    "image": "@image-url(\"./test.jpg\")"
  }
}
```
```
$ slint-viewer test.slint --style fluent --load-data test.json
Warning: cannot set property 'test_data' from data file: WrongType
```

**Comment by ogoffart** [comment]
Thanks for filing an issue.

Not all images is made out of a path, but we can find out the path for the image that have one.

I think we could say that if the json contains a string, this is a URL. 
I wonder if it is worth to try to save and load other kind of image by storing the raw data. (eg, png in base 64 as a data url)

**Comment by ianhattendorf** [comment]
Right, I was thinking even just handling the path is much better off than before.

Raw image encoding as base64/data url would be nice but image paths are probably fine 95% of the time and a big improvement to the development experience.

> I think we could say that if the json contains a string, this is a URL.

I think that's a good simple solution. I was originally worried about distinguishing between strings and images in the json, or a future raw image encoding scheme, however I'm probably over thinking it. The raw encoding scheme should probably just be a data URI, which is easy to test for.

**Comment by ogoffart** [comment]
In order to do this, one needs to handle Value::Image here to save https://github.com/slint-ui/slint/blob/3f3ac7e347ce852f629c4be38cb5e6146d7c7196/tools/viewer/main.rs#L179
and Type::Image here to load: https://github.com/slint-ui/slint/blob/3f3ac7e347ce852f629c4be38cb5e6146d7c7196/tools/viewer/main.rs#L386

**Comment by ianhattendorf** [comment]
Thanks for the pointer, I'll take a look at implementing this when I have some time.
