### ISSUE TITLE
`absolute-position` incorrectly documented?

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6174]
Trying to [assign to `absolute-position`](https://slintpad.com/?snippet=import+%7B+Button+%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Demo+%7B%0A++++Button+%7B%0A++++++++absolute-position%3A+%7Bx%3A+10px%2C+y%3A+20px%7D%3B%0A++++%7D%0A%7D%0A&style=native) gives the error:

```
Cannot assign to output property 'absolute-position'
```

But it's [documented](https://releases.slint.dev/1.7.2/docs/slint/src/language/builtins/elements) as `in Point`.

**Comment by ogoffart** [comment]
You're right, it should be documented as `out` property, because the property is read-only.
Well spotted.

Fixed in commit 21d60b1050d467d58bef9e6d2b0438f515d79b2d
