### ISSUE TITLE
Made the Slint Language server crash by passing a '0' to a rowspan.

### ISSUE THREAD

**Issue by MathieuFennema** [slint-ui/slint#6181]
Made the Slint Language server crash by passing a '0' to a rowspan in a gridbox.
```
 GridBox {
        connection:= LineEdit { 
            row: 0;
            rowspan: 0;
            read-only: true;
            height: 50px;
            text: "Keyboard Disconnected";
            font-size: 20px;
            horizontal-alignment: center;
        }
```

error message:
thread 'main' panicked at internal\core\layout.rs:463:41:
index out of bounds: the len is 3 but the index is 18446744073709551615
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 11:44:11 AM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues

p.s. Embedded software specialist messing with GUI's in Rust, sorry if I did stupid stuff.

**Comment by ogoffart** [comment]
Thanks for reporting the bug.

This can indeed be reproduced easily:

```slint
export component Demo {
    GridLayout {
        connection := Rectangle {
            row: 0;
            rowspan: 0;
        }
    }
}
```

> p.s. Embedded software specialist messing with GUI's in Rust, sorry if I did stupid stuff.

No stupid stuff there. Thank you for reporting because even stupid stuff shouldn't cause a panic.
