### ISSUE TITLE
Feature request: cast from the top-level window to a widget inheriting window

### ISSUE THREAD

**Issue by otiv-willem-vanhulle** [slint-ui/slint#6196]
I am running Slint 1.7.2 on Ubuntu 24.04 with Rust 1.79.0.

I have defined a Slint widget named `WidgetToBeExported` with an adapter `Adapter` that I would like to reuse in another cargo project. Because I would like to use the MVC pattern, I need to have a way to get to the Adapter after instantiating a window. 
1. One way would be to just use the `WidgetPreviewWindow` as a handle, but the problem is that I don't want to build in another cargo project on top of the preview window. I am only interested in the contained widget `WidgetToBeExported`.
2. Another way would be to _cast_ the main window to the _smaller_ contained widget that inherits window. Then I can export and call the function `forward_events_from_adapter_to_controller` also from other cargo projects that depend on the widget, adapter and controller in this project. However this is not implemented. Could you give workaround or implement this?

```rust
slint::slint! {
    import { Button } from "std-widgets.slint";
    export global Adapter {
        callback action();
    }

    export component WidgetToBeExported inherits Window {
        Button {
            text: "Click me!";
            clicked => {
                Adapter.action();
            }
        }
    }

    export component WidgetPreviewWindow inherits Window {
        WidgetToBeExported { }
    }
}

pub struct Controller {
    action: Box<fn()>,
}

pub fn forward_events_from_adapter_to_controller(widget: &WidgetToBeExported) {
    let controller = Controller {
        action: Box::new(|| println!("Clicked!")),
    };

    Adapter::get(widget).on_action(move || (controller.action)());
}

pub fn get_widget(_window: &WidgetPreviewWindow) -> &WidgetToBeExported {
    todo!("This should cast from the main window to the widget.")
}

pub fn main() {
    let widget_preview_handle = WidgetPreviewWindow::new().unwrap();
    let _widget_handle =
        forward_events_from_adapter_to_controller(get_widget(&widget_preview_handle));

    widget_preview_handle.run().unwrap();
}

```

My `Cargo.toml` file is:

```toml
[package]
name = "module"
version = "0.0.1"
edition = "2021"
publish = false
license = "MIT"

[[bin]]
path = "src/main.rs"
name = "main"

[dependencies]
slint = { version = "1.7.2" }
```

**Comment by tronical** [comment]
ping @otiv-willem-vanhulle

**Comment by otiv-willem-vanhulle** [comment]
@tronical @ogoffart The root cause of this issue is that Slint is not suitable for creating generic components because all bindings pass through a single unique code-generated window. If there is no way to compose functionality, and build separate functioning blocks, you can't build large applications efficiently. 

One way to implement such behavior would be to allow users to extract a single "component" from the generated Window tree. Then users could attach event handlers to this block. But it would still be clumsy experience compared to what Rust user interface frameworks such as `floem` are doing.

**Comment by tronical** [comment]
Ok, we discussed this and rephrased this, also based on an earlier discussion we had about the ability to more easily compose slint files and associated business logic encapsulated in crates in Rust. The rephrased issue is #7060.
