### ISSUE TITLE
Fluent style's `CheckBox` text is gray

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6239]
As [this](https://slintpad.com/?snippet=import+%7B+Button%2C+VerticalBox%2C+CheckBox%2C+LineEdit+%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+Demo+%7B%0A++++VerticalBox+%7B%0A++++++++CheckBox+%7B+text%3A+%22Lorem+ipsum+dolor+sit+amet%22%3B+%7D%0A++++++++Text+%7B+text%3A+%22Lorem+ipsum+dolor+sit+amet%22%3B+%7D%0A++++++++LineEdit+%7B+text%3A+%22Lorem+ipsum+dolor+sit+amet%22%3B+%7D%0A++++++++Button+%7B+text%3A+%22Lorem+ipsum+dolor+sit+amet%22%3B+%7D%0A++++%7D%0A%7D%0A&style=fluent-light) SlintPad demo shows, other text has high contrast (black/white), but an enabled `CheckBox`'s text is gray. This is only true for the light and dark Fluent styles, but not for any other style.

This looks weird in my Windows app.

**Comment by ogoffart** [comment]
I confirm, the fluent style guide has the normal text color as a color.
 https://www.figma.com/community/file/1159947337437047524/windows-ui-3
