### ISSUE TITLE
Crash due to debug assert in `default_geometry`

### ISSUE THREAD

**Issue by rscarson** [slint-ui/slint#6246]
Minimal example: 

```slint
export component MainWindow inherits Window {
    width: 800px;
    height: 600px;
    ScrollView {
        height: 100px;
        width: 100px;
        StandardTableView {
            height: 100%;
            width: parent.width;
        }
    }
}
```

Causes the following crash:
```
  --- stderr
  thread 'main' panicked at C:\Users\rcarson1\.cargo\registry\src\index.crates.io-6f17d22bba15001f\i-slint-compiler-1.7.2\passes\default_geometry.rs:283:9:
  assertion `left == right` failed
    left: Invalid
   right: LogicalLength
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Crash occurs here: https://github.com/slint-ui/slint/blob/eb3e1dded197f482dc40ff9672cc88a7e61e7704/internal/compiler/passes/default_geometry.rs#L287

Despite there being valid measurements in every component in the chain

Removing height from the tableview removes the error

**Comment by ogoffart** [comment]
Thanks for filing an issue!
This particular bug was already reported as https://github.com/slint-ui/slint/issues/4163 and fixed recently in https://github.com/slint-ui/slint/pull/4223 which will be in Slint 1.8.
So i'll close this issue but thanks anyway
