### ISSUE TITLE
clicking show preview in vscode doesn't pop the preview to the front when live-preview is running

### ISSUE THREAD

**Issue by szecket** [slint-ui/slint#6277]
when live-preview is not running and I press the link in vscode, the new app pops to the front. 
when I "quit" and the window closes, the interaction then is no longer the same
if we can pop live-preview to the front, that would fix it. 
if not, making it always on top and making quit hide the window (so it "shows" when I press show preview link) that would also fix it

**Comment by ogoffart** [comment]
Same as https://github.com/slint-ui/slint/issues/196
(PR in https://github.com/slint-ui/slint/pull/6295 )
