### ISSUE TITLE
SlintPad: Element selection unreliable

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6282]
I'm on Windows 10 and use Firefox.

The succession of steps triggering the bug is the following for me:

Load https://slintpad.com/:

![element-selection-1](https://github.com/user-attachments/assets/2aac4c5d-8313-4c07-ae1f-6328b390360f)

Select `AboutSlint` via element selection button (two clicks: first on element selection button, then on element):

![element-selection-2](https://github.com/user-attachments/assets/92e09825-3fcf-481e-857e-8bf3cb162b48)

Don't do anything else incl. switching OS windows, switching the browser tab, or intermediately focusing the SlintPad editor, and select the `Button` via element selection button:

![element-selection-3](https://github.com/user-attachments/assets/b0785f5f-57cb-4308-846b-76f72b31cc34)

The `Button` is erroneously briefly selected, and then deselected, in favor of `AboutSlint` being selected again. When you now switch away from the OS window and back, the `Button` will be selected at the time the OS window is activated again.

---

The SlintPad page can be reloaded to prepare for an additional bug reproduction.

When you intermediately do something like switching windows before using the element selection button a second time, the problem doesn't occur.

**Comment by hunger** [comment]
Interesting, I can reproduce this behavior.

**Comment by hunger** [comment]
Oh, this is fun. This is the first round:

1. `AboutSlint` is selected
2. The preview asks the monaco editor to change the cursor position
3. The monaco editor changes the cursor position to the `AboutSlint` position. I see the changed callback coming back with the expected position.
4. The monaco editor sends a document highlight request for an invalid cursor position
5. The preview ignores the invalid highlight request.

The second round works like this:

1. 'Button` is selected.
2. The preview asks the monaco editor to change the cursor position to `Button` position
3. The monaco editor changes the cursor position and I see this reflected in the change callback it triggers.
4. The monaco editor sends a document highlight request for the `AboutSlint` cursor position.
5. Slintpad updates its selection to the "new" cursor position based on the document highlight.

The VSCode extension sends DocumentHighlightRequests that reflect the "current" cursor positions.

Slintpad does not use the "normal" code path for the ShowDocument request though, so maybe that is what casses this. I'll check what can be done to make our custom code unnecessary.

**Comment by hunger** [comment]
#6308 actually closes this by updating the Monaco editor and by relying on built-in code to handle LSP showDocument -- which we could not do before.

**Comment by Enyium** [comment]
@hunger:

Is this the same error that's now already solved, or should I create a new issue for it?

Open [this SlintPad demo](https://slintpad.com/?snippet=import+%7B+VerticalBox%2C+Button+%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+Demo+%7B%0A++++VerticalBox+%7B%0A++++++++alignment%3A+start%3B%0A++++++++Rectangle+%7B%0A++++++++++++Button+%7B%0A++++++++++++++++%2F%2Ftext%3A+%22Foo%22%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native) and click once on `Button` to show its selection rectangle:

```slint
import { VerticalBox, Button } from "std-widgets.slint";

export component Demo {
    VerticalBox {
        alignment: start;
        Rectangle {
            Button {
                text: "Foo";
            }
        }
    }
}
```

Now remove and readd `//` repeatedly to see that the selection rectangle is always incorrectly placed.

**Comment by hunger** [comment]
@Enyium: What am I supposed to comment out?

The selection is based on URL and offset in the file. It will break when you add/remove text before the selection. Adding/removing `//` is enough. There is a bit of logic to update the selection when the live-preview itself changes the source code, but that does not apply when you edit the text behind the live-preview's back:-/

So that might be the root cause for what you are seeing, but I am not sure as I don't know what you commented out.

**Comment by Enyium** [comment]
@hunger: Is the following the same bug, so that it's now already solved, or is it a new one?

https://github.com/user-attachments/assets/d85d7b20-e5ba-40a5-96ad-0591880ab533

**Comment by hunger** [comment]
I think that is a different issue: That there is no way for the preview to know when something resized.
