### ISSUE TITLE
SlintPad: Prioritize other resize direction

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6286]
- Open [this empty SlintPad demo](https://slintpad.com/?snippet=export+component+Demo+%7B%0A%7D%0A&style=native).
- Resize it to the smallest size possible and release the mouse button.
- Approach the now very small square from the bottom right corner until you get a resize cursor.
- Try to resize into the bottom right direction. It doesn't work. The only direction that works to resize on both axes is the top left direction.

If possible, when having such a small rectangle, multiple resize directions should be possible. If this is too much of a hassle, I think the bottom right direction should be preferred over the top left direction, because, I'd say, it's generally used more often.

**Comment by hunger** [comment]
What an interesting bug! Thanks for reporting this :-)

**Comment by hunger** [comment]
I'll classify as enhancement as I do not expect this to happen in real live too often.
