### ISSUE TITLE
Infer enums i.e. `.left` instead of only full name space `Direction.left`

### ISSUE THREAD

**Issue by NigelBreslaw** [slint-ui/slint#6297]
I've used enums in other languages where in certain points the type system lets you infer them without having to type the whole name space. It also played nice with intellisense and you just type '.' to see the enum values. Less to type and less to read.

```
enum Direction { left, right }

function updateDirection(direction: Direction) -> Direction {
        return .left;  // Inferred based on return type
}

debug(updateDirection( .right )); // Inferred based on argument type

property <Direction> foo: .right; // Inferred based on type
```

It makes using enums in many places a lot more elegant especially in function arguments where you can replace ambiguous boolean values with `awesomeFunction( .upperCase )` or `awesomeFunction( .lowerCase )`. Where `awesomeFunction( aweText.upperCase )` is so long you just stick with a more ambiguous bool. Also has a knock on effect to general api design and readability if you know you can use enums but don't have to type the whole name space. 

Also if there is anything like module name spaces you can end up having to type `Navigation.Direction.left` or worse.

**Comment by ogoffart** [comment]
You don't need the dot for that

This works:
```slint
function updateDirection(direction: Direction) -> Direction {
        return left;  // Inferred based on return type
}
property <Direction> foo: right; // Inferred based on type
```

The third one (`updateDirection( right )`) doesn't work at the moment, but it is already tracked by issue https://github.com/slint-ui/slint/issues/897 , so I'll close this one as a duplicate.
