### ISSUE TITLE
Mouse cursor isn't updated when existence of overlayed `TouchArea` is toggled

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6309]
[This SlintPad demo](https://slintpad.com/?snippet=import+%7B+LineEdit+%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+Demo+%7B%0A++++property+%3Cbool%3E+modal-shown%3A+false%3B%0A%0A++++Timer+%7B%0A++++++++interval%3A+1s%3B%0A%0A++++++++triggered+%3D%3E+%7B%0A++++++++++++root.modal-shown+%3D+%21root.modal-shown%3B%0A++++++++%7D%0A++++%7D%0A%0A++++LineEdit+%7B+text%3A+%22foo%22%3B+%7D%0A%0A++++if+modal-shown+%3A+Rectangle+%7B%0A++++++++background%3A+black.with-alpha%2820%25%29%3B%0A%0A++++++++TouchArea+%7B%0A++++++++++++Rectangle+%7B%0A++++++++++++++++width%3A+50px%3B%0A++++++++++++++++height%3A+50px%3B%0A++++++++++++++++background%3A+yellow%3B%0A++++++++++++++++border-radius%3A+5px%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native) shows or hides an overlay every second:

```slint
import { LineEdit } from "std-widgets.slint";

export component Demo {
    property <bool> modal-shown: false;

    Timer {
        interval: 1s;

        triggered => {
            root.modal-shown = !root.modal-shown;
        }
    }

    LineEdit { text: "foo"; }

    if modal-shown : Rectangle {
        background: black.with-alpha(20%);

        TouchArea {
            Rectangle {
                width: 50px;
                height: 50px;
                background: yellow;
                border-radius: 5px;
            }
        }
    }
}
```

The mouse cursor over the `LineEdit` depends on what was displayed at that spot the last time you moved it. But it should also be updated without moving it when the overlay is toggled.

**Comment by ogoffart** [comment]
Similar to https://github.com/slint-ui/slint/issues/3904
Actually i'm going to merge the two issues because the fix is probably the same.
