### ISSUE TITLE
Copy button in SlintPad share dialog pushed out of view

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6318]
When having code like [this](https://slintpad.com/?snippet=%2F%2Faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa%0Aexport+component+Demo+%7B%7D%0A&style=native) (also, e.g., with many imports in the first line):

```slint
//aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
export component Demo {}
```

...the dialog behind the menu item "Project > Share > Copy Permalink to Clipboard" can have its copy button pushed out of view:

![copy-button-pushed-out-of-view](https://github.com/user-attachments/assets/0e93fead-e24a-4cc2-b3c3-aba210f4ff2d)

**Comment by hunger** [comment]
Thanks for catching this!
