### ISSUE TITLE
changed has-focus doesn't work for LineEdit

### ISSUE THREAD

**Issue by FischLu** [slint-ui/slint#6331]
Platform: Macos 15
Language: Rust 1.80.1
Slint version: 1.8.0

The `changed` callback of the property `has-focus` doesn't work for `LineEdit`, the app panicked when I ran it, with the following output
```
thread 'main' panicked at /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-compiler-1.8.0/llr/expression.rs:676:89:
  called `Option::unwrap()` on a `None` value
```
Here are code snippets to reproduce the problem:

.slint
```
import { LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    LineEdit {
        width: 50px;
        changed has-focus => { debug("hello") }
    }
}

```
.rs
```
// Prevent console window in addition to Slint window in Windows release builds when, e.g., starting the app via file manager. Ignored on other platforms.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::error::Error;

slint::include_modules!();

fn main() -> Result<(), Box<dyn Error>> {
    let ui = AppWindow::new()?;
    ui.run()?;
    Ok(())
}

```

More information:
I tried `changed text => { debug("hello") }` for `LineEdit`, it works without issue. I tried `changed has-focus => { debug("hello") }` for `TextInput`, works as well.

**Comment by hunger** [comment]
Thanks for the report!

**Comment by ogoffart** [comment]
The problem is that internally, has-focus is an alias to another property, and because it is not used (read) in the outer component, the property is deleted.

https://github.com/slint-ui/slint/pull/6336 fixes the problem.

The workaround is to use the property.
eg:

```slint
import { LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    LineEdit {
        width: 50px;
        // ADDED: read self.has-focus in the debug to workaround compiler bug
        changed has-focus => { debug("hello", self.has-focus) }
    }
}
```

**Comment by FischLu** [comment]
hi @ogoffart, thanks for the reply, I just tried, unfortunately, it doesn't work as well, error message:
```
thread 'main' panicked at /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-compiler-1.8.0/passes/const_propagation.rs:190:9:
  assertion failed: !matches!(ty, Type::Invalid)
``` 

for `TextInput` the code works.

**Comment by FischLu** [comment]
Hi, why the issue is closed??  #6336 doesn't solve the problem

**Comment by ogoffart** [comment]
https://github.com/slint-ui/slint/pull/6336

**Comment by ogoffart** [comment]
https://github.com/slint-ui/slint/pull/6336 solves the original problem.
Now this panic message, i cannot reproduce.

**Comment by ogoffart** [comment]
Actually, i can reproduce as well with my workaround, but https://github.com/slint-ui/slint/pull/6336 seems to fix it as well

**Comment by FischLu** [comment]
oh. it's strange, I delete the target folder and build again with #6336, it's the same panic message. Platform macos 15 on M1 mac

```
Caused by:
  process didn't exit successfully: `/Users/xxx/Data/Codes/Rust_Test/slint_template/target/release/build/slint-rust-template-be8acd59e5772759/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/i-slint-compiler-1.8.0/llr/lower_expression.rs:63:13:
  internal error, encountered invalid expression at code generation time
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
.slint
```
import { VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    VerticalBox {
        LineEdit {
            width: 50px;
            changed has-focus => { debug("hello", self.has-focus) }
        }     
    }
}
```
.rs
```
// Prevent console window in addition to Slint window in Windows release builds when, e.g., starting the app via file manager. Ignored on other platforms.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::error::Error;

slint::include_modules!();

fn main() -> Result<(), Box<dyn Error>> {
    let ui = AppWindow::new()?;
    ui.run()?;
    Ok(())
}
```

Cargo.toml
```
[package]
name = "slint-rust-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.8.0"

[build-dependencies]
slint-build = "1.8.0"

```

**Comment by ogoffart** [comment]
Ok, there was another bug.
I can't reproduce with your example, but i found another way to reproduce.
https://github.com/slint-ui/slint/pull/6337 fixes the problem even more.

The problem is that the compiler don't look at the changed callback to find out if a property is used, so has-focus has to be used somewhere else.

```slint
import { VerticalBox, LineEdit } from "std-widgets.slint";
export component AppWindow inherits Window {
    VerticalBox {
        LineEdit {
            width: 50px;
            changed has-focus => { debug("hello") }

            // workaround: force has-focus to be used:
            text: self.has-focus ? "" : ""; 
        }     
    }
}
```

**Comment by FischLu** [comment]
OK, this time the problem is solved, but does the alias issue only affect `LineEdit`? Why is `TextInput` not affected at all?

**Comment by ogoffart** [comment]
TextInput is fine because its property is a direct property and not an alias, so it can't be optimized out.
