### ISSUE TITLE
SwipeGestureHandler unexpected behaviour

### ISSUE THREAD

**Issue by NigelBreslaw** [slint-ui/slint#6344]
The SwipeGestureHandler can feel unresponsive at times and also cannot achieve certain iOS style swipes. It's especially noticeable on desktop.

If you are moving the mouse, click, and continue the movement it will be registered as a swipe.

But if you are not moving, click, and immediately or shortly after move then no swipe happens.

On iOS many of the swipes, say to bring down search on the app grid will happily work if you tap, pause, then swipe down. If say with the app grid you had tapped on an icon, the icon will show the pressed state. But once you drag down (quickly before engaging app grid re-arrange mode) the swipe gesture takes over and the pressed gesture the icon was receiving is cancelled.

**Comment by tronical** [comment]
Could you elaborate a bit on the exact sequence of events?

>  if you tap, pause, then swipe down

For me a tap is the sequence of finger put down and then lifted again. Any subsequence swipe down would have to put the finger down again, won't it?

Or do you mean with "tap" finger just down, not lifted anymore?

> But if you are not moving, click, and immediately or shortly after move then no swipe happens.

For me "click" implies mouse button pressed and then released again. So the low-level sequence you're describing sounds like the following to me:

- mouse button pressed
- mouse button released
- mouse cursor is moved

Do you mean that when the cursor is moved, a swipe gesture should be detected, despite the button not being pressed anymore?

**Comment by NigelBreslaw** [comment]
Sorry I can see how I wasn't clear.

On my track pad, I slide my finger gently (move), then press down (feel a click but don't lift), then continue my slide (with finger pressed down) and that works. 

If i have my finger at rest, then press down (feel a click, but don't lift), then move (with finger pressed down) I get no swipe gesture.

**Comment by NigelBreslaw** [comment]
https://github.com/user-attachments/assets/daabb9dd-7a70-4443-aab0-ded4e8251e3f

Video showing pressed events

**Comment by ogoffart** [comment]
You have `DURATION_THRESHOLD` (500ms) to move the mouse by at least `DISTANCE_THRESHOLD` (8px)

Maybe these threshold should be changed? Or made configurable? (Application-wide or per instance?) 
(there was also discussion about this in https://github.com/slint-ui/slint/discussions/6206#discussioncomment-10716675 )

**Comment by NigelBreslaw** [comment]
Just putting this here so the points don't get lost.

1. Had a chat earlier with @tronical and we screen shared an iPhone.
2. Something is off with gestures and maybe something is not fundamentally right with the algorithm.
3. Please don't get hung up on any solutions I suggest. This area seems bonkers complex. Sometimes it's hard to say what is wrong so I try and explain the issue with a solution. But my solution should not be taken seriously! Its the problem that is important. 

I'm also going to use iOS as the reference as it seems to have the best feeling gesture system.

I'm not sure iOS is doing anything fancy with timers. Instead it seems to happily allow many gestures to be nested. Then there are some kind of separation between 2 distinct concepts.  I'm going to call these 'gesture events' and 'gesture properties'. They are both similar. So 'swipe', 'pan', 'clicked' and 'longPressed' are gesture events. While 'isPressed' is a gesture property as is 'tracking' which I have seen on some ScrollViews from other platforms. 'Tracking' simply means a finger is down on the scrollview. It might be static, or moving the view. Then regardless of having a single or multiple gestures they are all live and can respond. So say you have a ScrollView or SwipeGesture full of other items that can take touch. Let's get specific, its a list of items and each item is basically a button. If you put your finger down the ScrollView and whatever list button you have touched now both get input. The ScrollView's 'tracking' is true AND the buttons 'isPressed' property is true. You can press and hold forever now as in this situation no gesture event will take place. If you lift your finger the button gesture now completed and fires its 'clicked' gesture event. This gesture event also has a side effect of cancelling all other gestures its with so you cannot accidentally click the item in the scrollView and have the scrollview start to pan (something I have seen in buggy react apps). 

Let's start again. You press and hold the ScrollView. Tracking is true and button isPressed is true. You hold for however long you like. Now with your finger down you start to move your finger in the direction the list can be scrolled. After whatever threshold you have for movement the 'scrolling' or whatever 'Gesture event' fires. This cancels the gestures for anything else its nested with. So the button is no longer 'isPressed' and also click gesture event cannot fire. Whoever gets to fire their gesture event first wins and cancels the others. 

Now a new example. You can then see why buttons with long press or whatever happily work in a scrollview. There isn't a generic timer that makes the system works. If the button in the scrollview has a long press that is a gesture event. It goes off after a certain amount of time (long press time) and does it's thing and that also cancels the scrollView gesture system from being able to do a scroll. 

I'm probably wrong?? But maybe this explains how on some systems I can take a vertical scrollview and then nest several other gestures in it. For example a side swipe and also fill the scrollView background with a touch event. You can scroll up and down and never have the other two conflict or fire. Then if I side swipe the swipe wins and does it thing. Then finally as there is a keyboard showing if you just tap the scrollview the toucharea or whatever in the background gets to fire its 'clicked' gesture event as that won over the scroll or swipe gesture. You can then use this clicked event to do something useful like dismiss the keyboard. 

Probably needs a few video calls or something to work this all out?

**Comment by ogoffart** [comment]
In addition, if you move by more than the distance threshold in another direction, this will prevent the swipe.

**Comment by lmaxyz** [comment]
> Sorry I can see how I wasn't clear.
> 
> On my track pad, I slide my finger gently (move), then press down (feel a click but don't lift), then continue my slide (with finger pressed down) and that works.
> 
> If i have my finger at rest, then press down (feel a click, but don't lift), then move (with finger pressed down) I get no swipe gesture.

I think it's about your sliding speed. I ran into it too. But I think it's good, that you should swipe quickly to get gesture, otherwise there might be some conflicts with Flickable or TouchArea components placed inside SwipeGestureHandler component.
