### ISSUE TITLE
Rename SixtyFPS

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#635]
The name of the product is not ideal because 60 is no longer the frame rate of newer screen and 
there is always the risk that we don't always reach 60fps. Also  people write "60fps" instead of 
"sixtyfps" when they search on google and find nothing related to us.
So we would like to rename the project.
 1. Find a name (See discussion #636) and a new logo
 2. in a branch, rename sixtyfps everywhere (namespaces function names, crate names, .60 files). 
    Note that we should still allow file in .60 to be loaded to keep compatibility. especially in the style,
    there should be a link from `sixtyfps_widgets.60` to whatever new name this file has.
 3. in another branch, prepare new versions of the sixtyfps crates, that re-export the new ones with
    old names to make it easier to upgrade.
 4. release on crates.io
 5. create new publisher on vs code market place and open-vsx.org
 6. rename vs code extension and publish
 7. rename the Github repository (Github allow renaming so it keeps all the issues and pr and metadata, 
     and all previous url just redirects 
 8. rebrand the website and publish a blog about the name change
 
We just have to pick a good name, suggestion welcome in discussion #636

**Comment by bwalter** [comment]
A GUI (especially) for Rouille (= Rust) can only be named "Gouille". But be careful not to break the gouille(s)!

(of course, just kidding ;))

**Comment by ogoffart** [comment]
The name is Slint
