### ISSUE TITLE
Live-Preview doesn't update correctly when a project changes via `git pull`

### ISSUE THREAD

**Issue by NigelBreslaw** [slint-ui/slint#6351]
1. Have a Slint project open in VScode or whatever and the live-preview is showing. 
2. Someone makes changes on another PC to the repo and commits the changes.
3. You `git pull` and some of the changes show and some do not. As if some values are cached. Pressing 'refresh' next to 'Preview' does not fix the problem. But `Slint: Restart server` does seem to fix the issues.

Expected behaviour is that git pull would cause the live-preview to restart correctly.

**Comment by hunger** [comment]
The problem is that we need to watch the filesystem for this to work.

**Comment by tronical** [comment]
It might make sense to implement this via the VS code extension and piggy-back on VS Code's built-in [file system watcher](https://code.visualstudio.com/api/references/vscode-api#FileSystemWatcher). The upside is that this means sharing resources with VS code (which watches anyway), reducing the risk of running into [typical issues](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc). The downside is that this means tunneling things and it being a VS Code only "solution". Not trying to anchor here, just food for thought.

But problems aside, I think this is a valid bug, not an enhancement.

**Comment by hunger** [comment]
Absolutely, in VSCode we need to hook into the default mechanismn. We might be running in WASM anyway, so we can not always watch the filesystem natively from within the LS.

But we will want to have a fallback for the stand-alone LS.

**Comment by ogoffart** [comment]
No need for a hook in the extension. The LSP supports this natively: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles 
(but we can still have a fallback for client that don't support this)
