### ISSUE TITLE
LSP doesn't recheck other files when one is saved

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6358]
When having, e.g., `app-window.slint` and `widgets.slint`, and `app-window.slint` incorrectly spells a property of a component from `widgets.slint`, but the spelling is corrected in `widgets.slint`, then you first have to edit `app-window.slint` in some way (like add and remove a space) for it to stop showing an error; even hitting Ctrl+S doesn't work. It's the same with the other direction, i.e., the delayed showing of errors that you just introduced; they're first kept quiet about.

Demo video (note my save actions recognizable by the tabs' dirty indicators):

https://github.com/user-attachments/assets/6785fb93-d1c1-40cf-9451-01e526b4a8b7

**Comment by ogoffart** [comment]
Thanks for filling an issue.
This is already an known issue filled in https://github.com/slint-ui/slint/issues/5797
Unfortunately, the fix for that is not trivial.
Closing as duplicate.
