### ISSUE TITLE
Opacity not always having an effect on the dropshadow of a rectangle

### ISSUE THREAD

**Issue by NigelBreslaw** [slint-ui/slint#6359]
Normally the drop shadow opacity will change when the Rectangle it belongs to has it opacity changed. So a zero opacity rectangle draws nothing. No rect. No shadow.

In [this example](https://slintpad.com/?snippet=import+%7B+AboutSlint+%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+AppWindow+inherits+Window+%7B%0A++++preferred-width%3A+800px%3B%0A++++preferred-height%3A+500px%3B%0A++++Rectangle+%7B%0A++++++++background%3A+white%3B%0A++++%7D%0A%0A++++swipe+%3A%3D+SwipeGestureHandler+%7B%0A++++++++property+%3Cbool%3E+showing-sidebar%3A+false%3B%0A++++++++handle-swipe-right%3A+%21showing-sidebar%3B%0A++++++++handle-swipe-left%3A+showing-sidebar%3B%0A++++++++swiped+%3D%3E+%7B%0A++++++++++++if+sidebar-holder.x+%3E%3D+%28sidebar.width+*+0.6%29+%7B%0A++++++++++++++++showing-sidebar+%3D+true%3B%0A++++++++++++%7D+%0A++++++++++++if+sidebar-holder.x+%3C%3D+%28sidebar.width+*+0.4%29+%7B%0A++++++++++++++++showing-sidebar+%3D+false%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++++++property+%3Clength%3E+sidebar-width%3A+400px%3B%0A%0A++++++++Rectangle+%7B%0A++++++++++++animate+background+%7B%0A++++++++++++++++duration%3A+500ms%3B%0A++++++++++++++++easing%3A+ease-in-out-sine%3B%0A++++++++++++%7D%0A%0A++++++++++++sidebar-holder+%3A%3D+Rectangle+%7B%0A++++++++++++++++sidebar+%3A%3D+Rectangle+%7B%0A++++++++++++++++++++x%3A+-self.width%3B%0A++++++++++++++++++++width%3A+sidebar-width%3B%0A++++++++++++++++++++height%3A+100%25%3B%0A++++++++++++++++++++background%3A+grey%3B%0A++++++++++++++++++++Rectangle+%7B%0A++++++++++++++++++++++++opacity%3A+sidebar-holder.x+%2F+sidebar-width%3B%0A++++++++++++++++++++++++%2F%2F+background%3A+darkgray%3B+%0A++++++++++++++++++++++++drop-shadow-offset-x%3A+5px%3B%0A++++++++++++++++++++++++drop-shadow-blur%3A+15px%3B%0A++++++++++++++++++++++++drop-shadow-color%3A+pink%3B%0A++++++++++++++++++++%7D%0A++++++++++++++++++++VerticalLayout+%7B%0A++++++++++++++++++++++++alignment%3A+space-between%3B%0A++++++++++++++++++++++++padding%3A+36px%3B%0A++++++++++++++++++++++++AboutSlint+%7B+%7D%0A++++++++++++++++++++%7D%0A++++++++++++++++%7D%0A++++++++++++++++states+%5B%0A++++++++++++++++++++swipping+when+swipe.swiping%3A+%7B%0A++++++++++++++++++++++++x%3A+showing-sidebar+%3F+Math.min%28sidebar-width+%2B+swipe.current-position.x+-+swipe.pressed-position.x%2C+sidebar-width%29+%3A+Math.min%28swipe.current-position.x+-+swipe.pressed-position.x%2C+sidebar-width%29%3B%0A++++++++++++++++++++%7D%0A++++++++++++++++++++showing-sidebar+when+showing-sidebar+%26%26+%21swipe.swiping%3A+%7B%0A++++++++++++++++++++++++x%3A+sidebar-width%3B%0A++++++++++++++++++++++++in+%7B%0A++++++++++++++++++++++++++++animate+x+%7B%0A++++++++++++++++++++++++++++++++duration%3A+150ms%3B%0A++++++++++++++++++++++++++++++++easing%3A+ease-in%3B%0A++++++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++%7D%0A++++++++++++++++++++not-showing-sidebar+when+%21showing-sidebar+%26%26+%21swipe.swiping%3A+%7B%0A++++++++++++++++++++++++x%3A+0%3B%0A++++++++++++++++++++++++in+%7B%0A++++++++++++++++++++++++++++animate+x+%7B%0A++++++++++++++++++++++++++++++++duration%3A+200ms%3B%0A++++++++++++++++++++++++++++++++easing%3A+ease-in%3B%0A++++++++++++++++++++++++++++%7D%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++%7D%0A++++++++++++++++%5D%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native) you need to swipe right to bring on a hidden sidebar. It has a pink dropshadow that should start with opacity 0 and be invisible and ramp up to 1.0 opacity and be fully visible once the whole sidebar shows. However it is always 1.0 opacity.

If you comment back in line 38 that gives the Rectangle with a shadow a background colour then it starts to work correctly. This issue is only in the live-preview on VSCode. The same example in Slintpad works as expected.

**Comment by tronical** [comment]
> This issue is only in the live-preview on VSCode. The same example in Slintpad works as expected.

Ahh, this is very helpful. I can reproduce this.
