### ISSUE TITLE
`max-...` ineffective and also making `preferred-...` ineffective

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6361]
Consider [this SlintPad demo](https://slintpad.com/?snippet=import+%7B+LineEdit%2C+ComboBox+%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+Demo+%7B%0A++++width%3A+300px%3B%0A++++height%3A+300px%3B%0A%0A++++HorizontalLayout+%7B%0A++++%2F%2FVerticalLayout+%7B%0A++++++++alignment%3A+start%3B%0A%0A++++++++Rectangle+%7B%0A++++++++++++%2F*%0A++++++++++++*%2F%0A++++++++++++preferred-width%3A+1000px%3B%0A++++++++++++max-width%3A+10px%3B%0A++++++++++++height%3A+10px%3B%0A%0A++++++++++++%2F*%0A++++++++++++preferred-height%3A+1000px%3B%0A++++++++++++max-height%3A+10px%3B%0A++++++++++++width%3A+10px%3B%0A++++++++++++*%2F%0A%0A++++++++++++background%3A+fuchsia%3B%0A++++++++%7D%0A%0A++++++++%2F%2F+%60max-...%60+on+its+own+doesn%27t+work.%0A++++++++%2F%2F+And+together+with+%60preferred-...%60%2C+it+makes+it+as+if%0A++++++++%2F%2F+%60preferred-...%60+was+removed.%0A++++++++LineEdit+%7B%0A++++++++%2F%2FComboBox+%7B%0A++++++++++++%2F*%0A++++++++++++*%2F%0A++++++++++++preferred-width%3A+1000px%3B%0A++++++++++++max-width%3A+10px%3B%0A%0A++++++++++++%2F*%0A++++++++++++preferred-height%3A+1000px%3B%0A++++++++++++max-height%3A+10px%3B%0A++++++++++++*%2F%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native) (see comment):

```slint
import { LineEdit, ComboBox } from "std-widgets.slint";

export component Demo {
    width: 300px;
    height: 300px;

    HorizontalLayout {
    //VerticalLayout {
        alignment: start;

        Rectangle {
            /*
            */
            preferred-width: 1000px;
            max-width: 10px;
            height: 10px;

            /*
            preferred-height: 1000px;
            max-height: 10px;
            width: 10px;
            */

            background: fuchsia;
        }

        // `max-...` on its own doesn't work.
        // And together with `preferred-...`, it makes it as if
        // `preferred-...` was removed.
        LineEdit {
        //ComboBox {
            /*
            */
            preferred-width: 1000px;
            max-width: 10px;

            /*
            preferred-height: 1000px;
            max-height: 10px;
            */
        }
    }
}
```

This may be somewhat similar to #6289. But it's about any direction, not just the non-flow-direction of the enclosing layout, and also about `preferred-...` being effected through `max-...`.

**Comment by ogoffart** [comment]
The issue seems to be that the widget has a minimum size coming from the LineEdit implementation.  When we have both maximum and minimum size this is an invalid constraint. Currently the minimum wins.

**Comment by Enyium** [comment]
But why is `preferred-...` affected?! As soon as you add `max-...` to an existing `preferred-...`, it's as if `preferred-...` was commented out, which it isn't.

**Comment by ogoffart** [comment]
I might have misunderstood, but in the example, the preferred is bigger than the max size. So that's why it doesn't have any effect.

**Comment by Enyium** [comment]
Okay. Some constraints coming from elsewhere makes this a little irritating. I conclude:

- Only having `preferred-...` in my code means there's really `preferred-...`, and `min-...` from the widget. Thus, a big `preferred-...` is applied.
- Having `preferred-...` and `max-...` means there's really `preferred-...`, `max-...`, and `min-...` from the widget. Thus, the tiny `max-...` first contrains the big `preferred-...`, and then, the widget's `min-...` enlargens the tiny `max-...`, because `min-...` takes precedence over `max-...`.

**Comment by ogoffart** [comment]
correct.  Normally, `min ≤ preferred ≤ max`  but if it is not the case, this will result in the final size being still constrained between min and max
