### ISSUE TITLE
Graphical drag and drop to generate slint

### ISSUE THREAD

**Issue by Hi-Mr-Wind** [slint-ui/slint#6370]
It is not known if slint has future plans to generate.slint layout files by dragging and dropping graphical pages. Writing a layout in a descriptive language can be tricky for newcomers. There are no plans to implement a form like.nte's winfrom to automatically generate a.slint layout file

**Comment by MichaelNZ85** [comment]
The Slint Live Preview in VSCode lets you do just that

**Comment by ogoffart** [comment]
If you use the slint-lsp or the vscode extension, you can get a "show preview" code lense or code action, with that you can enter edit mode where you can drag and drop widgets.
