### ISSUE TITLE
`in property` behaves like `out property`

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6400]
Consider [this SlintPad demo](https://slintpad.com/?snippet=import+%7B+VerticalBox%2C+StandardListView+%7D+from+%22std-widgets.slint%22%3B%0A%0Acomponent+List+%7B%0A++++in+property+%3Cint%3E+index+%3C%3D%3E+lv.current-item%3B%0A%0A++++lv+%3A%3D+StandardListView+%7B%0A++++++++model%3A+%5B%0A++++++++++++%7Btext%3A+%22Foo%22%7D%2C%0A++++++++++++%7Btext%3A+%22Bar%22%7D%2C%0A++++++++++++%7Btext%3A+%22Baz%22%7D%2C%0A++++++++%5D%3B%0A++++%7D%0A%7D%0A%0Aexport+component+Demo+%7B%0A++++VerticalBox+%7B%0A++++++++alignment%3A+start%3B%0A%0A++++++++list+%3A%3D+List+%7B%0A++++++++++++height%3A+150px%3B%0A++++++++%7D%0A%0A++++++++Text+%7B%0A++++++++++++text%3A+%22Select+list+items.%5Cn%5Cn%60in+property%60+value%3A+%5C%7Blist.index%7D%22%3B%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native):

```slint
import { VerticalBox, StandardListView } from "std-widgets.slint";

component List {
    in property <int> index <=> lv.current-item;

    lv := StandardListView {
        model: [
            {text: "Foo"},
            {text: "Bar"},
            {text: "Baz"},
        ];
    }
}

export component Demo {
    VerticalBox {
        alignment: start;

        list := List {
            height: 150px;
        }

        Text {
            text: "Select list items.\n\n`in property` value: \{list.index}";
        }
    }
}
```

When you select list items, the `in property` `index` changes. You can declare `index` as `in`, `out`, or `in-out`, and it doesn't make any difference.

**Comment by ogoffart** [comment]
Indeed, linking an input property to an input-output should be rejected.
Now we can't reject that anymore but we can make it a warning.
