### ISSUE TITLE
Should outer default value of two-way binding really supersede inner non-default?

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6402]
Consider [this SlintPad demo](https://slintpad.com/?snippet=import+%7B+VerticalBox+%7D+from+%22std-widgets.slint%22%3B%0A%0Acomponent+Inner+%7B%0A++++in-out+property+%3Cstring%3E+prop%3A+%22inner%22%3B%0A%7D%0A%0Aexport+component+Demo+%7B%0A++++%2F%2Fin-out+property+%3Cstring%3E+prop%3A+%22outer%22%3B+%2F%2F+This+should+supersede.%0A++++in-out+property+%3Cstring%3E+prop%3B+%2F%2F+Default+shouldn%27t+necessarily+supersede.%0A++++%2F%2Fin-out+property+%3Cstring%3E+prop+%3C%3D%3E+el.prop%3B+%2F%2F+With+this%2C+you+also+get+the+inner+value.+%28Below+binding+must+be+commented+out.%29%0A%0A++++VerticalBox+%7B%0A++++++++alignment%3A+start%3B%0A%0A++++++++el+%3A%3D+Inner+%7B%0A++++++++++++prop+%3C%3D%3E+root.prop%3B%0A++++++++%7D%0A%0A++++++++Text+%7B%0A++++++++++++text%3A+%22%5C%22%5C%7Bel.prop%7D%5C%22%22%3B%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native) (see comments):

```slint
import { VerticalBox } from "std-widgets.slint";

component Inner {
    in-out property <string> prop: "inner";
}

export component Demo {
    //in-out property <string> prop: "outer"; // This should supersede.
    in-out property <string> prop; // Default shouldn't necessarily supersede.
    //in-out property <string> prop <=> el.prop; // With this, you also get the inner value. (Below binding must be commented out.)

    VerticalBox {
        alignment: start;

        el := Inner {
            prop <=> root.prop;
        }

        Text {
            text: "\"\{el.prop}\"";
        }
    }
}
```

This demo shows that the value of `el.prop` is an empty string instead of `"inner"`. As far as I can see now, it isn't desirable for the implicit default value `""` to supersede the inner more specific value. I definitely had a case where the superseding implicit defaults on component usages were intruding and undesired over the specific default from inside the component.

**Comment by ogoffart** [comment]
Yes, that's right, when setting a binding, the right hand side of the binding wins.
I took the opportunity to update the documentation in https://github.com/slint-ui/slint/pull/6419

For context, this was done in https://github.com/slint-ui/slint/pull/1821 which explain the rational. (the behavior that you described was how it was first implemented)
