### ISSUE TITLE
Call sequence `select-all()`, `focus()` on `LineEdit` doesn't work from second time onwards

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6403]
Consider [this SlintPad demo](https://slintpad.com/?snippet=import+%7B+Button%2C+VerticalBox%2C+LineEdit+%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+Demo+%7B%0A++++VerticalBox+%7B%0A++++++++alignment%3A+start%3B%0A%0A++++++++Button+%7B%0A++++++++++++text%3A+%22Select+All+and+Focus%5CnClick+Me+Twice%22%3B%0A%0A++++++++++++clicked+%3D%3E+%7B%0A++++++++++++++++%2F%2F+When+you+swap+these+lines%2C+it+works.%0A++++++++++++++++le.select-all%28%29%3B%0A++++++++++++++++le.focus%28%29%3B%0A++++++++++++%7D%0A++++++++%7D%0A%0A++++++++le+%3A%3D+LineEdit+%7B%0A++++++++++++text%3A+%22%60LineEdit%60+content%22%3B%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native) (see comment):

```slint
import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component Demo {
    VerticalBox {
        alignment: start;

        Button {
            text: "Select All and Focus\nClick Me Twice";

            clicked => {
                // When you swap these lines, it works.
                le.select-all();
                le.focus();
            }
        }

        le := LineEdit {
            text: "`LineEdit` content";
        }
    }
}
```

**Comment by tronical** [comment]
The bug here is that `focus()` on an item that is already focused will make the item loose focus and then obtain it again. After #3136 this also clears the selection, but the focus transfer is the bug.
