### ISSUE TITLE
`@image-url()` with URL panics

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6407]
The docs page ["Syntax > Types > Images"](https://docs.slint.dev/1.8.0/docs/slint/src/language/syntax/types#images) has an example that works in SlintPad when you click "Edit" below the example. But when I copy it under Windows 10 into a Rust project with Slint (not matter whether FemtoVG or Skia), it panics:

```
error: failed to run custom build command for `slint-test v0.1.0 (C:\...\slint-test)`     
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `C:\...\slint-test\target\debug\build\slint-test-942f3281f804db67\build-script-build` (exit code: 101)
  --- stderr
  error: Cannot find image file https://slint.dev/logo/slint-logo-full-light.svg
   --> C:\...\slint-test\ui\app-window.slint:5:37
    |
  5 |     in property <image> some_image: @image-url("https://slint.dev/logo/slint-logo-full-light.svg");    
    |                                     ^

  thread 'main' panicked at build.rs:2:49:
  called `Result::unwrap()` on an `Err` value: CompileError(["C:\\...\\slint-test\\ui\\app-window.slint:5: Cannot find image file https://slint.dev/logo/slint-logo-full-light.svg"])
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\panicking.rs:72
     2: core::result::unwrap_failed
               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\result.rs:1679
     3: core::char::methods::encode_utf8_raw
     4: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tronical** [comment]
What I see is that `@image-url("http://....")` in a local build produces a slint compile error. That'll be visible in the LSP, it's a compile error in the build.rs, and it would be a `compile_error!` if it were inside a `slint!` macro.

Could you explain please what you think the bug is and what behaviour you'd expect instead of a compile error?

**Comment by Enyium** [comment]
I was on the track of needing to report inner Slint panics when seeing `` called `Result::unwrap()` on an `Err` value ``, because I saw such panics a couple of times. It was a bit careless. `expect()` instead of `unwrap()` in `build.rs` may be better to look less like a panic that should never happen. I created <https://github.com/slint-ui/slint-rust-template/pull/29> for this.
