### ISSUE TITLE
Selection rectangle reacts on clicking text to the right of `inherits` instead of text to the left

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6409]
Consider [this SlintPad demo](https://slintpad.com/?snippet=export+component+AppWindow+inherits+Window+%7B%0A++++width%3A+200px%3B%0A++++height%3A+self.width%3B%0A%0A++++Rectangle+%7B%0A++++++++width%3A+100px%3B%0A++++++++height%3A+self.width%3B%0A++++%7D%0A%7D%0A&style=native):

```slint
export component AppWindow inherits Window {
    width: 200px;
    height: self.width;

    Rectangle {
        width: 100px;
        height: self.width;
    }
}
```

Clicking the different spots behaves like this:

https://github.com/user-attachments/assets/7bb2c5d3-3a27-4ba6-bd47-33156333b330

I think this is counterintuitive and badly discoverable. Clicking on the identifier to the *left* of `inherits` should be what changes the selection rectangle.

**Comment by hunger** [comment]
True. This is because the Element ends at `Window` and we need the Component around it for the `AppWindow` :-)
