### ISSUE TITLE
TouchArea pressed: true doesn't reset to false when TouchArea.interactive is set to false

### ISSUE THREAD

**Issue by NigelBreslaw** [slint-ui/slint#6422]
See this [example](https://slintpad.com/?snippet=export+component+AppWindow+inherits+Window+%7B%0A%0A++++preferred-width%3A+300px%3B%0A++++preferred-height%3A+300px%3B%0A%0A++++Rectangle+%7B%0A++++++++width%3A+parent.width%3B%0A++++++++height%3A+parent.height%3B%0A++++++++background%3A+white%3B%0A++++++++VerticalLayout+%7B%0A++++++++++++Text+%7B+%0A++++++++++++++++text%3A+%22tap+and+hold%22%3B%0A++++++++++++++++color%3A+black%3B%0A++++++++++++%7D%0A++++++++++++Text+%7B%0A++++++++++++++++text%3A+%22TouchArea.pressed%3A+%22+%2B+%28ta.pressed+%3F+%22true%22+%3A+%22false%22%29%3B%0A++++++++++++++++color%3A+black%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++++++%0A++++++++ta+%3A%3D+TouchArea+%7B%0A%0A++++++++++++changed+pressed+%3D%3E+%7B%0A++++++++++++++++timer.running+%3D+true%3B%0A++++++++++++%7D%0A++++++++++++%0A++++++++++++timer+%3A%3D+Timer+%7B%0A++++++++++++++++interval%3A+100ms%3B%0A++++++++++++++++running%3A+false%3B%0A++++++++++++++++triggered+%3D%3E+%7B%0A++++++++++++++++++++ta.enabled+%3D+false%3B%0A++++++++++++++++%7D%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D&style=native).

Tap and hold anywhere. Pressed goes to true and after 100ms the TouchArea is set to interactive = false. It is now stuck in pressed = true and the expected cleanup never happens.

Noticed this with the new demo where on setting the dial to be `interactive: false` to stop any possible moves during the unlock animation. But then the code to clean up the dial behaviour when it's no longer pressed fails to happen.

**Comment by ogoffart** [comment]
(I assume you meant `enabled` and not `interactive`)

**Comment by NigelBreslaw** [comment]
Yes, enabled!
