### ISSUE TITLE
Unexpected delay to animation when using 'animate <property> { .....`

### ISSUE THREAD

**Issue by NigelBreslaw** [slint-ui/slint#6427]
See this [example](https://slintpad.com/?snippet=import+%7BButton%2C+ComboBox%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+ExportedComponent+inherits+Window+%7B%0A++++preferred-width%3A+200px%3B%0A++++preferred-height%3A+400px%3B%0A%0A++++property+%3Cbool%3E+toggle%3A+true%3B%0A%0A+++%0A%0A++++if+cb.current-value+%3D%3D+%22Demo+1%22%3A+Rectangle+%7B%0A++++++++x%3A+0%3B%0A++++++++y%3A+0%3B%0A++++++++background%3A+red%3B%0A++++++++width%3A+100%25%3B%0A++++++++height%3A+toggle+%3F+100%25+%3A+20%25%3B%0A++++++++animate+height+%7B%0A+++++++++++++duration%3A+2s%3B%0A+++++++++++++easing%3A+ease-in-out-sine%3B%0A++++++++%7D%0A++++++++Rectangle+%7B%0A++++++++++++x%3A+0%3B%0A++++++++++++y%3A+parent.height+-+self.height%3B%0A++++++++++++width%3A+100%25%3B%0A++++++++++++height%3A+40px%3B%0A++++++++++++background%3A+blue%3B%0A++++++++++++opacity%3A+parent.height+%3E%3D+root.height+%3F+1.0+%3A+0.0%3B%0A++++++++++++animate+opacity+%7B%0A++++++++++++++++duration%3A+250ms%3B%0A++++++++++++++++easing%3A+ease-in-out-sine%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%0A+++++Button+%7B%0A++++++++text%3A+%22Toggle%22%3B%0A++++++++clicked+%3D%3E+%7B%0A++++++++++++toggle+%3D+%21toggle%3B%0A++++++++%7D%0A++++%7D%0A%0A++++if+cb.current-value+%3D%3D+%22Demo+2%22%3A+Rectangle+%7B%0A++++++++x%3A+0%3B%0A++++++++y%3A+0%3B%0A++++++++background%3A+red%3B%0A++++++++width%3A+100%25%3B%0A++++++++height%3A+toggle+%3F+100%25+%3A+20%25%3B%0A++++++++animate+height+%7B%0A+++++++++++++duration%3A+2s%3B%0A+++++++++++++easing%3A+ease-in-out-sine%3B%0A++++++++%7D%0A++++++++Rectangle+%7B%0A++++++++++++x%3A+0%3B%0A++++++++++++y%3A+parent.height+-+self.height%3B%0A++++++++++++width%3A+100%25%3B%0A++++++++++++height%3A+40px%3B%0A++++++++++++background%3A+blue%3B%0A++++++++++++%0A++++++++++++states+%5B%0A++++++++++++++++isVisible+when+parent.height+%3E%3D+root.height%3A+%7B%0A++++++++++++++++++++opacity%3A+1.0%3B%0A++++++++++++++++++++in+%7B%0A++++++++++++++++++++++++animate+opacity+%7B%0A++++++++++++++++++++++++++++duration%3A+600ms%3B%0A++++++++++++++++++++++++++++easing%3A+ease-in-out-sine%3B%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++%7D%0A++++++++++++++++%7D%0A++++++++++++++++isNotVisible+when+parent.height+%3C+root.height%3A+%7B%0A++++++++++++++++++++opacity%3A+0.0%3B%0A++++++++++++++++++++in+%7B%0A++++++++++++++++++++++++animate+opacity+%7B%0A++++++++++++++++++++++++++++duration%3A+600ms%3B%0A++++++++++++++++++++++++++++easing%3A+ease-in-out-sine%3B%0A++++++++++++++++++++++++%7D%0A++++++++++++++++++++%7D%0A++++++++++++++++%7D%0A++++++++++++%5D%0A++++++++%7D%0A++++%7D%0A%0A+++++Button+%7B%0A++++++++text%3A+%22Toggle%22%3B%0A++++++++clicked+%3D%3E+%7B%0A++++++++++++toggle+%3D+%21toggle%3B%0A++++++++%7D%0A++++%7D%0A%0A+++++cb+%3A%3D+ComboBox+%7B%0A++++++++x%3A+10px%3B%0A++++++++y%3A+10px%3B%0A++++++++model%3A+%5B%22Demo+1%22%2C+%22Demo+2%22%5D%3B%0A++++++++current-value%3A+%22Demo+1%22%3B%0A++++%7D%0A%0A%0A%7D&style=native)

In Demo 1 there is a binding to change the opacity of the blue rectangle when the view is not the same height as the parent. An animation then changes the opacity. You can tap toggle to swap between the two states. However when the red rectangle starts to shrink the blue items opacity does not change. It is only when the red item has finished it's animation that the blue one starts.

In Demo 2 the exact same logic is controlled via states. Here the blue item fades in and out as expected.

**Comment by ogoffart** [comment]
Dusplicate of https://github.com/slint-ui/slint/issues/4811
