### ISSUE TITLE
Slint Memory Game Tutorial is not accessible (Error 404: Page not found)

### ISSUE THREAD

**Issue by Qubi0-0** [slint-ui/slint#6437]
![404-slint-cpp-example](https://github.com/user-attachments/assets/ce2c703b-7fde-4c3d-8a88-8889f3489e4b)

On https://docs.slint.dev/1.8.0/docs/cpp/getting_started in the tutorial section the link to  [Slint Memory Game Tutorial](https://docs.slint.dev/1.8.0/docs/quickstart/cpp). does not work. 

# Error 404: Page not found

**Comment by ogoffart** [comment]
Thanks a lot for reporting the issue. 

The correct link is https://slint.dev/docs/slint/src/quickstart/

I have fixed link in commit 1c3eb46752eba30200b9f38b7bf3527d58d0efe8
But the docs won't be updated until the next version.

We could consider patching the live website or adding redirect, but i'm not sure it's worth the trouble. @tronical?

**Comment by tronical** [comment]
(Thanks for fixing :)
