### ISSUE TITLE
Element selection rectangle incorrectly placed

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6438]
Consider [this SlintPad demo](https://slintpad.com/?snippet=import+%7B+VerticalBox%2C+Button+%7D+from+%22std-widgets.slint%22%3B%0A%0Aexport+component+Demo+%7B%0A++++VerticalBox+%7B%0A++++++++alignment%3A+start%3B%0A++++++++Rectangle+%7B%0A++++++++++++Button+%7B%0A++++++++++++++++%2F%2Ftext%3A+%22Foo%22%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native):

```slint
import { VerticalBox, Button } from "std-widgets.slint";

export component Demo {
    VerticalBox {
        alignment: start;
        Rectangle {
            Button {
                //text: "Foo";
            }
        }
    }
}
```

- In SlintPad, click once on `Button` to show its selection rectangle.
- Now remove and readd `//` repeatedly to see that the selection rectangle is always incorrectly placed.

This happens in SlintPad and the VS Code extension preview window.

Demo video:

https://github.com/user-attachments/assets/d85d7b20-e5ba-40a5-96ad-0591880ab533

**Comment by hunger** [comment]
This effect is a mix of the review not resizing when the min size changes (fixed in #6465) and the selection not updating when the preview resizes.

The later will be fixed in a PR marked as fixing this issue.
