### ISSUE TITLE
Clicking `TextInput`'s text with the secondary mouse button changes cursor

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6444]
Consider [this SlintPad demo](https://slintpad.com/?snippet=export+component+Demo+%7B%0A++++TextInput+%7B%0A++++++++text%3A+%22Click+text+with+secondary+mouse+button.%22%3B%0A++++%7D%0A%7D%0A&style=native):

```slint
export component Demo {
    TextInput {
        text: "Click text with secondary mouse button.";
    }
}
```

When hovering the text, a text selection (I-beam) cursor is shown. When clicking with the primary (and even tertiary) mouse button, it stays shown. But when clicking with the secondary mouse button, it becomes the default cursor. Without a reason, like a context menu being shown, the cursor shouldn't change.

**Comment by ogoffart** [comment]
This is caused because the TextInput "ignores" the mouse release of that button and caused an Exit event to change back to the default cursor
