### ISSUE TITLE
[BUG] slint::init_translations! expected one of `!` or `::` in this macro invocation

### ISSUE THREAD

**Issue by R3alCl0ud** [slint-ui/slint#6454]
`slint::init_translations` causes app to not compile

Arch Linux: Cosmic
Rust: Rustc 1.81.0
Slint: 1.8.0

Expected:
`slint::init_translations!("path/to/translations");` // compiles and includes translations for app

Actual:
```
error: expected one of `!` or `::`, found `(`
  --> src/main.rs:36:1
   |
36 | slint::init_translations!(concat!(env!("CARGO_MANIFEST_DIR"), "/lang/"));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   | |
   | expected one of `!` or `::`
   | in this macro invocation
   |
   = note: this error originates in the macro `slint::init_translations` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by tronical** [comment]
Is it possible that the fettest feature isn't enabled?

**Comment by R3alCl0ud** [comment]
Nope, I figured it out, the macro has to be placed inside of a function. 
The [main docs](https://docs.slint.dev/1.8.0/docs/slint/src/language/concepts/translations#select-and-load-translations-with-rust) didn't specify that so I placed it next to `slint::include_modules!();`
