### ISSUE TITLE
App freezes up after modifying model

### ISSUE THREAD

**Issue by whisperdoll** [slint-ui/slint#646]
I can reproduce on the Todo example. After adding an item and scrolling the list back and forth a bit, the app visually hangs (seems to accept inputs, just doesn't update anything visually) until I resize the window. After I resize the window, the display updates to reflect things I did while it was hanging.

I'm running this w/ Windows 10, Rust, Fluent style.

**Comment by tronical** [comment]
I have the strong feeling that this is most likely the same as #608 :-/

**Comment by tronical** [comment]
Commit 575665994aa348abec097178f3cc0b57333c110e fixes this (reproduced before and after on Windows 10 with GL backend)
