### ISSUE TITLE
Code suggestion uses `-` in name, if variable contains `_`

### ISSUE THREAD

**Issue by qarmin** [slint-ui/slint#6479]
https://releases.slint.dev/1.8.0/editor/?snippet=import+%7B+AboutSlint%2C+Button%2C+VerticalBox+%7D+from+%22std-widgets.slint%22%3B%0Aexport+component+Demo+%7B%0A++++item_with+%3A%3D+VerticalBox+%7B%0A++++++++alignment%3A+start%3B%0A++++++++Text+%7B%0A++++++++++++text%3A+it%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native

![Screenshot from 2024-10-07 22-50-05](https://github.com/user-attachments/assets/ce799a56-809d-45b5-881c-bc818e536fb0)

**Comment by hunger** [comment]
#382 normalized `_` to `-`.

#3935 is the same issue for property names, which has been fixed in #4389.
