### ISSUE TITLE
open slint show preview in vs code from VM debian12 got  Slint Language Server crashed

### ISSUE THREAD

**Issue by banrieen** [slint-ui/slint#6555]
Invalid MIT-MAGIC-COOKIE-1 key
VMware: No 3D enabled (0, Success).
VMware: No 3D enabled (0, Success).
Using Skia OpenGL renderer
Rendering at 1280x800
thread 'main' panicked at tools/lsp/preview/native.rs:122:40:
called `Result::unwrap()` on an `Err` value: OtherError("Error presenting framebuffer on screen: Permission denied (os error 13)")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 10:39:54] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues

**bug env** 
vs code: 1.92.2 ,
OS: win 11 (windows NT x64 10.0.22621)
VM : virtualbox 7.0.18 
VM OS: debian 12 
code lang: rust(cargo) 1.81.0

**Reproduce**
1. open vs code , connect the VM debian12 
2. open the VM code project(folder) UI 
3. open the *.slint file
4. Ctrl+shift+P , select the Slint show preview

**Comment by ogoffart** [comment]
I'm going to close this issue since the panic was fixed in #6430
But thanks anyway for reporting the bug.

The error itself means that the slint-lsp process can't access the display server.

**Comment by banrieen** [comment]
Ok,  thanks
