### ISSUE TITLE
`Dialog` doesn't auto-add callbacks for `dialog-button-role` elements

### ISSUE THREAD

**Issue by Enyium** [slint-ui/slint#6558]
The [docs on `Dialog`](https://docs.slint.dev/1.8.0/docs/slint/src/language/builtins/elements#dialog) say:

> A callback `<kind>_clicked` is automatically added for each `StandardButton` which doesn’t have an explicit callback handler

This isn't done for elements (like `Button`s) with `dialog-button-role`. But I think it's indicated to do this.

(This currently failing can't be demonstrated with SlintPad, since the `StandardButton` callbacks also only seem to be added for native code [for me Rust], and not other Slint code, not even the `Dialog` itself.)

**Comment by ogoffart** [comment]
Widget other than standard button don't have a kind. So we can't have automatic callback.
This was just made for convenience for the StandardButton.

For other button, you can declare the callback yourself
```slint
component Foo inherits Dialog {
   callback foo_clicked <=> foo.clicked;
   foo := Button { text: "Foo"; }
   //...
}
```
