### ISSUE TITLE
Add API to improve interaction between C++ application worker threads and the SixtyFPS event loop

### ISSUE THREAD

**Issue by tronical** [slint-ui/slint#658]
The discussion in #625 made us aware that we may want to add API to make it easier to have a clean and robust interaction between worker threads a C++ application might spawn and the event loop running in the main thread. In particular the phase of shutdown stands out.

Example scenario:

1. Application starts several worker threads
2. The event loop is run in the main thread with `sixtyfps::run_event_loop();`
3. The application decides that it wants to shut down and needs to (a) instruct the event loop to quit and (b) gracefully terminate all worker threads
4. If after the event loop has quit a worker thread still runs `sixtyfps::blocking_invoke_from_event_loop` then the worker will block forever and the application won't gracefully exit.

This can be solved purely on the application level using synchronisation primitives, but it would be great if we had API that made this easy - and it would be even better if we had an example in our repo that demonstrates this :-)

We'd like the ideal application code to look like this in the shutdown phase (pseudo code):

Option 1:

```cpp
// in main
// ...
ui->on_close_button_clicked([]() { sixtyfps::quit_event_loop(); }
sixtyfps::run_event_loop();
application_code_to_tell_threads_to_stop();
join_threads();
```

Option 2:

```cpp
// in main
// ...
sixtyfps::on_last_window_closed([]() { application_code_to_tell_threads_to_stop(); }); // or ::on_quit_event_loop_requested()
sixtyfps::run_event_loop();
join_threads();
```

Option 3:

```cpp
// in main
// ...
sixtyfps::run_event_loop_with_quit_notifier([](){ application_code_to_tell_threads_to_stop(); });
join_threads();
```

In all cases (not sure if (1) is possible?), we'd also need the worker threads to somehow establish a "claim" on the event loop, so that the loop remains available for receiving `blocking_invoke_from_event_loop()` events until all threads have finished. This could be an atomic reference count, perhaps implemented behind a C++ "guard" type that threads need to keep alive. For example:

```cpp
std::thread worker([]() {
    // increase refcount on event loop in constructor, release in destructor
    sixtyfps::ThreadedEventLoopGuard guard;
    for (;;) {
        // ...
    }
});
```

The implementation of `sixtyfps::run_event_loop()` then would have to keep spinning the loop until all guards have been destroyed. And when the loop has been instructed by the application to gracefully terminate, it would invoke an application-supplied callback that can send messages to the worker threads to terminate.

**Comment by ogoffart** [comment]
I think your option (2) is the best.

So we need to implement 
 - [ ] `sixtyfps::on_last_window_closed`
 - [ ] `sixtyfps::ThreadedEventLoopGuard`

Regarding ThreadedEventLoopGuard, a better name would maybe be simply `EventLoopGuard` because it could also be used in the main thread.  It kind of replace the use for [`EventLoopQuitBehavior`](https://docs.rs/sixtyfps-corelib/0.1.4/sixtyfps_corelib/backend/enum.EventLoopQuitBehavior.html)
It's constructor increment a eventloop refcount, and its destructor decrement the refcount and wakes up the event loop if it is in a thread and the refcount reached 0.  The main loop quits when the refcount reaches 0  (and windows also count as a refcount)

**Comment by DaMilyutin** [comment]
I initially thought about some custom ThreadPool which makes event loop to contunue until all workers stop.
But idea with `EventLoopGuard` seems even better to me.
Maybe, if this special ThreadPool occurs, it can use `EventLoopGuard` in implementation.

Doesn't Rust spawn worker threads? I mean, this seems to be useful for Rust, isn't it?

**Comment by tronical** [comment]
> I think your option (2) is the best.
> 
> So we need to implement
> 
> * [ ]  `sixtyfps::on_last_window_closed`

I'm leaning towards (3) to also support a third use-case: The application wants to quit, regardless of any open windows or not. Shouldn't it be sufficient to call `sixtyfps::quit_event_loop()` then? In that case, I think it's better to have a callback parameter on `sixtyfps::run_event_loop()` (or a variant of that function), instead of requiring a "stop_all_threads()" at every call site where the app may want to quit.

> Regarding ThreadedEventLoopGuard, a better name would maybe be simply `EventLoopGuard` because it could also be used in the main thread. It kind of replace the use for [`EventLoopQuitBehavior`](https://docs.rs/sixtyfps-corelib/0.1.4/sixtyfps_corelib/backend/enum.EventLoopQuitBehavior.html) It's constructor increment a eventloop refcount, and its destructor decrement the refcount and wakes up the event loop if it is in a thread and the refcount reached 0. The main loop quits when the refcount reaches 0 (and windows also count as a refcount)

Excellent point, I agree.

**Comment by ogoffart** [comment]
> I initially thought about some custom ThreadPool which makes event loop to contunue until all workers stop.

The problem is that the thread pool is that this might really be specific to your use in the application, and you may already be using another library that uses threads, so we don't want to be responsible for the creation and deletion of threads. You will have to use another library for that.
What do you currently use for your thread pool?

> Doesn't Rust spawn worker threads?

The current implementation of SixtyFPS doesn't make use of theads. But that we might use some in the backend to paralelize stuff at some point.

**Comment by DaMilyutin** [comment]
I used first one I found on github (https://github.com/bshoshany/thread-pool) and then (beause I thought it is something about thread pool but not event loop) switched to other (https://github.com/dabbertorres/ThreadPool.git).
But it does not really matter, what thread pool I use. You're right about that.
It might be specific. There may be few thread pools.

>The current implementation of SixtyFPS doesn't make use of theads. But that we might use some in the backend to paralelize stuff at some point.

I mean not SixtyFPS but Rust application using SixtyFPS may spawn threads.

**Comment by DaMilyutin** [comment]
Hello, @ogoffart, @tronical, It's been a while.
A loooot of changes in slint.
I'm curious if anything updated on this issue?

**Comment by tronical** [comment]
Hi @DaMilyutin . We haven’t done any work on this issue :(

**Comment by DaMilyutin** [comment]
@tronical, @ogoffart, I've got new thought on this. Quite simple and naive.
What if function `invoke_from_event_loop` would restart event loop if it is stopped?
Or ex. another you could provide function named ex. `force_invoke_from_event_loop` with named functionality. 
This releases user from writing boilerplate and looks like will ensure seamless exit when worker threads are interacting with event_loop.
Is this a solution?

**Comment by tronical** [comment]
Hmm, I’m not sure it’s possible to restart the event loop in the main thread when i_f_e is called. Could you elaborate a bit on the semantics that you have in mind?

**Comment by ogoffart** [comment]
We discussed this and decided this is outside of the scope of Slint
