### ISSUE TITLE
Fluent style's `Switch`  text is lighter/gray

### ISSUE THREAD

**Issue by alexeyabel** [slint-ui/slint#6595]
The text of a `Switch` is lighter (grey) than other text in 5032ff194326f68b11237fd0942ac5e9401a4b2b. This was [recently fixed](https://github.com/slint-ui/slint/issues/6239) for `CheckBox` but remains for at least `Switch`.

See "Copy original steams" in this picture. The switch is enabled.
![Screenshot_20241020_170353](https://github.com/user-attachments/assets/220868ce-6718-43c0-a61b-f25639b83b30)

**Comment by JoeySoprano420** [comment]
Undubscribe
