### ISSUE TITLE
triggering `changed` from a global and from code not working.

### ISSUE THREAD

**Issue by TheColorRed** [slint-ui/slint#6599]
**Note:** I am not sure where the point of failure is here, whether I am doing something wrong, or I am attempting something that isn't supported.

I would like `changed` to be triggered from the rust code where the callback is within a `global`. I have tried also calling this from another `slint` file, but that too doesn't do anything.

What I was expecting is for the event to trigger but it doesn't whether I call it from a `.rs` file or from another `.slint` file.

```slint
export global AppState {
    callback active-project-changed(int);
    in property <int> active-project: 0;
    changed active-project => {
        debug(active-project);
        active-project-changed(active-project);
    }
}

export component AppWindow inherits Window {
  Button  {
    clicked => { AppState.active-project: 0 }
  }
}
```

```rs
slint::slint! {
  export { AppWindow } from "packages/app/ui/main.slint";
  export { AppState } from "packages/app/ui/app-state.slint";
}
let app = AppWindow::new()?;

let app_state = app.global::<AppState>();

app_state.set_active_project(1);
```

**Comment by JoeySoprano420** [comment]
Unscribr

**Comment by ogoffart** [comment]
Thanks for reporting the issue. 
changed callback on global property indeed didn't work. Will be fixed in the next version.

**Comment by JoeySoprano420** [comment]
Unsubscribe
