### ISSUE TITLE
Android: the event loop should finish when the activity is destroyed

### ISSUE THREAD

**Issue by suguruwataru** [slint-ui/slint#6626]
Platform: Android
language: Rust
Slint version: 1.8.0
Reproduction:
1. Create a basic Android app. Something like a `Rectangle` with blue background. I can provide example code later. `android_main` must call `ComponentHandle::run`.
2. Open the app. Then destroy the activity by using the Android back button/gesture.
3. Open the app again. One will expect to see the blue rectangle again. However, they see a blank screen instead.

The problem here is that, the slint event loop doesn't get stopped when the activity is destroyed. So after the activity is destroyed, `android_main` just keeps running and never returns. However, `android_main` is actually expected to return soon after the destroy event:
https://docs.rs/android-activity/latest/android_activity/enum.MainEvent.html#variant.Destroy

I suppose `android_main` has the effect of blocking new events from being received, and since it never returns, no event is ever received, and no redraw ever happens, and the app becomes blank.

I have tried using `init_with_event_listener` and stop the event loop on `Destroy` event. After doing this, `android_main` does return and opening the app again calls `android_main` again to initialize a new activity. However, this still won't work. `init_with_event_listener` fails with `AlreadySet`. I then tried using `Once::call_once` to call `init_with_event_listener` only once. This time, on the second call of `android_main`, calling `new` for the component fails with `NoPlatform`. If I move this call also into `call_once`, calling `run` on the component still fails with `NoPlatform`. So upon the second call of `android_main`, slint seems to have entered a weird state of the platform being both set and not set. I guess some kind of cleanup needs to happen on the `Destroy` event to make this work.

**Comment by ogoffart** [comment]
Thanks for filing a bug.
Indeed, you're right, we should end the event loop wen receiving the Destroyed event.
(That explain the crash i was getting when changing to dark mode)
And even if we dod that, you're right again that slint::android::init* can only be called once,  while the android_main is called from a different thread. 

I'll have to think on how to fix this issue.
