### ISSUE TITLE
`slint::quit_event_loop()` causes QObject Timers error

### ISSUE THREAD

**Issue by DASPRiD** [slint-ui/slint#6627]
Given the following (overly simplified) example:

```rust
let app_window = AppWindow::new()?;

app_window.window().on_close_requested(|| {
    // Ignore that this is here, it's actually in a completely different part of
    // my program, but for simplicity I have it here.
    let _ = slint::quit_event_loop();
    CloseRequestResponse::HideWindow
});

std::thread::spawn({
    let handle = app_window.as_ref();
    move || {
        std::thread::sleep(Duration::from_secs(1));

        handle.upgrade_in_event_loop(|handle| {
            handle.show().unwrap();
        }).unwrap();
    }
})

slint::run_event_loop_until_quit()?;
```

Once I close the window to trigger `slint::quit_event_loop()`, the program exits as expected (with exit code `0`), but emits the following error message, which I assume is coming from QT:

`QObject::~QObject: Timers cannot be stopped from another thread`

I also once saw the following message instead, though I couldn't reproduce that since:

`QMutex: destroying locked mutex`

**Comment by DASPRiD** [comment]
My current workaround is to simply disable the QT backend and use `winit` on all systems, I guess there's not really any downside to that?

**Comment by ogoffart** [comment]
Thanks for the bug report.
I couldn't reproduce the problem.
I tried your example on Linux (with a few fix to make it compile like as_weak instead of as_ref) but it doesn't work.

Could you maybe give us a self contained example?
What version of Qt are you using?
What platform are you on?

**Comment by DASPRiD** [comment]
Nevermind, I boiled it down to something which seemed unrelated:

When calling `std::process::exit(1)` in another thread, QT is simply not happy about that. Ignore this disturbance :)
