### ISSUE TITLE
Add Markdown syntax support to Text, TextInput, TextEdit.

### ISSUE THREAD

**Issue by MINGtoMING** [slint-ui/slint#6684]
I'm using slint(rust) to develop a blog interface that needs to support Markdown syntax rendering to enhance presentation.  Thanks.

**Comment by ogoffart** [comment]
Thanks for the feature request.
The ability to have rich text backed by HTML or Markdown is already tracked in https://github.com/slint-ui/slint/issues/2723
I'm going to close this issue as a duplicate. But thanks anyway for the request.
