### ISSUE TITLE
Components of Slint 1.8.0 not found in Jetbrains plugin

### ISSUE THREAD

**Issue by Nikotecnology** [slint-ui/slint#6788]
On the latest version of Jetbrains Slint plugin the latest components of version 1.8.0 are not found

**Comment by kizeevov** [comment]
The plugin is supported separately from the main team. You can ask questions or write about the problem [here: slint-idea-plugin](https://github.com/kizeevov/slint-idea-plugin/issues).
The inclusion of binaries version 1.8.0 will be in the near future. If you can't wait, use the external [dependency setting](https://github.com/kizeevov/slint-idea-plugin?tab=readme-ov-file#dependencies)

**Comment by ogoffart** [comment]
I see this has been reported there: https://github.com/kizeevov/slint-idea-plugin/issues/64
Closing this issue, thanks for reporting.
