### ISSUE TITLE
Broken link to @image-url macro in Image docs

### ISSUE THREAD

**Issue by mgunyho** [slint-ui/slint#6843]
### Bug Description

In the [documentation](https://docs.slint.dev/latest/docs/slint/src/language/builtins/elements#image) for the Image element, the `source` doc says "use the `@image-url` macro to specify the image, but the link points to https://docs.slint.dev/latest/docs/slint/src/language/builtins/elements#../syntax/types#images which seems incorrect. I'm not sure where it should exactly point to, maybe to the image type docs here? https://docs.slint.dev/latest/docs/slint/src/language/syntax/types#images

### Environment Details

- Slint Version: 1.8.0
- Platform/OS:
- Programming Language:
- Backend/Renderer:

**Comment by ogoffart** [comment]
Thanks a lot for reporting the issue.

We are in process of revamping our docs, and the good news is the the new docs have fixed the problem already.
https://snapshots.slint.dev/master/docs/slint/reference/elements/image/#source

So this issue is fixed in the new version.
