### ISSUE TITLE
Converting enum to string

### ISSUE THREAD

**Issue by dorukotiv** [slint-ui/slint#6852]
### Feature Description

Currently, an enum that is defined in slint can not be given to the Text component as an input, a callback needs to be implemented in Rust to do the conversion. 

Ideally, I would directly use the enum text as an input to the text. 

Example:
```slint
enum Direction {
Right,
Left
}

Text {
text : Direction.Right;
}
```

that would be seen as "Right" on the screen.

### Product Impact

We are a railway company building Remote Supervision Control Desktop application for a locomotive.

It would reduce the code and time.

**Comment by tronical** [comment]
I suggest we don't implement this. But I'd like the ability for user to write something like this:

```slint
function direction-string(dir: Direction): string {
    match dir {
        Direction.Left => "left",
        // compiler errors out, because `Right` isn't handled here
    }
}
```

**Comment by ogoffart** [comment]
We already have a tracking issue for a match or switch: https://github.com/slint-ui/slint/issues/1307

In the mean time, it can be done with something like:
```slint
function direction-string(dir: Direction): string {
    return dir == Direction.Left ? "left"
         : dir == Direction.Right ? "right"
         : ""; // unfortunately no errors/warnings at this point
    }
}
``` 

or in rust with a callback that does `to-string` based on `@rust-attr(derive(strum_macros::Display))`
