### ISSUE TITLE
Native ListView widget on MacOS looks very non-native

### ISSUE THREAD

**Issue by cmot17** [slint-ui/slint#686]
Here is what the SixtyFPS ListView looks like:
![image](https://user-images.githubusercontent.com/25753364/143526132-6661d44b-d2fe-43a1-9e93-27704bcb370b.png)
And here it is with "red" selected (notice it is a very slightly different shade of grey):
![image](https://user-images.githubusercontent.com/25753364/143526193-ab4b1e52-c263-477b-b5fc-df77eaf8e3d6.png)

Here is an example of a real native list view:
![image](https://user-images.githubusercontent.com/25753364/143526358-e1a6da7f-d3fa-48c4-a444-4164c503b499.png)
and another slightly different one:
![image](https://user-images.githubusercontent.com/25753364/143526446-b2427db5-b102-4baf-8659-5203cb5dd986.png)

Notice a couple of things:
- The colors of the background are very different in the one with the alternating colors compared to the SixtyFPS one.
- The scrollbars on the MacOS ones are hidden until that area is moused over, and they overlay on the content instead of having a separate area designated for them.
- When an item is selected it's blue

**Comment by tronical** [comment]
Indeed. I wonder especially where the lack of color comes from. I remember debugging the same for the tabs (wasn't blue, but is now).

**Comment by ogoffart** [comment]
The cupertino style is now recommended on macOS. (and that's the default in 1.3)
closing issue related to the Qt style on macOS
