### ISSUE TITLE
TabWidget native MacOS style issues

### ISSUE THREAD

**Issue by cmot17** [slint-ui/slint#690]
Here is an example of a tabbed view from Handbrake, which matches the system style:
<img width="459" alt="handbrake" src="https://user-images.githubusercontent.com/25753364/143615224-c0adeb47-689a-45b3-9308-ec77286cd72b.png">

Here is what it looks like in the "gallery" example:
<img width="295" alt="gallery" src="https://user-images.githubusercontent.com/25753364/143615349-1524e47f-0c69-4d37-b5ee-3cdc80696711.png">

Besides the obvious style differences, the line from the box underneath the tabs is visible in the SixtyFPS version, under the tabs that are not currently selected.

**Comment by cmot17** [comment]
These both seem possibly related:

https://bugreports.qt.io/browse/QTBUG-71741
https://bugreports.qt.io/browse/QTBUG-73852

It also seems like the style difference is because Apple changed the native style sometime after Mojave - might be a Qt issue.

**Comment by ogoffart** [comment]
Yes this looks like a Qt bug.

In the long term, we would like to have a specific rendering backend for Mac that does not use Qt.
But this is not really in our priority right now, and it would be a lot of work.

**Comment by n-raine** [comment]
Would you accept a PR adding native theme(s) to the GL backend?

(This is definitely not a guarantee that I'll make one due to the amount of work required, but I'd be interested in trying.)

**Comment by ogoffart** [comment]
@n-raine yes of course we would accept. It would be amazing. It's just that this can be a huge task.


There are different way to go with this: either implement a similar enough looking theme in .skint. It won't look exactly native but it might be good enough.
Or implement the native style with native code that draw the widgets using calls to the macOs libraries.

Either way, i'd be happy to review or answer questions

**Comment by n-raine** [comment]
I think I'll go with the first one if possible. One of the many things I like about Slint is that there's very little room for security issues; as I understand it, when using the GL backend, almost everything is done in safe Rust, including vector graphics rendering. Adding a native theme to the GL backend would therefore improve security.

**Comment by tronical** [comment]
> when using the GL backend, almost everything is done in safe Rust, including vector graphics rendering.

Unfortunately that's not the case. Basically any call to a GL driver is "unsafe" - the driver can do anything with those pointers to texture data provided.

**Comment by n-raine** [comment]
I know, I just meant that the vector graphics drawing itself is done in safe Rust (rather than rasterizing on the GPU or in C/C++)

**Comment by ogoffart** [comment]
The cupertino style is now recommended on macOS. (and that's the default in 1.3)
closing issue related to the Qt style on macOS

**Comment by kekeimiku** [comment]
How did you achieve the native style? Do you need to customize the theme? Why does mine look so different from yours?

<img width="924" alt="image" src="https://github.com/slint-ui/slint/assets/36557882/a41936d5-04ce-4c76-8300-f13668c1bba0">
