### ISSUE TITLE
Double allocations on heap when loading image?

### ISSUE THREAD

**Issue by SKTT1Ryze** [slint-ui/slint#6993]
### Bug Description

I am testing the performance of a Slint application on the Android platform. Compared to native Android applications, Slint seems to use more heap memory in scenarios involving image loading.
Further analysis revealed that after loading an image, the heap memory growth in the Slint application is always twice that of a native Android application.
Using the heap-profile tool for analysis, it was found that Slint allocates heap memory twice each time an image is loaded:

![image](https://github.com/user-attachments/assets/1fb78a52-7477-44fa-bfc4-afcff46ac223)

Here is the pseudocode for loading images in the Slint application:
```Rust
slint::include_modules!();

use std::rc::Rc;
use slint::VecModel;
use slint::ModelRc;

let ui = Rc::new(App::new().unwrap());

let the_images = Rc::new(VecModel::from(vec![])); // A container that holds multiple images

ui.set_images(ModelRc::from(the_images.clone()));

ui.on_button_clicked(move || {
    let img = slint::Image::load_from_path("assets/rust.png")
        .expect("failed to load image"); // Here, a heap memory allocation for an image is made.
    the_images.push(img);
});
```

At the same time, I reviewed the Slint source code and found that in the core module, the image data is cloned and stored in an in-memory cache, which leads to two heap memory allocations:

```Rust
// internal/renderers/skia/itemrenderer.rs

impl<'a> SkiaItemRenderer<'a> {
    fn draw_image_impl(&mut self,
        item_rc: &ItemRc,
        item: Pin<&dyn RenderImage>,
        dest_rect: PhysicalRect) {
        
        ...
        
        let skia_image = self.image_cache.get_or_update_cache_entry(item_rc, || {
            let image = item.source();
            super::cached_image::as_skia_image(
                image,
                &|| item.target_size(),
                if tiling != Default::default() { ImageFit::Preserve } else { item.image_fit() },
                self.scale_factor,
                self.canvas,
            ) // Here, a copy of the image data is stored in the memory cache.
            .and_then(|skia_image| {
                let brush = item.colorize();
                if !brush.is_transparent() {
                    self.colorize_image(skia_image, brush)
                } else {
                    Some(skia_image)
                }
            })
        });
        
        ...
    }
}
```

I want to confirm if this logic is correct and whether this issue can be optimized.

Thanks.

### Environment Details

- Slint Version: 1.8.0
- Platform/OS: Android
- Programming Language: Rust
- Backend/Renderer: Skia

**Comment by ogoffart** [comment]
The same question was also asked in the discussions: https://github.com/slint-ui/slint/discussions/6992
Closing that issue in favor of the discussion
