### ISSUE TITLE
[slint-cpp] Name clash when naming a Slint struct member to a c++ keyword

### ISSUE THREAD

**Issue by antis81** [slint-ui/slint#7006]
### Bug Description

(NOTE: This is an accidental find in the process of "back-porting" one of my example applications to C++.)

Let's assume we created a valid slint struct:

```slint
export struct MyStruct {
    class string,    // ---> In C++ "class" is a registered keyword
}
```

Slint compiler will generate the following C++ code for `app-window.h`:

```c++
class MyStruct {
    public:
    slint::SharedString class;
    friend auto operator== (const class MyStruct &a, const class MyStruct &b) -> bool = default;
};
```

Logically trying to complile this will create the following compiler error:

```
cmake --build build
[ 25%] Generating app-window.h
[ 50%] Building CXX object CMakeFiles/json-visualize.dir/cpp-src/main.cpp.o
In Datei, eingebunden von /home/nils/Projects/rust/json-visualize/cpp-src/main.cpp:1:
/home/nils/Projects/rust/json-visualize/build/app-window.h:16:30: Fehler: expected identifier before »;« token
   16 |     slint::SharedString class;
```

This interoperability issue (corner case) can only be solved by renaming (C++) members. Some suggestions:

- (compilation) Generic solution: Add a `m_` prefix to generated (C++) members
- (compilation) Specific solution: Pre-/Suffix keywords with an underscore `class_`
- (editing) Code Analysis: Perform an LSP analysis step and warn/error out on registered keywords in the editor

### Environment Details

- Slint Version: 1.8
- Platform/OS: Any
- Programming Language: Rust/C++
- Backend/Renderer: Qt

### Product Impact

Language Interoperability (developer/user experience)

**Comment by ogoffart** [comment]
Thanks for reporting an issue.

This was already known as https://github.com/slint-ui/slint/issues/5613 and the good news is that it was fixed recently in https://github.com/slint-ui/slint/pull/6441 (will be in 1.9)

So this issue can be closed, but thanks anyway for reporting.
