### ISSUE TITLE
High RAM consumption

### ISSUE THREAD

**Issue by fakelog** [slint-ui/slint#7026]
### Bug Description

Opening dialog boxes causes huge RAM consumption

### Environment Details

- Slint Version: 1.8.0
- Platform/OS: Windows 11
- Programming Language: Rust
- Backend/Renderer: base (slint = { version = "1.8", features = ["serde"] })

![image](https://github.com/user-attachments/assets/a24d064c-d3e0-4b50-b455-64f0d179a484)

**Comment by fakelog** [comment]
```Slint
import { StandardButton, Button } from "std-widgets.slint";

export component ErrorDialog inherits Dialog {
    in property <string> error <=> error-text.text;
    
    callback report();

    title: "Error";

    error-text := Text {}

    StandardButton { kind: ok; }    
    
    Button {
        text: "Send report";
        dialog-button-role: action;
        
        clicked => { report() }
    }
}
```

```Rust
mod slint_ui {
    slint::include_modules!();
}

use slint::ComponentHandle;

pub struct ErrorHandler {
    error_dialog: Option<slint_ui::ErrorDialog>,
}

impl ErrorHandler {
    pub fn new() -> Self {
        let error_dialog = slint_ui::ErrorDialog::new().expect("Cannot create error dialog");

        Self {
            error_dialog: Some(error_dialog),
        }
    }

    pub fn show(&self, text: &str) {
        if let Some(dialog) = &self.error_dialog {
            dialog.set_error(text.into());

            if let Err(e) = dialog.run() {
                println!("Error: {}", e);
            }
        }
    }
}
```
```Rust
let error_handler = ErrorHandler::new();
error_handler.show("Back stack is empty. Cannot go back.");
```

**Comment by tronical** [comment]
I think that this is most likely the same as #4079 and #3376 , where the use of OpenGL causes the frame buffers to be allocated in main memory that's visible in the task manager. You could try enabling `renderer-skia` as a feature in your `Cargo.toml` - that might most likely reduce the usage. In light of the above linked discussions I'll close this as a duplicated, but please feel free to chime in or re-open if you think that this is unrelated.
