### ISSUE TITLE
Mouse pointer is blurry on high-dpi screen

### ISSUE THREAD

**Issue by ultimaweapon** [slint-ui/slint#7027]
### Bug Description

This happs only when the pointer is in the window:
![Screenshot From 2024-12-07 18-00-00](https://github.com/user-attachments/assets/3dc90d2a-41e2-4a74-b4c3-59123cc56975)

When the pointer outside the window:
![Screenshot From 2024-12-07 18-00-43](https://github.com/user-attachments/assets/92b6c79e-a9e9-4b8b-b6a4-dd6d6c0df063)

### Environment Details

- Slint Version: 1.8.0
- Platform/OS: Arch Linux with GNOME on Wayland
- Programming Language: Rust
- Backend/Renderer: Skia

### Product Impact

Not critical.

**Comment by ogoffart** [comment]
Thanks for filing an issue.

Slint doesn't draw the cursor directly, but this is done by winit and the compositor.

Can you reproduce the problem if you try to run a basic winit example?  (eg https://github.com/rust-windowing/winit/blob/master/examples/window.rs)

**Comment by ultimaweapon** [comment]
Indeed it is winit bugs. I'll close this and report to winit instead. Thanks.

![Screenshot From 2024-12-09 22-55-01](https://github.com/user-attachments/assets/8543593a-704b-4cb5-9317-44923c4fed69)
![Screenshot From 2024-12-09 22-55-36](https://github.com/user-attachments/assets/8737a1e7-be00-4462-b074-2f131ebd7962)

**Comment by ogoffart** [comment]
Thanks.
I see you've openned a bug in the winit bug tracker. Adding a link for reference: https://github.com/rust-windowing/winit/issues/4037
