### ISSUE TITLE
Some Math operations on percent type seem incorrect

### ISSUE THREAD

**Issue by jmEvoqua** [slint-ui/slint#7118]
### Bug Description

Max, Min and Clamp (other not tested) behave differently on the percent type.

Only max seems to be correct, or at least what is expected imo.

See test code

### Reproducible Code (if applicable)

```slint
export component Demo {

    property <percent> p_min: min(50%, 100%);
    property <percent> p_max: max(50%, 0%);
    property <percent> p_clamp: clamp(50%, 0%, 100%);


    VerticalLayout {
        alignment: start;
        Text {
            text: "Min: \{p_min / 1%}";
            font-size: 24px;
            horizontal-alignment: center;
        }  
        Text {
            text: "Max: \{p_max / 1%}";
            font-size: 24px;
            horizontal-alignment: center;
        }    
        Text {
            text: "Clamp: \{p_clamp / 1%}";
            font-size: 24px;
            horizontal-alignment: center;
        }   
    }
}
```

### Environment Details

- Slint Version: 1.8.0
- Platform/OS:
- Programming Language:
- Backend/Renderer:

**Comment by ogoffart** [comment]
I can reproduce the bug. Thanks for reporting.

Looks like the conversion from `%` to number is not done properly in the min/max function.
