### ISSUE TITLE
Components Losing Focus when they shouldn't be

### ISSUE THREAD

**Issue by MattyGam3r** [slint-ui/slint#7159]
### Bug Description

Hello, I am currently using slint, but have ran into a problem with elements losing focus when they shouldn't be.

Firstly, Expand all of the Blue rectangles by pressing the 'view page' buttons, then shrink the view to the point where the scrollview takes place (i.e, the Val 4 and 5 are out of the view). Now scroll down **slightly**, to the point where the text "Val1" in the first blue rectangle is out of the view. Now try and enter a long string into the LineEdit field in the first rectangle

In the code below, on SlintPad, it works as expected, however when compiling the code below into rust and running it, it has a problem where when you scroll down slightly over the blue rectangle (enough so that the top portion is out of the view), and then go into the LineEdit, it runs into an issue where typing into the LineEdit immediately causes it to lose focus, thus making it so the user has to click back onto it to edit it again.

I would expect it for this not to happen. I believe that this is because Slint is confused on the height values.

### Reproducible Code (if applicable)

```slint
import { AboutSlint, Button, VerticalBox, ScrollView, TextEdit, LineEdit, GroupBox } from "std-widgets.slint";
component InputField inherits Rectangle{
    in property <string> label;
    in-out property <bool> hidden : false;
    height: hidden ? 0px: 100px;
    VerticalLayout {
        GridLayout {
            padding-top: 5px;
            padding-bottom: 5px;
            spacing: 10px;
            Row{
                HorizontalLayout {
                    Text {
                        text: label;
                        color: orange;
                        font-size: 20pt;
                        visible: !hidden;
                    }
                    Button {
                        
                        text: hidden ? "View Page" : "Hide Page";
                        clicked => {
                            hidden = !hidden;    
                        }
                    }
                }

            }
            Row{
                input := LineEdit {
                    visible: !hidden;
                    height: 20pt;
                    placeholder-text: "Try and Enter a word here!";
                    min-width: 50pt;
                }
            }
    
        }
    }

    animate height {
        duration: 200ms;
    }
    background: blue;

}
export component Demo inherits Window {
    property <[string]> model: ["Val1", "Val2", "Val3", "Val 4", "Val 5"];
    property <[bool]> visibility: [false, true, true, true, false];
    HorizontalLayout {
        vertical-stretch: 1;
        GroupBox {
            ScrollView {
                VerticalLayout {
                    vertical-stretch: 0;
                    spacing: 40px;
                    for val[i] in model: HorizontalLayout {
                        InputField { 
                        label: val;
                        hidden: visibility[i];
                     }
                    }
                }
            }
        }
    }

}
```

### Environment Details

- Slint Version: 1.8
- Platform/OS: Ubuntu 24.04
- Programming Language: Rust
- Backend/Renderer: winit-femtovg

### Product Impact

This is a huge blocker at the moment, as it doesn't allow for nice entry of values, especially when you need to scroll in order to view more values

**Comment by MattyGam3r** [comment]
Ok I just updated to 1.9.0, and the bug disappeared! I had a headache tackling this yesterday! Thank you guys anyways for the amazing product

**Comment by ogoffart** [comment]
probably fixed by https://github.com/slint-ui/slint/pull/7109
