### ISSUE TITLE
1.9.0 software renderer, femtovg compile errors

### ISSUE THREAD

**Issue by zcanann** [slint-ui/slint#7160]
### Bug Description

slint = { version = ">=1.9.0", default-features = false, features = ["accessibility", "backend-winit", "compat-1-2", "renderer-software", "std"] }

This set of flags seems to fail for me

lib.rs fails at
return Err(format!("Graphics API use requested by the compile-time enabled renderers don't support that"))

Femtovg gives:
failed to select a version for the requirement `i-slint-renderer-femtovg = "=1.9.0"`
candidate versions found which didn't match: 1.8.0, 1.7.2, 1.7.1, ...
location searched: crates.io index
required by package `slint v1.9.0`

### Environment Details

- Slint Version: 1.9.0
- Platform/OS: Windows
- Programming Language: Rust
- Backend/Renderer: Software, femtovg

**Comment by ogoffart** [comment]
Thanks for reporting a bug.  The arror with only software should be fixed by #7165

I don't explain the error you get with femtovg. This might be because of a cache issue as the 1.9.0 release was just uploaded?  Can you maybe try with cargo update and try again?

**Comment by zcanann** [comment]
Ah yep that was it! Appreciate the quick turn around!
