### ISSUE TITLE
The search function in new document does not work

### ISSUE THREAD

**Issue by Horbin-Magician** [slint-ui/slint#7162]
### Bug Description

The search function in new document ((https://docs.slint.dev/latest/docs/slint/)) does not work.

![image](https://github.com/user-attachments/assets/68d2a07a-868c-4474-b6d9-56c500be059e)

### Environment Details

- Slint Version:
- Platform/OS:
- Programming Language:
- Backend/Renderer:

**Comment by ogoffart** [comment]
Thanks for your report. This is fixed now.
