### ISSUE TITLE
Slint-1.9.0 docs failed to build

### ISSUE THREAD

**Issue by yassinebenarbia** [slint-ui/slint#7186]
I was trying to check the docs of `slint` on [docs.rs](https://docs.rs/crate/slint/latest), but instead got this build error
> docs.rs failed to build slint-1.9.0
Please check the [build logs](https://docs.rs/crate/slint/1.9.0/builds) for more information.
See [Builds](https://docs.rs/about/builds) for ideas on how to fix a failed build, or [Metadata](https://docs.rs/about/metadata) for how to configure docs.rs builds.
If you believe this is docs.rs' fault, [open an issue](https://github.com/rust-lang/docs.rs/issues/new/choose).

and this as a part of the error logs

> [INFO] [stderr] error: error reading `docs/astro/src/utils/slint-docs-highlight.html`: No such file or directory (os error 2)
[INFO] [stderr] 
[INFO] [stderr] error: `ExternalHtml::load` failed
[INFO] [stderr] 
[INFO] [stderr] error: could not document `slint`

so my question is, is this intentional/expected? and can someone fix this soon : )

**Comment by tronical** [comment]
Yeah, this one slipped through. Oliver has a fix I #7185 . Meanwhile you can use https://docs.slint.dev/latest/docs/rust/slint/

**Comment by tronical** [comment]
1.9.1 is now on docs.rs
