### ISSUE TITLE
It is recommended that the official website and documents support multiple languages

### ISSUE THREAD

**Issue by sbfkcel** [slint-ui/slint#7205]
### Feature Description

This will enable slint to cover more people in more regions. It will help promote the popularization of slint.

I think it should be easy to do this with AI.

**Comment by ogoffart** [comment]
Thank you for your suggestion. We agree it would be great to make Slint more accessible, but we don't have the resources to do it right now. Also, users can already use online translators to access Slint in their language, so I don't think it's that useful to do it purely with AI.
