### ISSUE TITLE
Unable to center window on screen

### ISSUE THREAD

**Issue by LoganDark** [slint-ui/slint#723]
Follow-up to #722, for splash screens, sixtyfps currently does not support centering the window on-screen. It would be nice if there was a function to get access to the underlying `winit::Window` so I could fill in this functionality myself - I know that's the only backend I'd be using, but I'm not sure if it's worth it to add that for only one backend.

**Comment by ogoffart** [comment]
This is something we want to have, see also https://github.com/sixtyfpsui/sixtyfps/issues/323

It would indeed be nice to somehow give a way to give access to the winit::Window.  But the problem is that it means that upgrading the winit version will become a semver breaking change.

**Comment by tronical** [comment]
I wonder if we should expose the raw window handle instead, that seems like a stable trait? https://crates.io/crates/raw-window-handle

**Comment by ogoffart** [comment]
Closing this as we can now set the position of a window with https://github.com/slint-ui/slint/issues/323

**Comment by Berrysoft** [comment]
Although we can now set the position, we still need methods to get the size and position of the monitors. Slint seems not provide such methods.

**Comment by LoganDark** [comment]
> Although we can now set the position, we still need methods to get the size and position of the monitors. Slint seems not provide such methods.

Open a new issue. This issue is for setting the position to be centered.
