### ISSUE TITLE
Selecting text?

### ISSUE THREAD

**Issue by magnus-ISU** [slint-ui/slint#736]
Is this possible? It seems like an important feature but as far as I can tell you can only select text in an enabled TextEdit or TextInput. But I want to be able to select text without allowing it to be editable or showing a blinking cursor always.

I think one possible solution would be to have a `selectable: [true/false];` property on the generic Text, and maybe give it to the other widgets that can show text as well.

**Comment by tronical** [comment]
Yes, that makes sense and that seems the right straight-forward API for it.

**Comment by tronical** [comment]
`LineEdit`/`TextInput` supports a `read-only` property and it's possible to programmatically set the selection after https://github.com/slint-ui/slint/pull/4197 .
