### ISSUE TITLE
[VSCode Extension] Show preview embedded in VSCode

### ISSUE THREAD

**Issue by AsyncBanana** [slint-ui/slint#748]
It would be helpful to allow for VSCode previews to be embedded in VSCode. It can be not very pleasant to alt-tab to focus the window and then constantly size it to the correct size. This could be solved by doing something like VSCode's Markdown preview and embedding it inside VSCode. I am not sure how hard this would be due to VSCode being Electron-based, but I think the WASM  preview could work well in this case.

**Comment by tronical** [comment]
Yes, that would be awesome to have - I agree. Yes, the WASM preview should somehow be possible to use. The main challenge I see is that we need to implement support for redirecting all file system traffic from within the preview to exactly what the LSP sees.

Any insights or pointers to VSCode docs that support this kind of communication would be greatly appreciated. Perhaps the Markdown preview is using public interfaces for this that we could use, too.

**Comment by ogoffart** [comment]
We have that for the browser version of vscode.  And we could enable that as well for the normal extension.

Should it be an option or should we always have it embedded? And if an option, should it be the default?

**Comment by ogoffart** [comment]
There is a setting for that now
