### ISSUE TITLE
Button frame is not visible when compiling with default features

### ISSUE THREAD

**Issue by farmaazon** [slint-ui/slint#750]
When I add sixtyfps dependency with default features, the button in my project does not look like a clickable element. I build on Manjaro Linux.

To reproduce: clone the https://github.com/farmaazon/sixtyfps-bugs repository and run the application. The label "click-me" appears, but does not looks like a button. 
![image](https://user-images.githubusercontent.com/3919101/146741187-3d7c7e50-94cf-46b3-83ed-0ce38e279673.png)
You can uncomment last two lines in Cargo.toml: the button gets it's frame.
![image](https://user-images.githubusercontent.com/3919101/146741579-f2dfed87-2307-4a90-a7a4-4d18d8bd0708.png)
 After that, if you comment those line again, you need to run cargo clean to reproduce the bug.

Additonal note: I see in Readme and in issues, that themes are mentioned here and there. However, I don't see any mention of it in the official documentation.

**Comment by ogoffart** [comment]
Thanks for the bug report.
I'm not quite sure what you mean. I tried the example, and the default for me use the Qt backend which shows the button frame:
![Screenshot_20211219_164710](https://user-images.githubusercontent.com/959326/146681300-0df0364a-953f-4523-9bbb-8e76ce2daa50.png)
The padding is missing but that's because you specified the size of the button manually, so that's to be expected. (I much recommend using layout to place widgets in it)



> Additonal note: I see in Readme and in issues, that themes are mentioned here and there. However, I don't see any mention of it in the official documentation.

True, we should expand the documentation in that respect.

**Comment by farmaazon** [comment]
Thanks for your reply. And indeed, it's a good idea to put some screenshots. So, on my side, the window looks this way:
a) with the default features (qt backend):
![image](https://user-images.githubusercontent.com/3919101/146741187-3d7c7e50-94cf-46b3-83ed-0ce38e279673.png)
b) with gl backend:
![image](https://user-images.githubusercontent.com/3919101/146741579-f2dfed87-2307-4a90-a7a4-4d18d8bd0708.png)

(I'll add those screenshots to the description).

So it seems that this is platform specific. Perhaps running it on fresh Manjaro Linux with GNOME will show the problem. I reproduce it on two devices with GNOME Manjaro I have.  One runs on x11, the second on Wayland. The program links with the system Qt library, version 5.15.2+kde+r263-1. 

If you need more info about my platform, please let me know.

**Comment by ogoffart** [comment]
could simply be the gnome theme that does not have frame. Although it's a bit strange.

**Comment by ogoffart** [comment]
I cannot reproduce this issue. I'm going to blame it on the Qt style in use that doesn't have a border.
