### ISSUE TITLE
Generated rust code does not compile if the repeated element has `index` property.

### ISSUE THREAD

**Issue by farmaazon** [slint-ui/slint#751]
To reproduce: clone https://github.com/farmaazon/sixtyfps-bugs and uncomment commented block in main.rs (starting from line 52). This results in a compilation error with message about name collisions in generated structures.

I haven't found any mention in documentation that `index` is a reserved word. And even then, I think the error should be a clear error from 60 compiler.

**Comment by ogoffart** [comment]
Thanks for the bug report. That's indeed a bug, we should mangle the property name in the generated code so such conflict does not happen.

**Comment by ogoffart** [comment]
this will be fixed with the llr branch.

**Comment by ogoffart** [comment]
This has been fixed with the introduction of LLR some months ago.
