### ISSUE TITLE
`Table` or `Grid` Component

### ISSUE THREAD

**Issue by nu11ptr** [slint-ui/slint#759]
In addition to lack of a tree (which I see there is already an open issue for), I was surprised to find no grid or table. I realize these are the hardest components to implement/design, but without them, I couldn't even consider sixtyfps for my project, as it is almost entirely built around tabular data.

**Comment by tronical** [comment]
Yes, we'd like to have a `Table` or `Grid` component (next to Tree #505 as you rightly pointed out). This will be some work, I wonder how to best break that into smaller pieces.

**Comment by ogoffart** [comment]
There was some discussion about a table widget in https://github.com/sixtyfpsui/sixtyfps/discussions/574
