### ISSUE TITLE
Online Playground (Beta): Zoom level

### ISSUE THREAD

**Issue by saona-raimundo** [slint-ui/slint#780]
Hi there! Thank you for the hard work!

I know that the playground is in beta, but that is also why I wanted to mention some issues I noticed (hope I am not repeating). Feel free to close the issue upon repetition.

I have two experiences to share:

1. When changing the zoom level in the browser, the compiled GUI disappears.
Steps to reproduce
- Go to https://sixtyfps.io/releases/0.1.5/editor/
- Choose "Gallery" as a demo
- Change the zoom level (in my case, press `Ctrl`+`-`)

~2. Some usages of TextEdit do not work.
2.1. Up and down keys do not move the cursor between lines.
2.2. When the cursor is at the end of the text, pressing ENTER (newline) moves the cursor to the right (as if it were a new whitespace)
2.3. When a word is longer than a line, word-wrap makes the word disappear.
2.4. No support for Ctrl+Left and Ctrl+Right for moving the cursor in words units.~

~(Maybe these are known issues of TextEdit?)~ [edit: See below for text edit issue]

If it is of any use,
I am using Firefox, on Windows.

**Comment by ogoffart** [comment]
Thanks for the report

Regarding the first issue: there is a panic when the zoom level is changed (`unreachable`)

> 2.1. Up and down keys do not move the cursor between lines.
> 2.4. No support for Ctrl+Left and Ctrl+Right for moving the cursor in words units.

That's covered by issue #474 , and i guess the other TextEdit issue should be covered there as well.

**Comment by ogoffart** [comment]
I tried to investigate the panic, and it seems it occurs within the `winit` crate:

```
Uncaught RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h606d7c7f7a423b98 (2d35867ff2c7f2c905b1.module.wasm:0xd4b50d)
    at std::panicking::begin_panic_handler::{{closure}}::h9b985a293aac4ce1 (2d35867ff2c7f2c905b1.module.wasm:0xf3f1b3)
    at std::sys_common::backtrace::__rust_end_short_backtrace::ha03abef02a8b70fd (2d35867ff2c7f2c905b1.module.wasm:0x12ada26)
    at rust_begin_unwind (2d35867ff2c7f2c905b1.module.wasm:0x1222b14)
    at core::panicking::panic_fmt::h6314b5c91abe7349 (2d35867ff2c7f2c905b1.module.wasm:0x126ac6a)
    at core::result::unwrap_failed::hd584efb7b84bf326 (2d35867ff2c7f2c905b1.module.wasm:0xf9080d)
    at core::result::Result<T,E>::expect::h26e01bd8d4072070 (2d35867ff2c7f2c905b1.module.wasm:0xe77e46)
    at core::cell::RefCell<T>::borrow::h3cb72a5d6adba3b9 (2d35867ff2c7f2c905b1.module.wasm:0xef6fa6)
    at winit::platform_impl::platform::event_loop::runner::Shared<T>::handle_scale_changed::hb2d3d31a2eb43cdb (2d35867ff2c7f2c905b1.module.wasm:0x3b6cd9)
    at winit::platform_impl::platform::event_loop::window_target::WindowTarget<T>::run::{{closure}}::hcca9f9a69ad486d3 (2d35867ff2c7f2c905b1.module.wasm:0x119a71d)

$std::panicking::rust_panic_with_hook::h606d7c7f7a423b98	@	2d35867……odule.wasm:0xd4b50d
$std::panicking::begin_panic_handler::{{closure}}::h9b985a293aac4ce1	@	2d35867……odule.wasm:0xf3f1b3
$std::sys_common::backtrace::__rust_end_short_backtrace::ha03abef02a8b70fd	@	2d35867……dule.wasm:0x12ada26
$rust_begin_unwind	@	2d35867……dule.wasm:0x1222b14
$core::panicking::panic_fmt::h6314b5c91abe7349	@	2d35867……dule.wasm:0x126ac6a
$core::result::unwrap_failed::hd584efb7b84bf326	@	2d35867……odule.wasm:0xf9080d
$core::result::Result<T,E>::expect::h26e01bd8d4072070	@	2d35867……odule.wasm:0xe77e46
$core::cell::RefCell<T>::borrow::h3cb72a5d6adba3b9	@	2d35867……odule.wasm:0xef6fa6
$winit::platform_impl::platform::event_loop::runner::Shared<T>::handle_scale_changed::hb2d3d31a2eb43cdb	@	2d35867……odule.wasm:0x3b6cd9
$winit::platform_impl::platform::event_loop::window_target::WindowTarget<T>::run::{{closure}}::hcca9f9a69ad486d3	@	2d35867……dule.wasm:0x119a71d
$<alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::hb6f1e30237e19717	@	2d35867……dule.wasm:0x103c32d
$winit::platform_impl::platform::backend::scaling::ScaleChangeDetectorInternal::handler::hca28b9c014915a49	@	2d35867……odule.wasm:0x763acd
$winit::platform_impl::platform::backend::scaling::ScaleChangeDetectorInternal::new::{{closure}}::h6eb630d2460e735c	@	2d35867……odule.wasm:0x8d082f
$<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::ha487942515c192ab	@	2d35867……odule.wasm:0xda99ef
__wbg_adapter_50	@	index_bg.js?5ca1:297
real
```

There are a bunch of `borrow()` in the `handle_scale_changed` function. I'm not shure which one is failing or why
https://github.com/rust-windowing/winit/blob/6b250a74f8dd5343784538c5bc66a9b5a55000a7/src/platform_impl/web/event_loop/runner.rs#L292

**Comment by saona-raimundo** [comment]
Thank you for the quick answer!

**Comment by ogoffart** [comment]
looks like this works fine now.

**Comment by saona-raimundo** [comment]
Hi!

Thanks for looking into old issues! 
I think it is still a problem, at least for me. It seems that only the initial demo does not disappear, but after selecting the Gallery demo, it does disappear. Can you reproduce the error?

**Problem**. 
When changing the zoom level in the browser, the compiled GUI disappears.

**Steps to reproduce**.
1. Go to https://sixtyfps.io/releases/0.1.5/editor/
2. Choose "Gallery" as a demo
3. Change the zoom level (in my case, press Ctrl+-)
