### ISSUE TITLE
VSCode live-preview can lead to crashing Desktop Enviroment

### ISSUE THREAD

**Issue by Vollbrecht** [slint-ui/slint#782]
## Description
Live editing "width" values with relative length can lead to uncontrollable window growth.  This uncontrollable growth crashes Gnome on Debian

## Expectation
Arbitrary Values in width / height  should not crate a situation (on live edit) that gets uncontrollable.

## Behavior
Typing the wrong value on edit leads to an instantaneous not responsible DE.
Example that creates the issue.
```

export AppWindow := Window {
    VerticalBox{
        HorizontalLayout {
            alignment: end;
            Rectangle {
                width: parent.width * 80%; 
                horizontal-stretch: 0.2;
             }
            GridLayout {
                width: parent.width * 20%;
                horizontal-stretch:0.2;
                Row {
                    Button {
                        width: 80px;
                        height: 80px;
                                ....
                        }
                    }                  
                 
            }
        }
    }
}
```
### Software version
sixtyfps master/ 75ba29cf2fc593e824718bc2b21036b4ee2430f4
sixtyfps-vscode nightly v2021.12.2818

### Operating System
Linux 5.10.0-8-amd64 -- Debian11
### DE
GNOME 3.38.6

**Comment by ogoffart** [comment]
I have noticed such problems myself before.
I'm not sure how to mitigate them.   Maybe limmiting the window size to some value?
Or detecting the binding loop in this case even if that's technicly not a binding loop?

**Comment by ogoffart** [comment]
This is fixed for the live preview since we have a new UI.
Although the root cause is still there, but tracked in https://github.com/slint-ui/slint/issues/2902
