### ISSUE TITLE
dimensions of child elements do not affect dimensions of parents

### ISSUE THREAD

**Issue by Be-ing** [slint-ui/slint#783]
Only the second Rectangle within this VerticalLayout is shown:
![image](https://user-images.githubusercontent.com/9455094/147863704-080e7220-e4a0-4e4f-ad27-ff24af42717f.png)

```
MainWindow := Window {
    VerticalLayout {
        Rectangle {
            Rectangle {
                height: 100px;
                background: blue;
            }
        }
        Rectangle {
            Rectangle {
                height: 100px;
                background: red;
            }
        }
    }
}
```

The first Rectangle within the VerticalLayout seems to have dimensions of 0 even though its child has a height of 100px, so it seems the second Rectangle is drawn over it.

This can be hacked around by specifying dimensions of the outer Rectangles, but I expected this to not be needed: 
![image](https://user-images.githubusercontent.com/9455094/147863709-df967204-fbdd-41d2-9ae4-66bbdd6b9598.png)

```
MainWindow := Window {
    VerticalLayout {
        Rectangle {
            height: 100px;
            Rectangle {
                height: 100px;
                background: blue;
            }
        }
        Rectangle {
            height: 100px;
            Rectangle {
                height: 100px;
                background: red;
            }
        }
    }
}
```

**Comment by ogoffart** [comment]
I can't reproduce this.
Looks alright in https://sixtyfps.io/snapshots/master/editor/?snippet=MainWindow+%3A%3D+Window+%7B%0A++++VerticalLayout+%7B%0A++++++++Rectangle+%7B%0A++++++++++++Rectangle+%7B%0A++++++++++++++++height%3A+100px%3B%0A++++++++++++++++background%3A+blue%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++++++Rectangle+%7B%0A++++++++++++Rectangle+%7B%0A++++++++++++++++height%3A+100px%3B%0A++++++++++++++++background%3A+red%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D

**Comment by Be-ing** [comment]
Ah, it depends on the alignment mode. Try this:
```
MainWindow := Window {
    VerticalLayout {
        alignment: start;
        Rectangle {
            Rectangle {
                height: 100px;
                background: blue;
            }
        }
        Rectangle {
            Rectangle {
                height: 100px;
                background: red;
            }
        }
    }
}
```
It also happens with `alignment: center`. `alignment: end`... doesn't show anything.

**Comment by ogoffart** [comment]
When you have 

```
Rectangle { Rectangle { ... }  } 
```

The outer rectangle size does not depends on the inner rectangle size. 
Only layout make their parents size depends on their contents.

In your example, you have two rectangle that don't have a minimum or preferred size, so when you put them in the layout with an alignment, their size will be 0.

**Comment by Be-ing** [comment]
>  Only layout make their parents size depends on their contents.

Yes, this is counterintuitive IMO. I would expect the size of children to be adopted for parents that don't have any size explicitly set.
