### ISSUE TITLE
Focus handling with TabWidget

### ISSUE THREAD

**Issue by Futsch1** [slint-ui/slint#798]
When switching between tabs, the input focus is left unchanged. As a consequence, a control having the focus will continue to process input events even if its tab is no longer visible.

This can be reproduced with cargo-ui by focusing on the manifest input box and then switching to the "About" tab. When text is entered, it will be put into the invisible input box.

I think the focus should be passed to the first focusable element on the new tab or, even better, to the previously focused element.

**Comment by ogoffart** [comment]
I made commit 6699067 which is working around that problem by making sure that changing tabs clear the focus

In the future we really need to have better focus handling. and in this case, the focus should be sent to the tab's content instead.

**Comment by Futsch1** [comment]
The commit fixes the issue that controls on invisible tabs lose their focus, but it causes another issue: Now, the tab rectangle seems to have the focus instead and will accept all key events, so that neither a FocusHandler in the parent nor in the tab content will receive key events.

Minimal example:
```
import { TabWidget, HorizontalBox } from "sixtyfps_widgets.60";
export TabFocusDemo := Window {
    forward-focus: key-handler; 
    key-handler:= FocusScope {  
        key-pressed(event) => {
            test.text = test.text + "K";
            accept
        }
    }
    TabWidget { 
        tab1 := Tab {            
            title: "Tab1";
            
            HorizontalBox {            
                test := Text {
                    text: "";
                }
            }
        }

        Tab {
            title: "Tab2";

            HorizontalBox {
                
            }
        }
    }
}
```

When starting the GUI, key events will be processed. After switching to Tab2 and back, key events will no longer be processed by the key-handler.

Is there a workaround or might there be a callback when tabs are switched to re-focus manually?

**Comment by ogoffart** [comment]
Yes, this is how the workaround works. We still need to implement proper focus handling.
In the mean time, the tab don't accept focus event, so parent FocusScope would still handle the event. The workaround is to have a focus scope as a parent.
Example:

```
import { TabWidget, HorizontalBox } from "sixtyfps_widgets.60";
export TabFocusDemo := Window {
  forward-focus: key-handler; 
  key-handler:= FocusScope {  
      key-pressed(event) => {
          test.text = test.text + "K";
          accept
      }
    
      TabWidget { 
        tab1 := Tab {            
            title: "Tab1";
            HorizontalBox {            
                test := Text {
                    text: "";
                }
            }
        }

        Tab {
            title: "Tab2";
            HorizontalBox {
            }
        }
      }
  }
}
```

notice how the key-handler is a parent of the TabWidget
