### ISSUE TITLE
Border around ScrollView native widget

### ISSUE THREAD

**Issue by jrmoulton** [slint-ui/slint#824]
https://github.com/sixtyfpsui/sixtyfps/blob/ce7a13b70d0a4be183626a234834251e62046589/sixtyfps_runtime/rendering_backends/qt/qt_widgets/scrollview.rs#L270

This section of code and it's references create a black border around a ScrollView that becomes obvious and distracting and non-removable when it's x or y are set inside the window. Why does this border exist? If I delete this section of code and its references everything compiles fine and the ScrollView looks much better in my opinion without the distracting border. Why is that border created by default?

**Comment by jrmoulton** [comment]
<img width="186" alt="Screen Shot 2022-01-09 at 10 05 18 PM" src="https://user-images.githubusercontent.com/13090441/148720480-053f1732-a737-4d4c-a25f-48cc243c5218.png">
vs.
<img width="199" alt="Screen Shot 2022-01-09 at 10 05 05 PM" src="https://user-images.githubusercontent.com/13090441/148720494-2ac2b2f9-a016-42a3-b732-976421b3fd74.png">

**Comment by ogoffart** [comment]
It depends on the QStyle used. For some QStyle it might be required.
But there is definitively something wrong. Looks like we should draw this differently. As this is a problem for this style.
What desktop environment are you using? Is that Gnome?  Do you know if Qt is using the GTK style? Is it Qt5 or Qt6 ?

**Comment by jrmoulton** [comment]
I'm currently on macOS and I'm running Qt6

**Comment by dilawar** [comment]
I also agree with @jrmoulton. I also don't like border around `ScrollView` and `ListView`. Is there a simple way to disable the border? I am on Windows and using defaults. 

![image](https://user-images.githubusercontent.com/895681/173290665-f8ebd636-7af0-45e4-9db7-dbe7898a50a9.png)

**Comment by dilawar** [comment]
Setting `border-width : 0px` for `ScrollView` removed the border for me. I feel dumb for not trying the first obvious thing before commenting here 😳.

**Comment by ogoffart** [comment]
Perhaps this is related to https://github.com/slint-ui/slint/issues/686 ?

**Comment by tronical** [comment]
As discussed with Florian, this does not seem relevant anymore - with QStyle not being used on macOS and Windows anymore, and the ability to set the border-width manually.
