### ISSUE TITLE
Select the default style

### ISSUE THREAD

**Issue by ogoffart** [slint-ui/slint#83]
Currently the way to select the style is by setting the `SLINT_STYLE` environment variable while compiling (when running the slint-compiler)

 * `SLINT_STYLE=native`  for the native desktop style using Qt 
 * `SLINT_STYLE=fluent`  for our current builtin style
 * `SLINT_STYLE=material`  for the builtin material style

We would like the native style to be the default on desktop, but only if Qt was found while compiling the runtime lib. But since we don't know that when running the compiler, the experience would be quite bad.

The native style require Qt, see https://github.com/slint-ui/slint/blob/master/docs/install_qt.md 

Update: When using the rust integration or the interpreter, the default style is Qt if Qt was found

Update: some extra documentation in https://github.com/slint-ui/slint/blob/master/docs/widgets.md#selecting-a-widget-style

**Comment by flukejones** [comment]
Given that there are two main native styles (QT and GTK), will you be supporting GTK style at all?

**Comment by ogoffart** [comment]
> Given that there are two main native styles (QT and GTK), will you be supporting GTK style at all?

In a GTK-based desktop environment, Qt itself is using the GTK style begind the scene. Using the Qt framework as an abstraction to draw native widget allow us to be looking native on every platform with less work for us at the moment.
(This means we have SixtyFPS -> Qt -> GTK.)

Creating a GTK backend is totally possible, and we might consider doing that, but this is not a priority given that Qt provide a decent native look even in a GTK environment right now.
