### ISSUE TITLE
TextEdit ceases to display a text when the width is less 60px.

### ISSUE THREAD

**Issue by besok** [slint-ui/slint#843]
I stumbled across the case that can be recognized(in my opinion, correct me if I am wrong, please) as a bug.

When I set the width of the element TextEdit to less than 60px (in my case 58px) the text inside magically disappears. 
It was reproduced in the online editor (https://sixtyfps.io/releases/0.1.5/editor/) and locally using vscode extension for preview

```60
import { TextEdit } from "sixtyfps_widgets.60";
Example := Window {
 
    TextEdit {
        width: 50px;
        height: 100px;
        text: "Lorem ipsum dolor sit amet\n, consectetur adipis...";
    }
}
````

**Comment by ogoffart** [comment]
I think the problem you're seeing is that (with the GL backend) we don't show words that are too big to be shown in one line.
This is a bug in the word wrapping algorithm.

**Comment by tronical** [comment]
I think https://github.com/femtovg/femtovg/pull/85 might help

**Comment by ogoffart** [comment]
Don't we plan anyway to use the textlayout module on all backend ?

**Comment by tronical** [comment]
Yes, there I've fixed that case as well (I believe)

**Comment by tronical** [comment]
Keeping this open as this is still present in the MCU text layout and needs to be fixed there, too.
