### ISSUE TITLE
Custom items in ListView overlap with the list

### ISSUE THREAD

**Issue by VictorKoenders** [slint-ui/slint#860]
I'm trying to add a button to the top and bottom of the ListView, but it seems like the ListView doesn't properly render it.

Tested on the [online editor](https://sixtyfps.io/releases/0.1.6/editor/)
```
import { ListView, Button } from "sixtyfps_widgets.60";
export Demo := Window {
    width:  300px;
    height: 300px;

    ListView {
        Button { height: 32px; text: "Foo"; } 
        for i in [0, 1, 2, 3]: Button { height: 32px; text: i; }
        Button { height: 32px; text: "Bar"; }
    }
}
```

Expected:
- Foo
- 0
- 1
- 2
- 3
- Bar

Got:
![image](https://user-images.githubusercontent.com/2743142/150630612-2d053878-3982-4955-87ac-c201d15bf30b.png)

Commenting out the "Bar" button shows the "0" button but does not show the "Foo" button:
![image](https://user-images.githubusercontent.com/2743142/150630619-44821c40-2b45-49d4-b455-d2245b6f1970.png)

QML has a custom [header](https://doc.qt.io/qt-5/qml-qtquick-listview.html#header-prop) and [footer](https://doc.qt.io/qt-5/qml-qtquick-listview.html#footer-prop) property, which might be easier to implement and would work for my use case.

**Comment by ogoffart** [comment]
Currently, ListView only layout the elements that are in the `for`. Other element are not laid out by the list view, so they are located in (0, 0).
We should either:
 1. warn about it.
 2. fix it 

should we also support no `for` or several `for`?

An easy workaround currently is to use a ScrollArea with a VerticalLayout: (The main difference then is that all elements are always instantiated)

```
import { ScrollView, Button } from "sixtyfps_widgets.60";
export Demo := Window {
    width:  300px;
    height: 300px;

    ScrollView {
        VerticalLayout {
            Button { height: 32px; text: "Foo"; } 
            for i in [0, 1, 2, 3, 4, 5, 6, 7, 8]: Button { height: 32px; text: i; }
            Button { height: 32px; text: "Bar"; }
        }
    }
}
```

**Comment by VictorKoenders** [comment]
Note that this happens with `@children`. The following code has the same issue:

```
import { ScrollView, Button } from "sixtyfps_widgets.60";

ListView := ScrollView {
    VerticalLayout {
        @children
    }
}

export Demo := Window {
    width:  300px;
    height: 300px;

    ListView {
        Button { height: 32px; text: "Foo"; } 
        for i in [0, 1, 2, 3, 4, 5, 6, 7, 8]:  Button { height: 32px; text: i; }
        Button { height: 32px; text: "Bar"; }
    }
}
```

**Comment by ogoffart** [comment]
You're hitting another bug here that we just recognize the ListView by name, so here you are redefining a builtin item in a way. If you rename your ListView to `MyListView` it should work.

**Comment by ogoffart** [comment]
This is an error since 1.0
