### ISSUE TITLE
JS: Invalid data in `Model`s

### ISSUE THREAD

**Issue by hunger** [slint-ui/slint#883]
In JS we can have invalid/unexpected data in our Models that can not get converter to the expected type.

When that happens we throw an exception to JS.

Afterwards I can no longer call any method on the Model. Calling e.g. `rowCount` in the `JsModel` comes back with a `JavaScript` Error:/

I think the exception damages the `PersistentContext` we keep around somehow.

**Comment by hunger** [comment]
Note to self: @simon fixed a similar issue with the following code:

```diff
diff --git a/api/sixtyfps-node/native/lib.rs b/api/sixtyfps-node/native/lib.rs
index 30843d1f7..e2f3782cd 100644
--- a/api/sixtyfps-node/native/lib.rs
+++ b/api/sixtyfps-node/native/lib.rs
@@ -391,8 +391,10 @@ fn to_js_value<'cx>(
                 persistent_context::PersistentContext::from_object(&mut cx, this.downcast().unwrap())?;

             let value = to_eval_value(cx.argument::<JsValue>(1)?, ty, &mut cx, &persistent_context)?;
-            component.set_property(prop_name.as_str(), value)
-                .or_else(|_| cx.throw_error("Cannot assign property"))?;
+            run_scoped(&mut cx, this.downcast().unwrap(), || {
+                component.set_property(prop_name.as_str(), value)
+                    .map_err(|_| "Cannot assign property".to_string())
+            })?;

             Ok(JsUndefined::new().as_value(&mut cx))
         }
```

**Comment by ogoffart** [comment]
I don't understand this issue.  Is there a sample code to reproduce?

**Comment by tronical** [comment]
I don't recall exactly anymore how @hunger ran into this, but I do recall commit 6ddfe9489c676ee89098a8b5955b2ba2d2531277 . I think the issue there was that the exception was stored in the wrong global context (and never retrieved/cleared?), while that commit used `run_scoped` to set `GLOBAL_CONTEXT` to the "local" `cx`.

It's possible that throwing an exception in the callback of a single shot timer causes a similar "destruction" of the global context.

**Comment by tronical** [comment]
It's not clear what needs to be done here. I think this is no longer valid with the napi-rs port.
