### ISSUE TITLE
Spinner

### ISSUE THREAD

**Issue by bq-wrongway** [slint-ui/slint#902]
Is there any widget that acts like progress indicator,i havent seen anything in docs.

If not what would be "proper" way to implement something like that

**Comment by ogoffart** [comment]
There is currently no progress indicator.

And there is unfortunately not yet a proper way to have permanent animation. 
But there are workaround for that like what is done in cargo-ui
https://github.com/sixtyfpsui/cargo-ui/blob/483547abb9136044467cf29ebe46e86fd51c804e/ui/install.60#L34-L39
This is how to get a permanently animated property, but one must make sure to call the `ensure-start-animation()` callback at least once.
Then you can use it on any widget to make it animated. Depending on how you want it to look.

**Comment by ogoffart** [comment]
The animation part can now be done with `animation-tick()`

[Example](https://slint-ui.com/releases/0.3.2/editor/?snippet=import+%7B+Button%2C+VerticalBox+%2C+HorizontalBox%7D+from+%22std-widgets.slint%22%3B%0A%0A%0ASpinner+%3A%3D+Rectangle+%7B%0A++++for+idx+in+20+%3A+Rectangle+%7B%0A++++++++width%3A+min%28root.height%2C+root.width%29+*+0.1%3B%0A++++++++height%3A+width%3B%0A++++++++background%3A+gray%3B%0A++++++++border-radius%3A+width%2F2%3B%0A%0A++++++++x%3A+parent.width+*+%280.5+%2B++Math.sin%281turn+*+%28idx%2F20+%2B+animation-tick%28%29%2F5s%29%29+*+0.4%29+-+width%2F2%3B%0A++++++++y%3A+parent.height+*+%280.5+%2B++Math.cos%281turn+*+%28idx%2F20+%2B+animation-tick%28%29%2F5s%29%29+*+0.4%29+-+height%2F2%3B%0A++++%7D%0A%7D%0A%0Aexport+Demo+%3A%3D+Window+%7B%0A++++width%3A+100px%3B%0A++++height%3A+100px%3B%0A++++VerticalBox+%7B+++++%0A++++++++Spinner+%7B%7D%0A++++%7D%0A%0A%7D%0A)

**Comment by ogoffart** [comment]
Note: the fluent spinner: https://developer.microsoft.com/en-us/fluentui#/controls/web/spinner  and progressbar https://developer.microsoft.com/en-us/fluentui#/controls/web/progressindicator

the material spinner and progress indicator https://m3.material.io/components/progress-indicators/overview

**Comment by ogoffart** [comment]
Either two animation with intermediate properties,  or do some math to merge them together.

Can also animate a Path element

**Comment by ogoffart** [comment]
1.1 has a ProgressIndicator.  It could get a spinner.

**Comment by ogoffart** [comment]
Done in 1.3
