### ISSUE TITLE
Broken link in LicenseRef-Slint-commercial.md

### ISSUE THREAD

**Issue by Y0ba** [slint-ui/slint#932]
1. Open [LicenseRef-Slint-commercial.md](https://github.com/slint-ui/slint/tree/master/LICENSES/LicenseRef-Slint-commercial.md)
2. Click `Licensing FAQ`.
3. Github opens https://github.com/slint-ui/slint/blob/master/LICENSES/FAQ.md#licensing which doesn't exist.

I think link in `[Licensing FAQ](FAQ.md#licensing)` should be either `/FAQ.md#licensing` or `../FAQ.md#licensing`.

**Comment by hunger** [comment]
Thank you for reporting this issue! I pushed a fix, pointing to the copy of the file on github but also mentioning the FAQ.md in the top level checkout for local browsing.

The file is symlinked into several places all over the tree, so there unfortunately is no local path that will work everywhere.
