### ISSUE TITLE
0.2 release docs wrong build.rs command

### ISSUE THREAD

**Issue by jannes** [slint-ui/slint#934]
https://slint-ui.com/releases/0.2.0/docs/rust/slint/#the-slint-code-in-external-files-is-compiled-with-buildrs

should be
```
fn main() {
    slint_build::compile("ui/hello.slint").unwrap();
}
```

not 
```
fn main() {
    slint::compile("ui/hello.slint").unwrap();
}
```

**Comment by ogoffart** [comment]
You're absolutely right. Well spotted. Thank you for reporting
