### ISSUE TITLE
failed to write request: The pipe is being closed. (os error 232)

### ISSUE THREAD

**Issue by morvagergely** [slint-ui/slint#978]
Rust analyzer produces this error when using the [example code](https://lib.rs/crates/slint) in vscode.
```rust
use slint::slint;

slint! {
    HelloWorld := Window {
        Text {
            text: "hello world";
            color: green;
        }
    }
}

fn main() {
    HelloWorld::new().run();
}
```

rust-analyzer version: **02904e99a 2022-02-14 stable**
rustc version: **1.58.1 (db9d1b20b 2022-01-20)**
slint version: **0.2.0**

There has been a [similar issue](https://github.com/slint-ui/slint/issues/674) which has been closed.

**Comment by snylonue** [comment]
I find that the error occurs every time I edit `Cargo.toml`

**Comment by ogoffart** [comment]
What version of rust and rust analyzer are you using?

**Comment by snylonue** [comment]
rust-analyzer version: 0.3.1131-standalone (897a7ec4b 2022-07-17)
rustc 1.63.0-nightly (e71440575 2022-06-02)

Sorry that I thought this issue was under rust-analyzer repo.

**Comment by ogoffart** [comment]
I'm closing this issue because this is probably just a bug in rust-analyzer. `https://github.com/rust-lang/rust-analyzer/issues/12673`
