### ISSUE TITLE
Formatted Strings

### ISSUE THREAD

**Issue by jrmoulton** [slint-ui/slint#980]
Is there a way to define a certain number of decimals (and spaces) that should be printed in `Text` Element? Something with `printf` functionality?

**Comment by ogoffart** [comment]
We currently don't have that.
You can hack it with round like this:  `Math.round(value * 100)/100`

(For reference, this was also discussed there: https://github.com/slint-ui/slint/discussions/586 )

**Comment by jrmoulton** [comment]
Haha oh whoops. Thanks
