### ISSUE TITLE
panicked at 'Constant property being changed' when changing text inside HorizontalLayout

### ISSUE THREAD

**Issue by leofidus** [slint-ui/slint#983]
I have some code that essentially looks like this (using the rust template on Windows)

```
FileLine := Rectangle {
    property <string> filename;
    HorizontalLayout {
        t_filename := Text {
            text: root.filename;
        }
    }
}

MainWindow := Window {
    property <[FileItem]> file-model: [
    ];

    VerticalBox {
        list-view := ListView {
            for file in file-model:  FileLine {
                filename: file.filename;
            }
        }
    }
}
```

If I now assign something to file-model from rust code the program crashes with `thread 'main' panicked at 'Constant property being changed', C:\Users\redacted\.cargo\registry\src\github.com-1ecc6299db9ec823\i-slint-core-0.2.0\properties.rs:588:13`.

Removing the `text: root.filename` resolves the crash. I tried using `property <string> filename <=> t_filename.text` and removing the text assignment in the text element, but that didn't help.

Removing the HorizontalLayout helps, but normally there would be more elements inside it, so I want it there. Inlining the component into the for loop also solves the issue (removing the properties and filling in directly from the for loop).

I have uploaded full code to reproduce it [here](https://github.com/leofidus/ntfs-explorer/tree/slint-reproduce1)

**Comment by ogoffart** [comment]
Thanks for the bug report!
This is now fixed in master.

**Comment by ogoffart** [comment]
If you want a workaround in the mean time before the next release, i think adding a fake binding to `y` will do it:

```
list-view := ListView {
            for file in file-model:  FileLine {
                filename: file.filename;
                // Just a dummy binding that adds a dependency from the filename to y 
                // to workaround https://github.com/slint-ui/slint/issues/983
                y: filename == "" ? 0 : 1px;
           }
        }
 ```

**Comment by leofidus** [comment]
Thanks for the quick bugfix and the workaround
