### ISSUE TITLE
Add an option to disable the scrollbox containing the scrollbar

### ISSUE THREAD

**Issue by jrmoulton** [slint-ui/slint#988]
Currently Slint has no way to disable the boxes around a scrollbar in a scrollview. It would be nice to have the option to be able to disable them. 

with 
<img width="116" alt="Screen Shot 2022-02-25 at 5 49 19 PM" src="https://user-images.githubusercontent.com/13090441/155821586-035be1d6-7e96-40b3-8ed7-76e3628ac60a.png">

vs without
<img width="136" alt="Screen Shot 2022-02-25 at 5 49 32 PM" src="https://user-images.githubusercontent.com/13090441/155821601-0ed07c53-1e90-4d76-8859-0a03a4acaf30.png">

I got this workign in Qt but it feels pretty hacky. On this line
 https://github.com/slint-ui/slint/blob/55fb9c13aaec5a011951b0aa8a9b1d814d2395bb/internal/backends/qt/qt_widgets/scrollview.rs#L356
I initialized QRect with `(0,0,0, r.size().height())`

What would be the best way to go about adding this feature? Do similar changes need to be made in all backends?

**Comment by jrmoulton** [comment]
The way I listed above isn't a great way to not draw the scrollbox. I haven't used Qt much but it looks like the option should be in the QStyleOptionSlider but I can't find a way to manipulate the drawing of the box. I've tried setting the painter to fill transparent and tried to set the painter pen to have no width but that didn't have any effect on the box. 

How could I go about hiding the scrollbox?

**Comment by ogoffart** [comment]
What Style and what platform are you on?
How does Qt application looks otherwise?

**Comment by jrmoulton** [comment]
Fluent Style on macOS with Qt 6.
Do you know of an option inside of Qt to draw the slider without the box?

**Comment by jrmoulton** [comment]
Oh your right I got confused. It is the native style. 
And I don't think this is a bug I'm just trying to add a style option to the native style because it is common on macOS to have a scrollslider but without the scrollbox. So I've found a way to color it differently using the QPainter but I haven't found a way to just hide it.

**Comment by tronical** [comment]
Hm, now that you mention it - I see the scroll box on macOS, for example in Safari and TextEdit. Where in macOS would it be absent?

Or do you mean transparent overlay scrollbars like on iOS/iPadOS?

Maybe @n-raine has an idea as well?

**Comment by jrmoulton** [comment]
@tronical Yep. I didn't know the name of what I was looking for but after a google search it seems like overlay scrollbars are what I was looking for.
Another example would be in the mattermost app on macOS it has a scrollslider but no scollbox around that slider.
<img width="274" alt="Screen Shot 2022-03-03 at 4 35 03 PM" src="https://user-images.githubusercontent.com/13090441/156671036-cdcffe39-0ff4-4002-a119-59e9bb0bbd4a.png">

I'll keep looking and see if I can find how to do that with Qt.

**Comment by ogoffart** [comment]
Relates to https://github.com/slint-ui/slint/issues/824 ?

**Comment by ogoffart** [comment]
The cupertino style is now the recommended style on mac, and we don't really support the qt style on mac anymore.

**Comment by aurexav** [comment]
> The cupertino style is now the recommended style on mac, and we don't really support the qt style on mac anymore.

But this question still exist. The scrollbar should be able to hide automatically if user doesn't focus on the widget.
