### ISSUE TITLE
Hover not updated when cursor leaves window area

### ISSUE THREAD

**Issue by sztomi** [slint-ui/slint#989]
Consider the following slint code that creates a rectangle with a hover effect. 

```slint
Button := Rectangle {
  property<bool> hover <=> ta.has-hover;

  width: 192px;
  height: 64px;
  background: #323;
  border-radius: 8px;
  clip: true;

  Text {
    width: parent.width;
    height: parent.height;
    text: "Hello!";
    color: #ddd;
    font-size: 24px;
    vertical-alignment: center;
    horizontal-alignment: center;
  }

  ta := TouchArea { }

  states [
    hovered when root.hover : {
      root.color: #328;
    }
  ]
}
```

Hovering works when inside the window, but it stops updating when the mouse cursor leaves the window. It updates again when the mouse is inside the window, even if it doesn't touch the rectangle upon entering.

https://user-images.githubusercontent.com/240594/155852815-c6f43863-6a16-4263-97f4-60bee74cf596.mp4

**Comment by ogoffart** [comment]
The problem exists in all backends.  I guess both Qt and winit should deliver an event when the mouse leave the window. We should translate that to a MouseExit event

**Comment by sztomi** [comment]
Wow, thanks for the quick turnaround, I really appreciate it!
