### ISSUE TITLE
Keyboard interaction with widgets

### ISSUE THREAD

**Issue by hunger** [slint-ui/slint#991]
Many of our widgets do not accept keyboard handling. Improve this:

* [x] Button -- should be "clickable" via the keyboard
* [x] Spinbox -- Change value, increment/decrement
* [x] ComboBox -- open menu, navigate menu
* [x] ...

**Comment by tronical** [comment]
Maybe another critical to add to each widget is that if it is focusable it should be visible, i.e. using a focus rect?

**Comment by hunger** [comment]
Yeap. We need to improve out logic for when items can get focus quite a bit:-)
